### ISSUE TITLE
feat: Promote Shorebird to push full releases instead of patches

### ISSUE THREAD

**Issue by GeylanKalafMohe** [shorebirdtech/shorebird#1002]
**Description**

For companies and also for me as a developer I don't like Shorebird to be promotes to push "patch" releases instantly to users. I would prefer it to be a real full push of a release and not only a "patch".

In my opinion it is not worth to pay 20$ or even more monthly for a big company to push an eventual "patch" release. Rather they want to push full releases to users instantly.

What I mean with full releases is like adding new asset images/ fonts/ native code changes etc. It should replace the need for a manual upload through the stores.

**Comment by eseidel** [comment]
We will be adding asset support soon: https://github.com/shorebirdtech/shorebird/issues/318. I don't think it's possible to make native code changes outside of the store release processes however.

**Comment by eseidel** [comment]
It sounds like you're asking for Asset support, which is tracked in #318.  We hope to add that soon.  Let us know if you were asking for other things?
