### ISSUE TITLE
fix: error when generating iOS snapshot: "Can't load Kernel binary"

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1003]
Just encountered this when running `shorebird patch ios-alpha`. The command

```
/Users/bryanoltman/Shorebird/_shorebird/shorebird/bin/cache/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64 -v --deterministic --snapshot-kind=app-aot-elf --elf=/Users/bryanoltman/Documents/sandbox/ios_build_test/build/out.aot /Users/bryanoltman/Documents/sandbox/ios_build_test/.dart_tool/flutter_build/447eb257e6929635aa1de43596304bc9/app.dill
```

Failed with the error:

```
Can't load Kernel binary: File size is too small to be a valid kernel file.
```

This app.dill is 0B, which I suspect is the issue. Not exactly sure how this happened

**Comment by bryanoltman** [comment]
This was fixed by deleting the `.dart_tool` directory and running the `shorebird patch ios-alpha` command a second time. Will update the error handling to add a log message suggesting the user try this.

**Comment by eseidel** [comment]
A better (long-term) fix is for us to hook in in a way that doesn't require us to grep through .dart_tool for random .dill files but rather always know we got the right one as part of the build process. :)

**Comment by eseidel** [comment]
The solid fix for this is to modify the `flutter` tool in our fork to make this call for us, since it knows what the path to the dill is, and we don't.

Alternatively maybe we could parse it out of the `flutter` tool logs.

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/shorebird/issues/637 may just fix this.

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/shorebird/issues/637 is the correct fix.
