### ISSUE TITLE
shorebird install no longer needs to clone flutter (since shorebird knows how to itself)

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#1014]
Thoughts on removing this from the install script (not in this PR, obviously)

_Originally posted by @bryanoltman in https://github.com/shorebirdtech/shorebird/pull/1012#discussion_r1283671973_

**Comment by eseidel** [comment]
I don't think we do anymore? https://github.com/shorebirdtech/install/blob/main/install.sh
