### ISSUE TITLE
fix: without a build number, shorebird reports incorrect iOS version numbers

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1020]
**Description**

When a pubspec.yaml's version does not contain a build number (the `2` in `1.0.0+2`), shorebird will determine the version (incorrectly) to be something like 1.0.0+1.0.0.

**Steps To Reproduce**

1. Create a Flutter project
2. Change the pubspec.yaml's version to not include a build number (e.g., `1.0.0`)
3. Run `shorebird release ios-alpha`
4. See that the release version is `1.0.0+1.0.0` or similar

**Expected Behavior**

Release version reflects what is in Info.plist/pubspec.yaml

**Comment by bryanoltman** [comment]
What seems to be happening is that the build number in Xcode is being used as `CFBundleShortVersionString` (which we treat as the release number) and `CFBundleVersion` is being set to the pubspec.yaml version and being used as the build number.

**Comment by eseidel** [comment]
I believe https://github.com/shorebirdtech/engine/blob/655974aed33b608d1075cffae0fcaf06772d90d8/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm#L219 is the problem.

**Comment by eseidel** [comment]
I can easily change the Rust code to plumb that through as a string (or happy to help you do so).

**Comment by bryanoltman** [comment]
First going to see what App Store Connect does with a 1.0.0+1.0.0 build and if this is even a valid config.

**Comment by bryanoltman** [comment]
Looks like this in Transporter.app

![Screenshot 2023-08-04 at 10 29 17 AM](https://github.com/shorebirdtech/shorebird/assets/581764/d3940cad-5523-43f2-bd71-659fbbf559bc)

**Comment by bryanoltman** [comment]
What I've found:

- `x.y.z+x.y.z` is a 100% legal versioning scheme from the perspective of App Store Connect.
- Changing `x.y.z` in `pubspec.yaml` to `x.y.a` will yield `x.y.a+x.y.a`, which is a completely different release version. App Store Connect will reject this, as there is (presumably) already a pending version for `x.y.z`.
- This is Flutter behavior – I see the same thing when taking Shorebird out of the equation.

What I propose:

- Update the Rust/C++ code to support build numbers of the form `x.y.z` (i.e., change the data type from int to string)
- No changes on the CLI side, as this is standard Flutter behavior, and App Store Connect seems happy to accept said behavior.

**Comment by eseidel** [comment]
Sgtm. This will make it so “1.0.0” in the pub spec produces different
shorebird releases for iOS cs android. Which may be more argument for us to
separate the two explicitly. 🤷

**Comment by bryanoltman** [comment]
Yep, it looks like Android defaults to `1` as a build number if none is provided in the pubspec. I'm going to finish up my ipa diffing change (it's taking a bit longer than it needs to because I'm doing a little extra refactoring while I'm in there) and then tackle this.

**Comment by bryanoltman** [comment]
This is fixed. Shorebird will now report the same version number as what is recognized by Xcode.
