### ISSUE TITLE
feat: support obfuscation

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#1044]
**Description**
From a customer:

This is the command I usually use for creating aab release
flutter build appbundle --release --obfuscate 
- what's the equivalent command to this in shorebird please ? and versioning number?

**Comment by felangel** [comment]
This should work today:

```
shorebird release android -- --obfuscate
```

Will leave this open until someone confirms that everything works as expected.

**Comment by felangel** [comment]
Closing as we've had a customer confirm this works as expected 👍

**Comment by eseidel** [comment]
We've now launched official obfuscation support for iOS:
https://shorebird.dev/blog/obfuscation-on-ios
