### ISSUE TITLE
fix: -- --dart-define Not working

### ISSUE THREAD

**Issue by gauravmehta13** [shorebirdtech/shorebird#1053]
**Description**

i would like to build my app using
` shorebird release android --flavor cineflix --dart-define=flavor=cineflix  `

But it throws error 

```
 shorebird release android --flavor cineflix --dart-define=flavor=cineflix    
Could not find an option named "dart-define".
To proxy an option to the flutter command, use the -- --<option> syntax.

Example:

shorebird release android -- --no-pub lib/main.dart

Usage: shorebird release android [arguments]
-h, --help                   Print this usage information.
-t, --target                 The main entrypoint file of the application.
    --flavor                 The product flavor to use when building the app.
    --artifact               They type of artifact to generate.

          [aab] (default)    Android App Bundle
          [apk]              Android Package Kit

    --split-per-abi          Whether to split the APKs per ABIs. To learn more, see: https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
-f, --force                  Release without confirmation if there are no errors.
```
![image](https://github.com/shorebirdtech/shorebird/assets/51997260/c7b06153-f9ea-43e2-9395-95b7663ab5e3)

Shorebird doctor
![image](https://github.com/shorebirdtech/shorebird/assets/51997260/661fa551-32cc-4d4f-aa88-a57c1511fb6d)

**Comment by bryanoltman** [comment]
I think the fix is in the error message – `use the -- --<option> syntax`. This should work with:

```
shorebird release android --flavor cineflix -- --dart-define=flavor=cineflix 
```

**Comment by gauravmehta13** [comment]
Already tried not working

**Comment by vyPal** [comment]
I have found a solution that works for me. I also get this error: 
![image](https://github.com/shorebirdtech/shorebird/assets/66716025/9109ec54-43b8-42cf-a939-f7458c2c4ca6)
ends up that you have to include '--' even with the quotes. So my command then looks like this 
![image](https://github.com/shorebirdtech/shorebird/assets/66716025/c83827dc-4004-421a-bae0-df29ea4efecd)
and then it works. It is a little confusing I must admit

**Comment by bryanoltman** [comment]
It turned out this was a powershell issue. We introduced better logging (shown in https://github.com/shorebirdtech/shorebird/issues/1053#issuecomment-1680824555) in https://github.com/shorebirdtech/shorebird/pull/1074. Closing this issue as fixed.

**Comment by nailongyeshilong** [comment]
> I have found a solution that works for me. I also get this error: ![image](https://private-user-images.githubusercontent.com/66716025/261056478-9109ec54-43b8-42cf-a939-f7458c2c4ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjAxMzgsIm5iZiI6MTcwNjg1OTgzOCwicGF0aCI6Ii82NjcxNjAyNS8yNjEwNTY0NzgtOTEwOWVjNTQtNDNiOC00MmNmLWE5MzktZjc0NThjMmM0Y2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA3NDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjOGQ2NmU1MGI3ZTBiYWQ5YTg2MmIyYzcxMDgxMmNmNzBiNTg4OTQ2MGVhMGFiZTcwMDg3OGVmODdlNDhhY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S8F1eCclV4nQESG5oNMb54PQLGlWSUM1riFoy3R8Zlc) ends up that you have to include '--' even with the quotes. So my command then looks like this ![image](https://private-user-images.githubusercontent.com/66716025/261056967-c83827dc-4004-421a-bae0-df29ea4efecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjAxMzgsIm5iZiI6MTcwNjg1OTgzOCwicGF0aCI6Ii82NjcxNjAyNS8yNjEwNTY5NjctYzgzODI3ZGMtNDAwNC00MjFhLWJhZTAtZGYyOWVhNGVmZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA3NDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNDlkNDA4ZmY5MzYxNTliNjY4ZTJkNjA5Zjc5MTVmOWJhMzIxMzUzYjgxY2IxYjRjYzc2NWVlNzc5ZTEwYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5jpjQoVUu_OGh6s3BWfS-37umd_YVTT_T83Jj4mCS5g) and then it works. It is a little confusing I must admit

it works!
