### ISSUE TITLE
Support for Single Patch Update Across Multiple Flavors

### ISSUE THREAD

**Issue by gauravmehta13** [shorebirdtech/shorebird#1080]
### Problem:
I am currently developing an application using Flutter that has two flavors, each with its own bundle ID. The flavors enable distinct branding and functionality for different target audiences. However, the current update mechanism in Shorebird does not support the ability to push a single patch update that simultaneously updates both flavors of the app.

### Scenario:
I have two flavors of my Flutter app, each with its own bundle ID.
Shorebird currently handles updates based on the app ID and release number.
When I release a patch or update, I need to generate separate updates for each flavor due to the dependency on the app ID.

### Benefits:
Efficient Updates: Developers can release a single patch update that applies seamlessly to all flavors, saving time and reducing the complexity of managing separate updates.
Consistency: Users across all flavors receive the same updates simultaneously, ensuring a consistent user experience.
Streamlined Maintenance: Developers can focus on maintaining a single update package instead of generating multiple updates for different flavors.

Discord Discussion [here](https://discord.com/channels/1030243211995791380/1030243213002412164/1139037031712968765)

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/shorebird/pull/1190 may get you part of the way there.

**Comment by eseidel** [comment]
Very similar to https://github.com/shorebirdtech/shorebird/issues/860.

**Comment by eseidel** [comment]
I think for now we should assume this can get built on top of Shorebird?  Let us know if you disagree.
