### ISSUE TITLE
How can signed the release with my certificate

### ISSUE THREAD

**Issue by JgomesAT** [shorebirdtech/shorebird#1082]
I use this command shorebird release android --artifact=apk

but when I try to install this say, invalid package  I think that it is by the signature

How can I signed??

**Comment by SpajicM** [comment]
https://docs.flutter.dev/deployment/android#signing-the-app

**Comment by eseidel** [comment]
Let us know if the above link doesn't help!  Thanks.

**Comment by JgomesAT** [comment]
Thanks
