### ISSUE TITLE
feat: in china, please help.

### ISSUE THREAD

**Issue by shaoting0730** [shorebirdtech/shorebird#1088]
 ~  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.81.0)
[!] Proxy Configuration
    ! NO_PROXY does not contain ::1
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
 shorebird doctor
Shorebird 0.12.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.10.6 • revision 0e2d280277cf9f60f7ba802a59f9fd187ffdd050
Engine • revision bf07ad7b0b777cb9aff15e59bf928504857f4ada

✓ Shorebird is up-to-date (1.6s)
✗ Flutter install is correct (0.9s)
  [!] Shorebird does not respect the FLUTTER_STORAGE_BASE_URL environment variable at this time
1 issue detected.

**Comment by eseidel** [comment]
I suspect you're running into https://github.com/shorebirdtech/shorebird/issues/435.

Shorebird ignores FLUTTER_STORAGE_BASE_URL at this point, so it likely will work still in your setup so long as you're able to reach Google Cloud Storage.

We hope to resolve #435 soon, but have not started work on it yet.

**Comment by eseidel** [comment]
Let us know if there is more we can do to help.  We're also reachable on discord at https://discord.gg/shorebird.

**Comment by nailongyeshilong** [comment]
>  ~  flutter doctor Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-x64, locale zh-Hans-CN) [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2) [✓] Xcode - develop for iOS and macOS (Xcode 14.2) [✓] Chrome - develop for the web [✓] Android Studio (version 2022.1) [✓] VS Code (version 1.81.0) [!] Proxy Configuration ! NO_PROXY does not contain ::1 [✓] Connected device (3 available) [✓] Network resources
> 
> ! Doctor found issues in 1 category. shorebird doctor Shorebird 0.12.2 • [git@github.com](mailto:git@github.com):shorebirdtech/shorebird.git Flutter 3.10.6 • revision 0e2d280277cf9f60f7ba802a59f9fd187ffdd050 Engine • revision bf07ad7b0b777cb9aff15e59bf928504857f4ada
> 
> ✓ Shorebird is up-to-date (1.6s) ✗ Flutter install is correct (0.9s) [!] Shorebird does not respect the FLUTTER_STORAGE_BASE_URL environment variable at this time 1 issue detected.

If someone in Chinese mainland can't login with 'shorebird login', maybe you need set proxy to your terminal, just input follow command(if you use clash):
set http_proxy=http://127.0.0.1:7890
set https_proxy=https://127.0.0.1:7890
shorbird login


筒子们如果发现开了全局代理之后，用shorebird login命令也登陆不了的话，试下给终端把代理设置上再去登陆！
