### ISSUE TITLE
Shorebird for mixed app (React Native + Flutter)

### ISSUE THREAD

**Issue by gaurav-zdroid** [shorebirdtech/shorebird#1093]
Hi, 

I want to implement Shorebird in our project but the problem is App is not entirely Flutter based, We are migrating from RN to Flutter but for now, it's a combination of React Native and Flutter.

So in this case how do we implement Shorebird ? 🤷

Thanks.

**Comment by eseidel** [comment]
Shorebird should work fine in that case for updating the Flutter bits:
https://docs.shorebird.dev/guides/add-to-app

**Comment by eseidel** [comment]
Let us know if that doesn't help.  Or please reach out on Discord: https://discord.gg/shorebird, we'd be happy to help.

**Comment by gaurav-zdroid** [comment]
I am trying to build but facing some issues while assembling signed build while adding this code piece.
````
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url '../my_flutter_module/build/host/outputs/repo'
        }
+       maven {
-           url 'https://storage.googleapis.com/download.flutter.io'
+           url 'https://download.shorebird.dev/download.flutter.io'
+      }
    }
}

Error

`Build was configured to prefer settings repositories over project repositories but repository 'MavenLocal' was added by build file 'build.gradle'`

**Comment by eseidel** [comment]
It looks like you're following https://docs.shorebird.dev/guides/add-to-app/android.  But I don't actually know what that error means. 🤔

**Comment by eseidel** [comment]
Looks like its this: https://stackoverflow.com/questions/69163511/build-was-configured-to-prefer-settings-repositories-over-project-repositories-b

**Comment by eseidel** [comment]
I suspect your build.gradle is using old-style dependencies?

**Comment by gaurav-zdroid** [comment]
Yes, using old-style dependencies, For Shorebird I have to go with new-style dependencies only?

**Comment by eseidel** [comment]
No, shorebird shouldn't care what style dependencies you use for Gradle, just our instructions are written for new style dependencies.  I'm not a gradle expert, but I suspect you or I could figure out with some internet searching how to translate.

**Comment by gaurav-zdroid** [comment]
Getting Error
```
Could not resolve com.example.my_flutter_module:flutter_release:1.0.
     Required by:
         project :app
      > Could not resolve com.example.my_flutter_module:flutter_release:1.0.
         > Could not get resource 'https://s3-ap-southeast-1.amazonaws.com/jp-build-packages/ec-android-sdk/com/example/my_flutter_module/flutter_release/1.0/flutter_release-1.0.pom'.
```

when adding in app/build.gradle as mentioned [here.](https://docs.shorebird.dev/guides/add-to-app/android#update-your-android-app-to-use-this-version-of-the-flutter-module) 
I also tried with my package but getting same error.

**Comment by eseidel** [comment]
I'm very confused.  Why is it trying to load https://s3-ap-southeast-1.amazonaws.com/jp-build-packages/ec-android-sdk/com/example/my_flutter_module/flutter_release/1.0/flutter_release-1.0.pom?

Is com.example.my_flutter_module registered with some central gradle registry to point to that url?

**Comment by gaurav-zdroid** [comment]
Yes it is defined in project level  `build.gradle` -> `allprojects`

```
maven {
    url 'https://s3-ap-southeast-1.amazonaws.com/jp-build-packages/ec-android-sdk'
}
```

but this was already there and I am not able to understand why this link with `releaseImplementation 'com.example.my_flutter_module:flutter_release:1.0'`

**Comment by gaurav-zdroid** [comment]
@eseidel Above issues are resolved but now when I am running the command `shorebird release android`

Getting error 
```
PathNotFoundException: Directory listing failed, (OS Error: No such file or directory, errno = 2)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      AndroidInternetPermissionValidator.validate (package:shorebird_cli/src/validators/android_internet_permission_validator.dart:32:10)
#3      ShorebirdValidator.runValidators.<anonymous closure> (package:shorebird_cli/src/shorebird_validator.dart:96:31)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#6      Future.wait (dart:async/future.dart:523:26)
#7      ShorebirdValidator.runValidators (package:shorebird_cli/src/shorebird_validator.dart:95:44)
#8      ShorebirdValidator.validatePreconditions (package:shorebird_cli/src/shorebird_validator.dart:83:36)
#9      ReleaseAndroidCommand.run (package:shorebird_cli/src/commands/release/release_android_command.dart:71:32)
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#11     CompletionCommandRunner.runCommand (package:cli_completion/src/command_runner/completion_command_runner.dart:81:18)
#12     ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:167:30)
#13     ShorebirdCliCommandRunner.run.<anonymous closure> (package:shorebird_cli/src/command_runner.dart:96:19)
#14     _rootRun (dart:async/zone.dart:1399:13)
#15     _CustomZone.run (dart:async/zone.dart:1301:19)
#16     _runZoned (dart:async/zone.dart:1804:10)
#17     runZoned (dart:async/zone.dart:1747:10)
#18     runScoped (package:scoped/src/scoped.dart:64:10)
#19     ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:95:20)
#20     main.<anonymous closure> (file:///Users/gaurav/.shorebird/packages/shorebird_cli/bin/shorebird.dart:30:47)
#21     _rootRun (dart:async/zone.dart:1399:13)
#22     _CustomZone.run (dart:async/zone.dart:1301:19)
#23     _runZoned (dart:async/zone.dart:1804:10)
#24     runZoned (dart:async/zone.dart:1747:10)
#25     runScoped (package:scoped/src/scoped.dart:64:10)
#26     main (file:///Users/gaurav/.shorebird/packages/shorebird_cli/bin/shorebird.dart:29:11)
#27     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)
#28     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

For better understanding I am showing structure of my project

- my_project [React + Flutter]
  - app -> src (react)
  - android
  - ios
  - flutter_module (flutter)
     - .android
     - .ios

**Comment by gaurav-zdroid** [comment]
If we create release build with third party tool [[Bitrise](https://bitrise.io/)], then how will that build reflect/add on shorebird account and how we can push patch on that release build is not reflecting on dashboard.

**Comment by eseidel** [comment]
> 

Interesting.  https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/validators/android_internet_permission_validator.dart#L25 must report true, but
Then some part of https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/validators/android_internet_permission_validator.dart#L31 fails.  FYI @bryanoltman

**Comment by bryanoltman** [comment]
@gaurav-zdroid If I'm understanding correctly, you should be using `shorebird release aar` and *not* `shorebird release android`. `shorebird release android` is for apps that are entirely Flutter.

In any case, this shouldn't crash, and it looks like it does reliably when `shorebird release android` is run in a flutter module.

**Comment by bryanoltman** [comment]
Filed https://github.com/shorebirdtech/shorebird/issues/1253, closing this issue.

**Comment by eseidel** [comment]
Please let us know if using `shorebird release aar` does not resolve the issue!

**Comment by gaurav-zdroid** [comment]
Hi @eseidel `shorebird release aar` solve the problem and successfully aar file created, but as I asked above...

If we create release build with third-party tool [[Bitrise](https://bitrise.io/)], then how will that build reflect/add on shorebird account and how we can push patch on that release build which not reflecting on dashboard.

`shorebird release aar` create aar file but I this build is incomplete because it doesn't contain `React Native Code` 

I created a build from Bitrise, installed the build, and then made a patch, but the changes did not reflect. I think I have to add 
`shorebird release aar` command in bitrise workflow.
whats your thought?

**Comment by eseidel** [comment]
Yes, I suspect you need to add `shorebird release aar` as part of the bitrise workflow.  We're happy to help you work up some instructions on using bitrise with Shorebird, similarly to what we've done for GitHub and NeverCode:
https://docs.shorebird.dev/ci

**Comment by gaurav-zdroid** [comment]
Hi @eseidel, i tried to add this script but getting error.
First script runs successful 
<img width="989" alt="Screenshot 2023-09-23 at 12 51 10 AM" src="https://github.com/shorebirdtech/shorebird/assets/78362839/5d34eb9a-7728-48ed-af01-991a11e72467">


but when try to build aar cmd in second script it gives error `shorebird: command not found`

```
- script@1:
        title: Setup Shorebird
        inputs:
        - content: |

            cd $BITRISE_SOURCE_DIR

            # Install Shorebird
            curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

            # Add Shorebird to PATH
            echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
    - script@1:
        inputs:
        - content: |-

            cd $BITRISE_SOURCE_DIR
            sh install.sh
            shorebird release aar --release-version $AMI_VERSION_NAME
        title: Flutter Config
```

**Comment by bryanoltman** [comment]
`CM_ENV` appears to be a CodeMagic variable, so I don't think that will work on Bitrise. I'm not finding anything that clearly states how to edit PATH on bitrise, but it looks like they use a tool called envman (based on the docs at https://devcenter.bitrise.io/en/builds/environment-variables.html#setting-and-managing-env-vars-during-a-build)

**Comment by bryanoltman** [comment]
https://devcenter.bitrise.io/en/builds/installing-tools-during-a-build.html may also be relevant

**Comment by eseidel** [comment]
I'd recommend we also move to a new issue.  The danger of having this conversation on an older/closed issue is that we're more likely to not notice the new comments and fail to reply.  Otherwise we try to track all open customer issues and always reply.
