### ISSUE TITLE
feat: `shorebird` commands should not hang when run in CI

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1097]
Right now your options are to run `shorebird` with no flags and it will hang in CI when it hits a prompt.

Or you can run it with `--force` and it will say "yes" to every prompt.

1. We should never hang (maybe that's a mason_logger fix to detect non-interactive and always return the defaults?)
2. We should support failing instead of --force, so that CI can fail on a prompt (e.g. "this contains unpatchable changes are you sure you want to continue?") rather than hanging or continuing.

**Comment by felangel** [comment]
Regarding 2. we discussed something like `--no-prompt` which would use defaults and skip prompting but still fail on warnings (e.g. native changes detected).
