### ISSUE TITLE
fix: iOS patch reports changes for unchanged assets (.car files)

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1102]
**Description**

This is happening with the Adyen SDK.

**Steps To Reproduce**

1. Create a Flutter project
2. Initialize cocoapods
3. Add the Adyen pod
4. Make an iOS release
5. Make an iOS patch
6. See a report that two of the Adyen Assets.car files have changed, despite being the same code.

The .ipa crc32 is changing for these files, even though they have the same sha 256 checksum.

**Expected Behavior**

The unchanged files are not reported as changed.

**Comment by eseidel** [comment]
Wild.  That sounds like a bug in whatever generates the IPAs.  Maybe we can't trust the crc32's?  Maybe we need to check lengths too?

**Comment by bryanoltman** [comment]
Updating this, it seems like `.car` files can be different on disk (i.e., not bit-for-bit equivalent), but there is an `assetutil` tool that can be used to compare the contents of `.car` files. Going to see how much work it would be to use this.
