### ISSUE TITLE
ios-alpha: Error (Xcode): Error: Couldn't resolve the package 'flutter_gen' in 'package:flutter_gen/gen_l10n/app_localizations.dart'.

### ISSUE THREAD

**Issue by maherjaafar** [shorebirdtech/shorebird#1128]
**Description**

When I run: `shorebird patch ios-alpha --flavor staging -t lib/main_staging.dart`, it returns the error shown below

```
[WARN] iOS support is alpha. See https://docs.shorebird.dev/status#ios-alpha for more information.
✓ Fetching apps (0.7s)
✗ Failed to build: Error (Xcode): Error: Couldn't resolve the package 'flutter_gen' in 'package:flutter_gen/gen_l10n/app_localizations.dart'.
```

**Comment by HenrySarukh** [comment]
Hello, I am getting this kind of issue, when trying to release on android

**Comment by eseidel** [comment]
> Hello, I am getting this kind of issue, when trying to release on android

Would love to help, but we should probably start a new issue.

I might start by making sure that you've run `flutter pub get`?  I'm not sure if `shorebird release android` runs pub get before building.

**Comment by HenrySarukh** [comment]
Hello

The issue was related to Flutter's default localization, it is not adding flutter_gen to pubspec.yaml.

**Comment by eseidel** [comment]
> Hello
> 
> The issue was related to Flutter's default localization, it is not adding flutter_gen to pubspec.yaml.

Thank you for clarifying!  Would you be willing to open a new issue?  Ideally with the log from the failed build command?  We'd love to help!

**Comment by HenrySarukh** [comment]
I just cannot tell whether it is a shorebird build command issue or not.

**Comment by eseidel** [comment]
> I just cannot tell whether it is a shorebird build command issue or not.

Would *love* to support you, but need to do so on Discord or via a new issue.  This one is closed and from a very different era of the product.  Thanks!
