### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by TawhidHassan** [shorebirdtech/shorebird#1134]
**Description**

**Expected Behavior**

Shorebird Doctor when run give me :
Flutter install is correct (0.7s)
  [✗] Failed to determine Shorebird Flutter version. FlutterValidationException: Could not detect version number in output

**Screenshots**

If applicable, add screenshots to help expla
<img width="584" alt="Screenshot 2023-08-19 at 12 55 14 PM" src="https://github.com/shorebirdtech/shorebird/assets/43006217/e7717b53-15f9-42e1-81cd-585726d20846">
in your problem.

**Additional Context**

help me to solve this problem

**Comment by felangel** [comment]
Hi @TawhidHassan 
This is fixed on the main branch and will be available in the next release. Sorry for the inconvenience!

**Comment by eseidel** [comment]
Let us know if you're still seeing this. Thanks!
