### ISSUE TITLE
feat: The download feature has a process for users to know the progress of the download.

### ISSUE THREAD

**Issue by choepro577** [shorebirdtech/shorebird#1136]
i tried it and had a problem with my app. New updates take a long time to load, and there's no way of knowing how much progress is being made.

**Comment by eseidel** [comment]
I'd love to learn more.  How large are the updates?  I would expect them only to be a few hundred bytes or maybe a couple kilobytes (smaller than almost all web pages!) in size.  So any load delays are unlikely to be network related.

By default updates apply in the background on launch to require *two* re-launches of the app to apply (the first to get the update, the second to use the update).

It's also possible to trigger an update manually (which can remove one of the re-launches) with package:shorebird_code_push.

**Comment by eseidel** [comment]
I think this may be covered by https://github.com/shorebirdtech/updater/issues/38?
