### ISSUE TITLE
fix: `shorebird patch android` shows iOS versions too

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1139]
From a customer:
https://discord.com/channels/1030243211995791380/1125516353370075306/1143100427928338522

`When I try to apply the patch, it's asking me to select versions, but only +163 is for Android. Why is it displaying other iOS versions as well?`

![image](https://github.com/shorebirdtech/shorebird/assets/478541/880f36d1-15a2-4562-a1ff-5f7236157834)

![image](https://github.com/shorebirdtech/shorebird/assets/478541/35a3d010-641a-400f-9c46-43a17eaa6298)

**Comment by bryanoltman** [comment]
We no longer ask the user which version they would like to patch. Closing as obsolete.
