### ISSUE TITLE
App not recieving updates if apk is built with `shorebird release android --artifact apk --split-per-abi`

### ISSUE THREAD

**Issue by Chalwe19** [shorebirdtech/shorebird#1141]
Hello, lovely work you guys are doing. I have noticed an issue when you build using shorebird release android `--artifact apk --split-per-abi` and try and create a patch using `shorebird patch android`, the app will not receive an update. I thought it was a problem on my side so i tried using the example from the [shorebird_code_push package](https://pub.dev/packages/shorebird_code_push/example) and ran both `shorebird release android --artifact apk --split-per-abi` and `shorebird release android --artifact apk`  and noticed that only the later would receive updates. your guidance will highly be appreciated.

**Comment by eseidel** [comment]
Will take a look, thanks!

**Comment by eseidel** [comment]
Looking now.

**Comment by eseidel** [comment]
I've checked out shorebird_code_push, opened up the example, run `shorebird init -f` (to replace the provided shorebird.yaml with one with an app_id from my account).

I successfully ran `shorebird release android` and `shorebird preview` and correctly verified no updates (I haven't made a patch yet).

Then changed the theme color to blue and ran `shorebird patch android` and verified that the update worked.

Then I updated the build number in the pubspec from +21 to +22, and ran `shorebird release android --artifact apk`.

I uninstalled the existing "example" app on the emulator (to make sure it's gone) and then ran:
`adb install build/app/outputs/apk/release/app-release.apk` to install the apk-built one.
I launched it and verified it was blue (I had left the color change in).

I then changed the them color to orange and did another `shorebird patch android`.

Hmm, I see surprisingly large patch sizes:
`🕹️  Platform: android [arm64 (42.72 KB), arm32 (25.85 KB), x86_64 (25.79 KB)]`
(But maybe they were that way the first time too and I just didn't notice.)

Patch worked as expected.

Ok, now updating to +23 and trying `shorebird release android --artifact apk --split-per-abi`

Well, for one, it gives me the wrong path, it says:
`build/app/outputs/apk/release/app-release.apk`, but the apks are really:
`app-arm64-v8a-release.apk   app-armeabi-v7a-release.apk app-x86_64-release.apk` under that directory.

Removing the existing example app from the phone.

Installing with `adb install build/app/outputs/apk/release/app-arm64-v8a-release.apk`
Launched fine, now changing color to purple and trying patching:  `shorebird patch android`

This now had surprisingly (but appropriately) small patch sizes:
`🕹️  Platform: android [arm64 (241 B), arm32 (253 B), x86_64 (331 B)]`

But yes... the "check for update" button is not working it seems.

The check for update button doesn't even cause any logs to appear in `adb logcat -s flutter`, however relauching the app does (but still does not get an update).

Clearly more to debug.

Thanks for the report!

**Comment by eseidel** [comment]
My first guess would be that:
https://github.com/shorebirdtech/updater/blob/main/library/src/android.rs#L108 is wrong? e.g. that we fail to find the base apk.  I would expect it to long in that case (which I don't see).  I'm not sure.

**Comment by bryanoltman** [comment]
I was able to reproduce what I think the issue is:

1. Created a new Flutter app
2. Initialized shorebird
3. Created a release with `shorebird release android --artifact apk --split-per-abi`
4. Dragged one of the apks onto the emulator to install
5. Saw in logcat that the build number is being reported as `1.0.0+2001` despite the pubspec.yaml having a version `1.0.0+1`.

**Comment by bryanoltman** [comment]
This is a known issue https://github.com/flutter/flutter/issues/39817, going to see if we can provide a reasonable workaround.

**Comment by bryanoltman** [comment]
@Chalwe19 can you tell us about your use case for generating split apks? Was this just for development, or is this part of your app distribution?

**Comment by mobiledevelopment25** [comment]
Hi, i can't split my apk with "shorebird release android --artifact=apk --split-per-abi", but i get this log:

> Shorebird does not support the split-per-abi option at this time
> Split APKs are each given a different release version than what is specified in the pubspec.yaml.

Is this not supported or i'm doing something wrong? If this is not supported i think i can't use shorebird because i need split per abi. Any help please ?
