### ISSUE TITLE
feat: Ability to install a particular version of cli

### ISSUE THREAD

**Issue by ghost** [shorebirdtech/shorebird#1151]
**Description**

I  should be able to install a particular version of cli like 
`curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash -s -- --version 0.13.2`

**Additional Context**

In my cicd builds are failing after new [v0.14.2](https://github.com/shorebirdtech/shorebird/releases/tag/v0.14.2) release due to issues in flutter in latest version . But it is working in  Shorebird [v0.13.2](https://github.com/shorebirdtech/shorebird/releases/tag/v0.13.2) .
I had to make changes in https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh to install older version by checking out commit for  [v0.13.2](https://github.com/shorebirdtech/shorebird/releases/tag/v0.13.2) . 
```echo "Cloning Shorebird into $(install_dir)"  
git clone https://github.com/shorebirdtech/shorebird.git -b stable "$(install_dir)"  
cd "$(install_dir)"  
git checkout 37303df76d5493d0e51f551db2781e75ce521b48

**Comment by ghost** [comment]
for the time being we can use this workaround 
``` 
install_dir() {
 [ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.shorebird" || printf %s "${XDG_CONFIG_HOME}/shorebird"
}
git clone https://github.com/shorebirdtech/shorebird.git -b stable "$(install_dir)" 
cd $(install_dir) && git checkout tags/v0.13.2 #replace with your required version 
export PATH="/home/vsts/.config/shorebird/bin:$PATH"
shorebird --version
``` 
`shorebird --version` will download all required dependencies when ran first time including flutter

**Comment by eseidel** [comment]
Would this be resolved if https://github.com/shorebirdtech/shorebird/pull/1190 lands?

**Comment by eseidel** [comment]
The problem with supporting this is that we currently have a "tight coupling" between our CLI and server.  Sometimes we make breaking changes on our Server which required all CLI clients to upgrade.  So while we could support this, it would break often (sometimes quickly).  I think we will need to revisit that "tight coupling" (making it a "loose coupling") before we can support this.

Closing for now.  Thank you again for the suggestion.
