### ISSUE TITLE
fix: `flutter` prefers Android Studio over JAVA_HOME for java

### ISSUE THREAD

**Issue by MohammedAbdulaziz** [shorebirdtech/shorebird#1163]
When i use ```shorebird preview``` I get this error after ```shorebird release android```
 
this is the error 
```shorebird preview
Which app would you like to preview?
Which app would you like to preview? next
✓ Fetching releases (0.2s)
Which release would you like to preview?
❯ ◉  1.0.1+1

Which release would you like to preview? 1.0.1+1
Which platform would you like to preview? android
✓ Fetching aab artifact (0.2s)
✓ Downloading release (14.2s)
✗ Exception: Failed to extract package name from app bundle: Error while parsing the flags: Syntax error: flags should start with -- (Abdelaziz\.shorebird\bin\cache\previews\7475aa43-6d88-4cdb-8f0e-08f8d117e2eb\android_1.0.1+1.aab)
 (0.2s)
```

this is my ```shorebird doctor```

```shorebird doctor
Shorebird 0.14.3 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.0 • revision d84d466eacbeb47d6e81e960c22c6fdfe5a3917d
Engine • revision a4613505045177f96d7cbfbb42335e2db7cf7b51

✓ Shorebird is up-to-date (1.4s)
✓ Flutter install is correct (1.4s)
✓ AndroidManifest.xml files contain INTERNET permission (99ms)

No issues detected!
```

**Comment by bryanoltman** [comment]
I'm not able to reproduce this. It would be helpful to know:

1. What OS you're running on
2. What the full output of `shorebird preview -v` is

**Comment by MohammedAbdulaziz** [comment]
> I'm not able to reproduce this. It would be helpful to know:
> 
> 1. What OS you're running on

This is my OS specifications
Edition	Windows 10 Home
Version	21H2
Installed on	‎8/‎14/‎2021
OS build	19044.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0

> 2. What the full output of `shorebird preview -v` is

This is the full output of `shorebird preview -v`
```shorebird preview -v
[HTTP] POST https://oauth2.googleapis.com/token
⠋ Fetching apps... (1.6s)[HTTP] GET https://api.shorebird.dev/api/v1/apps
✓ Fetching apps (2.3s)
Which app would you like to preview? next
[HTTP] GET https://api.shorebird.dev/api/v1/apps/7475aa43-6d88-4cdb-8f0e-08f8d117e2eb/releases
✓ Fetching releases (0.2s)
Which release would you like to preview? 1.0.3+1
Which platform would you like to preview? android
⠦ Extracting metadata... (24.5s)[Process.run] A:\Downloads\Folders\jdk1.8.0_202\bin\java.exe -jar C:\Users\Mohammad Abdelaziz\.shorebird\bin\cache\artifacts\bundletool\bundletool.jar dump manifest --bundle=C:\Users\Mohammad Abdelaziz\.shorebird\bin\cache\previews\7475aa43-6d88-4cdb-8f0e-08f8d117e2eb\android_1.0.3+1.aab --xpath /manifest/@package
✗ Exception: Failed to extract package name from app bundle: Error while parsing the flags: Syntax error: flags should start with -- (Abdelaziz\.shorebird\bin\cache\previews\7475aa43-6d88-4cdb-8f0e-08f8d117e2eb\android_1.0.3+1.aab)
 (35.6s)```

**Comment by eseidel** [comment]
That's very helpful, thank you!

**Comment by eseidel** [comment]
It looks like it's using Java 1.8.0 (a 10 year old version of Java) which I'm not sure if bundle tool supports.  It looks like it has some support for it:
https://github.com/google/bundletool/blob/master/build.gradle#L100

I suspect you have JAVA_HOME set.

Do `flutter doctor` and `shorebird doctor` both run cleanly?  Does `flutter doctor -v` show that it's using your Java 1.8.0 or something else?  If `flutter doctor` is picking a different Java that `shorebird` is, we may need to update our Shorebird code to avoid older java versions?

**Comment by eseidel** [comment]
I would try:
`Remove-Variable JAVA_HOME` and see if it works after JAVA_HOME is unset.  Android Studio comes with its own Java (which `flutter` and `shorebird` know how to find).

**Comment by MohammedAbdulaziz** [comment]
Flutter doctor was showing a different java version, yes.
I removed JAVA_HOME, now shorebird doctor -v gives JAVA_HOME undetected
now running `shorebird release android --artifact apk` then `shorebird preview` surprisingly gives the same error
so I skipped preview all together and just manually installed the apk on my device and tested patch 😅

**Comment by eseidel** [comment]
Can you share the output from `shorebird doctor -v`?  You should not have to install by yourself (you're always welcome to of course), but we'd like to fix `shorebird preview` to work correctly for you (and others)!

**Comment by MohammedAbdulaziz** [comment]
of course,
 ```
 shorebird doctor -v
Shorebird 0.14.6 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.10.1 • revision 7cd77f78a51576652edc337817152abf4217a257
Engine • revision 13201c941a044e30b59cbb2c8f87c1033ffce661

Android Toolchain
  • Android Studio: not detected
  • Android SDK: B:\Sdk
  • ADB: B:\Sdk\platform-tools\adb.exe
  • JAVA_HOME: not detected

✓ Shorebird is up-to-date (1.5s)
✓ Flutter install is correct (2.9s)
✓ AndroidManifest.xml files contain INTERNET permission (66ms)

No issues detected!
```

this is my `flutter doctor -v` as well for reference 
```
flutter doctor -v
[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.19044.1826], locale en-US)
    • Flutter version 3.10.1 on channel stable at A:\Downloads\Compresssed\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (4 months ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at B:\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = B:\Sdk
    • ANDROID_SDK_ROOT = B\Sdk
    • Java binary at: A:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.4)
    • Visual Studio at A:\Microsoft Visual Studio
    • Visual Studio Community 2022 version 17.6.33815.320
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include
      these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.2)
    • Android Studio at A:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\Mohammad Abdelaziz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (4 available)
    • SM G770F (mobile) • RF8N60WLGMJ • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 116.0.5845.111
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 116.0.1938.69

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by eseidel** [comment]
I think the work for us here is to better validate/explain bundletool constraints.  I think we should assume that bundletool requires a recent java.

We also may want to change our java lookup to match what Flutter does more closely?  Does Flutter prefer AndroidStudio over JAVA_HOME if it can find it?  We seem to have a variety of complaints involving JAVA_HOME pointing to an old java and I wonder if we're respecting JAVA_HOME when Flutter is not?

**Comment by MohammedAbdulaziz** [comment]
> I wonder if we're respecting JAVA_HOME when Flutter is not?

I have had an experience where I set JAVA_HOME to a path of java.exe
And flutter doctor came back with an error in Android Studio criteria saying something like run flutter doctor --android-licenses to accept something and that JAVA_HOME is set to an incorrect path and when I unset JAVA_HOME it worked fine, but when I had my JAVA_HOME set to an older version of JDK like in this issue here, Flutter seemed to ignore it and use a newer version anyways unlike shorebird which relied on the old version

**Comment by eseidel** [comment]
Very interesting.  Thanks for the context.

Looks like Flutter *does* prefer Android Studio over JAVA_HOME?
https://github.com/flutter/flutter/blob/969911d1d09d6c4f145e9ce27c08093e8c285561/packages/flutter_tools/lib/src/commands/config.dart#L25

I haven't been able to find the code which supports it doing that, but at least the help text claims it does?

**Comment by MohammedAbdulaziz** [comment]
i think you can find the code here 
https://github.com/flutter/flutter/blob/e7058f568faf49458f83d479577f66c923bf8445/packages/flutter_tools/lib/src/commands/config.dart#L217
I might be wrong though

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/shorebird/issues/1213 is somewhat related as well.

**Comment by eseidel** [comment]
For those reading this, a workaround if you have Android Studio installed is:
```
unset JAVA_HOME
```
Which will remove the JAVA_HOME environment variable for that terminal session.  (It will still be there next time you open a terminal window.) Flutter (and Shorebird) know how to find Java from inside Android Studio, even if you don't have JAVA_HOME set.

I expect we'll also fix this bug soon (hopefully this week).  Thanks for your patience.

**Comment by eseidel** [comment]
We've fixed this on main, we expect to release the fix later this week!
