### ISSUE TITLE
feat: In app notification to restart

### ISSUE THREAD

**Issue by vyPal** [shorebirdtech/shorebird#1166]
**Description**

Essentially this would allow an app to show a notification or banner or something when a patch has been found and downloaded, so that the user can know to restart the app.

**Additional Context**

I just think it would be nice to be able to tell the user when to restart the app, or to leave it open so that the patch can finish downloading. Something like https://github.com/shorebirdtech/shorebird/issues/1136

**Comment by eseidel** [comment]
This should be possible today with https://pub.dev/packages/shorebird_code_push.

Or maybe I've misunderstood?

**Comment by vyPal** [comment]
Oh, didn't know about that. It's basically what I wanted, thanks! (Closing this now)
