### ISSUE TITLE
`shorebird patch android` 404 when fetching release artifact

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1167]
**Description**

[Discord thread](https://discord.com/channels/1030243211995791380/1143884992007655448)

A customer has reported that, after a successful release, they cannot patch due to one of the release artifacts not being found.

![image](https://github.com/shorebirdtech/shorebird/assets/581764/490109f9-5446-4b22-99c1-58d0ae6dcf90)

![image](https://github.com/shorebirdtech/shorebird/assets/581764/922b712a-118f-4bd3-9360-484c7d735a08)

**Comment by bryanoltman** [comment]
The [cloud storage bucket](https://console.cloud.google.com/storage/browser/shorebird_release_artifacts/cc6b6010-07b3-4048-acde-b3ce607866c9/android?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=code-push-prod&prefix=&forceOnObjectsSortingFiltering=false) for this app shows missing artifacts for releases (some releases are missing an architecture, but which architecture is missing does not seem to be consistent), so it's possible something is failing in the release command?

**Comment by eseidel** [comment]
I'm not sure what we should do with this bug?  We've definitely seen other times where releases have been missing due to what we believe to be customers having canceled release commands.  Not sure if that's what applied here.

Not sure what our next steps are here other than to close.

**Comment by bryanoltman** [comment]
I think you're right. The user has not responded in discord with more info, so my best (and only) guess was that the release command didn't succeed. Closing for the time being.
