### ISSUE TITLE
feat: gradle errors should explain what command they were running

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1169]
From discord:
```
omarsfd@Omars-MacBook-Pro cloundry-guest-ui % shorebird init 
✗ Detecting product flavors (1.1s)
Unable to extract product flavors.
Exception: 
ERROR: JAVA_HOME is set to an invalid directory: /Library/Java/JavaVirtualMachines/jdk-11.0.18.jdk/Contents/Home

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

omarsfd@Omars-MacBook-Pro cloundry-guest-ui % echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-11.0.18.jdk/Contents/Home
```

Which is coming from:
https://github.com/shorebirdtech/shorebird/blob/ff86a5a46bae501bf7928fa03884fb356085534b/packages/shorebird_cli/lib/src/commands/init_command.dart#L91
Caused by:
https://github.com/shorebirdtech/shorebird/blob/ff86a5a46bae501bf7928fa03884fb356085534b/packages/shorebird_cli/lib/src/gradlew.dart#L59

I suspect the real fix is that our "Process.run" should catch exceptions and wrap them in an exception which includes the command which failed?  Or at least something needs to add that context to the exception if callers are going to be able to print something useful.

**Comment by eseidel** [comment]
Slightly related to https://github.com/shorebirdtech/shorebird/issues/2211.  When we're running subprocesses it's sometimes hard to debug when they fail or hang.

**Comment by erickzanardo** [comment]
I believe we can close this.

with the recent improvements that we did with logging errors, we will be able to see which command were ru, any command, not only gradlew, in the log file, or in the output if running on verbose mode.

Example, I ran `shorebird init` and forced an error which gave me:

```
✗ Detecting product flavors (3.3s)
Unable to extract product flavors.
Exception: > Task :gradle:compileJava NO-SOURCE
> Task :gradle:compileGroovy FAILED
1 actionable task: 1 executed


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gradle:compileGroovy'.
> BUG! exception in phase 'semantic analysis' in source unit '/Users/erick/flutter/packages/flutter_tools/gradle/src/main/groovy/app_plugin_loader.groovy' Unsupported class file major version 66

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s


If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
/Users/erick/Library/Application Support/shorebird/logs/1718808056713_shorebird.log
```

Then if I `cat "/Users/erick/Library/Application Support/shorebird/logs/1718808056713_shorebird.log"`

The first line is:

```
2024-06-19T11:40:56.756077 [Process.run] /Users/erick/projects/shorebird/no_time_to_release/android/gradlew app:tasks --all --console=auto (in /Users/erick/projects/shorebird/no_time_to_release/android)
```

**Comment by eseidel** [comment]
sgtm.
