### ISSUE TITLE
Add a restart app API

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#117]
When we show an update UI we need a "restart" button, that button needs to be wired up to something.

**Comment by eseidel** [comment]
Might just write it from the Dart side for now?

https://stackoverflow.com/questions/6609414/how-do-i-programmatically-restart-an-android-app

**Comment by faustobdls** [comment]
Android:

```kt
private fun restartApp() {
        context.startActivity(
            Intent.makeRestartActivityTask(
                (context.packageManager.getLaunchIntentForPackage(
                    context.packageName
                ))!!.component
            )
        )
        Runtime.getRuntime().exit(0)
    }
```

For Android, I believe that the ideal is a mix between what you suggested and this function, the part of clearing the intent makes a lot of sense, to save resources

iOS

https://stackoverflow.com/questions/66205648/is-there-any-way-to-restart-my-ios-app-programmatically/66206070#66206070

For iOS there is the problem of needing to run the register plugin again, other than that they were the best solutions I found.

**Comment by eseidel** [comment]
Thank you!

**Comment by eseidel** [comment]
We have an example of this now, but we don't currently have plans to add this api to our engine.  package:restart_app does this.

https://github.com/shorebirdtech/updater/tree/main/shorebird_code_push/example
https://github.com/shorebirdtech/fluttercon_demo

**Comment by hussam-supy-io** [comment]
> We have an example of this now, but we don't currently have plans to add this api to our engine. package:restart_app does this.
> 
> https://github.com/shorebirdtech/updater/tree/main/shorebird_code_push/example https://github.com/shorebirdtech/fluttercon_demo

I just tried restart_app package, but it didn't work. I still need to kill the app and open it again
Android 16
