### ISSUE TITLE
feat: Would like to be able to target newer version code against older release versions

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1170]
See also https://github.com/shorebirdtech/shorebird/pull/1108#issuecomment-1690635889

Would like to be able to target newer version code against older release versions

e.g. Did a bunch of updates have "1.0.3+1" and want to be able to use those sources to patch "1.0.2+1" without editing pubspec.yaml (or other files) to change the release number.

**Comment by bryanoltman** [comment]
This has been fixed – we prompt users for a release version when patching.
