### ISSUE TITLE
feat: webhooks

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#1176]
**Description**

As a developer, I want to be able to configure webhooks so that shorebird can notify a custom endpoint whenever various events occur (e.g. apps created/delete, releases created/deleted, patches created/deleted).

The use case I have in mind is a custom backend component that sends silent notifications to devices when a new patch is available.

**Comment by eseidel** [comment]
I would just use your app as a test balloon before we commit to any specific API.

I wouldn't be surprised if we end up offering our own notification service, similar to what Expo does.

**Comment by FirdousNath** [comment]
It would be helpful to send a message on slack/google-chat whenever we release a new patch

**Comment by eseidel** [comment]
Would be nice.  We've gotten very few requests for this, so I think I'm going to close this for now and we can re-open later.

**Comment by nicolarigoni** [comment]
@eseidel  I'm also interested on this. I would be very usefull fo us too. In order to set the minimum patch requirement on our apps and to make the updated required or not
