### ISSUE TITLE
fix: Is There a problem the console web stie?

### ISSUE THREAD

**Issue by cafefarm-johnny** [shorebirdtech/shorebird#1180]
**Description**

When i visit `console.shorebird.dev` then show Get Started page and now i can't use release command from CLI. please see below output.

**Steps To Reproduce**

1. Visit "console.shorebird.dev"
2. Show "Get Started" page.

1. Execute release command in terminal.
2. Then print fail message.

**Expected Behavior**

I want to visit Web Console page and use release command.

**Screenshots**

<img width="1820" alt="iShot_2023-08-29_11 07 31" src="https://github.com/shorebirdtech/shorebird/assets/44919702/7838e3c9-2d09-49cc-b50c-d7d69a7a0dc1">

**Additional Context**

```bash
$ shorebird release android --artifact apk --flavor prod --force
✓ Building release (16.1s)
✓ Fetching apps (0.5s)
Could not find app with id: "8f252fe1-769b-4418-b7f6-3a70258724df".
This app may not exist or you may not have permission to view it.
```

**Comment by felangel** [comment]
Hi @cafefarm-johnny 👋 
It looks like the app_id in your shorebird.yaml does not belong to the email you are signed in with in the console. Can you ensure that you are signed into the same account in the console and in the CLI? You can re-initialize the project and generate a new `app_id` by running `shorebird init --force`. Let me know if that helps!

**Comment by cafefarm-johnny** [comment]
Hi @felangel 👋
When i checked account it logged-in same account from console, CLI. 
Just i tried re-initialize you told me and solved. Thank you. :)
