### ISSUE TITLE
fix: iOS builds sometimes crash after update

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1183]
@felangel is able to repro, but I have not been.  I have a theory (namely that we're necessarily loading the pages of the snapshot as executable, and that's confusing the OS into thinking we're executing unsigned code, when we're in fact not).

Here are two crash reports.
[message (7).txt](https://github.com/shorebirdtech/shorebird/files/12469624/message.7.txt)
[message (6).txt](https://github.com/shorebirdtech/shorebird/files/12469625/message.6.txt)

**Comment by felangel** [comment]
New crash report using engine revision: 7163af137c15715735168474b1487df81fef9a65
[always-crashing.txt](https://github.com/shorebirdtech/shorebird/files/12477732/always-crashing.txt)

**Comment by eseidel** [comment]
> New crash report using engine revision: 7163af137c15715735168474b1487df81fef9a65 [always-crashing.txt](https://github.com/shorebirdtech/shorebird/files/12477732/always-crashing.txt)

Fascinating.  That one crashes much earlier:
```Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   Flutter                       	       0x1012c9600 dart::BSS::Initialize(dart::Thread*, unsigned long*, bool) (in Flutter) (bss_relocs.cc:42) + 10507776
1   Flutter                       	       0x1012c9590 dart::BSS::Initialize(dart::Thread*, unsigned long*, bool) (in Flutter) (bss_relocs.cc:36) + 10507664
2   Flutter                       	       0x1012c7c54 dart::FullSnapshotReader::ReadVMSnapshot() (in Flutter) (app_snapshot.cc:9201) + 10501204
3   Flutter                       	       0x1012cd268 dart::Dart::DartInit(Dart_InitializeParams const*) (in Flutter) (dart.cc:436) + 10523240
4   Flutter                       	       0x1013d9770 Dart_Initialize (in Flutter) (dart_api_impl.cc:1212) + 11622256
5   Flutter                       	       0x101283a14 flutter::DartVMRef::Create(flutter::Settings const&, fml::RefPtr<flutter::DartSnapshot const>, fml::RefPtr<flutter::DartSnapshot const>) (in Flutter) (dart_vm_lifecycle.cc:78) + 10222100
6   Flutter                       	       0x10108ac44 flutter::Shell::Create(flutter::PlatformData const&, flutter::TaskRunners const&, flutter::Settings, std::_LIBCPP_ABI_NAMESPACE::function<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::PlatformView, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::PlatformView>> (flutter::Shell&)> const&, std::_LIBCPP_ABI_NAMESPACE::function<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::Rasterizer, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::Rasterizer>> (flutter::Shell&)> const&, bool) (in Flutter) (shell.cc:165) + 8154180```

**Comment by eseidel** [comment]
> > New crash report using engine revision: 7163af137c15715735168474b1487df81fef9a65 [always-crashing.txt](https://github.com/shorebirdtech/shorebird/files/12477732/always-crashing.txt)
> 
> Fascinating. That one crashes much earlier:
> 
> ```
> Thread 0 Crashed:
> 0   Flutter                       	       0x1012c9600 dart::BSS::Initialize(dart::Thread*, unsigned long*, bool) (in Flutter) (bss_relocs.cc:42) + 10507776
> 1   Flutter                       	       0x1012c9590 dart::BSS::Initialize(dart::Thread*, unsigned long*, bool) (in Flutter) (bss_relocs.cc:36) + 10507664
> 2   Flutter                       	       0x1012c7c54 dart::FullSnapshotReader::ReadVMSnapshot() (in Flutter) (app_snapshot.cc:9201) + 10501204
> 3   Flutter                       	       0x1012cd268 dart::Dart::DartInit(Dart_InitializeParams const*) (in Flutter) (dart.cc:436) + 10523240
> 4   Flutter                       	       0x1013d9770 Dart_Initialize (in Flutter) (dart_api_impl.cc:1212) + 11622256
> 5   Flutter                       	       0x101283a14 flutter::DartVMRef::Create(flutter::Settings const&, fml::RefPtr<flutter::DartSnapshot const>, fml::RefPtr<flutter::DartSnapshot const>) (in Flutter) (dart_vm_lifecycle.cc:78) + 10222100
> 6   Flutter                       	       0x10108ac44 flutter::Shell::Create(flutter::PlatformData const&, flutter::TaskRunners const&, flutter::Settings, std::_LIBCPP_ABI_NAMESPACE::function<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::PlatformView, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::PlatformView>> (flutter::Shell&)> const&, std::_LIBCPP_ABI_NAMESPACE::function<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::Rasterizer, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::Rasterizer>> (flutter::Shell&)> const&, bool) (in Flutter) (shell.cc:165) + 8154180```
> ```

Turns out this was that my fix was wrong.  I have a better fix for you to try, building now.

**Comment by eseidel** [comment]
Felix reports that this fixed the bug.

The fix was to simply not mark some of the pages of memory executable (we were never executing anything from them anyway).  As far as I can tell, if you ever mark a page executable and then try to read from it, iOS may kill your process (on some versions of the OS but not all?) even if you never are actually executing the code, just reading it.

Fix is posted, should be landing shortly.

**Comment by eseidel** [comment]
We're working on the builds now, should have 0.14.3 out with the fix either later today or tomorrow.
