### ISSUE TITLE
fix: ios - Bug when create patch on ios-alpha: Release not found

### ISSUE THREAD

**Issue by giapnhgc** [shorebirdtech/shorebird#1188]
**Bug when create patch on ios-alpha: Release not found**

I released 1.0.12+2 then I create patch. Its show Release not found: "1.0.12+3".

**Screenshots1**
<img width="1303" alt="Screenshot 2023-08-30 at 11 08 17" src="https://github.com/shorebirdtech/shorebird/assets/36390095/71af517d-ffa2-498c-9023-a515c87f2bb5">

Then I changed version to 1.0.12+3 on pubspec.yaml -> run flutter clean, flutter pub get ->After that, I built release with shorebird command => It worked. But I got this problem on image when create patch. It show  Release not found: "1.0.12+4" => but I did not change version to 1.0.12+4

**Screenshots2**
<img width="1303" alt="Screenshot 2023-08-30 at 09 22 41" src="https://github.com/shorebirdtech/shorebird/assets/36390095/6e959bc7-eeef-47de-b630-dcf7cae5f0b0">

**Comment by eseidel** [comment]
@bryanoltman is this auto-version management from xcode?  Or maybe us not respecting the --build-number flag (or not seeing it since it was passed through to flutter?

**Comment by bryanoltman** [comment]
I suspect @eseidel is correct.

@giapnhgc can you share the contents of your `export.plist`? Shorebird will not work if `manageAppVersionAndBuildNumber` is `true`.

**Comment by giapnhgc** [comment]
This is my export.plist and yes manageAppVersionAndBuildNumber in mycontent is true. Let me change it back to false and try as you answered...
```
<dict>
	<key>destination</key>
	<string>export</string>
	<key>manageAppVersionAndBuildNumber</key>
	<true/>
	<key>method</key>
	<string>app-store</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>com.myapp.app</key>
		<string>DistributeKey</string>
	</dict>
	<key>signingCertificate</key>
	<string>Apple Distribution</string>
	<key>signingStyle</key>
	<string>manual</string>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>teamID</key>
	<string>MYTEAMID</string>
	<key>uploadSymbols</key>
	<true/>
</dict>
</plist>
```

**Comment by giapnhgc** [comment]
@eseidel @bryanoltman Its works correct. The `manageAppVersionAndBuildNumber` must change to `false`.

![Screenshot 2023-09-01 at 10 20 11](https://github.com/shorebirdtech/shorebird/assets/36390095/c4598475-009e-41ad-b058-19ba3fc425c4)

Thanks guys! 😄
