### ISSUE TITLE
fix: ✗ Failed to build: Flutter assets will be downloaded

### ISSUE THREAD

**Issue by asadamatic** [shorebirdtech/shorebird#1192]
**Description**

After upgrading to `Flutter 3.13.1, `shorebird release android` command fails.
```
✗ Failed to build: Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
```

**Steps To Reproduce**

1. Switch to `Flutter 3.13.1` using `shorebird flutter versions use 3.13.1`
2. Create android releae using `shorebird release android --flavor flavor_name --target path_main` 

**Expected Behavior**

Should generate an appbundle.

**Additional Context Behavior**

`flutter build appbundle --release` works fine.

<details><summary>Logs</summary>
<p>
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkStagingReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':app:stagingReleaseRuntimeClasspath'.
   > Could not resolve io.flutter:armeabi_v7a_release:1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770.
     Required by:
         project :app
      > Could not resolve io.flutter:armeabi_v7a_release:1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770.
         > inconsistent module metadata found. Descriptor: io.flutter:armeabi_v7a_release:1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae Errors: bad version: expected='1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770' found='1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae'
   > Could not resolve io.flutter:arm64_v8a_release:1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770.
     Required by:
         project :app
      > Could not resolve io.flutter:arm64_v8a_release:1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770.
         > inconsistent module metadata found. Descriptor: io.flutter:arm64_v8a_release:1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae Errors: bad version: expected='1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770' found='1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae'
   > Could not resolve io.flutter:x86_64_release:1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_64_release:1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770.
         > inconsistent module metadata found. Descriptor: io.flutter:x86_64_release:1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae Errors: bad version: expected='1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770' found='1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae'
   > Could not resolve io.flutter:flutter_embedding_release:1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770.
     Required by:
         project :app > project :firebase_core
         project :app > project :flutter_pdfview
         project :app > project :firebase_crashlytics
         project :app > project :flutter_plugin_android_lifecycle
         project :app > project :flutter_local_notifications
         project :app > project :url_launcher_android
         project :app > project :file_picker
         project :app > project :path_provider_android
         project :app > project :flutter_secure_storage
         project :app > project :flutter_native_splash
         project :app > project :image_cropper
         project :app > project :shared_preferences_android
         project :app > project :permission_handler_android
         project :app > project :flutter_isolate
         project :app > project :open_file
         project :app > project :share_plus
         project :app > project :package_info_plus
         project :app > project :device_info_plus
         project :app > project :image_picker_android
         project :app > project :firebase_messaging
         project :app > project :stripe_android
      > Could not resolve io.flutter:flutter_embedding_release:1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770.
         > inconsistent module metadata found. Descriptor: io.flutter:flutter_embedding_release:1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae Errors: bad version: expected='1.0.0-e7bdf38443dff65d64446d6ca4074a35a587c770' found='1.0.0-401e07ae76c9e3d9ba1a427a92b9b89a2ba3cbae'
</p>
</details>

**Comment by mustafaezer** [comment]
Getting the same error on Azure DevOps Pipelines as well:

`✗ Failed to build: Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
Can't load Kernel binary: Invalid kernel binary format version.
Dart snapshot generator failed with exit code 254
`

**Comment by felangel** [comment]
I’m seeing this in our e2e as well. Will look into it shortly.

**Comment by felangel** [comment]
I believe this should be resolved now re-running the e2e and doing smoke tests. It may take up to an hour for the change to take effect since storage artifacts have a cache max-age of 1 hour. Really sorry for the inconvenience!

**Comment by felangel** [comment]
All of our e2e tests are passing again so I'm closing this issue but feel free to let us know if you're still encountering the same issue.

**Comment by asadamatic** [comment]
It is working now.

**Comment by mustafaezer** [comment]
I can confirm this on our end as well—thanks for the quick fix! ✨
