### ISSUE TITLE
feat: move shorebird artifact downloads behind CDN

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#120]

**Comment by eseidel** [comment]
This could bring two known benefits:
1. Would reduce our network costs (which are the bulk of our unit costs at the moment).
2. Might make Shorebird available in more parts of the world (not all parts of the world can access Google Cloud Storage urls).

**Comment by eseidel** [comment]
This might also be one part of resolving https://github.com/shorebirdtech/shorebird/issues/435

**Comment by eseidel** [comment]
This was originally about "engine" downloads, but I've broadened it to all artifact downloads.

**Comment by edeuss** [comment]
@eseidel Would be good to look into Backblaze B2 + Cloudflare CDN. We save thousands of dollars a month by using this combo.

**Comment by eseidel** [comment]
Agreed.  We can definitely save a lot on costs by changing our network setup.  We're still focused on fixing bugs blocking adoption (like iOS slowness on some patches, and artifact signing -- for several large fin-tech customers), but I suspect we'll do another round of infra updates, including moving to a CDN in the next couple months.

**Comment by eseidel** [comment]
> @eseidel Would be good to look into Backblaze B2 + Cloudflare CDN. We save thousands of dollars a month by using this combo.

Yeah, this is what we're finding as well.  Felix has done some prototyping with Cloudflare and it looks likely to save us 2/3rds of our cloud bill 🤣  and potentially give us better reachability.  We've also reached out to our Google cloud contact to see if they have suggestions.

**Comment by edeuss** [comment]
@eseidel Yep for the company I worked for it removed basically all egress costs and only thing we really had to pay for was storage. It's an amazing deal, plus with only 6$ per terabyte.

**Comment by felangel** [comment]
This should be done now 🎉
