### ISSUE TITLE
feat: Support 3.0.6 flutter 

### ISSUE THREAD

**Issue by pushpendraKh** [shorebirdtech/shorebird#1201]
**Description**

We are currently on 3.0.6 flutter version but Shorebird is not supporting it. Requesting to support this version also.

**Comment by eseidel** [comment]
Thanks for the issue!  It will probably be a while before we can support this specific version, but I've filed https://github.com/shorebirdtech/shorebird/issues/1100 to track the general idea of adding more versions.
