### ISSUE TITLE
fix: Changes in language files are not updated

### ISSUE THREAD

**Issue by yusufsirinn** [shorebirdtech/shorebird#1207]
When I make changes or additions to the language file (en.json), I cannot update it with code push.

**Comment by vyPal** [comment]
I believe this is not a bug.
As stated here: https://docs.shorebird.dev/faq#what-types-of-changes-does-shorebird-code-push-support

> Shorebird can change any Dart code in your application.

So if you use a system with json files and your app reads the files, then code push doesn't work for that. If you use something like [this](https://docs.flutter.dev/ui/accessibility-and-localization/internationalization#adding-your-own-localized-messages) where a tool converts your arb files into dart files, it should work (not sure, haven't tested)

**Comment by eseidel** [comment]
I suspect we will support this as part of https://github.com/shorebirdtech/shorebird/issues/318, but don't yet.  Thanks for the issue!

**Comment by eseidel** [comment]
Going to resolve this in favor of #318, please let us know if that's incorrect.
