### ISSUE TITLE
Fix rust build to build updater.h automatically

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#121]

**Comment by eseidel** [comment]
The bug is that you currently have to run `cbindgen` manually instead of having it be part of `build.rs` or similar:
https://github.com/shorebirdtech/shorebird/blob/main/updater/library/README.md

**Comment by eseidel** [comment]
Way easier than I thought:
https://github.com/eqrion/cbindgen/blob/master/docs.md#buildrs
