### ISSUE TITLE
feat: Ability to get the patch number via the shorebird CLI

### ISSUE THREAD

**Issue by psatler** [shorebirdtech/shorebird#1212]
is it possible to retrieve the patch number of a given patch release via the shorebird CLI on a CI environment?

a little bit of context: I'm currently spiking on the use of Shorebird on our app and one of the steps we do in our release process is uploading the debug symbols to sentry after the build of the ipa/aab (using this package https://pub.dev/packages/sentry_dart_plugin). If using Shorebird, I would like to push these symbols to sentry with the following format for the release: `version+build_number+shorebird_patch_number`

So, in my CI, after successfully running the command `shorebird patch <android | ios-alpha>`  I would like to obtain the patch number to be able to use it in my next CI step which is where I upload the debug symbols to sentry by running the command `flutter packages pub run sentry_dart_plugin` so my idea would be to set the `RELEASE` in the aforementioned format. 

any ideas on how I could achieve that? 

Another thing I was thinking of was to create a dart script and try to leverage this package https://pub.dev/packages/shorebird_code_push in order to get the patch number for my CI step, but it would be more convenient getting this patch number from the shorebird CLI directly, if possible. 

Thanks in advance!

- My current shorebird and flutter versions used (if necessary)

```
shorebird --version
Shorebird 0.14.6 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.10.6 • revision 03e895ee09dfbb9c18681d103f4b27671ff65429
Engine • revision f9578b37c4490c75cc66b650fcba51e221c78411
```

**Comment by bryanoltman** [comment]
If I'm remembering the Discord conversation correctly, the answer is "yes", but: would it be sufficient to print the patch number to the console as part of the `patch` command output?

**Comment by bryanoltman** [comment]
I've addressed this in https://github.com/shorebirdtech/shorebird/pull/1229, although not quite in the way you described. The patch number is set by the backend and thus is not known at the time we print the confirmation prompt that contains the release version. 

I hesitate to display the info as `version+build_number+shorebird_patch_number`, as that will likely lead to confusion about version number ("is the version number `1.0.0+1+1` or `1.0.0+1`?"). Let me know here or in the PR if this approach will suit your needs.

**Comment by psatler** [comment]
> I've addressed this in https://github.com/shorebirdtech/shorebird/pull/1229, although not quite in the way you described. The patch number is set by the backend and thus is not known at the time we print the confirmation prompt that contains the release version.

Oh, I see. But receiving the patch number as the output of the patch command (like you showed in the PR) would be enough for us. We'll just need to perform some regex on the output message, but that's fine.

> I hesitate to display the info as version+build_number+shorebird_patch_number, as that will likely lead to confusion about version number ("is the version number 1.0.0+1+1 or 1.0.0+1?"). Let me know here or in the PR if this approach will suit your needs.

Yeah, I might have expressed myself wrong. We usually display the app version in a similar fashion to what we have in the `version` of the _pubspec.yaml_, for example, 

```
version: 1.18.12+1876
```

would be displayed in the app as `1.18.12.1876` . 

So, using _shorebird_ on forward, we'd like to also display the patch number for that build (if there is a patch number for it), so, something like  `1.18.12.1876.2`, so that last number (`2` in the example) would be the patch number from _shorebird_. This same release number, `1.18.12.1876.2`, will also be used when we upload the debug symbols to the sentry so we can identify which version an issue belongs to in the sentry panel. 
Sorry for any misunderstanding and my poor explanation/example above.


Thanks for your help with this issue!!

**Comment by bryanoltman** [comment]
No apologies necessary, glad the fix was (or will be) helpful. Thanks for filing the issue!
