### ISSUE TITLE
fix: ADB: not detected

### ISSUE THREAD

**Issue by ABausG** [shorebirdtech/shorebird#1213]
**Description**

Shorebird is not able to find `adb`. It surfaced using `shorebird preview` but also `shorebird doctor -v` shows that it cannot find adb

This is the output from `shorebird doctor -v`
```
~ shorebird doctor -v
Shorebird 0.14.6 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.2 • revision 9486b6431e6c808c4e131f134b5d88017b3c32ab
Engine • revision e7bdf38443dff65d64446d6ca4074a35a587c770

Android Toolchain
  • Android Studio: /Applications/Android Studio.app/Contents
  • Android SDK: /Users/antonborries/Library/Android/sdk
  • ADB: not detected
  • JAVA_HOME: /Users/antonborries/.jenv/versions/11

✓ Shorebird is up-to-date (0.8s)
✓ Flutter install is correct (0.7s)

No issues detected!
```

However adb is working in the terminal

```
~ adb --version
Android Debug Bridge version 1.0.41
Version 34.0.1-9680074
Installed as /usr/local/bin/adb
```

**Expected Behavior**

Shorebird should detect adb

**Additional Context**

Noticed during Workshop at Flutter 'n' Friends

**Comment by ABausG** [comment]
Further investigation showed that actually the Android sdk location that was is output by `shorebird doctor -v` was actually not the correct one. Exporting the correct sdk location via `ANDROID_HOME` fixes the issues where Shorebird has the correct Android Location as well as finding adb

**Comment by eseidel** [comment]
Oh?  I'm very curious to know more about the location `shorebird doctor -v` was showing you?

**Comment by eseidel** [comment]
As far as I can tell, `shorebird doctor` is at least validating that the path it returns exists:
https://github.com/shorebirdtech/shorebird/blob/2da950246d0cb11fc3315c249e3519e97d91046f/packages/shorebird_cli/lib/src/android_sdk.dart#L63C57-L63C57

**Comment by eseidel** [comment]
Sorry, look like you noted above.  That `shorebird doctor` showed:
```
Android Toolchain
  • Android Studio: /Applications/Android Studio.app/Contents
  • Android SDK: /Users/antonborries/Library/Android/sdk
  • ADB: not detected
  • JAVA_HOME: /Users/antonborries/.jenv/versions/11
```

Interesting it says "ADB: not detected" (Should probably make that red, etc if it does.)

**Comment by bryanoltman** [comment]
@ABausG I'm curious what the correct Android SDK path was. By default, Android Studio installs to `/Users/<username>/Library/Android/sdk` on Mac. Do you have a custom Android SDK installed or have you moved it to a custom location?

**Comment by ABausG** [comment]
Yes I have installed the Android sdk at custom location at `/Users/shared/Library/Android/sdk` to share between work/private user accounts on my mac.
I vaguely remember there being an issue in the past hence I had the android platform tools installed via homebrew hence adb was installed at `/usr/local/bin/adb`

Also based on the experience I had it seems like it seems like it just looks for adb in the presumed Android Install Location. During the workshop @felangel proposed to add `/Users/shared/Library/Android/sdk` to the platform path but this did also not work (plus adb was installed at the brew location)

As this is farely custom and not the default/recommend way I would not actually expect shorebird to support this setup however I think it should have some guidance in the output of `shorebird doctor`

My expectation would be something like:

If the Android sdk is not found at either `ANDROID_HOME` or the default `/Users/<username>/Library/Android/sdk` it should issue a warning in the output do set the `ANDROID_HOME` variable
