### ISSUE TITLE
feat: `shorebird build` support --split-per-abi

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1220]
See https://github.com/shorebirdtech/shorebird/issues/878#issuecomment-1706750646

This works in `release` but not `build`.  Should be an easy fix.

**Comment by eseidel** [comment]
FYI, split-per-abi is also broken somehow at the moment: https://github.com/shorebirdtech/shorebird/issues/1141

**Comment by felangel** [comment]
Closing this since we no longer support this for `shorebird release` either https://github.com/shorebirdtech/shorebird/pull/1255
