### ISSUE TITLE
feat: improve shorebird's seo

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1223]
Our blurb doesn't even mention "Flutter":

<img width="687" alt="Screenshot 2023-09-05 at 9 31 25 AM" src="https://github.com/shorebirdtech/shorebird/assets/478541/c2afd123-f6db-4dda-9104-83e984f6ce41">

80% of our traffic from Google comes from searching just for "shorebird".

**Comment by LeonardoRosaa** [comment]
I have other considerations:

- the title is too short;
- the description is too short;
- the landing page doesn't have a `<h1>` tag.
