### ISSUE TITLE
getting errors when shorebird tries to download in cli

### ISSUE THREAD

**Issue by MohammedAbdulaziz** [shorebirdtech/shorebird#1232]
**Description**

I am getting errors when shorebird tries to download anything in cli

 Also when I visit console.shorebird.dev on browser, the page never loads
 
 Using a VPN in any other country seems to fix these issues, I am from Egypt

**Steps To Reproduce**

Using `shorebird release android --artifact apk`
gives the following error 

```
shorebird release android --artifact apk
✗ Failed to build: Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
Failed to download https://download.shorebird.dev/flutter_infra_release/flutter/fonts/3012db47f3130e62f7cc0beabff968a33cbec8d8/fonts.zip. Ensure you have network connectivity and then try again.
all) no address was supplied.
 (OS Error: A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) 
, errno = 10057), address = download.shorebird.dev, port = 51143
 (43.2s)
 ```
 
 and using `shorebird init --force`
gives 
```
✓ Detecting product flavors (23.3s)
? How should we refer to this app? (next) next
ClientException with SocketException: The semaphore timeout period has expired.
 (OS Error: The semaphore timeout period has expired.
, errno = 121), address = api.shorebird.dev, port = 62699, uri=https://api.shorebird.dev/api/v1/apps
```

and console.shorebird.dev displays this 
```
This site can’t be reached console.shorebird.dev took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT
```

**Comment by eseidel** [comment]
If I recall correctly you mentioned over Discord that you were able to get it to work via a VPN?  e.g. that your ISP was (partially?) blocking access to Google Cloud Storage?

**Comment by MohammedAbdulaziz** [comment]
That's true, using a VPN resolved the issue for me, but what's weird is that almost a week ago it worked fine without a VPN

**Comment by eseidel** [comment]
Thanks.  Nothing changed about our cloud setup to my knowledge.

We could add something to `shorebird doctor` to test reachability of our servers?
https://github.com/shorebirdtech/shorebird/issues/1252

I'm not sure if there is anything more for us to do with this bug.  Please let us know if you have suggestions, we'd certainly be happy to help further if possible.

**Comment by MohammedAbdulaziz** [comment]
Thanks for looking into this, I guess a heads-up in shorebird doctor would be nice, or maybe you ping your storage before you begin any downloads and if they fail, you can abort, if not continue? But other than that I don't think there is anything you can do to resolve the issue itself.
