### ISSUE TITLE
client_id changes across releases

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1239]
We thought we had code to keep these consistent, but it's not working in testing.

**Comment by bryanoltman** [comment]
Logs https://console.cloud.google.com/logs/query;query=jsonPayload.message.event.app_id%3D%226144a026-27bb-4a81-a593-cbfb5dabe54c%22;summaryFields=:false:32:beginning;cursorTimestamp=2023-09-08T19:57:59.109572Z;startTime=2023-09-01T13:07:19.927Z;endTime=2023-09-09T21:07:19.927Z?referrer=search&project=code-push-prod

The same android device was responsible for all android logs in that link

**Comment by bryanoltman** [comment]
This may simply be a development build issue. Just verified this is not an issue on iOS, waiting for play store approval to verify on Android.

**Comment by eseidel** [comment]
Seems reasonable to me.  Feel free to close.

**Comment by eseidel** [comment]
Closing based on the belief this is fixed.

**Comment by bryanoltman** [comment]
Verified this is an issue on Android. See the two android events in https://console.cloud.google.com/logs/query;query=resource.type%3D%22cloud_run_revision%22%0A--%20httpRequest.requestUrl%3D%22https:%2F%2Fapi.shorebird.dev%2Fapi%2Fv1%2Fpatches%2Fevents%22%0AjsonPayload.message.event.app_id%3D%22f2184ee6-9a85-498c-bfeb-114d638c462e%22;summaryFields=:false:32:beginning;cursorTimestamp=2023-09-11T21:50:23.136294Z;startTime=2023-09-11T15:18:49.958Z?referrer=search&project=code-push-prod

**Comment by eseidel** [comment]
Supposedly Android does not clear the cache path on update:
https://stackoverflow.com/questions/51148717/does-android-clean-app-cache-on-update

We get our cache path passed down to us from Java:
https://github.com/shorebirdtech/engine/blob/655974aed33b608d1075cffae0fcaf06772d90d8/shell/platform/android/flutter_main.cc#L126

Which is passed into init here:
https://github.com/shorebirdtech/engine/blob/655974aed33b608d1075cffae0fcaf06772d90d8/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java#L200

Which comes from:
https://github.com/shorebirdtech/engine/blob/655974aed33b608d1075cffae0fcaf06772d90d8/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java#L328

Which is the result of this task:
https://github.com/shorebirdtech/engine/blob/655974aed33b608d1075cffae0fcaf06772d90d8/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java#L207

Which appears to come from this call:
https://github.com/shorebirdtech/engine/blob/655974aed33b608d1075cffae0fcaf06772d90d8/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java#L200

So this is where the actual path resolution is:
https://github.com/shorebirdtech/engine/blob/shorebird/dev/shell/platform/android/io/flutter/util/PathUtils.java#L33

Which calls this:
https://developer.android.com/reference/android/content/Context#getCodeCacheDir()

I suspect that's not the directory we want?  I suspect the codeCache may be cleared on release?  Then again maybe we should store the *code* there, just not other things like the state.json.

It's also possible that Flutter itself is detecting the release change and nuking the code dir?

**Comment by eseidel** [comment]
See also https://github.com/flutter/flutter/issues/14704.

I think the net of this is that we need to be a bit smarter about how we store things on Android?

**Comment by eseidel** [comment]
My guess is we should consider just pulling clientId out of state.json for now?  Or just ignore this for now.  I doubt this blocks our 1.0?

**Comment by bryanoltman** [comment]
It looks like the directory structure is being preserved but that state.json is being deleted. Logs from a custom updater build, where `code_cache_dir` is `/data/user/0/com.example.android_clientid/code_cache` and `updater_cache_dir` is `/data/user/0/com.example.android_clientid/code_cache/shorebird_updater`

```
09-12 11:30:02.782 10599 10599 I flutter : updater::cache: code_cache_dir contents: [Ok(DirEntry("/data/user/0/com.example.android_clientid/code_cache/shorebird_updater"))]
09-12 11:30:02.782 10599 10599 I flutter : updater::cache: updater_cache_dir exists? true
09-12 11:30:02.782 10599 10599 I flutter : updater::cache: updater_cache_dir contents: []
```

**Comment by bryanoltman** [comment]
Code cache dir is the wrong place to put this:

> The system will delete any files stored in this location both when your specific application is upgraded, and when the entire platform is upgraded.

(from https://developer.android.com/reference/android/content/Context#getCodeCacheDir())
