### ISSUE TITLE
"existing release" message should give a console link

### ISSUE THREAD

**Issue by heshesh2010** [shorebirdtech/shorebird#1246]
heshamelnemr@heshams-MacBook-Pro siyaq % shorebird --version
Shorebird 0.14.7 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.2 • revision 402424409c29c28ed69e14cbb39f0a7424a47e16
Engine • revision 40fdb8d94011b28516a28c34b6bb2ef142afde1d
heshamelnemr@heshams-MacBook-Pro siyaq %  shorebird release ios-alpha
[WARN] iOS support is alpha. See https://docs.shorebird.dev/status#ios-alpha for more information.
✓ Fetching apps (0.4s)
✓ Building release (606.1s)
✓ Getting release version (0.3s)
✓ Fetching releases (0.6s)

🚀 Ready to create a new release!

📱 App: siyaq (cb45c7ca-0a37-4d08-99bd-5a9ffa41e0bf)
📦 Release Version: 6.2.4+34
🕹️  Platform: ios

Would you like to continue? (y/N) Yes
✓ Updating release status (0.2s)
✗ Error uploading ipa: A release artifact for this release, platform, and architecture already exists.
A release artifact for release id: 7852, platform: ios, and arch: ipa already exists. (3.1s)

**Comment by felangel** [comment]
Hi @heshesh2010 👋
That means there’s already a release for iOS for that same release version. You can verify this by visiting https://console.shorebird.dev.

Let us know if that helps 👍

**Comment by eseidel** [comment]
I think the resolution here is that we should change the message:
```
✗ Error uploading ipa: A release artifact for this release, platform, and architecture already exists.
A release artifact for release id: 7852, platform: ios, and arch: ipa already exists. (3.1s)
```
To point to the console?

e.g:
```
✗ Error uploading ipa: A release artifact for this release, platform, and architecture already exists.
https://console.shorebird.dev/apps/9101fe7a-9896-4746-a688-fedb574a64dd/releases/1231
If you'd like to upload a new release for this version number, please remove the existing one first.
```

**Comment by bryanoltman** [comment]
The CLI is now on version `0.16.2`, so it's a bit tough (any maybe not all that useful) to try to diagnose issues from `0.14.7`. If you try to create a release for a version that already exists, this is now the output:

```
⑆ shorebird release ios-alpha
[WARN] iOS support is alpha. See https://docs.shorebird.dev/status#ios-alpha for more information.
✓ Fetching apps (0.1s)
✓ Building release (46.5s)
✓ Fetching releases (92ms)
It looks like you have an existing ios release for version 1.0.0+1.
Please bump your version number and try again.
```
