### ISSUE TITLE
feat: Add a validator to `shorebird doctor` to test reachability of Shorebird servers

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1252]
Sometimes users complain that shorebird isn't working correctly on their network.

We document which servers are needed to be reachable:
https://docs.shorebird.dev/faq#can-i-use-shorebird-in-my-country

But we could also just add a validator to `shorebird doctor` which tested connectivity to the list of servers we use. 🤷

**Comment by eseidel** [comment]
This should be very easy since we already have one for storage.googleapis.com

**Comment by wzslr321** [comment]
@eseidel I can try and handle that, if it is still relevant

**Comment by eseidel** [comment]
Patches are certainly welcome.  Thanks!
