### ISSUE TITLE
fix: `shorebird preview` exception

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#1257]
```
Unhandled exception:
FormatException: Unfinished UTF-8 octet sequence (at offset 4409)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
#3      PreviewCommand.installAndLaunchAndroid.<anonymous closure> (package:shorebird_cli/src/commands/preview_command.dart:220:24)
#4      _rootRunUnary (dart:async/zone.dart:1407:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#10     _StreamController._add (dart:async/stream_controller.dart:658:7)
#11     _StreamController.add (dart:async/stream_controller.dart:606:5)
#12     _Socket._onData (dart:io-patch/socket_patch.dart:2445:41)
#13     _rootRunUnary (dart:async/zone.dart:1415:13)
#14     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#19     _StreamController._add (dart:async/stream_controller.dart:658:7)
#20     _StreamController.add (dart:async/stream_controller.dart:606:5)
#21     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1934:33)
#22     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1377:14)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#26     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
```

**Comment by HigorMadeira** [comment]
Unhandled exception:
FormatException: Unfinished UTF-8 octet sequence (at offset 4409)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
#3      PreviewCommand.installAndLaunchAndroid.<anonymous closure> (package:shorebird_cli/src/commands/preview_command.dart:220:24)
#4      _rootRunUnary (dart:async/zone.dart:1407:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#10     _StreamController._add (dart:async/stream_controller.dart:658:7)
#11     _StreamController.add (dart:async/stream_controller.dart:606:5)
#12     _Socket._onData (dart:io-patch/socket_patch.dart:2445:41)
#13     _rootRunUnary (dart:async/zone.dart:1415:13)
#14     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#19     _StreamController._add (dart:async/stream_controller.dart:658:7)
#20     _StreamController.add (dart:async/stream_controller.dart:606:5)
#21     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1934:33)
#22     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1377:14)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#26     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)

**Comment by bryanoltman** [comment]
Have you been able to reproduce this? Going to close if not.

**Comment by felangel** [comment]
No haven't been able to reproduce.
