### ISSUE TITLE
Failed to download release artifact: 404 Not Found in Patch 

### ISSUE THREAD

**Issue by dev-medico** [shorebirdtech/shorebird#1271]
1. Device - M1 Mac Air
2. App ID - 3f5268bd-acea-44f3-9e41-cf3f4766f3c3 ( V - [1.0.5+9])
3. shorebird release command has no error.
4. it shows the same error whenever I patch.

Error Log -
```
shorebird patch android
✓ Fetching apps (0.6s)
✓ Building patch (64.7s)
✓ Detected release version 1.0.5+9 (0.5s)
✓ Fetching releases (0.5s)
✓ Fetching release artifacts (1.0s)
✓ Fetching aab artifact (0.3s)
✓ Downloading release artifacts (14.5s)
✗ Verifying patch can be applied to release (0.4s)
Unhandled exception:
Exception: Failed to download release artifact: 404 Not Found
#0      PatchDiffChecker.confirmUnpatchableDiffsIfNecessary (package:shorebird_cli/src/patch_diff_checker.dart:55:7)
<asynchronous suspension>
#1      PatchAndroidCommand.run (package:shorebird_cli/src/commands/patch/patch_android_command.dart:214:7)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#3      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:167:18)
<asynchronous suspension>
#4      ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:95:14)
<asynchronous suspension>
#5      main (file:///Users/sithuaung/.shorebird/packages/shorebird_cli/bin/shorebird.dart:29:5)
<asynchronous suspension>
```

**Comment by eseidel** [comment]
We should definitely give a better error.  It appears that the release in question does not exist on our servers, even though we think it should.

https://console.shorebird.dev/apps/3f5268bd-acea-44f3-9e41-cf3f4766f3c3 (I can't click the link, but you should be able to) should be a link to the apps page where you can see what releases our servers do know about.

**Comment by eseidel** [comment]
This might go away with https://github.com/shorebirdtech/shorebird/issues/1382

**Comment by Srini-B** [comment]
Hi, getting the following on android, worked on ios

❯ shorebird patch android -v
[HTTP] GET https://api.shorebird.dev/api/v1/apps
✓ Fetching apps (0.5s)
[Process.run] /Users/cyron/.shorebird/bin/cache/flutter/ef4b661ddc0c71b738432ae59c6bc573e917854b/bin/flutter build appbundle --release
⠏ Building patch... (16.7s)[Process.run] flutter --no-version-check pub get --offline
✓ Building patch (18.7s)
[Process.run] java -jar /Users/cyron/.shorebird/bin/cache/artifacts/bundletool/bundletool.jar dump manifest --bundle=./build/app/outputs/bundle/release/app-release.aab --xpath /manifest/@android:versionName
[Process.run] java -jar /Users/cyron/.shorebird/bin/cache/artifacts/bundletool/bundletool.jar dump manifest --bundle=./build/app/outputs/bundle/release/app-release.aab --xpath /manifest/@android:versionCode
✓ Detected release version 1.2.7+70 (0.2s)
[HTTP] GET https://api.shorebird.dev/api/v1/apps/0c040191-b766-44d9-afac-0f4191d6da29/releases
✓ Fetching releases (0.5s)
[HTTP] GET https://api.shorebird.dev/api/v1/apps/0c040191-b766-44d9-afac-0f4191d6da29/releases/13315/artifacts?arch=aarch64&platform=android
⠴ Fetching release artifacts... (0.4s)[HTTP] GET https://api.shorebird.dev/api/v1/apps/0c040191-b766-44d9-afac-0f4191d6da29/releases/13315/artifacts?arch=arm&platform=android
⠏ Fetching release artifacts... (0.7s)[HTTP] GET https://api.shorebird.dev/api/v1/apps/0c040191-b766-44d9-afac-0f4191d6da29/releases/13315/artifacts?arch=x86_64&platform=android
✓ Fetching release artifacts (1.1s)
[HTTP] GET https://api.shorebird.dev/api/v1/apps/0c040191-b766-44d9-afac-0f4191d6da29/releases/13315/artifacts?arch=aab&platform=android
✓ Fetching aab artifact (0.4s)
[HTTP] GET https://storage.googleapis.com/shorebird_release_artifacts/0c040191-b766-44d9-afac-0f4191d6da29/android/aarch64/13315/dlc.vmcode
✗ Exception: Failed to download file: 404 Not Found (0.4s)


❯ shorebird doctor
Shorebird 0.16.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.6 • revision ef4b661ddc0c71b738432ae59c6bc573e917854b
Engine • revision 35809a641ed60f9595fcb6c6f939a8768eaca976

✓ Shorebird is up-to-date (0.8s)
✓ Flutter install is correct (0.2s)
✓ AndroidManifest.xml files contain INTERNET permission (31ms)

**Comment by bryanoltman** [comment]
Just got another report of this on Discord https://discord.com/channels/1030243211995791380/1125516353370075306/1163843314580193493

**Comment by bryanoltman** [comment]
I think these DB logs might be related – there seem to be a bunch of cases where think an artifact already exists for a given architecture https://console.cloud.google.com/logs/query;query=resource.type%3D%22alloydb.googleapis.com%2FInstance%22%0Aseverity%3DWARNING%20OR%20severity%3DERROR%20severity%3E%3DDEFAULT;cursorTimestamp=2023-10-17T12:17:26.623142Z;duration=P7D?project=code-push-prod

**Comment by bryanoltman** [comment]
Specifically for the release mentioned in https://github.com/shorebirdtech/shorebird/issues/1271#issuecomment-1766529404: https://console.cloud.google.com/logs/query;query=resource.type%3D%22alloydb.googleapis.com%2FInstance%22%0Aseverity%3DWARNING%20OR%20severity%3DERROR%20severity%3E%3DDEFAULT%0A13315;cursorTimestamp=2023-10-16T15:54:03.403966Z;duration=P7D?project=code-push-prod

**Comment by bryanoltman** [comment]
The user experiencing this issue says that they ran the release command several times before it successfully completed, so my theory is that a release artifact entry existed in the DB with no artifact having been successfully uploaded. Checking the code now to see how that might happen – I could've sworn we only created the DB entries after successfully uploading the artifacts…
