### ISSUE TITLE
fix: Build failed when shorebird build appbundle

### ISSUE THREAD

**Issue by abinvs-2019** [shorebirdtech/shorebird#1275]
**Description**

Issue while building appbundle

✗ Failed to build: 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':in_app_review:generateReleaseRFile'.
> Could not resolve all files for configuration ':in_app_review:releaseCompileClasspath'.
   > Could not find io.flutter:flutter_embedding_release:1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420.
     Required by:
         project :in_app_review

**Steps To Reproduce**

1. Shorebird build appbundle with :in_app_review in .yaml file

**Comment by eseidel** [comment]
Notes to myself:
https://github.com/shorebirdtech/engine/commit/45f6e009110df4f34ec2cf99f63cf73b71b7a420
is 3.10.5 (upstream, not shorebird).

This also looks like it's trying to use Shorebird add2app? `flutter_embedding_release`?  Or maybe that's the normal target for aabs?

Would you be willing to share the command you're using to build?

I presume it's `shorebird build android`?  After having switched to a specific older Shorebird version?

**Comment by bryanoltman** [comment]
@abinvs-2019 I'm unable to reproduce in a new Flutter project (created with `flutter create project_name`) that has `in_app_review: ^2.0.6` as a dependency. Can you run the offending command with the `-v` flag and paste the full output here? I believe that would be `shorebird build appbundle -v`.

**Comment by abinvs-2019** [comment]
But after i run flutter clean and then shorebird build appbundle it got worked.
