### ISSUE TITLE
fix: Info.plist lookup fails if Runner has been renamed

### ISSUE THREAD

**Issue by omar6533** [shorebirdtech/shorebird#1290]
**Description**

omarsfd@Omars-MacBook-Pro example % shorebird release ios-alpha -v --flavor prod
[WARN] iOS support is alpha. See https://docs.shorebird.dev/status#ios-alpha for more information.
[HTTP] POST https://oauth2.googleapis.com/token
⠴ Fetching apps... (0.4s)[HTTP] GET https://api.shorebird.dev/api/v1/apps
✓ Fetching apps (0.8s)
[Process.run] /Users/omarsfd/.shorebird/bin/cache/flutter/012153de178d4a51cd6f9adc792ad63ae3cfb1b3/bin/flutter build ipa --release --export-options-plist=/var/folders/yk/zxf9lr0156n54s7bn_ggd9_m0000gn/T/0eZDlY/ExportOptions.plist --flavor=prod
⠋ Building release... (217.6s)[Process.run] flutter --no-version-check pub get --offline
✓ Building release (222.3s)
No Info.plist file found at /Users/omarsfd/Documents/GitHub/2.0/example/build/ios/archive/Runner.xcarchive/Info.plist.

my actual path is : /Users/omarsfd/Documents/GitHub/2.0/example/build/ios/archive/التعاونية | Tawuniya.xcarchive/Info.plist

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by eseidel** [comment]
Thanks for the issue!  Bryan has fixed it in #1293 above.
