### ISSUE TITLE
fix: `shorebird preview` fails with Xcode 15/iOS 17

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1292]
**Description**

When running `shorebird preview` on a machine with Xcode 15 targeting an iPhone running iOS 17, the deployment to the device fails with the following message:

```
⠇ [ 95%] GeneratingApplicationMap... (6.6s)2023-09-19 17:33:40.706 ios-deploy[5779:22498] [ !! ] Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg'. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
```

**Comment by bryanoltman** [comment]
https://github.com/flutter/flutter/commit/54040e60411942430b82c807177d8e5f63c6abcc is how Flutter solved this issue

**Comment by bryanoltman** [comment]
As per christopherfujino:

> the latest Flutter SDK releases have been hotfixed to "fix" this by opening xcode to start debugging 🙃
none of the open source ios debug tools support ios17 yet

**Comment by JohnSamy11** [comment]
@bryanoltman  I'm facing the exact same issue and I've been searching a lot but still can't find a fix for it.
