### ISSUE TITLE
fix: Handle exceptions caught by the Dart entry frame

### ISSUE THREAD

**Issue by kmillikin** [shorebirdtech/shorebird#1294]
The FFI test `tests/ffi/abi_test.dart` fails when the loop in `StackResource::UnwindAbove`  reaches null before finding the resource it's looking for.

This is because there is a `CPUToSimulator` transition resource at the base of the transition stack representing the initial entry into Dart code.  This will simulate the target architecture code in the `InvokeDartCode` stub, which will clear the thread's top resource (and save it on the side, in the entry frame).

The fix is that we should **not** simulate the `InvokeDartCode` stub.  Since the target and host architectures are the same and we can run code on the host CPU we should just run this stub natively.  So: rather than simulating the `InvokeDartCode` stub and then calling the code which will either continue on the simulator or transition *back* to the CPU we should instead run the `InvokeDartCode` stub on the CPU and then call the code which will either continue on the CPU or transition into the simulator.  We still might need some special handling for exceptions that reach the Dart entry frame.

**Comment by kmillikin** [comment]
It's not completely trivial.  The `RunOnCPU` assembly function saves the simulator's C++ stack pointer in the thread before calling out.  The `RunInSimulator` stub will restore this from the thread before calling out.

So everything works if we have nested `RunOnCPU` -> `RunInSimulator` -> `RunOnCPU` -> `RunInSimulator` -> ... calls.  If instead we have `RunInSimulator` -> `RunOnCPU` -> ... then we have to have an initial simulator C++ stack pointer.

**Comment by kmillikin** [comment]
I couldn't make this work simply (at all, really).  Since we're not entirely sure how we will get into mixed-mode in a deployed iOS app anyway, I just adopted a simpler solution.

Instead of unwinding the chain of transitions when handling an exception, unwind the chain of stack resources.  They don't coincide for entry frames because the entry frame breaks the chain or stack resources (and ignores the chain of transitions).

**Comment by eseidel** [comment]
I think you fixed this already?  Please feel welcome to re-open if desired.
