### ISSUE TITLE
Wire up Flutter to use Mixed Mode (demo)

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1297]

**Comment by eseidel** [comment]
This is blocked on https://github.com/shorebirdtech/shorebird/issues/1294.  Until then Flutter will crash on boot.

**Comment by eseidel** [comment]
Also blocked on https://github.com/shorebirdtech/shorebird/issues/1279

**Comment by eseidel** [comment]
This has been done, btw.  the branch is "mixed" in shorebirdtech/engine.

Issues:
* Currently just runs every other function on the CPU vs. simulator (similar to the richards demo), it does not support updating code, etc.
* There seems to be some trouble with a snapshot version mismatch for the font treeshaker.  Not sure if that's caused by mixed-mode or not?  It goes away by building a second time.

**Comment by bryanoltman** [comment]
This is done
