### ISSUE TITLE
Re-enable `public_member_api_docs` analysis option for `shorebird_cli`

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1302]
There have been a couple occasions where I've been in an area of the code I didn't write and was not 100% clear about the purpose of the class/method in question. Enforcing the presence of doc strings would help with this.

**Comment by felangel** [comment]
For context, I omitted this rule when creating the repo since a CLI's public API is not consumed as a library but I have no objections against enabling it 👍
