### ISSUE TITLE
fix: iOS app crash:   io.flutter.1.ui EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by ABHINANDRK** [shorebirdtech/shorebird#1318]
**Description**
App crash on launching the iOS app

Shorebird 0.14.11 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.10.5 • revision ba444de6ceb9313320a70563d7b6203344e0cd87
Engine • revision 24fdd628e38b6dbc75ac25e72f61f6e8c75e4344

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**
<img width="1131" alt="Screenshot 2023-09-23 at 10 25 25 PM" src="https://github.com/shorebirdtech/shorebird/assets/14967375/ef5cfddd-3aaa-4a49-b879-02fee8a6b71d">

**Additional Context**

**Comment by ABHINANDRK** [comment]
Attaching the pubspec.yaml file content

name: Dummy
version: 1.1.0+23
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: 3.2.3
  circular_countdown_timer: 0.2.3
  country_picker: 2.0.20
  cupertino_icons: 1.0.5
  dartz: 0.10.1
  device_info_plus: ^9.0.0
  dio: ^5.2.1+1
  easy_localization: 3.0.2
  easy_localization_loader: 1.0.1+1
  event_bus: 2.0.0
  file_picker: ^5.3.2
  firebase_analytics: 10.4.3
  firebase_core: 2.14.0
  firebase_remote_config: 4.2.3
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_branch_sdk: 6.6.0
  flutter_cache_manager: ^3.3.1
  flutter_config: ^2.0.0
  flutter_displaymode: ^0.6.0
  flutter_image_compress: ^2.0.3
  flutter_keyboard_visibility: ^5.4.1
  flutter_local_notifications: ^15.1.0+1
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  flutter_secure_storage: 8.0.0
  flutter_svg: ^2.0.5
  flutter_typeahead: ^4.6.1
  gap: ^3.0.0
  get: 4.6.5
  get_it: ^7.6.0
  get_storage: 2.1.1
  google_sign_in: ^6.1.4
  image_picker: ^1.0.0
  injectable: ^2.1.2
  intl: 0.18.0
  intl_phone_field:
    path: ./plugins/intl_phone_field
  jwt_decoder: 2.0.1
  local_auth: 2.1.6
  lottie: ^2.4.0
  mixpanel_flutter: 2.1.1
  mocktail: 0.3.0
  modal_bottom_sheet: 3.0.0-pre
  money2: ^3.4.1
  number_to_words: ^1.0.0
  oktoast: 3.3.1
  package_info_plus: ^4.0.0
  path_provider: ^2.0.15
  pdfx: ^2.4.0
  permission_handler: ^10.3.0
  pinput: 2.2.31
  pretty_dio_logger: 1.3.1
  razorpay_flutter: ^1.3.5
  sentry_flutter: ^7.7.0
  share_plus: ^7.0.2
  sign_in_with_apple: ^5.0.0
  url_launcher: ^6.1.11
  uuid: 3.0.7
  version: 3.0.2
  webview_flutter: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: 5.3.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  integration_test:
    sdk: flutter
  lints: ^2.1.1

dependency_overrides:
  package_info_plus: ^4.0.0
  device_info_plus: ^9.0.0
  win32: ^4.0.0

flutter_gen:
  integrations:
    flutter_svg: true
    rive: false
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/avatar/
    - assets/images/profile_avatar/
    - assets/images/transaction/
    - assets/images/syndicate/
    - assets/images/kyc/
    - assets/icons/
    - shorebird.yaml

  fonts:
    - family: CabinetGrotesk
      fonts:
        - asset: fonts/CabinetGrotesk-Regular.otf
        - asset: fonts/CabinetGrotesk-SemiBold.otf
        - asset: fonts/CabinetGrotesk-Bold.otf
        - asset: fonts/CabinetGrotesk-Light.otf
        - asset: fonts/CabinetGrotesk-Medium.otf
    - family: Syne
      fonts:
        - asset: fonts/Syne-Regular.ttf
        - asset: fonts/Syne-SemiBold.ttf
        - asset: fonts/Syne-Bold.ttf
        - asset: fonts/Syne-ExtraBold.ttf
        - asset: fonts/Syne-Medium.ttf

**Comment by eseidel** [comment]
If it's possible to share, the most useful part would be the crash log.
https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs

**Comment by eseidel** [comment]
From what you've shared of the log in that picture, it's trying to read memory at an unaligned address (not a multiple of 16).  Which also means it's trying to read memory from a value which isn't a memory address.  But what exact stack it's crashing on might help us know if this is Shorebird related or not.  Thanks!

**Comment by kmillikin** [comment]
`0x107888081` looks like a Dart heap object pointer (tagged with a 1 in the low-order bit).  It's trying to return to an instruction at that address (that value is in `lr` and `pc`).  I'm not sure why we'd be trying to do that, though.

**Comment by eseidel** [comment]
> Attaching the pubspec.yaml file content

Is this suggesting that you've reproduced the crash with just this pubspec.yaml and an otherwise empty app?

**Comment by thecaptainXgod** [comment]
I had the same issue, when i tried using shorebird for the first time in IOS. What might be causing it?

**Comment by eseidel** [comment]
> I had the same issue, when i tried using shorebird for the first time in IOS. What might be causing it?

We would love to work with you to get a backtrace.  Console.app should be able to pull one from your phone.  If you're willing to post such here, or send it to contact@shorebird.dev I'm happy to work with you to figure out what's gone wrong.  Thank you!

**Comment by eseidel** [comment]
https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs

**Comment by kmillikin** [comment]
> I had the same issue, when i tried using shorebird for the first time in IOS. What might be causing it?

Definitely a bug on our end.  Unfortunately it's hard to know what it is without a more detailed crash report or a way to reproduce it.

`frame #0: 0x0000000108608081` is the symptom.  That's a stack frame with a bad return address.  ARM instructions are 4-byte aligned so this should end with `0`, `4`, `8`, or `c` and never `1`.  Dart heap object pointers have their low bit set like this as a way of tagging the pointer (though it could also be some other value).

The cause is probably a stack layout mismatch of some kind.

**Comment by eseidel** [comment]
We would love to help but will need a crash report to move forward.  This may also be resolved by "iOS beta" when we release that later this month as it will run Dart code in a different execution environment.

**Comment by minhtritc97** [comment]
same issue, I tried using shorebird for iOS and i got this
[stacktrace.txt](https://github.com/shorebirdtech/shorebird/files/13973323/stacktrace.txt)

**Comment by eseidel** [comment]
> same issue, I tried using shorebird for iOS and i got this [stacktrace.txt](https://github.com/shorebirdtech/shorebird/files/13973323/stacktrace.txt)

That crash is crashing on `Crashed: io.flutter.1.raster`, which AFAIK Shorebird has no way of affecting.  Unless by chance we somehow have a bad engine build.  I'd want to test and see if the same crass occurred without shorebird.

It also looks like stack traces may be obfuscated in some way?  Or maybe they're just that way due to being a stripped build.

We fixed a bunch of crashes in 0.22.0 (just released today).  I would love to help anyone who's seeing a crash, but I don't think there is a lot we can do with this old bug.
