### ISSUE TITLE
"shorebird patch aar --release-version" does not update changes in app

### ISSUE THREAD

**Issue by gaurav-zdroid** [shorebirdtech/shorebird#1319]
I pushed a patch for andriod with some changes in code. But changes are not reflecting in the application. 

Release build and patch release were successful.

Note : Release build was created through CI in Bitrise and patch pushed through IDE.

<img width="707" alt="Screenshot 2023-09-24 at 10 06 20 PM" src="https://github.com/shorebirdtech/shorebird/assets/78362839/f0914880-e7f2-4b41-a65c-11fec2e69e5f">

<img width="770" alt="Screenshot 2023-09-24 at 10 07 29 PM" src="https://github.com/shorebirdtech/shorebird/assets/78362839/95d2994a-2ef3-427f-8cc6-434e4d8185a1">

**Comment by eseidel** [comment]
Are you able to share logs from the app running on a device?  e.g. `adb log -s flutter`?

I'm surprised that the release version is just 10.16 and not 10.16+1,  I wonder if the lack of buildNumber could be confusing our update checks?  `adb logcat` will tell us either way.

**Comment by eseidel** [comment]
Oh, sorry this is an AAR build, not an AAB build, so the release number is not built into the aar, but rather passed to it during execution if I recall correctly?

https://docs.shorebird.dev/guides/add-to-app/android

@bryanoltman may have further thoughts.

**Comment by bryanoltman** [comment]
Yeah, it's odd that the release version has no build number. The only release I'm seeing for your app in our DB has a version `10.16+9034350`, which won't pick up patches created for release version `10.16`. Has the release command output been altered?

**Comment by gaurav-zdroid** [comment]
@bryanoltman yes, I deleted previous version i.e. 10.16 and deployed new build `10.16+9034350` and push patch on that build but now i open my app multiple times but there is no changes detected.

**Comment by bryanoltman** [comment]
What do you see in `logcat`? Is shorebird checking for a patch and not finding it? Also, what do you see for the release in the [Shorebird console](https://console.shorebird.dev/)? Does the logcat output match the version number you see there?

**Comment by gaurav-zdroid** [comment]
No shorebird is not checking for patch.

**Comment by bryanoltman** [comment]
That means that your app is not using the shorebird-produced `aar`.

Have you gotten this working locally? Can you build in Android Studio with the result of `flutter release aar --release-version x.y.z`?

**Comment by gaurav-zdroid** [comment]
No, For creating a complete build I am using the Bitrise tool because my app is mix code[React + Flutter] and for patch I pushed locally.

**Comment by bryanoltman** [comment]
Hrm, I worry it will be tough to debug if it's only building on bitrise. Have you followed the guide at https://docs.shorebird.dev/guides/add-to-app/android? Can you share the edits you made to your `settings.gradle` and `app/build.gradle`?

**Comment by bryanoltman** [comment]
I'm also not sure how you would be able to generate a patch locally without also being able to build in Android Studio. Have you tried?

**Comment by gaurav-zdroid** [comment]
yes I followed the steps.

this piece of code I added in android/build.gradle
<img width="1039" alt="Screenshot 2023-09-26 at 12 59 10 AM" src="https://github.com/shorebirdtech/shorebird/assets/78362839/83fdc626-e93a-48b2-a3df-eb040d259b0a">

and this one in app/build.gradle
<img width="637" alt="Screenshot 2023-09-26 at 1 00 24 AM" src="https://github.com/shorebirdtech/shorebird/assets/78362839/ce0e4fff-a29b-45f6-a73b-78bcccb9b2e9">
<img width="627" alt="Screenshot 2023-09-26 at 1 04 07 AM" src="https://github.com/shorebirdtech/shorebird/assets/78362839/70d943f1-36d8-46a0-896c-6e2725278b43">

**Comment by bryanoltman** [comment]
That looks fine. What command are you running in your CI? Are you sure you're packaging up the app with the aar that is generated by shorebird? Based on the absence of shorebird in your logs, I would guess not

**Comment by gaurav-zdroid** [comment]
For creating aar i am running this command.
Release version is hard coded for now.
<img width="1144" alt="Screenshot 2023-09-26 at 1 26 16 AM" src="https://github.com/shorebirdtech/shorebird/assets/78362839/de6b83ea-5a50-49d9-8e8f-fd66e4b4b819">

but let me check that which aar is used for final build and I will also try to make a release build locally.

**Comment by gaurav-zdroid** [comment]
Its fixed, issue was not using aar generated by shorebird.
thanx @bryanoltman

**Comment by muhammad-asim786** [comment]
Hi- I am just confirming that, shorebird is working perfectly but there is one thing, when i push the patch and successful but when i open my app first time the change are not reflected right, but when i kill the app and reopen it so then the changes are there working fine why it's not working on first time. Please any one. Specially shorebird team
