### ISSUE TITLE
fix: Crash when unwinding stack resources, due to nullptr

### ISSUE THREAD

**Issue by kmillikin** [shorebirdtech/shorebird#1325]
`tests/ffi/function_callbacks_structs_by_value_generated_test.dart` fails when unwinding stack resources in `Simulator::JumpToFrame`.  It's trying to unwind past an entry frame because there is a `Simulator::Transition` missing when we call an FFI function.

**Comment by eseidel** [comment]
Is calling to FFI a "Simulator::Transition"?  Seems like there are 3 kinds of exits from the simulator:
- "natives" (dart vm c++ calls)
- Transitions to Dart on the CPU for mixed-mode
- FFI

Are all 3 "Transitions"?

**Comment by kmillikin** [comment]
That's right.  "Natives" includes some different things with slightly different calling conventions --- C++ runtime calls and Dart functions implemented by native code.

All of those things are ARM 64 code that should run on the CPU and is called from code that is potentially running in the simulator.  If the caller is running in the simulator we need to perform a transition (and the reverse transition when it returns).  If the caller is *not* running in the simulator, we can directly call the target.

We need some changes to FFI calls.  (1) we need to detect whether we are calling them from the simulator or not.  Currently we assume we always are, which isn't necessarily right.  If we're not calling them from the simulator, we don't need any transition.  (2) when we call them from the simulator, we should use the Dart stack for the called function.  This is the way that they are called from the CPU.  We could probably make it work to use the simulator's C++ stack when called from the simulator, but that seems more complicated for now.

Transition is currently performed by the simulator recognizing a special marker instruction and calling `RunOnCPU` to perform a transition.  For now I'm going to make FFI follow the same logic.

Eventually we will want to have different versions of `RunOnCPU` for the different calling conventions, probably, to avoid doing more saving/restoring registers than we need.

**Comment by eseidel** [comment]
I believe this is fixed now?

**Comment by eseidel** [comment]
Speculatively closing.
