### ISSUE TITLE
feat: add `--ignore-diff-warnings` 

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1328]
**Description**

Add a flag to skip native/asset diff warnings when running any of the `shorebird patch` commands. This would allow users whose dependencies introduce native changes (including a timestamp in their output artifacts, for example) to bypass these specific warnings without bypassing any other issues.

The only way to bypass this warning in CI at the moment is the `--force` flag, which we don't want to encourage use of.

**Additional Context**

https://github.com/shorebirdtech/docs/pull/148

**Comment by vivaan-vama** [comment]
By when we can expect it ?

**Comment by bryanoltman** [comment]
The patch command now has `allow-asset-diffs` and `allow-native-diffs` for this purpose.
