### ISSUE TITLE
fix: Unable to add collaborators to app id. Colloborators do not have paid account

### ISSUE THREAD

**Issue by gouravd** [shorebirdtech/shorebird#1330]
**Description**

When I am trying to add collaborators I get the following error - The account requires an upgraded plan to use this functionality.

**Steps To Reproduce**

1. Have user 1 create a hobby account and create an app
2. Have user 2 create team account
3. Try to add user 1 as collaborator using app id created by user 1

**Expected Behavior**

Should be able to add collaborators (irrespective of account type) from my paid account.

**Comment by eseidel** [comment]
Correct, should be possible to add collaborators regardless of account type.  We can check to see if we broke something.  Here are the docs:
https://docs.shorebird.dev/teams

**Comment by felangel** [comment]
I’ll take a look 👍

**Comment by eseidel** [comment]
It's not possible to add collaborators to a *hobby* account, but it is possible to add collaborators to a *teams* account.

I'm not sure which direction you're trying to go: `Try to add user 1 as collaborator using app id created by user 1`?

**Comment by gouravd** [comment]
So trying to add user 1 as collaborator by user 2. User 2 is team account
and user 1 is hobby. App id is created by user 1.

**Comment by felangel** [comment]
@gouravd if the app is owned by an account that is part of the free tier then you can’t add collaborators. The app must be owned by a paid account to add collaborators. In this case you should be able to add the hobby account to the app if you create the app using a paid account. Let me know if that helps.

**Comment by gouravd** [comment]
Thanks for the update. Is there a way I can transfer the account. Basically
move the ownership to the other hobby account so that they can continue
business as usual .

**Comment by gouravd** [comment]
Or transfer app ownership to my account so that I can then add
collaborators ?

**Comment by eseidel** [comment]
Happily.  Can you please email me the two account emails and which direction you'd like to go (moving the billing from the paid to the free account, or moving the app from the free to the paid account).  Thanks!  contact@shorebird.dev

**Comment by felangel** [comment]
@gouravd this should be done now. Let us know if you encounter any issues, thanks!

**Comment by gouravd** [comment]
adding collborators to the above App id is throwing an error about invalid app id. Sent email about this. Please take a look.

**Comment by eseidel** [comment]
Apologies.  We had a thread with another customer about the same issue which I may have confused with yours.  That thread is resolved, and I can't seem to find yours?

Can you try emailing me again?  Thank you!  contact@shorebird.dev.
