### ISSUE TITLE
Failed to build iOS framework: ProcessException

### ISSUE THREAD

**Issue by gaurav-zdroid** [shorebirdtech/shorebird#1332]
Getting error when running `shorebird release ios-framework-alpha --release-version version+build` on IDE and CI.

`✗ Failed to build iOS framework: ProcessException: Flutter assets will be downloaded from https://download.shorebird.dev/. Make sure you trust this source!`

**Comment by bryanoltman** [comment]
`Flutter assets will be downloaded from https://download.shorebird.dev/. Make sure you trust this source` is standard output. Can you run `shorebird release ios-framework-alpha -v` (the `-v` flag gives us verbose output) and paste what you see here?

**Comment by eseidel** [comment]
We'd love to help, but will need a lot to better understand what error is encountered while building the framework.

@bryanoltman I wonder if we should change `shorebird` to dump the log on failure?

**Comment by bryanoltman** [comment]
@eseidel In the case of a ProcessException, we print all of stderr to the console. I'm not sure what additional info we would print 🤔

**Comment by eseidel** [comment]
> @eseidel In the case of a ProcessException, we print all of stderr to the console. I'm not sure what additional info we would print 🤔

It seems like the problem here is that we really want that -v output from Flutter itself.  I wonder if we should always run flutter in -v so we can print Flutter logs on failure?  Or maybe the bug here is Flutter just doesn't print enough on this kind of failure?

**Comment by bryanoltman** [comment]
Verbosity of Flutter was turned up in https://github.com/shorebirdtech/shorebird/pull/1420. Going to close this for now since we don't have a lot else to go on. @gaurav-zdroid feel free to reopen with more info if you're still experiencing this issue.
