### ISSUE TITLE
fix: shorebird doesn't update to the latest stable flutter version 3.13.6

### ISSUE THREAD

**Issue by JohnSamy11** [shorebirdtech/shorebird#1338]
**Description**

shorebird is up to date on flutter 3.13.5 but doesn't want to go further up to flutter 3.13.6 which has been out for about 5 days now.

I've tried pumping up the version manually by adding the flutter 3.13.6 SDK in the `bin/cache/flutter` folder with the version name `a794cf2681c6c9fe7b260e0e84de96298dc9c18b` also changed it in `bin/internal/flutter.version` file then I ran `shorebird doctor` and it gave me this error:
```
Shorebird 0.15.1 • git@github.com:shorebirdtech/shorebird.git
Flutter • revision a794cf2681c6c9fe7b260e0e84de96298dc9c18b
Engine • revision a794cf2681c6c9fe7b260e0e84de96298dc9c18b

✓ Shorebird is up-to-date (0.9s)
✗ Flutter install is correct (0.4s)
  [✗] Failed to determine Shorebird Flutter version. FlutterValidationException: Flutter version check did not complete successfully. error: no such commit a794cf2681c6c9fe7b260e0e84de96298dc9c18b

✓ AndroidManifest.xml files contain INTERNET permission (40ms)
1 issue detected.
```

**Comment by felangel** [comment]
Sorry for the inconvenience! We’re going to release support for 3.13.6 Monday.
