### ISSUE TITLE
feat: Shorebird Release List

### ISSUE THREAD

**Issue by chillbrodev** [shorebirdtech/shorebird#1339]
**Description**

I would like the ability to use the shorebird CLI to list all releases and also list the current release. I have my CI system Bitrise auto increment a release's build number using the CI build's number. I do not track this build number in my git. When I go to run the patch workflow, I need to know the current release so I can strip off the build number and set for the patch using the flutter build arg --build-number.

This allows me to sync the patches to the release.

**CLI Command Requirements**

- [ ] shorebird releases list (Lists all releases)
- [ ] shorebird releases current (Lists the current/top release)

**Additional Context**

Discussed in Discord https://discord.com/channels/1030243211995791380/1125516353370075306/1158075745864786032

**Comment by eseidel** [comment]
Seems like a reasonable ask.

**Comment by eseidel** [comment]
I wonder if what you actually want here is an API endpoint rather than a CLI you have to parse?

**Comment by chillbrodev** [comment]
> I wonder if what you actually want here is an API endpoint rather than a CLI you have to parse?

Hmm that is an interesting idea to move it towards the API.

**Comment by felangel** [comment]
We created the `shorebird-release` GitHub Action which creates a shorebird release and includes the release version as part of its output. Check it out at https://github.com/shorebirdtech/shorebird-release.

**Comment by chillbrodev** [comment]
I'll borrow that regex for my Bitrise step. Thanks. Been busy with some personal stuff, have plans to wrap up those steps before the end of the year. 🤞
