### ISSUE TITLE
Desktop Support 

### ISSUE THREAD

**Issue by shaghasemi** [shorebirdtech/shorebird#1357]
Desktop Support, mostly windows. Looking forwardto it.

**Comment by SpajicM** [comment]
Duplicate of https://github.com/shorebirdtech/shorebird/issues/397

**Comment by eseidel** [comment]
Thanks for reaching out.  We're currently focused on getting iOS 1.0 out the door, once that's done Desktop builds should be rather easy to do, just a question of how much capacity we'll have in engineering.  Either way, @SpajicM is right, we'll keep #397 updated with our progress!
