### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by santoshkmr683** [shorebirdtech/shorebird#1358]
****Created android patch using shorebird, but not able to install****

Created android patch which display on shorebird console, but not able to install on real device.

Please check screen shot here :-
<img width="1030" alt="Screenshot 2023-10-04 at 1 36 30 PM" src="https://github.com/shorebirdtech/shorebird/assets/28430673/3786c236-1a62-4bad-854b-48ef4d0abb2e">

<img width="1030" alt="Screenshot 2023-10-04 at 1 36 58 PM" src="https://github.com/shorebirdtech/shorebird/assets/28430673/00a69396-b766-43b7-bd3e-3b5f83bd0030">

**Comment by felangel** [comment]
Hi 👋 

Are you sure you created a patch? In the screenshot you’re showing the releases page. You should be able to click on a specific release to see the patches for that release.

Also, can you share the adb logs from when you run the release? The most likely cause is that you’re not running the same version that you patched.

See https://docs.shorebird.dev/troubleshooting#i-created-a-patch-but-its-not-showing-up-in-my-app for more info.

**Comment by santoshkmr683** [comment]
Please check patch screen shot:-

<img width="1054" alt="Screenshot 2023-10-05 at 10 44 55 AM" src="https://github.com/shorebirdtech/shorebird/assets/28430673/4ca70640-2bb4-4b53-9451-bf37bf5dbf4e">

**Comment by bryanoltman** [comment]
@santoshkmr683 can you share the logcat output when running the app that you would expect to be patched? You can see these by running `adb logcat | grep flutter` if you're on mac/linux. Also see @felangel's link to our troubleshooting page. Going to close this for the time being, but if none of that helps, feel free to reopen with more info.
