### ISSUE TITLE
Can we use ofuscation?

### ISSUE THREAD

**Issue by JgomesAT** [shorebirdtech/shorebird#1359]
in flutter, I usually do this command to generate an APK obfuscated flutter build apk --release  --obfuscate --split-debug-info=./ofuscate/debug/android 
 but in shorebird I can't Do it --obfuscation is not valid param,
 
 can I use obfuscation with shorebird or is it not necessary??

**Comment by felangel** [comment]
Hi 👋 
You should be able to do:
`shorebird release android -- --obfuscate`. Let us know if that helps.

**Comment by JgomesAT** [comment]
I try this:

shorebird release android --artifact=apk --obfuscate --split-debug-info=./ofuscate/debug

and have this error:
Could not find an option named "obfuscate".
To proxy an option to the flutter command, use the -- --<option> syntax.

**Comment by JgomesAT** [comment]
Like this seems to be working:

shorebird release android --artifact=apk -- --obfuscate --split-debug-info=./ofuscate/debug

**Comment by eseidel** [comment]
We also have a request to write up docs on how to use obfuscation with Shorebird: https://github.com/shorebirdtech/shorebird/issues/1289

**Comment by tbm98** [comment]
> Hi 👋 You should be able to do: `shorebird release android -- --obfuscate`. Let us know if that helps.

The correct is `shorebird release android '--' --obfuscate`

**Comment by eseidel** [comment]
We've now launched official support for obfuscation on iOS:
https://shorebird.dev/blog/obfuscation-on-ios
