### ISSUE TITLE
feat: install specific version of flutter while installing shorebird first time. 

### ISSUE THREAD

**Issue by dhruvinnv** [shorebirdtech/shorebird#1378]
**Description**
- According to the Mac shoebird installation guide this is the command that is documented over Shorebird docs:
    - ``` shell
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
       ```
- And uses the latest available Flutter version instead of the Flutter version.

**Requirements**
- Provide a convenient method/guide to install a specific version of flutter used by the shorebird while installing. 

**Additional Context**
- While installing Shorebird first time irrespective of the local Flutter version shorebird installs the latest available version of Flutter.
- In my case, I was using Flutter `3.10.5` for my all projects, and when I tried to install the Shorebird it had installed Flutter version `3.13.5`, so I had to switch to another version after installing. 
- It would be nice if I can directly install shorebird flutter version which in sync with my local flutter version.

**Comment by eseidel** [comment]
Thanks!  We support automatically configuring the flutter version as part of CI, but not currently at time of install:
https://docs.shorebird.dev/ci/github

I think it's reasonable that we could provide a mention in the docs about using a different Flutter version, e.g. https://docs.shorebird.dev/flutter-version

**Comment by eseidel** [comment]
I've added a link to the flutter-version instructions during install.  I don't intend for us to add a flag to the installer at this time.
