### ISSUE TITLE
fix: Failed to determine release version: Exception: Could not determine release version for iOS flutter

### ISSUE THREAD

**Issue by yishaq06** [shorebirdtech/shorebird#1381]

**Comment by eseidel** [comment]
Would love to help.   Was there any more of the log?  You might try running with `-v` to see more details from the command.

This typically happens because our parsing logic for versions cannot find the resulting IPA or xcarchive after the build is complete.

**Comment by yishaq06** [comment]
I resolved the issue by running flutter clean and flutter pub get
