### ISSUE TITLE
feat: having one command to build Android and iOS together

### ISSUE THREAD

**Issue by anderscheow** [shorebirdtech/shorebird#1383]
**Description**

Currently we're required to run two commands `shorebird release android` and `shorebird release ios-alpha` to release for both Android and iOS.

It could be nice that if we can just use single command to release for both Android and iOS. It can also support to return error if either release build failed or ignore error on any build failed.

**Requirements**

- [ ] Single command to release for Android and iOS
- [ ] Support existing flags, for example: `flavour`, `artifact`, `force` etc.
- [ ] Can introduce `ignore-error` to ignore any build error or throw error if any

**Comment by eseidel** [comment]
It's now possible to build both at the same time with the --platforms option.
