### ISSUE TITLE
fix: ##[error]Bash exited with code '70'.

### ISSUE THREAD

**Issue by yusufsirinn** [shorebirdtech/shorebird#1384]
When you run the 

`shorebird release android --target ./lib/main_${{ parameters.flavour }}.dart --flavor ${{ parameters.flavor }} --artifact apk --force `

command in the Azure pipeline, `##[error]Bash exited with code '70'.` I'm getting the error.

`shorebird release android --target ./lib/main_${{ parameters.flavour }}.dart --flavor ${{ parameters.flavour }} --artifact apk --force
            shorebird patch android --target ./lib/main_${{ parameters.flavour }}.dart --flavor ${{ parameters.flavour }} --force`

But when I run these two commands together, I don't get any errors.

**Comment by yusufsirinn** [comment]
`⠋ Building release...[WARN] Build was successful, but `flutter pub get` failed to run after the build completed. You may see unexpected behavior in VS Code.

Either run `flutter pub get` manually, or follow the steps in https://docs.shorebird.dev/troubleshooting#i-installed-shorebird-and-now-i-cant-run-my-app-in-vs-code

[WARN] Build was successful, but `flutter pub get` failed to run after the build completed. You may see unexpected behavior in VS Code.

Either run `flutter pub get` manually, or follow the steps in https://docs.shorebird.dev/troubleshooting#i-installed-shorebird-and-now-i-cant-run-my-app-in-vs-code

Also, another warning like above.

I couldn't find a solution when I looked at what was written in the link.

**Comment by bryanoltman** [comment]
Which OS are you running? Is Flutter on your path? (i.e., if you run `which flutter` on mac or linux or `where.exe flutter` on Windows, what do you see?)

**Comment by felangel** [comment]
Closing this for now since there aren't any actionable next steps without additional info. If you're still facing this issue please feel free to provide additional info and we're happy to take a closer look 👍
