### ISSUE TITLE
Total installs per month not resetting

### ISSUE THREAD

**Issue by azeek** [shorebirdtech/shorebird#1389]
hello.

I have been using the team plan since last month. 

This month, on October 8, it was renewed and payment went through, but the total install count didn't reset and the remaining install count didn't increase. 

What happened?

Thank you for creating such a great service.

**Comment by eseidel** [comment]
Hmm, thank you very much for raising this.  We can look shortly.

**Comment by eseidel** [comment]
Oh, could you please post one of your app_id's so that we can find your account in our system?
https://docs.shorebird.dev/faq#do-i-need-to-keep-my-app_id-secret

**Comment by azeek** [comment]
my app_id is: 8e78abcd-b845-485d-a9e7-3e91640eb0b1

**Comment by felangel** [comment]
@azeek are you able to share the number of patch installs you're seeing the console?

**Comment by bryanoltman** [comment]
It looks like your patch install count should have reset on the 8th, as you expect. The app ID that is responsible for your patch installs is `969ca550-a1d1-4178-9f92-83206a35a451` (mostly noting that for our record keeping). We're seeing 7969 patch installs over the past 6 days. As @felangel says, it'd be great to get a screenshot of what you're seeing in the console.

**Comment by azeek** [comment]
<img width="1033" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/12044384/3a9d26ef-ce83-45d9-bf32-72dcb0ba96f7">
This is what's currently floating on my console screen.

**Comment by eseidel** [comment]
Thanks.  We found the bug and have fixed it.  We'll be deploying the fix shortly.

**Comment by eseidel** [comment]
The fix was just deployed.  Please let us know if you're still seeing anything unexpected!  Thanks!
