### ISSUE TITLE
fix: teams account can't add collaborators

### ISSUE THREAD

**Issue by actiondirect** [shorebirdtech/shorebird#1390]
**Description**

Just paid for the teams account. Created app id, but still cannot add collaborators to my apps.
Shorebird console/account view shows that I am teams account owner and also lists my app with app id, but command line will still say "**The account requires an upgraded plan to use this functionality**."

**Expected Behavior**

Able to add collaborators

**Screenshots**

![image](https://github.com/shorebirdtech/shorebird/assets/31061202/441dfb6a-91b4-45fb-9c03-ce54fbbbf31e)

**Additional Context**

**Comment by eseidel** [comment]
Thanks for the report!  Are you able to email us or post here your app_id so we can check?  (app_ids don't need to be kept secret):
https://docs.shorebird.dev/faq#do-i-need-to-keep-my-app_id-secret
https://docs.shorebird.dev/teams

**Comment by actiondirect** [comment]
6afe9b46-25b6-4348-9a24-7e6bae8dbe95 is the app id. Thanks!

**Comment by felangel** [comment]
> 6afe9b46-25b6-4348-9a24-7e6bae8dbe95 is the app id. Thanks!

Can you confirm that you're logged into the Shorebird CLI using the same account that created the app? You can double check this by signing into https://console.shorebird.dev and making sure you see the app.

**Comment by actiondirect** [comment]
yes and yes!
![image](https://github.com/shorebirdtech/shorebird/assets/31061202/946a33b5-dd60-4984-8154-12d043aa6e02)

Also attaching my account,
![image](https://github.com/shorebirdtech/shorebird/assets/31061202/258eaa88-3e38-44d3-b275-cf5ced1733b0)

**Comment by actiondirect** [comment]
![image](https://github.com/shorebirdtech/shorebird/assets/31061202/a8cbccf7-4c92-49eb-a599-129c59829662)

**Comment by felangel** [comment]
> yes and yes! ![image](https://user-images.githubusercontent.com/31061202/274777659-946a33b5-dd60-4984-8154-12d043aa6e02.png)
> 
> Also attaching my account, ![image](https://user-images.githubusercontent.com/31061202/274777868-258eaa88-3e38-44d3-b275-cf5ced1733b0.png)

Thanks we’ll take a closer look shortly sorry for the inconvenience!

**Comment by bryanoltman** [comment]
Fixed by https://github.com/shorebirdtech/_shorebird/commit/6ebc48f9499391b33191be970505a7c7168d08ce
