### ISSUE TITLE
fix: yaml errors result in confusing gradle errors

### ISSUE THREAD

**Issue by gabrielmulyawan** [shorebirdtech/shorebird#1391]
- flutter version 3.13.6
- build with 2 flavors
- shorebird init and doctor not issue

- shorebird.yaml success generating with 2 flavor 
- already flutter clean

run 
shorebird release android --artifact apk --flavor dev

get error 
* Where:
Script 'C:\Users\gabri\.shorebird\bin\cache\flutter\ef4b661ddc0c71b738432ae59c6bc573e917854b\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1125

* What went wrong:
Execution failed for task ':app:copyFlutterAssetsDevRelease'.
> expected '<document start>', but found '<block mapping start>'
   in 'string', line 8, column 1:
      app_id: b130ef1a-cce7-4b84-bc37- ...
      ^

screenshot 
![image](https://github.com/shorebirdtech/shorebird/assets/17560222/6b86b9eb-d695-4d5f-9c0e-fce7256120bc)

![image](https://github.com/shorebirdtech/shorebird/assets/17560222/914aa890-24e0-4cb8-8aae-7f36bf196842)

**Comment by felangel** [comment]
Hi @gabrielmulyawan 
Can you please share your `shorebird.yaml`?

**Comment by gabrielmulyawan** [comment]
Hi @felangel 
yes, that my shorebird.yaml
![image](https://github.com/shorebirdtech/shorebird/assets/17560222/c81b6910-130f-4169-9216-251306e905d1)

**Comment by felangel** [comment]
It looks like it’s because the you have the word “hi” at the start of your shorebird.yaml which makes it an invalid yaml file

**Comment by gabrielmulyawan** [comment]
Thanks, my bad. now running correctly

**Comment by eseidel** [comment]
I'm going to keep this open so we fix the error to be better.  Thanks!

**Comment by eseidel** [comment]
Actually, closing.  This seems like a reasonable error from Groovy, if a bit verbose.
