### ISSUE TITLE
Issue: shorebird init command not working on windows machine

### ISSUE THREAD

**Issue by santoshkmr683** [shorebirdtech/shorebird#1392]
**After running shorebird init command on windows machine, getting below error:-**

✗ Detecting product flavors (5.2s)
Unable to extract product flavors.
Exception: > Task :gradle:extractPluginRequests NO-SOURCE
> Task :gradle:generatePluginAdapters UP-TO-DATE
> Task :gradle:compileJava NO-SOURCE
> Task :gradle:compileGroovy FAILED
2 actionable tasks: 1 executed, 1 up-to-date

FAILURE: Build failed with an exception.

**Comment by carllosnc** [comment]
+1 

`flutter create my_app`
`shorebird init`

````
❯ shorebird init
✗ Detecting product flavors (6.7s)
Unable to extract product flavors.
Exception: Starting a Gradle Daemon, 3 busy and 5 incompatible and 1 stopped Daemons could not be reused, use --status for details


FAILURE: Build failed with an exception.

* Where:
Build file '\my_app\android\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not open cp_proj generic class cache for build file \my_app\android\app\build.gradle' (.gradle\caches\7.5\scripts\52c2dfmq86br7sqw5y13kinam).
      > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
````

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on Microsoft Windows [Version 10.0.22621.2361], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.4)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**shorebird doctor**
```
Shorebird 0.16.1 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.6 • revision ef4b661ddc0c71b738432ae59c6bc573e917854b
Engine • revision 35809a641ed60f9595fcb6c6f939a8768eaca976

✓ Shorebird is up-to-date (0.7s)
✓ Flutter install is correct (0.7s)
✓ AndroidManifest.xml files contain INTERNET permission (44ms)

No issues detected!
```

**Comment by eseidel** [comment]
> +1
> 
> `flutter create my_app` `shorebird init`
> 
> ```
> ❯ shorebird init
> ✗ Detecting product flavors (6.7s)
> Unable to extract product flavors.
> Exception: Starting a Gradle Daemon, 3 busy and 5 incompatible and 1 stopped Daemons could not be reused, use --status for details
> 
> 
> FAILURE: Build failed with an exception.

I've filed a separate issue for this: https://github.com/shorebirdtech/shorebird/issues/1393.

**Comment by eseidel** [comment]
Thank you both.  These seem like two separate failures from gradle, so I've broken the second one off into https://github.com/shorebirdtech/shorebird/issues/1393.

**Comment by eseidel** [comment]
> **After running shorebird init command on windows machine, getting below error:-**
> 
> ✗ Detecting product flavors (5.2s) Unable to extract product flavors. Exception: > Task :gradle:extractPluginRequests NO-SOURCE
> 
> > Task :gradle:generatePluginAdapters UP-TO-DATE
> > Task :gradle:compileJava NO-SOURCE
> > Task :gradle:compileGroovy FAILED
> > 2 actionable tasks: 1 executed, 1 up-to-date
> 
> FAILURE: Build failed with an exception.

This is where we call out to gradle:
https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/executables/gradlew.dart#L74

If you run `shorebird init -v` it will also post the full call.  My guess is that your build.gradle file may be missing?

I think what it's running is `gradelw app:tasks --all --console=auto`

Does `flutter build appbundle` work with your project?

**Comment by JaysonKhan** [comment]
BUG! exception in phase 'semantic analysis' in source unit 'C:\src\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' Unsupported class file major version 65

**Comment by eseidel** [comment]
> BUG! exception in phase 'semantic analysis' in source unit 'C:\src\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' Unsupported class file major version 65

That's likely https://github.com/shorebirdtech/shorebird/issues/1163.

**Comment by bryanoltman** [comment]
I believe this has been fixed by https://github.com/shorebirdtech/shorebird/pull/1405
