### ISSUE TITLE
BUG! exception in phase 'semantic analysis' in source unit

### ISSUE THREAD

**Issue by JaysonKhan** [shorebirdtech/shorebird#1394]
PS C:\games\iBilling> shorebird init   
✗ Detecting product flavors (5.9s)
Unable to extract product flavors.
Exception: > Task :gradle:extractPluginRequests NO-SOURCE
> Task :gradle:generatePluginAdapters UP-TO-DATE
> Task :gradle:compileJava NO-SOURCE
> Task :gradle:compileGroovy FAILED
2 actionable tasks: 1 executed, 1 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gradle:compileGroovy'.
> BUG! exception in phase 'semantic analysis' in source unit 'C:\src\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by eseidel** [comment]
My guess is this is a java version mismatch, e.g. https://github.com/shorebirdtech/shorebird/issues/1163

@betta347 would you be able to provide the output of `shorebird doctor -v`?  Thanks!

**Comment by rikiyanuar** [comment]
Hi, I got same issue when run shorebird init.
Btw, I use Macbook Pro M2

this is the result of `shorebird doctor -v`

```
➜  ~ shorebird doctor -v
Shorebird 0.16.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.10.5 • revision ba444de6ceb9313320a70563d7b6203344e0cd87
Engine • revision 24fdd628e38b6dbc75ac25e72f61f6e8c75e4344

Android Toolchain
  • Android Studio: /Applications/Android Studio.app/Contents
  • Android SDK: /Users/me/Library/Android/sdk
  • ADB: /Users/me/Library/Android/sdk/platform-tools/adb
  • JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home

✓ Shorebird is up-to-date (1.1s)
✓ Flutter install is correct (2.6s)

No issues detected!
```

**Comment by eseidel** [comment]
Bryan fixed https://github.com/shorebirdtech/shorebird/issues/1163 yesterday, which we will be releasing today or tomorrow.  Until then you should be able to work around the issue by running `unset JAVA_HOME` before `shorebird`

**Comment by bryanoltman** [comment]
I think this should be fixed by https://github.com/shorebirdtech/shorebird/pull/1405
