### ISSUE TITLE
fix: shorebird release should support being run from child directories

### ISSUE THREAD

**Issue by btrautmann** [shorebirdtech/shorebird#1395]
**Description**

Running `shorebird release ...` from a child directory of the Flutter project's root directory fails with the following error:

```console
Shorebird is not initialized. Did you run "shorebird init"?
```

However, running `flutter build ...` in the same directory produces the following logs before succeeding:

```console
path/to/root/of/project/ios » flutter build ipa
Changing current working directory to: /path/to/root/of/project
```

Because `shorebird release` is a pipe through to `flutter build` as called out in the docs [here](https://docs.shorebird.dev/code_push/release), it should behave similarly and succeed as if it were run in the root of the project.

This was discussed in Discord [here](https://discord.com/channels/1030243211995791380/1125516353370075306/1162224072973877309).

**Steps To Reproduce**

1. Create a flutter project
2. Run `shorebird init`
3. `cd` into a child directory (e.g `ios/` or `android/`)
4. Run `shorebird release ...`

**Expected Behavior**

The command succeeds (assuming no other issues).

**Comment by eseidel** [comment]
This is very similar to https://github.com/shorebirdtech/shorebird/issues/1213 and https://github.com/shorebirdtech/shorebird/issues/1163.  Basically `flutter` has one set of (sometimes quirky) behaviors, and we're offering `shorebird` as a drop-in replacement for `flutter`, so whenever possible we need to match those quirks.
