### ISSUE TITLE
feat: ability to specify build number and version name for patches

### ISSUE THREAD

**Issue by btrautmann** [shorebirdtech/shorebird#1396]
**Description**

Due to the fact that `shorebird release` allows you to provide `--build-number` and `--build-name` arguments when creating releases (they're passed to the underlying `flutter build` invocation), I expected to be able to do the same for `shorebird patch`. Because I can't, there's no way (AFAICT) for me to create a patch for a release that used `--build-number` and `--build-name` without manually changing my `pubspec.yaml` file.

**Rationale**

I never change my `pubspec.yaml` file and instead use a Github Action that determines (based on tags) the correct build name to use and a simple file within my repo to track build number (mainly to fulfill Android's `versionCode` always-increments requirement. Otherwise I'd use the aforementioned Github Action's `increment` output to satisfy build number).

**Requirements**

- [ ] Add flags for `--build-name` and `--build-number` to the `shorebird patch` command
- [ ] Use these flags to patch the corresponding version (if it exists/has been released)

**Additional Context**

Another potentially reasonable intermediate fix is to always patch the latest version of the release Shorebird last built/uploaded. This is actually what I expected to happen when running `shorebird patch` without any version arguments.

**Comment by btrautmann** [comment]
For the record, I saw [this message](https://discord.com/channels/1030243211995791380/1125516353370075306/1158952020535947365) from @felangel indicating how the version is determined. I suspect that this has the same disadvantage in that it's using the `pubspec.yaml` defined version to determine the version to patch. I'd like to essentially be able to override this via the proposed arguments.

**Comment by btrautmann** [comment]
So I have to admit that I opened this after "pulling an all-nighter" (not by choice, I'm sick and couldn't sleep) and I've since learned that `shorebird patch` does in fact operate like `shorebird release` in that it consumes arguments meant for `flutter build` appended after the `--` in the command. My read on the following image on the `Release` docs was that only `release` accepted the args, but both do!

![Screenshot 2023-10-13 at 16 24 53](https://github.com/shorebirdtech/shorebird/assets/8343465/2b6421a0-0faf-426e-b7ac-439695a34f95)

This means that you CAN pass `--build-number` and `--build-name` to `shorebird patch` and it seems to respect them:

![Screenshot_2023-10-13_at_16 21 08](https://github.com/shorebirdtech/shorebird/assets/8343465/c8e4087d-93f9-4cab-b753-abf0bd4870e4)

_**Note** that I have not released a version `0.0.1+3`, I was purely testing that it respected the inputs and gave me the correct error message_

I have not yet done a full end-to-end release cycle using these inputs, but I'm going to close this issue optimistically because I believe everything should be working as expected. Apologies for the noise!

**Comment by eseidel** [comment]
Posted https://github.com/shorebirdtech/docs/pull/163 to add the note about passing args to `flutter build` to `shorebird patch` as well.

**Comment by bryanoltman** [comment]
To expand on this, it is possible to specify a release version via this flags. For example, if I wanted to patch the release with version `1.0.0+3`, I would use the commands:

`shorebird patch ios-alpha -- --build-number 3 --build-name 1.0.0`

and

`shorebird patch android -- --build-number 3 --build-name 1.0.0`

**Comment by bryanoltman** [comment]
However, this doesn't work if the android/iOS apps do not consume the version number from the pubspec

**Comment by bryanoltman** [comment]
To expand:

I create a new flutter app (flutter create) and go into the android app's build.gradle , by default you'll see something like this: 

```
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
```

But if I were to change that to something like:

```
        versionCode 5
        versionName "1.2.3"
```

And run shorebird release android -- --build-number 50 --build-name 1.0.0, the release that is generated is version 1.2.3+5.
