### ISSUE TITLE
fix: ios build didn't receive notification

### ISSUE THREAD

**Issue by RaflyLesmana3003** [shorebirdtech/shorebird#1407]
**Description**

Greetings everyone, I'm currently utilizing Braze for customer engagement tools. However, when I attempt to launch a push notification campaign, I encounter an issue where I do not receive the notification on my iOS build, although it works perfectly on Android.

For in-app message notifications, both iOS and Android are functioning as expected. The problem only arises when attempting to receive push notifications on iOS.

**Expected Behavior**

The iOS build of Shorebird should be able to receive the push notification.

**Comment by Nortina** [comment]
My build is works fine. Did you check the APN Settings?

You can check settings in Firebase console and apple developer site.

Apple developer settings in Apple developer Certificates, Identifiers & Profiles, please follow below this. 
- Identifiers > your app identifier > Push Notifications is checked
- Keys > your APN key (if you didn't have, create one) > Enabled Services, Apple Push Notifications service (APNs) is exist, and ~.p8 key file is stored. (If you losted the key file, invoke the key and create another one then you can download the key file)

Firebase settings is in Firebase console > your project > project settings > cloud messaging > Apple app configuration > APNs Authentication Key is registered (the key is .p8 file, the team id is in apple developer page's right top side, next to the your team name)

**Comment by eseidel** [comment]
@RaflyLesmana3003 we'd love to help, but I expect it's as @Nortina says, this is unlikely to be caused by shorebird.

iOS does have additional restrictions around notifications and requires setting up entitlements.

https://github.com/felangel/flutter_and_friends is one example of an app using Shorebird and notifications in case it's useful.
