### ISSUE TITLE
feat: support for Windows, MacOS and Linux

### ISSUE THREAD

**Issue by anderscheow** [shorebirdtech/shorebird#1415]
**Description**

Since Flutter is getting more popular on desktop platforms (Windows, MacOS and Linux), it's great if Shorebird can provide support to desktop platforms. 

**Requirements**

- [ ] Windows platform
- [ ] MacOS platform
- [ ] Linux platform

**Comment by bryanoltman** [comment]
This is a duplicate of https://github.com/shorebirdtech/shorebird/issues/397, closing in favor of the existing issue
