### ISSUE TITLE
feat: Utilizing flutter_smooth to avoid jank introduced by iOS non-AOT dart code?

### ISSUE THREAD

**Issue by fzyzcjy** [shorebirdtech/shorebird#142]
Hi, excited to see a code push solution! Cannot wait to try the code push out :)

I wonder whether this will be helpful for code push (disclaimer: I am the author): https://github.com/fzyzcjy/flutter_smooth 

The proposal:
https://github.com/flutter/flutter/issues/113281

Roughly speaking, the idea is that:
IMHO iOS only allows interpreted code, so cannot have a AOT/JIT binary pushed to ios. Then the build/layout phase can be quite slow because the Dart is now interpreted instead of JIT/AOTed. Then flutter_smooth can avoid this problem by making build/layout phase as smooth as full FPS no matter how slow it is.

For future readers: I also posted here https://discord.com/channels/1030243211995791380/1030243213002412164/1088257874674860042

**Comment by eseidel** [comment]
Thank you for the offer! Best of luck with the project!

**Comment by fzyzcjy** [comment]
@eseidel You are welcome!
