### ISSUE TITLE
Enforce Patch Limits

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1421]
Right now we're only enforcing patch limits on "hobby" plans, and any paid plan currently has no enforced limit.

This bug is about turning on limit enforcement for paid plans.

Steps I can think of:
- [x] Make it possible to self-serve purchase a higher tier
- [ ] Email customers over the 50k limit and invite them to upgrade
- [x] Setup automated emailing for customers when they are near limits
  - https://github.com/shorebirdtech/_shorebird/pull/444
- [ ] Let customers disable automated emails
  - https://github.com/shorebirdtech/_shorebird/pull/428
  - https://github.com/shorebirdtech/_shorebird/pull/429
  - https://github.com/shorebirdtech/_shorebird/pull/430
  - TODO: console work
- [x] Turn on limit enforcement

**Comment by bryanoltman** [comment]
This is all done except for "Email customers over the 50k limit and invite them to upgrade" and "Let customers disable automated emails" (support for which is implemented, we just need a checkbox on the console).

**Comment by eseidel** [comment]
Done enough for now.
