### ISSUE TITLE
[shorebird] failed to generate shorebird configuration.

### ISSUE THREAD

**Issue by hamzehmathamneh** [shorebirdtech/shorebird#1428]
```
[shorebird] failed to generate shorebird configuration.
Exception: Cannot find shorebird.yaml in /Users/../build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app/Frameworks/App.framework/flutter_assets/shorebird.yaml.
Please file an issue at: https://github.com/shorebirdtech/shorebird/issues/new

Could not build the precompiled application for the device.

Error launching application on Hamzeh’s iPhone.
```

**This message appeared when i removed flutter flavors configuration from my flutter project**

I'll appreciate any help, thanks.

**Comment by bryanoltman** [comment]
You will need to re-init your shorebird project if you are removing flavors (that is, re-run `shorebird init`)

**Comment by bryanoltman** [comment]
Your project should have a `.dart_tool/package_config.json` file. Can you share the entry for flutter? I think the changing of flavors might be a red herring here.

**Comment by bryanoltman** [comment]
And to be clear, this is happening when you're trying to run your app using the "run" option in VS Code?

**Comment by bryanoltman** [comment]
We figured this out last week, and resolved with https://github.com/shorebirdtech/docs/pull/168. See that bug for more details.

**Comment by asadamatic** [comment]
I'm facing this issue, even after upgrading `shorebird`.

**Comment by asadamatic** [comment]
I noticed that the `shorebird upgrade` command didn't fetch the latest update, so I ran it again. 

I had to run `shorebird cache clean` after that. 

This issue is fixed.
