### ISSUE TITLE
feat: Record --force or "yes" in our db when making a patch

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1437]
More information about how the user may have created an unstable patch might be useful to log in our db?

This is similar to the idea of possibly recording (some of?) the command line arguments during release, for later re-use, just the idea that we should possibly be capturing more information about how the release/patch was made so we can later help the user debug.

**Comment by bryanoltman** [comment]
This is done. We have a `wasForced` column in the patches table and record other metadata from the patch and release commands.
