### ISSUE TITLE
FormatException: Could not find End of Central Directory Record

### ISSUE THREAD

**Issue by josercc** [shorebirdtech/shorebird#1440]
➜  flavors shorebird preview android                                                                                  
✓ Fetching apps (0.6s)
Which app would you like to preview? flavors (internal)
✓ Fetching releases (0.6s)
Which release would you like to preview? 1.0.0+6
✗ FormatException: Could not find End of Central Directory Record (14ms)

<img width="1012" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/4713847/e224a85d-afae-4fff-9733-eb61ed1e2afe">

**Comment by eseidel** [comment]
This would suggest that the tool is having difficulty parsing the .aab file.  We could check our servers to see if somehow the .aab is corrupted.

**Comment by eseidel** [comment]
For clarity "Could not find End of Central Directory Record" is a message from zip (in this case, probably package:archive).  .apk and .aab files are just zips under the covers.  Since we store .aab files on our servers by default, this is most likely the .aab failing to parse.

**Comment by josercc** [comment]
You can preview it after repackaging.

**Comment by eseidel** [comment]
When you say "repackaging" to you mean running `shorebird release` again?  It seems like a bug (and concerning) that we would ever produce a binary that we can't later parse.

**Comment by josercc** [comment]
> When you say "repackaging" to you mean running `shorebird release` again? It seems like a bug (and concerning) that we would ever produce a binary that we can't later parse.

YES is mean shorebird release
