### ISSUE TITLE
fix: User reports SocketException on login

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1442]
User is reporting:
```
ClientException with SocketException: Operation timed out (OS Error: Operation timed out, errno = 60), address = oauth2.googleapis.com, port = 49950, uri=https://oauth2.googleapis.com/token
I don’t know how to log in
```
I believe this is during `shorebird login`, and I believe the user may be in China or behind another firewall.  This probably a variant of: https://github.com/shorebirdtech/shorebird/issues/435

**Comment by 956569686** [comment]
I use a VPN proxy to go to the United States, and the IP is also shown as the United States, but I still can’t log in.

**Comment by eseidel** [comment]
Hmm, I wonder if somehow `shorebird login` is not respecting the proxy?

I'm not sure if `dart` respects http proxies from the system without setting environment variables, e.g.
https://github.com/dart-lang/pub-dev/issues/2186

**Comment by rizkijuliansyaham** [comment]
previously i cant login too (use my default web browser Brave), then i try to use google chrome for login and open link login. tadaaaaaa, login success @eseidel , maybe you must to try.

**Comment by eseidel** [comment]
We've not had any reports of this since.  We'd be very happy to help, but not really sure what to do here.

https://discord.gg/shorebird reaches us by chat.
https://calendly.com/eseidel reaches us by google meet or zoom.

Closing for now, but please don't hesitate to re-open or reach out if we can be of help!
