### ISSUE TITLE
fix: Error: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME or PATH environment variable.

### ISSUE THREAD

**Issue by neetable-chollarasan** [shorebirdtech/shorebird#1466]
**This issue happening while running shorebird preview in android device**

my shorebird doctor 

Android Toolchain
  • Android Studio: /Applications/Android Studio.app/Contents
  • Android SDK: /Users/chollarasan/Library/Android/sdk
  • ADB: /Users/chollarasan/Library/Android/sdk/platform-tools/adb
  • JAVA_HOME: /Applications/Android Studio.app/Contents/jbr/Contents/Home

✓ Shorebird is up-to-date (0.7s)
✓ Flutter install is correct (0.4s)
✓ AndroidManifest.xml files contain INTERNET permission (32ms)

No issues detected!

my flutter doctor
[!] Flutter (Channel stable, 3.13.9, on macOS 13.5.2 22G91 darwin-arm64, locale en-IN)
    • Flutter version 3.13.9 on channel stable at /Users/chollarasan/Documents/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/chollarasan/Documents/flutter. Consider adding /Users/chollarasan/Documents/flutter/bin to the front of
      your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/chollarasan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode14.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Pixel 6a (mobile) • 23261JEGR11935 • android-arm64 • Android 13 (API 33)
    • macOS (desktop)   • macos          • darwin-arm64  • macOS 13.5.2 22G91 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by felangel** [comment]
Hi @neetable-chollarasan 👋 
Are you able to reproduce this on the latest stable version of shorebird? If this is still an issue can you please share the output of `shorebird doctor --verbose`? Thanks!

**Comment by bigBoy-mm** [comment]
Hi, I have exactly the same issue.

```
Shorebird 0.18.1 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.9 • revision 39df2792f537b1fc62a9c668a6990f585bd91456
Engine • revision e81fa131e59506d9f6af2a0cee7de749131f1bf0

Android Toolchain
  • Android Studio: /Applications/Android Studio.app/Contents
  • Android SDK: /Users/marcinmakurat/Library/Android/sdk
  • ADB: /Users/marcinmakurat/Library/Android/sdk/platform-tools/adb
  • JAVA_HOME: /Applications/Android Studio.app/Contents/jbr/Contents/Home

✓ Shorebird is up-to-date (0.9s)
✓ Flutter install is correct (0.5s)
✓ AndroidManifest.xml files contain INTERNET permission (37ms)

No issues detected!
```

**Comment by bryanoltman** [comment]
@bigBoy-mm can you share the output of the command that is triggering this issue with the `-v` flag? e.g., `shorebird release android -v`

**Comment by neetable-chollarasan** [comment]
@felangel  yes reproducible in stable version here my output for shorebird doctor --verbose

Shorebird 0.18.3 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.9 • revision 39df2792f537b1fc62a9c668a6990f585bd91456
Engine • revision e81fa131e59506d9f6af2a0cee7de749131f1bf0

Android Toolchain
  • Android Studio: /Applications/Android Studio.app/Contents
  • Android SDK: /Users/chollarasan/Library/Android/sdk
  • ADB: /Users/chollarasan/Library/Android/sdk/platform-tools/adb
  • JAVA_HOME: /Applications/Android Studio.app/Contents/jbr/Contents/Home

✓ Shorebird is up-to-date (0.7s)
✓ Flutter install is correct (0.4s)
✓ AndroidManifest.xml files contain INTERNET permission (31ms)
✓ Has access to storage.googleapis.com (0.5s)

No issues detected!

**Comment by felangel** [comment]
> @felangel yes reproducible in stable version here my output for shorebird doctor --verbose
> 
> Shorebird 0.18.3 • [git@github.com](mailto:git@github.com):shorebirdtech/shorebird.git Flutter 3.13.9 • revision 39df2792f537b1fc62a9c668a6990f585bd91456 Engine • revision e81fa131e59506d9f6af2a0cee7de749131f1bf0
> 
> Android Toolchain • Android Studio: /Applications/Android Studio.app/Contents • Android SDK: /Users/chollarasan/Library/Android/sdk • ADB: /Users/chollarasan/Library/Android/sdk/platform-tools/adb • JAVA_HOME: /Applications/Android Studio.app/Contents/jbr/Contents/Home
> 
> ✓ Shorebird is up-to-date (0.7s) ✓ Flutter install is correct (0.4s) ✓ AndroidManifest.xml files contain INTERNET permission (31ms) ✓ Has access to storage.googleapis.com (0.5s)
> 
> No issues detected!

Can you share the full output you're seeing when running with the `--verbose` flag? Thanks!
