### ISSUE TITLE
Should be some way to know your login status

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#148]
e.g. `shorebird whoami` or similar?

**Comment by eseidel** [comment]
Or even `shorebird login` could tell me:
```
eseidel@erics-mbp GitHub % shorebird login
You are already logged in.
Run 'shorebird logout' to log out and try again.
```

**Comment by eseidel** [comment]
Maybe this is just part of `shorebird doctor`? https://github.com/shorebirdtech/shorebird/issues/152

**Comment by carl-duncan** [comment]
Already integrated

**Comment by eseidel** [comment]
Yes, true!  `shorebird account` exists now.  Thanks!
