### ISSUE TITLE
fix: update shorebird

### ISSUE THREAD

**Issue by the-best-is-best** [shorebirdtech/shorebird#1486]
iwr -UseBasicParsing 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex 
 
iwr -UseBasicParsing 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex --force

no anyone work to update shorebird.

**Comment by eseidel** [comment]
`shorebird upgrade` is all that should be needed to update shorebird.
