### ISSUE TITLE
Upgrade to Flutter 3.16.0 / Dart 3.2.0

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1501]
The bulk of the work will likely be doing the Dart 3.2.0 upgrade because there were more changes to how Dart handles FFI (and one of the large changes in our private Dart fork is how we handle FFI).

**Comment by eseidel** [comment]
Update: I've decided to delay our upgrade to 3.16.0 for a bit while we finish getting iOS Beta out the door.  Please let us know if that's a problem.

**Comment by eseidel** [comment]
Update:  I want to acknowledge that this is much slower than our typical update cadence (normally we try to update to the latest flutter within hours of release).  We're extremely close on releasing iOS (might even be able to ship our ios-beta today), and we continue to delay the work to upgrade to 3.16.0.  Regardless we will update to 3.16.0 next week (week of Nov 27th) whether we've shipped iOS Beta or not.  I still believe releasing our faster iOS first is the right trade-off for customers.  Thank you for your patience.

**Comment by mfurkanyuceal** [comment]
@eseidel  What is the latest situation, when will you be able to support flutter 3.16.1?

**Comment by eseidel** [comment]
Currently we continue to press forward on trying to release our improved iOS on top of 3.13.9.  My hope is that we ship that this week and then immediately update to 3.16.0 or 3.16.1.  Updating to 3.16.x shouldn't take very long, we've just actively chosen not to do so in order to focus all our efforts on https://github.com/shorebirdtech/shorebird/issues/674.

My estimate for 3.16.x update is mid next week.

**Comment by eseidel** [comment]
Update: We're still focused on iOS, but think we're only a day or two away from our next iOS release and then will pick up this bug right after. My current expectation is that we should release 3.16.x late this week.  Thank you all for your patience.

**Comment by eseidel** [comment]
We started this on Friday and expect to ship today or tomorrow. 🤞

**Comment by eseidel** [comment]
Reading 0.19.0 now.  Smoke testing:

- [x] e2e tests
- [ ] framework tests
- [x] engine tests
https://github.com/shorebirdtech/_build_engine/actions/runs/7187147320
- [x] flutter create + shorebird init works

- [x] iOS release
- [x] iOS patch
- [x] iOS preview

- [ ] `shorebird doctor`
    - [ ] Win
    - [x] Mac

- [x] Android release
    - [x] Win
    - [x] Mac
- [x] Android patch
    - [x] Win
    - [x] Mac
- [x] Android preview
    - [x] Win
    - [x] Mac

- [ ] iOS Add to App release
- [ ] iOS Add to App patch

- [ ] Android Add to App release
    - [ ] Win
    - [ ] Mac
- [ ] Android Add to App patch
    - [ ] Win
    - [ ] Mac

- [x] iOS Flavors release
- [x] iOS Flavors patch
- [x] iOS Flavors preview

- [ ] Android Flavors release
    - [ ] Win
    - [ ] Mac
- [ ] Android Flavors patch
    - [ ] Win
    - [ ] Mac
- [ ] Android Flavors preview
    - [ ] Win
    - [ ] Mac

**Comment by eseidel** [comment]
We found a bug in reporting patch installs in our smoke testing, which delayed the release by a few hours, but we believe we've fixed and should be releasing shortly.

**Comment by eseidel** [comment]
Shipped in 0.19.0 https://github.com/shorebirdtech/shorebird/releases/tag/v0.19.0
