### ISSUE TITLE
android hybrid app does not detect new patch

### ISSUE THREAD

**Issue by dinhtran16** [shorebirdtech/shorebird#1502]
I try to build a hybrid app according to the doc, but in the last step the app doesn't detect the new patch and nothing changes

shorebird doctor
![Screenshot 2023-11-16 at 10 00 04](https://github.com/shorebirdtech/shorebird/assets/35059033/0804b1e3-9a01-47ea-a91e-9e3395c96221)
![Screenshot 2023-11-16 at 10 01 58](https://github.com/shorebirdtech/shorebird/assets/35059033/01754007-db43-4778-967d-66e407de90fe)
![Screenshot 2023-11-16 at 10 04 18](https://github.com/shorebirdtech/shorebird/assets/35059033/4c21d1d2-e22b-49a2-a5ac-2fd7cefc104f)

**Comment by eseidel** [comment]
"Thread finished with status: No update" would suggest that the updater code got a successful response from Shorebird's servers and the servers responded there was no update for the provided release version.

Do we know what release version this hybrid app is claiming to be?  The patch was published against "1.2.3+1", but if the AndroidManifest.xml of the Hybrid app says something other than 1.2.3+1 it won't apply the patch.

https://github.com/shorebirdtech/shorebird/issues/828 and https://github.com/shorebirdtech/shorebird/issues/793 are also related here.

**Comment by bryanoltman** [comment]
@TranVanDinh235  Can you share the release and patch commands you ran?

**Comment by bryanoltman** [comment]
I believe @eseidel is correct here in that the release version you specified when running `shorebird release aar` does not match what is in your build.grade (or pubspec.yaml, depending on where you define your version number) file. These need to be the same in order for shorebird to work.

**Comment by dinhtran16** [comment]
It looks like the published patch number is different from the hybrid app release number.
![Screenshot 2023-11-27 at 15 07 07](https://github.com/shorebirdtech/shorebird/assets/35059033/bb597030-5e5c-4703-8f78-f6c99f460c19)
![Screenshot 2023-11-27 at 14 55 31](https://github.com/shorebirdtech/shorebird/assets/35059033/317bdfd7-b9f5-4eb5-95d1-7f126d902ddf)

But whichever version I set, that hybrid app release number is always **1.0+2**
![Screenshot 2023-11-27 at 14 54 41](https://github.com/shorebirdtech/shorebird/assets/35059033/0248c0fe-2312-4013-aecb-625c7fc78365)
I tried refreshing gradle. Is this a problem?

**Comment by bryanoltman** [comment]
The version code you provide to the shorebird command should match what is in your `app/build.grade` file. If https://docs.shorebird.dev/guides/hybrid-app/android#create-a-shorebird-release doesn't help, let us know!
