### ISSUE TITLE
`shorebird preview` fails: "Error: Unable to get bundle id" from .app

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1507]
From a user on Discord just now:
https://discord.com/channels/1030243211995791380/1174578672636796948/1174579135323066489

```
➜  dev_shorebird_hotupdate git:(dev_shorebird_hotupdate) ✗ shorebird preview ios-alpha -v
[HTTP] GET https://api.shorebird.dev/api/v1/apps
✓ Fetching apps (0.7s)
Which app would you like to preview? meta_winner_app
[HTTP] GET https://api.shorebird.dev/api/v1/apps/ae93cf08-88ee-49d9-9fb0-66ab75091158/releases?sideloadable=true
✓ Fetching releases (0.5s)
Which release would you like to preview? 1.0.1+1700100258
✓ Using production track (20ms)
[Process.run] xcrun devicectl --version
Exited with code 72

stderr:
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find devicectl 2> /dev/null' failed with exit code 17664: (null) (errno=Invalid argument)
xcrun: error: unable to find utility "devicectl", not a developer tool or in PATH

Using ios-deploy to install and launch.
[Process.start] /Users/king/.shorebird/bin/cache/flutter/39df2792f537b1fc62a9c668a6990f585bd91456/bin/cache/artifacts/ios-deploy/ios-deploy --debug -r --bundle /Users/king/.shorebird/bin/cache/previews/ae93cf08-88ee-49d9-9fb0-66ab75091158/ios_1.0.1+1700100258.app
[....] Waiting for iOS device to be connected
⠹ Starting app... (0.2s)[....] Using 00008101-0016405A0E82001E (D53gAP, iPhone 12, iphoneos, arm64e, 16.1, 20B82) a.k.a. '张行的iPhone12'.
------ Uninstall phase ------
2023-11-16 13:17:34.539 ios-deploy[74476:510334] [ !! ] Error: Unable to get bundle id from user command or package /Users/king/.shorebird/bin/cache/previews/ae93cf08-88ee-49d9-9fb0-66ab75091158/ios_1.0.1+1700100258.app.
Uninstall failed.
[ios-deploy] exited with code: 0
➜  dev_shorebird_hotupdate git:(dev_shorebird_hotupdate) ✗
```

**Comment by bryanoltman** [comment]
The logs are confusing, this seems to be working as intended. `devicectl` is indeed missing, but the preview command correctly falls back to `ios-deploy`. The real issue seems to be `2023-11-16 13:17:34.539 ios-deploy[74476:510334] [ !! ] Error: Unable to get bundle id from user command or package /Users/king/.shorebird/bin/cache/previews/ae93cf08-88ee-49d9-9fb0-66ab75091158/ios_1.0.1+1700100258.app.`. I'm not sure if this is an `ios-deploy` issue or an issue with the app we built, will dig further.

**Comment by bryanoltman** [comment]
Updated the title. The error message about devicectl is bad and I will fix that now, but the main issue is `Error: Unable to get bundle id from user command or package /Users/king/.shorebird/bin/cache/previews/ae93cf08-88ee-49d9-9fb0-66ab75091158/ios_1.0.1+1700100258.app`

**Comment by bryanoltman** [comment]
Ah, and the error logging is happening because verbose is on and we've told shorebird to be really loud when a command exits with a non-zero code in verbose mode. I'm not sure if there's any change to be made here re: logging.

**Comment by eseidel** [comment]
Nothing more to do here at this time.
