### ISSUE TITLE
fix: `analyze_snapshot` should be moved into ios

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#1508]
**Description**
Currently, in order to use the linker for iOS, users need to have done an android release (since we require analyze snapshot which is currently located in `shorebird/bin/cache/flutter/39df2792f537b1fc62a9c668a6990f585bd91456/bin/cache/artifacts/engine/android-arm-release/darwin-x64/analyze_snapshot`.

**Expected Behavior**

We should move this into `ios-arm-release/darwin-x64` in order to allow users to release on iOS independently of android.

**Comment by bryanoltman** [comment]
Taking over since Felix is out today
