### ISSUE TITLE
Failed to extract version name from app bundle: Error: could not open `C:\Program Files\Android\Android Studio\jbr\lib\jvm.cfg'

### ISSUE THREAD

**Issue by the-best-is-best** [shorebirdtech/shorebird#1514]
shorebird release android 

Exception: Failed to extract version name from app bundle: Error: could not open `C:\Program Files\Android\Android Studio\jbr\lib\jvm.cfg'

in last version in android studio

**Comment by bryanoltman** [comment]
Can you share the output of this command with the `-v` flag? There's not a lot to go on in this bug report.

**Comment by bryanoltman** [comment]
Seeing the output of `shorebird doctor -v` would be helpful as well.

**Comment by the-best-is-best** [comment]
if i use fvm how make shorebird  use the sdk version from flutter
The version of Flutter that Shorebird includes and the Flutter on your path are different.
        Shorebird Flutter: 3.13.9
        System Flutter:    3.16.0

**Comment by the-best-is-best** [comment]
Shorebird 0.18.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.9 • revision 39df2792f537b1fc62a9c668a6990f585bd91456
Engine • revision e81fa131e59506d9f6af2a0cee7de749131f1bf0

Android Toolchain
  • Android Studio: C:\Program Files\Android\Android Studio
  • Android SDK: C:\Users\MichelleRaouf\AppData\Local\Android\Sdk
  • ADB: C:\Users\MichelleRaouf\AppData\Local\Android\Sdk\platform-tools\adb.exe
  • JAVA_HOME: C:\Program Files\Android\Android Studio\jbr

✓ Shorebird is up-to-date (0.9s)
✗ Flutter install is correct (0.7s)
  [!] The version of Flutter that Shorebird includes and the Flutter on your path are different.
        Shorebird Flutter: 3.13.9
        System Flutter:    3.16.0
This can cause unexpected behavior if you are switching between the tools and the version gap is wide. If you have any trouble, please let us know on Shorebird discord.
✓ AndroidManifest.xml files contain INTERNET permission (51ms)
✓ Has access to storage.googleapis.com (0.1s)
1 issue detected.

**Comment by the-best-is-best** [comment]
i use flutter 3.16

**Comment by eseidel** [comment]
> i use flutter 3.16

Typically we upgrade our flutter hours after release.  This round we've decided to wait while we release our improved iOS support first.  We expect to handle the 3.16 upgrade next week: https://github.com/shorebirdtech/shorebird/issues/1501

**Comment by the-best-is-best** [comment]
oh ok i will close this issue now and wait for new update but how know the new version is released from website and thank you
