### ISSUE TITLE
Add Dart SDK layer linker / update tests.

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1519]
e.g. Actually running the linker on the result of compiling a file and seeing how much it links?

**Comment by eseidel** [comment]
This is also possible at just the dart vm layer.

**Comment by eseidel** [comment]
The test is just take one or two dart files.  Compile them to aot.  Link them (possibly against themselves) and then test for things.  e.g. did the update happen?  What percentage was linked?  Did it crash?

**Comment by bryanoltman** [comment]
Setup instructions: https://docs.google.com/document/d/17ndjgB_kES1eRzrVqLyPm4zD9CwNxpTn0DIHG6TbCM4/edit
