### ISSUE TITLE
How to deal with multiple testing groups?

### ISSUE THREAD

**Issue by shinayser** [shorebirdtech/shorebird#1532]
I just started testing the package for my company, but it makes usage of internal testing on Google Play store.
This means that a group of our users have a "more updated" code than most of the user base.

So I wonder, what will happend if I push a release on shorebird? It will update to every user possible, right?
It can't differentiate between who is an Internal tester user, or not, causing some weird stuff to happen!

My question is, there is a way to control this? If yes, any thoughts, ideas, insights?

**Comment by eseidel** [comment]
Shorebird keys updates based on the release version of the app.  So presumably the internal testers have 1.0.0+2 vs the public 1.0.0+1 or similar?  If so, then when you push an update to 1.0.0+2 it will not affect 1.0.0+1 apps as when they ask for an update they'll be told "no update available" by our servers.

You can also manually control who gets what update via shorebird_code_push pub package if desired:
https://docs.shorebird.dev/update-strategies

**Comment by shinayser** [comment]
Amazing.
But what happens if I push an emergency update to my 1.0.0+1 users. The 1.0.0+2 will also get it?
This might cause some complications too, right?

**Comment by felangel** [comment]
> Amazing.
> But what happens if I push an emergency update to my 1.0.0+1 users. The 1.0.0+2 will also get it?
> This might cause some complications too, right?

No, patches are tied to a specific release. A patch for 1.0.0+1 won’t apply to 1.0.0+2.

**Comment by shinayser** [comment]
> > Amazing.
> > But what happens if I push an emergency update to my 1.0.0+1 users. The 1.0.0+2 will also get it?
> > This might cause some complications too, right?
> 
> No, patches are tied to a specific release. A patch for 1.0.0+1 won’t apply to 1.0.0+2.

Amazing to hear that.
