### ISSUE TITLE
Execution failed for task ':app:signProductionReleaseBundle'.

### ISSUE THREAD

**Issue by shinayser** [shorebirdtech/shorebird#1533]
I tried to run ` shorebird release android --artifact apk`

![image](https://github.com/shorebirdtech/shorebird/assets/1146982/a007f51d-f373-4b5b-9d14-35bc4669a62d)

Turns out that we do not use aab on our company, just apks. 
Is there a way to force shorebird to ignore aab steps?

**Comment by eseidel** [comment]
Does https://stackoverflow.com/questions/66661789/a-failure-occurred-while-executing-com-android-build-gradle-internal-tasks-final apply in this case?

**Comment by shinayser** [comment]
I don't think so. Out signing info comes from Env vars.
As I said, we do not use aab.

There is a way to skip aab generation by shorebird? Seems that --artifact apk still genarates aab.

**Comment by lberaldodev** [comment]
@eseidel i tried to reproduce the issue related by @shinayser and I get 2 "issues"

1- The release command is using the order of the entries inside build.gradle/signingConfigs. So, in the screenshot that @shinayser published, the CLI is using the production flavor, and here in my tests, the CLI used the internal 🦀. I don't know if it's a bug, so should I open an issue?
But the problem that @shinayser find was about the values of the configs, that was not present inside the build.gradle.

2- The --artifact command that @shinayser mentioned that is not working. In my tests, it only works if I specify the --flavor. (here I think that it's a bug or just a requirement that should be mentioned)

So, with this observations, i was able to generate my release with @shinayser .

**Comment by eseidel** [comment]
Slightly related to https://github.com/shorebirdtech/shorebird/issues/2113 (also a gradle signing issue).

**Comment by bryanoltman** [comment]
What does "fixed" look like for this issue?

**Comment by eseidel** [comment]
I'm not sure.  It appears the original issue was due to not finding keystores.

I'm not sure how one specifies which keystore to use in gradle.  It's possible this was simply a not-specifyin-flavor issue?

Without more information I think we can close and wait for another issue?
