### ISSUE TITLE
feat: Shorebird Preview should have a flag to build the ipa or the apk without installing it on the device

### ISSUE THREAD

**Issue by blk-raffy** [shorebirdtech/shorebird#1534]
**Description**

I've noticed `shorebird preview android` build and try to install the apk/ipa directly into the device connected in debug mode but I didn't found any command to build the application in apk or ipa format (only app bundle and ipa in release mode). It would be great if the preview command has an option like --build-only to build only the apk or the ipa without installing it on the device. This would be useful to send compiled applications to others without going through the stores and waste time by installing the application on every smartphone or sharing code to who doesn't know how to compile it.

**Requirements**

- [ ] add a flag to preview command to only build the apk or ipa file (no aab or ipa in release mode)

**Additional Context**

Nothing

**Comment by felangel** [comment]
Hi @blk-raffy
You can use `shorebird build appbundle` or `shorebird build ipa` to create builds that contain Shorebird which you can then distribute. Hope that helps 👍

**Comment by blk-raffy** [comment]
Thanks for the answer but I'm asking for something else. With `shorebird build appbundle` I receive an .aab file as output which it can't be installed directly on android. So I'm asking if it's possible to get directly the .apk instead of the .aab with some options in the cli. 

At the moment to extract the .apk from the .aab I have to do one of these two things:
- publish it on the store and initialize a testing group
- extract it with the official tool of google
Both options takes a while.

This feature would be great on those project which doesn't have already a store's page and the app needs to be shown to the customer before it's approval. I don't know if the use-case is clearly understand.

**Comment by felangel** [comment]
> Thanks for the answer but I'm asking for something else. With `shorebird build appbundle` I receive an .aab file as output which it can't be installed directly on android. So I'm asking if it's possible to get directly the .apk instead of the .aab with some options in the cli.
> 
> At the moment to extract the .apk from the .aab I have to do one of these two things:
> 
> * publish it on the store and initialize a testing group
> * extract it with the official tool of google
>   Both options takes a while.
> 
> This feature would be great on those project which doesn't have already a store's page and the app needs to be shown to the customer before it's approval. I don't know if the use-case is clearly understand.

You can build an apk with shorebird build as well via `shorebird build apk`.

**Comment by blk-raffy** [comment]
As I didn't say, I was just focusing on the release and the preview. Thanks, I appreciate it

**Comment by felangel** [comment]
> As I didn't say, I was just focusing on the release and the preview. Thanks, I appreciate it

You can do `shorebird release android --artifact apk` to generate an apk in addition to the aab during release.

**Comment by blk-raffy** [comment]
> You can do `shorebird release android --artifact apk` to generate an apk in addition to the aab during release.

Nice, I will definetely use that

**Comment by blk-raffy** [comment]
> You can do `shorebird release android --artifact apk` to generate an apk in addition to the aab during release.

Nice thanks, I will use that!
