### ISSUE TITLE
403 Forbidden error :

### ISSUE THREAD

**Issue by AmirAslami** [shorebirdtech/shorebird#1544]
Hello
Do not be tired

We in Iran need to use this wonderful technology of yours...

But as always and like some other things, your technology is also **banned** and we need **VPN** to use it so that we don't face the 403 problem and everything is done perfectly and perfectly...

Do you have a solution to bypass this problem?

Thanks...❤️

**Comment by eseidel** [comment]
Shorebird currently uses Google Cloud Storage for storing patch and release artifacts.  It appears Google Cloud Storage is currently unavailable in Iran:
https://support.google.com/cloudidentity/answer/2891389?hl=en
https://docs.shorebird.dev/faq#can-i-use-shorebird-in-my-country
`shorebird doctor` was also just updated to check for reachability of our servers.

I don't have any solution, no.

**Comment by mahanabd** [comment]
hello we have same problem.
is any way that we replace Google Cloud Storage with other storage?

**Comment by eseidel** [comment]
403 is definitely unexpected.  Are you still experiencing such @mahanabd?

**Comment by AmirJabbari** [comment]
We have still got 403
can we replace Google Cloud Storage with our storage or something like this
we need code push, Please give me a solution

**Comment by eseidel** [comment]
We do not currently have the ability to swap out storage, no:
https://github.com/shorebirdtech/shorebird/issues/485

We are considering moving to a CDN soon (instead of direct use of Google Cloud), which may change connectivity.
https://github.com/shorebirdtech/shorebird/issues/120

**Comment by AmirJabbari** [comment]
Hello again @eseidel 
i set a socks or http proxy in flutter app for access to shorebird update
but dont work

with this code i can access to shorebird endpoint

`  
SocksProxy.initProxy(proxy: 'SOCKS5 serverIp:port');
  await HttpClient()
      .getUrl(Uri.parse('https://api.shorebird.dev'))
      .then((value) {
        return value.close();
      })
      .then((value) {
        return value.transform(utf8.decoder);
      })
      .then((value) {
        return value.fold(
            '', (dynamic previous, element) => previous + element);
      })
      .then((value) => print('response $value'))
      .catchError((e) => print('eeeeee $e'));
`

now my question is can any way to request manualy with HttpClient to get update?

**Comment by mahanabd** [comment]
@eseidel 
We are honored to have you here and thank you for your time.

I read the links you gave
Is there a specific date for changing your CDNs?

**Comment by eseidel** [comment]
We do not currently have a timeline for moving our infrastructure onto a CDN.  I expect it's probably another month or two away would be my guess.

**Comment by AmirJabbari** [comment]
> Hello again @eseidel i set a socks or http proxy in flutter app for access to shorebird update but dont work
> 
> with this code i can access to shorebird endpoint
> 
> ` SocksProxy.initProxy(proxy: 'SOCKS5 serverIp:port'); await HttpClient() .getUrl(Uri.parse('https://api.shorebird.dev')) .then((value) { return value.close(); }) .then((value) { return value.transform(utf8.decoder); }) .then((value) { return value.fold( '', (dynamic previous, element) => previous + element); }) .then((value) => print('response $value')) .catchError((e) => print('eeeeee $e'));`
> 
> now my question is can any way to request manualy with HttpClient to get update?

@eseidel any idea?

**Comment by mahanabd** [comment]
Hello. I hope our questions will not take much of your time.

Like Amir Jabari, I tried the proxy setting solution.
The interesting result is that sites like YouTube and Twitter (which are filtered in our country) are displayed in a web view by connecting a proxy.

Even the links:
https://api.shorebird.dev
https://download.shorebird.dev/
https://storage.googleapis.com/
When I called with HTTP, it responds.

But the "Code Push SDK" still cannot download the patch.

To make sure that the "Code Push" starts working after the proxy is turned on ,I set auto_update to false and call update manually .

Does Shorebird use a special method (such as time) to find out whether we are Iranian or not?

@AmirJabbari 
@eseidel

**Comment by eseidel** [comment]
Shorebird makes no attempt to restrict access by country, however our cloud provider does, in compliance with US law:
https://docs.shorebird.dev/faq/#can-i-use-shorebird-in-my-country
https://support.google.com/cloudidentity/answer/2891389?hl=en
