### ISSUE TITLE
feat: Supports beta versions.

### ISSUE THREAD

**Issue by tbm98** [shorebirdtech/shorebird#1548]
**Description**

Currently, beta versions are released approximately every 1 to 2 weeks, while stable versions are usually released every 3 months.

I often have to decide between staying on the stable version so I can support code push or upgrading the app to the beta version so I can use new features and get many bug fixes.

It would be great if this library could support the beta version :D

**Requirements**

- [ ] Checklist of requirements to be fulfilled

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by eseidel** [comment]
We'd like to eventually support more versions, but it's probably many months before we'll support beta versions of Flutter.
