### ISSUE TITLE
feat: Upgrade the shorebird flutter version to 3.16.x 

### ISSUE THREAD

**Issue by Yuvaarth-Technocrats** [shorebirdtech/shorebird#1552]
**Description**
when the shorebird will support the 3.16.x version of the flutter.

**Comment by masterwok** [comment]
My company is very interested in using Shorebird within our Flutter application on version `3.16.2`. A general estimate for when Shorebird will support `3.16.+` would be greatly appriciated as it would allow me to communicate and plan the initial spike with my team.

**Comment by felangel** [comment]
We’ve been focusing on getting iOS mixed mode shipped for the last few weeks and we’re very close. We should be able to wrap that up and upgrade to Flutter 3.16.x sometime next week 🤞

**Comment by eseidel** [comment]
Yes, this has been a very unusual delay for us.  Typically we upgrade within a few hours of release, this time we intentionally have delayed upgrading while we finish work on production iOS builds.  As Felix notes, I expect we'll upgrade next week. Sorry for the delay.

See https://github.com/shorebirdtech/shorebird/issues/1501
