### ISSUE TITLE
feat: about signing key

### ISSUE THREAD

**Issue by lvmaoya** [shorebirdtech/shorebird#1555]
**Description**
The signing key used by your Android App Bundle is incorrect. Be sure to sign your App Bundle with the correct signing key and try again. 
Can i use my own signing key?

**Comment by eseidel** [comment]
Shorebird does not provide any signing keys.  That message is coming from Android's build system which `shorebird` invoked by calling `flutter build`.   I suspect you may need to edit android/build.gradle or one of the properties files to set your signing keys, or use whatever mechanism you normally would have used with `flutter`.  You can pass any argument directly down to `flutter` by adding a `--` after the shorebird args.  See the "info" section in https://docs.shorebird.dev/code_push/release

**Comment by eseidel** [comment]
You can also try running `shorebird` with`-v` to see all the commands it's exectuting.

Let us know if that doesn't help!
