### ISSUE TITLE
feat: Distinguish patch/release with environnement variables

### ISSUE THREAD

**Issue by TheCarpetMerchant** [shorebirdtech/shorebird#1562]
**Description**

I'd like different scripts to be able to distinguish between when they're running for a release or for a patch.
This is because when building an app bundle, I'm using the artifact autoincrement number, which means running `shorebird patch android` yields a new version id.
If Shorebird were to set an environment variable readable by the build.gradle describing what it's building, I'd be able to ignore the autoinc.

**Comment by bryanoltman** [comment]
I believe we discussed this on Discord and decided that this wasn't the correct approach and that there wasn't a clear path to consuming these environment variables in gradle. Feel free to reopen if I'm misremembering.
