### ISSUE TITLE
fix: SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8)

### ISSUE THREAD

**Issue by rcarvs** [shorebirdtech/shorebird#1563]
**Description**

When trying to login it's returning:
SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8)

**Steps To Reproduce**

Installed on macos 14.1.1  without previous flutter installed (I use fvm). Installed successful, shorebird command worked but when running shorebird login it's returning:
SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8)

the doctor command tells that everything is great:
```
Shorebird 0.18.5 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.9 • revision a3d5f7c614aa1cc4d6cb1506e74fd1c81678e68e
Engine • revision 0757a9001dc3dcfce6f09fdd443904827274d22e

✓ Shorebird is up-to-date (0.6s)
✓ Flutter install is correct (1.0s)
✓ Has access to storage.googleapis.com (0.3s)

No issues detected!
```

**Expected Behavior**

Generate the login URL

**Screenshots**
![Screenshot 2023-12-12 at 3 27 27 PM](https://github.com/shorebirdtech/shorebird/assets/10063882/c2958677-4f50-4297-846c-74caf0d5bac9)

**Additional Context**

I tried to finalize docker that was serving web app on port 80 on localhost, but the error continues.
I tried to run shorebird as root but the error continues.

Any info or test I'm available. Thank you!

**Comment by bryanoltman** [comment]
What do you see if you run `cat /etc/hosts`?

**Comment by rcarvs** [comment]
@bryanoltman There is
```
  ╱  ~/Development  cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

#work development
127.0.0.1      rcarvs.lvh.me
127.0.0.1      renanfresh.lvh.me
... (a lot of other sites like that)
127.0.0.1      site.lvh.me
```

**Comment by rcarvs** [comment]
@bryanoltman I made a test cleaning everything on my /etc/hosts and it doesn't fix the issue, keep the same output 😔
Is there something else you suggest I check? TY

**Comment by bryanoltman** [comment]
You should have `127.0.0.1	localhost` in your `/etc/hosts` file – this is almost certainly the cause of the error you're seeing.

**Comment by rcarvs** [comment]
It worked, thank you!

**Comment by rcarvs** [comment]
Not sure, but there is some way of switching from localhost to 127.0.0.1 to prevent others from having this issue in the future?

**Comment by bryanoltman** [comment]
I don't believe so – the use of localhost comes from `package:googleapis_auth`, and it's pretty standard to assume `localhost` exists and points to 127.0.0.1.

**Comment by zhanglijie5997** [comment]
I have a sample problem.

 `Waiting for your authorization...
ClientException with SocketException: Operation timed out (OS Error: Operation timed out, errno = 60), address = oauth2.googleapis.com, port = 53861, uri=https://oauth2.googleapis.com/token`

> shorebird --version
Shorebird 0.22.1 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.16.7 • revision 0a7a66cbc9850f7bd7fe9c36a2f9b9084fa73a13
Engine • revision a070b8d394991f4f4457fedf2246038120847841

> /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost

**Comment by eseidel** [comment]
> I have a sample problem.
> 
> `Waiting for your authorization... ClientException with SocketException: Operation timed out (OS Error: Operation timed out, errno = 60), address = oauth2.googleapis.com, port = 53861, uri=https://oauth2.googleapis.com/token`
> 
> > shorebird --version
> > Shorebird 0.22.1 • [git@github.com](mailto:git@github.com):shorebirdtech/shorebird.git
> > Flutter 3.16.7 • revision 0a7a66cbc9850f7bd7fe9c36a2f9b9084fa73a13
> > Engine • revision a070b8d394991f4f4457fedf2246038120847841
> 
> > /etc/hosts
> 
> # Host Database
> # localhost is used to configure the loopback interface
> # when the system is booting. Do not change this entry.
> 127.0.0.1 localhost 255.255.255.255 broadcasthost ::1 localhost

This looks like your system cannot reach Google oauth servers. `Operation timed out (OS Error: Operation timed out, errno = 60), address = oauth2.googleapis.com, port = 53861, uri=https://oauth2.googleapis.com/token`.
https://docs.shorebird.dev/faq#can-i-use-shorebird-in-my-country might help.
