### ISSUE TITLE
docs: Add instructions for using XCode with iOS App using Shorebird

### ISSUE THREAD

**Issue by fei1990** [shorebirdtech/shorebird#1571]
when i user `Dart_LoadELF` function load a aot file, i can launch my app from xcode, but can't launch without xcode. when i click my app icon, my app crashed directly. How can i do?

<img width="1239" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/20367597/c0601e41-d9f0-431c-bf85-5bef400b50f3">

**Comment by eseidel** [comment]
This is probably a scheme issue.  In order to use XCode with Shorebird you have to set your XCode Scheme to "Release".

**Comment by eseidel** [comment]
We should add some instructions about this.

**Comment by eseidel** [comment]
Can you help us understand what you're trying to do?  Are you trying to work on the Shorebird Engine?

Our Dart VM is not currently open source, so it's not possible to build Shorebird for iOS from open source.

Please feel free to re-open if you had further questions.  Thanks.
