### ISSUE TITLE
`shorebird init` hangs on Windows when using the default suggested app name

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1574]
**Description**

When attempting to create a new app on my windows machine, I was unable to get past the "How should we refer to this app?" prompt when trying to use the default suggestion.

I'm having trouble with repro steps. I've tried:

1. Creating a new dart app and using `mason_logger` to prompt with a default. This works as expected, so I'm not sure the issue lies with `mason_logger`.
2. Prompting as the first step of `InitCommand`'s `run` method. This exhibits the same hang behavior as below, but I have no idea what is different between the two.

**Steps To Reproduce**

On Windows 11, in powershell:

1. Create a new flutter app
3. Run `shorebird init`
4. Press "enter" when prompted for app name to use the name from the pubspec file.
5. Note that no further progress is made

**Expected Behavior**

The init process proceeds, using the default name.

**Comment by bryanoltman** [comment]
After digging more, I believe this to be a `mason_logger` issue https://github.com/felangel/mason/issues/1189

**Comment by codesculpture** [comment]
This has been fixed in windows terminal v1.18.2 🎉 can be closed.
