### ISSUE TITLE
Log detected Xcode version on iOS release/patch with verbose logging

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1579]
This would give us more information to help customers having issues with iOS and Shorebird.

**Comment by eseidel** [comment]
I think flutter also does this via `flutter doctor`:

<img width="528" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/478541/9060eeee-29fa-49ca-b0c1-dff6d053af1c">

**Comment by eseidel** [comment]
I think you've solved this with your metadata work? @bryanoltman

**Comment by bryanoltman** [comment]
Yep, we've definitely solved the problem outlined in this issue with the metadata work. Closing.
