### ISSUE TITLE
`preview` command termination can corrupt cache

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1584]
**Description**

Terminating the `shorebird preview` command during the "using production track" step can cause the cached aab file to become corrupted and future previews to fail. 

I can consistently reproduce this on Windows.

**Steps To Reproduce**

1. Create an Android release
2. Run `shorebird preview`
3. After the artifact has downloaded and the preview command is on the "using production track" step, force quit the preview command with ctrl+C
4. Note that the size on disk of the aab has changed and it is no longer recognized as a valid zip file.

**Comment by eseidel** [comment]
Sounds like we will want to use temp files and rename them on download
completion.

**Comment by bryanoltman** [comment]
I think that's the correct solution (copying the file before trying to edit it), although for clarity, the issue isn't that the download is interrupted, but rather that we're being interrupted while editing a fully-downloaded file.
