### ISSUE TITLE
feat: Support Flutter 3.16.4

### ISSUE THREAD

**Issue by tjarvstrand** [shorebirdtech/shorebird#1586]
**Description**
Shorebird seems to be using a pre-release version of Flutter 3.16.4

**Steps To Reproduce**
1. In pubspec.yaml, set the Flutter minimum version to 3.16.4
2. Build a release using shorebird

**Expected Behavior**

The build completes successfully.

**Output**

```
✗ Failed to build: Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
The current Flutter SDK version is 3.16.4-0.0.pre.54.

Because myapp requires Flutter SDK version >=3.16.4, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.16.4.
```

The weird thing is, when I run `shorebird flutter versions list`, it says I'm using 3.16.3, not 3.16.4 🤔

**Comment by eseidel** [comment]
Apologies, we haven't yet updated to 3.16.4 yet.  We've been 100% focused on trying to get iOS out of alpha.  Should be easy for us to update, but probably not for a few days yet.

I recommend downgrading to 3.16.3 for now with `flutter downgrade`.

**Comment by eseidel** [comment]
Felix is making a release for 3.16.4 right now, should be live in a couple hours.  Thanks for your patience!
