### ISSUE TITLE
fix: Shorebird Engine not available, using no-op implementation.

### ISSUE THREAD

**Issue by TranHanHieu** [shorebirdtech/shorebird#1588]
**Description**

**Steps To Reproduce**

1. In Terminal Project run ```shorebird init```
2. Step 1 success, run ```shorebird release ios-alpha```
3. Install ```shorebird_code_push``` && add `ShorebirdCodePush` to lib/main.dart, call currentPatchNumber()
3. Run ```shorebird preview```, select release step 2
4. In log: 
```
2023-12-20 14:08:54.919121+0700 Runner[7432:1111418] flutter: [ShorebirdCodePush]: Shorebird Engine not available, using no-op implementation.
2023-12-20 14:08:54.923423+0700 Runner[7432:1111361] [quic] sec_framer_open_aesgcm failed to open for AESGCM: -4308
2023-12-20 14:08:54.923455+0700 Runner[7432:1111361] [quic] sec_framer_open_aesgcm failed to open for AESGCM: -4308
2023-12-20 14:08:54.925133+0700 Runner[7432:1111418] flutter: 157.0
2023-12-20 14:08:54.928244+0700 Runner[7432:1111418] flutter: current patch number is null
```
**Expected Behavior**
- Got current patch number, pull new patch

**Additional Context**

Shorebird 0.19.0 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.10.0 • revision 6b9b5ff45af7a1ef864038dd7d0c32b620b357c6
Engine • revision b7ddfb07396cd786a85709cdfdacfd737559bdb2

✓ Shorebird is up-to-date (1.5s)
✓ Flutter install is correct (2.2s)
✓ AndroidManifest.xml files contain INTERNET permission (25ms)
✓ Has access to storage.googleapis.com (0.4s)

No issues detected!

**Comment by eseidel** [comment]
package:shorebird_code_push support was added in Flutter 3.10.6:
https://docs.shorebird.dev/flutter-version

We could probably provide a better message, but for now the only solution we have to offer is to upgrade the project to Flutter 3.10.6 or higher.

**Comment by TranHanHieu** [comment]
@eseidel Thank you for response, I tried the case without shorebird_code_push integration but still couldn't update the new patch, not set auto_update in shorebird.yaml

**Comment by eseidel** [comment]
In general we recommend leaving auto-update enabled:
https://docs.shorebird.dev/update-strategies

This might help?
https://docs.shorebird.dev/troubleshooting

**Comment by bryanoltman** [comment]
I would be very surprised if much (if any) iOS worked with Flutter 3.10. If you look at https://docs.shorebird.dev/flutter-version, you can see the first Flutter version that officially includes iOS support is 3.10.6.

**Comment by TranHanHieu** [comment]
@bryanoltman  thank you, i upgrade flutter, it’s worked. Also, is there any way to download the patch but don’t must restart the app?

**Comment by bryanoltman** [comment]
There is no way to apply a patch without restarting your app.

**Comment by ev-turenko** [comment]
@bryanoltman you can restart the app manually. Just check if there are available patches and if there are – download them and then restart the app programmatically on OS level. **Nota bene:** do that upon app start – this way you won't screw up the user experience.
