### ISSUE TITLE
Smoke Test 0.20.0

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1591]
Our first release with mixed mode enabled by default!

- [x] e2e tests
https://github.com/shorebirdtech/shorebird/actions/runs/7279428703
- [ ] framework tests
- [ ] engine tests
https://github.com/shorebirdtech/_build_engine/actions/runs/7279430672
- [x] flutter create + shorebird init works

- [x] iOS release
- [x] iOS patch
- [x] iOS preview

- [ ] `shorebird doctor`
    - [ ] Win
    - [ ] Mac

- [ ] Android release
    - [ ] Win
    - [ ] Mac
- [ ] Android patch
    - [ ] Win
    - [ ] Mac
- [ ] Android preview
    - [ ] Win
    - [ ] Mac

- [x] iOS Add to App release
- [x] iOS Add to App patch

- [ ] Android Add to App release
    - [ ] Win
    - [ ] Mac
- [ ] Android Add to App patch
    - [ ] Win
    - [ ] Mac

- [ ] iOS Flavors release
- [ ] iOS Flavors patch
- [ ] iOS Flavors preview

- [ ] Android Flavors release
    - [ ] Win
    - [ ] Mac
- [ ] Android Flavors patch
    - [ ] Win
    - [ ] Mac
- [ ] Android Flavors preview
    - [ ] Win
    - [ ] Mac

**Comment by bryanoltman** [comment]
Closing because we have released
