### ISSUE TITLE
fix: shorebird doesn't work on mac x64 machines

### ISSUE THREAD

**Issue by johnsulf** [shorebirdtech/shorebird#1595]
**Description**

Just got started with Shorebird today. `shorebird release iOS-alpha` worked fine, but `shorebird patch iOS-alpha` gave an error: Failed to link AOT files: ProcessException: Bad CPU type in executable.

See screenshots for the entire response and result from shorebird doctor.

**Screenshots**

![repsonse](https://github.com/shorebirdtech/shorebird/assets/96027411/1bf06816-3450-448b-b441-9264c22b37cf)
![doctor](https://github.com/shorebirdtech/shorebird/assets/96027411/a5f746b6-410d-4534-9656-1537afa8c1b3)

**Comment by bryanoltman** [comment]
This is caused by our release process compiling `aot-tools` as an arm64 binary. We should probably either

1. Just provide `aot-tools` as source and `dart run` the package
2. Compile `aot-tools` to a kernel and distribute that

**Comment by bryanoltman** [comment]
Another interesting note: despite the name, `analyze_snapshot_arm64` seems to run on an x64 machine without issue.
