### ISSUE TITLE
fix:Unable to extract product flavors | ProcessException: xcode-select: error

### ISSUE THREAD

**Issue by sazzadh88** [shorebirdtech/shorebird#1597]
**Description**

Unable to extract product flavors.
ProcessException: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Steps To Reproduce**

1. run `shorebird init`

I don't want it to be built for the iOS platform. Is there any way to run it only for the Android platform?

Note: I use macOS 14.0

**Comment by eseidel** [comment]
I've had xcrun get confused about whether I had the full xcode installed before, I believe I got past his with `xcode-select --reset`?

https://github.com/nodejs/node-gyp/issues/569 is one discussion of such.

**Comment by eseidel** [comment]
We might need to add this as a check to `shorebird doctor` to help users make sure their xcrun command line is pointing to a full XCode.  Maybe `flutter doctor` already does this?  This feels like something the Flutter layer should handle.

**Comment by sazzadh88** [comment]
> We might need to add this as a check to `shorebird doctor` to help users make sure their xcrun command line is pointing to a full XCode. Maybe `flutter doctor` already does this? This feels like something the Flutter layer should handle.

Is there any temporary way to run without `xcode`?

**Comment by felangel** [comment]
> > We might need to add this as a check to `shorebird doctor` to help users make sure their xcrun command line is pointing to a full XCode. Maybe `flutter doctor` already does this? This feels like something the Flutter layer should handle.
> 
> Is there any temporary way to run without `xcode`?

You can delete your iOS directory.

**Comment by sazzadh88** [comment]
> > > We might need to add this as a check to `shorebird doctor` to help users make sure their xcrun command line is pointing to a full XCode. Maybe `flutter doctor` already does this? This feels like something the Flutter layer should handle.
> > 
> > 
> > Is there any temporary way to run without `xcode`?
> 
> You can delete your iOS directory.

I completed that command in windows system and got `shorebird.yaml` file. Then I test other commands like `shorebird release android`, `shorebird patch android --staging` etc. It is working fine.

**Comment by eseidel** [comment]
We could improve `shorebird doctor` to validate xcode is set up better, but I think we can just close this for now.
