### ISSUE TITLE
feat: ability to pause serving patches to specific releases

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1599]
"I want previous releases to stop getting patches, so as to not eat up the quota when a store update is out anyway."  Is the customer ask.

**Comment by bryanoltman** [comment]
Do you think this is another way of asking for the ability to delete patches?

**Comment by eseidel** [comment]
Maybe?  I think in general we should discourage "deleting" since that's an irreversible operation.

**Comment by bryanoltman** [comment]
Maybe instead of deleting we move them to a non-active channel so users can "retire" a patch?

**Comment by eseidel** [comment]
Not sure 🤷.  Maybe patches are initially "paused" and then "go live" and then can be "paused" again?

**Comment by eseidel** [comment]
I think this specific prompt is also likely to be an uncommon one.  Our large customers currently purchase 10s of millions of patch deliveries per month and seem unlikely to be concerned about "pausing" a specific single release to a single version.  I suspect we're more likely to need "omg that patch is bad (in ways Shorebird can't detect), please stop sending it to users" as a motivation.

**Comment by bryanoltman** [comment]
Fair. We have a concept of staging patches that uses channels as a mechanism (https://docs.shorebird.dev/guides/staging-patches) that I think would be a good fit to solve this problem. We could probably even use the same "staging" channel, although we would probably want to change "staged" to "ready" on the console to avoid confusion.
