### ISSUE TITLE
run shorebird release android error，please help

### ISSUE THREAD

**Issue by hanxiaofeng** [shorebirdtech/shorebird#1600]
**Screenshots**

<img width="238" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/10582931/13dd96b7-c94e-45cf-bf7d-c2f50d8ddf4a">

<img width="1347" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/10582931/8aac1c82-f4d4-463d-8140-017c159aa8b2">

**Comment by techadot** [comment]
> **Screenshots**
> 
> <img alt="image" width="238" src="https://private-user-images.githubusercontent.com/10582931/292941009-13dd96b7-c94e-45cf-bf7d-c2f50d8ddf4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMjg2MTAsIm5iZiI6MTcwNDEyODMxMCwicGF0aCI6Ii8xMDU4MjkzMS8yOTI5NDEwMDktMTNkZDk2YjctYzk0ZS00NWNmLWJmN2QtYzJmNTBkOGRkZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE2NTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOTgwNGVjMWFiYWQ1MjRkYmU5M2UzYmRkODZjMDQyMTQ5NzViMWFiNWIyYTI5ZTNkYjI2ZGEwYTc5NGEzMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zs5A821EG1TNqc-v_-wYZ9BPLI6XhW1Njx5KJ7ncSCA"> <img alt="image" width="1347" src="https://private-user-images.githubusercontent.com/10582931/292940928-8aac1c82-f4d4-463d-8140-017c159aa8b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMjg2MTAsIm5iZiI6MTcwNDEyODMxMCwicGF0aCI6Ii8xMDU4MjkzMS8yOTI5NDA5MjgtOGFhYzFjODItZjRkNC00NjNkLTgxNDAtMDE3YzE1OWFhOGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE2NTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmOGI2Mjg3ZTY0ZTUwOTY5NTc1YTJmNmFlMDQ3NDIwYzUxM2I1ZTgxNDViMWE2ZTdmYzYyZDEwMTZjM2MyZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lQRKzflCwe06ucSFfIXgnFKYHRNBfBoZJkMhZi1uMtk">

nǐ hǎo hanxiaofeng, After Going through the Screenshot, i realize that First of all, your Flutter install is in correct, once you have fixed that, Kindly Rerun Shorebird Doctor, once you have everything green tick ✅, then you can run shorebird release android

**Comment by bryanoltman** [comment]
I haven't seen this error before, but some ideas of what might be going wrong and some things to try:

1. Based on the `FLUTTER_STORAGE_BASE_URL` warning, I'm guessing you're in China. Other users in China have reported issues accessing some of our artifacts that are hosted on Google Cloud.
2. I'm not sure what those gradle commands are (they seem unrelated to Shorebird and not commands that are included by default in a Flutter app), but you can run `shorebird release android -v` to see exactly which command is failing, which should help to diagnose the underlying issue.
3. If you run `flutter build appbundle --release`, do you see this error?

**Comment by bryanoltman** [comment]
Closing due to lack of response. If this is still an issue, please reopen and reply to https://github.com/shorebirdtech/shorebird/issues/1600#issuecomment-1874306909
