### ISSUE TITLE
 curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 75248 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by AayushPaigwar** [shorebirdtech/shorebird#1602]
` curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 75248 ms: Couldn't connect to server`
 
  - Getting the above error when I try to install ShoreBird in my Mac M1.
  - Code: `curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
`

- If anyone knows how to fix, please reply to this issue.

**Comment by bryanoltman** [comment]
We've seen an issue with certain ISPs restricting access to `raw.githubusercontent.com`. Can you access https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh  in your browser?

**Comment by AayushPaigwar** [comment]
Yepp!
I can access this in my browser.
Here's the Screenshot.

<img width="720" alt="Screenshot 2024-01-02 at 10 20 44 PM" src="https://github.com/shorebirdtech/shorebird/assets/90213184/fd25a358-4197-42fc-959f-0607fff16dd7">

**Comment by bryanoltman** [comment]
Interesting – I'm not sure what the issue is then. If you're able to access that script in your browser, you can download and run it, which is what the `curl` command from our installation docs does. Let us know if you run into any other issues!
