### ISSUE TITLE
Allow users to share Stripe subscription

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1606]
**Description**

This is basically asking for the concept of organizations. We've seen this need with a couple customers so far. One user (the CEO or finance person) is paying but wants their developer(s) to be able to create apps, releases, etc. 

**Requirements**

The user who signs up for shorebird can add other shorebird users to their "organization" (we can call it something different if we want). The other users are treated as though they have an active subscription and are allowed to create apps, releases, etc. and have the same permissions the account owner has.

**Thoughts/Questions**

- We should probably cap org size.
- Should there be more sophisticated permissions than "all or nothing"? i.e., can I let members of my team create but not delete apps?
- How does this interact with our existing collaborators concept?

**Comment by eseidel** [comment]
Dupe with https://github.com/shorebirdtech/shorebird/issues/739?

**Comment by bryanoltman** [comment]
Yep. Closing as a duplicate of https://github.com/shorebirdtech/shorebird/issues/739
