### ISSUE TITLE
Run shorebird release ios-alpha error on mac x64

### ISSUE THREAD

**Issue by nhorsopheak** [shorebirdtech/shorebird#1610]
<img width="1191" alt="Screenshot 2024-01-03 at 11 40 28 in the morning" src="https://github.com/shorebirdtech/shorebird/assets/52164658/613f3d03-90b8-4b91-9642-081b4e887e8b">

**Comment by eseidel** [comment]
Thanks!  We can look in the morning.

**Comment by bryanoltman** [comment]
Update to provide context from the PR that fixed this:

This issue was happening on all macs, and was caused by an update to one of our dependencies (`package:archive`) that was released yesterday. We have fixed this in release 0.21.1.
