### ISSUE TITLE
feat: publish profile builds

### ISSUE THREAD

**Issue by Yongle-Fu** [shorebirdtech/shorebird#1620]
Hello,

I'm encountering an issue while attempting to compile my Flutter project in profile mode using the command flutter build apk --profile. It seems that I'm facing an error related to resolving the package io.flutter:flutter_embedding_profile:1.0.0-35809a641ed60f9595fcb6c6f939a8768eaca976.

The specific error message I'm receiving is:

`Could not resolve io.flutter:flutter_embedding_profile:1.0.0-35809a641ed60f9595fcb6c6f939a8768eaca976`

I would like to inquire about the current support for profile mode compilation. Is there any additional configuration or dependency that needs to be considered for profile mode compilation?

Any insights or guidance on resolving this issue would be greatly appreciated.

Thank you!

**Comment by eseidel** [comment]
This should be very easy for us to do, we just need to change our bots to also upload profile builds.

**Comment by eseidel** [comment]
Update:  We don't currently have plans to add Profile or Debug modes to Shorebird any time soon.  (We do eventually plan to not restrict Shorebird to release-mode only, but we just have other work higher on the list.) Let us know if this is blocking you.  Thanks!

**Comment by eseidel** [comment]
This would be needed as part of https://github.com/shorebirdtech/shorebird/issues/2105.  Tracking this there.
