### ISSUE TITLE
fix: Invoking flutter.bat instead of shorebird.bat while installation of shorebird

### ISSUE THREAD

**Issue by codesculpture** [shorebirdtech/shorebird#1625]
While i installing shorebird, 
This error happens

```bash 
iwr -UseBasicParsing 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex
Installing Shorebird to C:\Users\Aravind\.shorebird...
Cloning into 'C:\Users\Aravind\.shorebird'...
remote: Enumerating objects: 14062, done.
remote: Counting objects: 100% (1992/1992), done.
remote: Compressing objects: 100% (786/786), done.
remote: Total 14062 (delta 1373), reused 1678 (delta 1146), pack-reused 12070
Receiving objects: 100% (14062/14062), 101.29 MiB | 1.23 MiB/s, done.
Resolving deltas: 100% (9549/9549), done.
Rebuilding shorebird...
Updating Flutter...
Invoke-Expression: The term 'C:\Users\Aravind\.shorebird\bin\cache\flutter\4e8a7c746ae6f10951f3e676f10b82b21d7300a5\bin\flutter.bat' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

And i inspected that folder seems there's been shorebird.bat but the script is somehow trying to execute flutter.bat

**Comment by codesculpture** [comment]
Don't take this as high priority, i will look on this.  Since i before this, i tried once try installing shorebird but failed with git packet issue. So thinking that introduce this or something else is. Now tricked shorebird.ps1 to actually install shorebird with no problem

**Comment by bryanoltman** [comment]
The flutter `.bat` file you're seeing there is part of shorebird's flutter checkout, so the fact that it is being executed is not surprising. Can you check whether that file (`C:\Users\Aravind\.shorebird\bin\cache\flutter\4e8a7c746ae6f10951f3e676f10b82b21d7300a5\bin\flutter.bat`) actually exists?

**Comment by codesculpture** [comment]
I understand this issue is from while executing `shorebird.ps1` through `install.sh`, 

```ps1
    # Set FLUTTER_STORAGE_BASE_URL=https://download.shorebird.dev and execute
    # a `flutter` command to trigger a download of Dart, etc.
    $env:FLUTTER_STORAGE_BASE_URL = 'https://download.shorebird.dev';
    & $flutter --version
```

I realize this not supposed to execute, since this part covered in `if-else` which only executes when there is flutter folder already there. But its weird why it assumed there is a flutter and try to executed.


One Reason Could be that i previously tried to install shorebird but ended failing due to git packet issue. Am not sure that git packet happened during cloning the `shorebird` repo or `flutter` repo. If it failed during `flutter` repo, then its possible to happen

**Comment by bryanoltman** [comment]
Ah, we don't gracefully handle partial/failed installations it seems. If you delete the shorebird installation and try again, it should successfully install.

**Comment by codesculpture** [comment]
Yes i just tricked (modified) the script to make everything works
So seems this is not a valid issue, sorry for that. And thanks @bryanoltman

**Comment by CodeRebirth** [comment]
Please tell the modification, I am facing the same issue.

**Comment by bryanoltman** [comment]
> Please tell the modification, I am facing the same issue.

This issue has been closed for a while. I believe the solution of deleting your existing shorebird installation and reinstalling should work. Let us know if it does not.

**Comment by CodeRebirth** [comment]
I have tried that but it showing an issue of unexpected EOF while sideband packet, I have tried increasing the git buffer also but stills its not working.

**Comment by bryanoltman** [comment]
Are you able to clone this repository?

**Comment by bryanoltman** [comment]
That's really all the script is doing—cloning this repository, setting it up to track the `stable` branch, and adding the checkout path to your PATH environment variable.

**Comment by codesculpture** [comment]
Sorry am bit a late to join here, and again sorry that i forget what i actually did to solve this issue, i will look on my computer whether i had something that might helpful.
