### ISSUE TITLE
Error hash mismatch

### ISSUE THREAD

**Issue by ClauberBM** [shorebirdtech/shorebird#1630]
hello

I'm testing shorebird, I followed the steps in the tutorial for hybrid application (https://docs.shorebird.dev/guides/hybrid-app/android) but I'm getting an error

![image](https://github.com/shorebirdtech/shorebird/assets/139567963/597bbb06-e8a5-4a47-a363-391e84772349)

**Comment by bryanoltman** [comment]
We'll need some more information to help debug. Can you share the full sequence of commands you ran/steps you took (release, app launch, patch, app restart, etc.) that led you to this error?

**Comment by ClauberBM** [comment]
1- get https://github.com/shorebirdtech/samples/tree/main/add_to_app
2 - cd my_flutter_module
3 - shorebird init
4 - shorebird release aar --release-version 1.0+3 (I modify version code to 3) 
5-  I updated gradle to accept flutter as described in the tutorial
6 - Modify my flutter_module 
7- Lauch app 
8 - shorebird patch aar --release-version 1.0+3
9 - Restart App
10 - That print message appears

**Comment by bryanoltman** [comment]
Hmm, that looks right. How did you restart the app? If you pressed the "play" button in android studio after running the patch command, it's possible the patch build was attempting to download the update, which would explain this error.

**Comment by ClauberBM** [comment]
I simply ended the process, I restarted the device, but always the same hash error message. If I press Play in Android Studio it loads the patch with the modification, but I need to test it in a remote scenario

**Comment by bryanoltman** [comment]
For clarity, these are the steps that will work:

1. run shorebird release aar
2. Press "play" in android studio to install a version of the app containing the aar you just built
3. run shorebird patch aar
4. kill the app on the device and relaunch _without using Android Studio_
5. You should see a message saying that a patch has been downloaded and installed
6. kill the app on the device and relaunch _without using Android Studio_
7. You should see the patch installed

The error message you're seeing indicates that the aar running in your app is not the one that was created with shorebird release aar.

**Comment by ClauberBM** [comment]
I did the procedure but I still have the same problem. This time I noticed the following message in the "shorebird init" command:

✗ Flutter install is correct (2.4s)
  [!] The version of Flutter that Shorebird includes and the Flutter on your path are different.
        Shorebird Flutter: 3.16.7
        System Flutter:    3.4.0

Could this flutter version difference be causing the problem?

**Comment by bryanoltman** [comment]
I'm not sure if that's the cause of this particular problem, but that's definitely something worth addressing. Your system Flutter should match (or be very close to) shorebird's version of flutter.

**Comment by ClauberBM** [comment]
![image](https://github.com/shorebirdtech/shorebird/assets/139567963/de12da43-99fb-4dbb-9ee9-a01c42fe41b3)
Here's how my settings are

**Comment by bryanoltman** [comment]
As mentioned on Discord, the url to your flutter module is incorrect. It needs to be relative (yours is absolute) and it needs to point to your module's release directory (yours is pointing to something in your `build` directory)

**Comment by ClauberBM** [comment]
![image](https://github.com/shorebirdtech/shorebird/assets/139567963/50b805cb-3551-4e5b-bb23-00e3204b5af2)


![image](https://github.com/shorebirdtech/shorebird/assets/139567963/4deff446-0f82-4c7a-ae42-aecd373bd303)

Same error with change

**Comment by bryanoltman** [comment]
The path needs to be **relative**. Paths starting with `C:\` are absolute

**Comment by ClauberBM** [comment]
The version that shorebird is downloading is correct, I compared libapp.so that was generated locally on my machine with the version that was downloaded. But when comparing with the hash that comes from the shorebird response it is incorrect

![image](https://github.com/shorebirdtech/shorebird/assets/139567963/eae02d91-e766-42f9-9771-9d802fbe0888)

PS:I noticed that when launching the patch, I put it in verbose mode to check if there was something wrong, try downloading aot-tools-windowsx64, I don't know if this could be impacting the wrong api hash for vim, follow the logs

Aborting.
PS C:\Users\csouza\Downloads\samples\add_to_app\my_flutter_module> shorebird patch aar --release-version 1.0+2 -v
[HTTP] GET https://storage.googleapis.com/download.shorebird.dev/shorebird/fa52b1848d838ae51c129ced7cb3e5a28dd43e63/aot-tools.dill
[cache] optional artifact: "aot-tools.dill" was not found, skipping...
[HTTP] GET https://storage.googleapis.com/download.shorebird.dev/shorebird/fa52b1848d838ae51c129ced7cb3e5a28dd43e63/aot-tools-windows-x64
[cache] optional artifact: "aot-tools" was not found, skipping...
[HTTP] POST https://oauth2.googleapis.com/token
⠸ Fetching apps... (1.0s)[HTTP] GET https://api.shorebird.dev/api/v1/apps
✓ Fetching apps (2.1s)
[HTTP] GET https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/releases
✓ Fetching releases (0.2s)
[HTTP] GET https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/releases/27973/artifacts?arch=aarch64&platform=android
⠹ Fetching release artifacts... (0.2s)[HTTP] GET https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/releases/27973/artifacts?arch=arm&platform=android
⠼ Fetching release artifacts... (0.3s)[HTTP] GET https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/releases/27973/artifacts?arch=x86_64&platform=android
✓ Fetching release artifacts (0.6s)
[HTTP] GET https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/releases/27973/artifacts?arch=aar&platform=android
✓ Fetching aar artifact (0.2s)
[HTTP] GET https://storage.googleapis.com/shorebird_release_artifacts/c3722880-f327-4652-b2d8-2765395f0a30%2Fandroid%2Faarch64%2F27973%2Fdlc.vmcode?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=patch-artifacts-storage-bucket%40code-push-prod.iam.gserviceaccount.com%2F20240122%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240122T160201Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=76d2c5e0e963bded6310d9f83b848eb6c8ed463347b741d3a46988d00546490765f3beb99e13ee0f6073f722aebf20e757b733ed45334c581deb2d9106dc659bf14147bcc9cb7e75a7c688b643671f645bf323aca631437d63e620db163600ba9923100b431b53293ef298af256158c9c05b43e9b38bda22725b30fe23f11f038f886cb4e4c4f2edc81188a8729d307859056897867e9c5947bd0a2861500b25aa0f20aa33f87be524b1ba48069e2d502463c620d352e08da9fc6467e1f07ebd03e942164e66789e8e935590a2aac67e833996236f23d32ba7d9bdba894e1f55fef07c2e623ef17823cf027ffea5d8c73d4e27855976102838a2daf417029c05
⠧ Downloading release artifacts... (1.4s)[HTTP] GET https://storage.googleapis.com/shorebird_release_artifacts/c3722880-f327-4652-b2d8-2765395f0a30%2Fandroid%2Farm%2F27973%2Fdlc.vmcode?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=patch-artifacts-storage-bucket%40code-push-prod.iam.gserviceaccount.com%2F20240122%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240122T160201Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=790d92fe62d63222047b4c30bc5e7706257254486c7875f1fca9c4126f9b9101f9449d9aaf8d2a14ad478088be5f0a66dbdc0da34f0210b4ede15c6e871f987688e00d3c8cb4b818a2f5d003b7b6d430b35115892a6ed0d9ff8dd685f351706abe577ad9c0be07a38436632ebce79f5bfb807f769e469dbd65662d5c4fe55f8b905f91908a26499883f2bfaaa5c0d1eb8a07b86c0aa4447f3ced774524f8f1c96dfe690f7a6e9f0968bca4ab12b5a12010941096d7b31f03fd5318e141ffb3c20c8b2d23a2f3e3bb50b12c6808177760fc9b3b8ceb1426c1200d73ad36e6692e5a98b748628578ec275a796023430e39df4442e38e355a5bb7f56598fed5e8d0
⠹ Downloading release artifacts... (2.6s)[HTTP] GET https://storage.googleapis.com/shorebird_release_artifacts/c3722880-f327-4652-b2d8-2765395f0a30%2Fandroid%2Fx86_64%2F27973%2Fdlc.vmcode?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=patch-artifacts-storage-bucket%40code-push-prod.iam.gserviceaccount.com%2F20240122%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240122T160201Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=233c2da51ea0422663cadcf44df9363fc2cd28f35282ab46fa8298d038d388d21ded34e388be7c6b12ded320f9b1cf00c08a8d62f95115989d1b51faf74ec1d767a27e326d8b5945cbdfd2a31633ac2045491a60b44b2f59b51c0e9fd120532ceb6c7d8a37f3fa1880826f44310cb143db588e39843a268e2883828dfa85303984a080a5a8c25d84d92e71a5f3c39c52c3e396b43bfc5baf106695cc1c64ecab10a78465d45c58cc361b9071f61d05b90022c843fd4378cab52e70bbbc9026bf0efaf6e3dc856490c326792b1f1215071365103a62424d379f3994fdc010abbecdb93ed7881d3fc38e87515ac08c3b03ddaa7d99bd374ff688afabd2a79e1e76
✓ Downloading release artifacts (3.4s)
[Process.run] C:\Users\csouza\.shorebird\bin\cache\flutter\b7ad8d5759c4889ea323948fe589c69a39c26135\bin\flutter build aar --no-debug --no-profile --build-number=1.0 --verbose
⠸ Building patch... (25.0s)[Process.runSync] where.exe flutter
[Process.run] flutter --no-version-check pub get --offline --verbose
✓ Building patch (27.6s)
Extracting C:\Users\csouza\Downloads\samples\add_to_app\my_flutter_module\build\host\outputs\repo\com\example\my_flutter_module\flutter_release\1.0\flutter_release-1.0.aar to C:\Users\csouza\AppData\Local\Temp\b426a505\flutter_release-1.0.zip
[HTTP] GET https://storage.googleapis.com/shorebird_release_artifacts/c3722880-f327-4652-b2d8-2765395f0a30%2Fandroid%2Faar%2F27973%2Fdlc.vmcode?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=patch-artifacts-storage-bucket%40code-push-prod.iam.gserviceaccount.com%2F20240122%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240122T160202Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=7fb1bed718d38ebb3c660184272e28cd2a669fb4ee515c0f8b252eadc571041c6ce78c385b73f16b6db13c9e63515d9002dc90a68bd6e781c95200dfba937674eabab56c5c630a7ce3d8f4ed8f3b1bc078b06b7242930cd3c5c5994477d278826c9dd182eeb0a405ab058248735909c371cab7c0df565a334d790ff1a304c8b6926a9c705416cbab3aff3b49794bfffe02d9c9ee92384e47e4f3e52f5c6be085d77a4be83b5aef696bf3ba559e639b086d3accf538dbc6dea2f71619e365bbd4ac5c042eb83f9012ba0de465199dba9af96046457f542de348366fa6fd3f142894bd383c057998eceb01d2b3e7f42290334593872d42ffe0827e0e5732e80a15
✓ Verifying patch can be applied to release (26ms)
Creating artifact for C:\Users\csouza\Downloads\samples\add_to_app\my_flutter_module\build\host\outputs\repo\com\example\my_flutter_module\flutter_release\1.0\flutter_release-1.0\jni\arm64-v8a\libapp.so
[Process.run] C:\Users\csouza\.shorebird\bin\cache\artifacts\patch\patch C:\Users\csouza\AppData\Local\Temp\68f70341\artifact C:\Users\csouza\Downloads\samples\add_to_app\my_flutter_module\build\host\outputs\repo\com\example\my_flutter_module\flutter_release\1.0\flutter_release-1.0\jni\arm64-v8a\libapp.so C:\Users\csouza\AppData\Local\Temp\b6c49cb5\diff.patch
⠴ Creating artifacts... (0.4s)Creating artifact for C:\Users\csouza\Downloads\samples\add_to_app\my_flutter_module\build\host\outputs\repo\com\example\my_flutter_module\flutter_release\1.0\flutter_release-1.0\jni\armeabi-v7a\libapp.so
⠦ Creating artifacts... (0.5s)[Process.run] C:\Users\csouza\.shorebird\bin\cache\artifacts\patch\patch C:\Users\csouza\AppData\Local\Temp\b4eb816d\artifact C:\Users\csouza\Downloads\samples\add_to_app\my_flutter_module\build\host\outputs\repo\com\example\my_flutter_module\flutter_release\1.0\flutter_release-1.0\jni\armeabi-v7a\libapp.so C:\Users\csouza\AppData\Local\Temp\4bd09f30\diff.patch
⠙ Creating artifacts... (0.9s)Creating artifact for C:\Users\csouza\Downloads\samples\add_to_app\my_flutter_module\build\host\outputs\repo\com\example\my_flutter_module\flutter_release\1.0\flutter_release-1.0\jni\x86_64\libapp.so
[Process.run] C:\Users\csouza\.shorebird\bin\cache\artifacts\patch\patch C:\Users\csouza\AppData\Local\Temp\69000e2d\artifact C:\Users\csouza\Downloads\samples\add_to_app\my_flutter_module\build\host\outputs\repo\com\example\my_flutter_module\flutter_release\1.0\flutter_release-1.0\jni\x86_64\libapp.so C:\Users\csouza\AppData\Local\Temp\ad8f40f5\diff.patch
✓ Creating artifacts (1.3s)

🚀 Ready to publish a new patch!

📱 App: my_flutter_module (c3722880-f327-4652-b2d8-2765395f0a30)
📦 Release Version: 1.0+2
🕹️  Platform:  android [arm64 (3.55 KB), arm32 (3.62 KB), x86_64 (3.61 KB)]
🟢 Track:  Production

Would you like to continue? (y/N) Yes
[HTTP] POST https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/patches
✓ Creating patch (1.0s)
[HTTP] POST https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/patches/30369/artifacts
⠹ Uploading artifacts... (0.2s)[HTTP] POST https://storage.googleapis.com/shorebird_patch_artifacts/c3722880-f327-4652-b2d8-2765395f0a30%2Fandroid%2Faarch64%2F30369%2Fdlc.vmcode?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=patch-artifacts-storage-bucket%40code-push-prod.iam.gserviceaccount.com%2F20240122%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240122T160239Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=000bd0aa6105e55dab4827e236b9ba433b851cce7aee7b5af44a3a87ad57bd8eb43a13b6499897a00191ddc4c474ac1e3fdaf8b51f94dfca10df04311f9080594c834dd6c2cb3720134a6511fdfb8ae5fac29ea8cddf81e9379fb236560e9546235171fbdd2eb7f812fc6f155ef87701c05f69c02f917a7ffa15cbd8414ef78f571f58e56ebd132287c2e8ed1a581196831f619e86fb4a10b4dca122d0b23ae69bf32158eab9f520326c772f2de64919d0ca473c091ac4f6f4ccb92b92586f813be7a372e45d59502d3da00dda5145119013f1fda600bdf22c205257937ca9b7059593fb746afd53fc7a186f63c7b3d9cad0c295d6dc0edc7798b7a86523e7ab
⠦ Uploading artifacts... (0.5s)[HTTP] POST https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/patches/30369/artifacts
⠇ Uploading artifacts... (0.6s)[HTTP] POST https://storage.googleapis.com/shorebird_patch_artifacts/c3722880-f327-4652-b2d8-2765395f0a30%2Fandroid%2Farm%2F30369%2Fdlc.vmcode?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=patch-artifacts-storage-bucket%40code-push-prod.iam.gserviceaccount.com%2F20240122%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240122T160240Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=7241f664a6585e938dc4008de5bf506fb08f2e4107a11b24da1d32da42641c0d5f140871d5e8e3ce8507e1d03092a63167f7c18553c7c2994734f2dcb07f7bc32fb2cf9879421c833ffa8946d0a43fb3b997baf73e46ff1761e44561b9de5daacbbf18ed7dc866f42f11442a11552c5a638d2c658780632bf6bca95874e8fb787eefd7cefd95035bec575ebd117d5f54065195020beb3a3089cb3b33a568e8becaa2c112420954665f96e4be6736e42e240cf9478ce82d78a5a29f58465e4ab1dcc047515646a5958c78507859bf5eeb550a222abcd8b04d8f1f1db50c3067d7266c9de01debf7dac7da67de2404e35139565dcd32b12910a0eaac52e2af5ab9
⠙ Uploading artifacts... (0.9s)[HTTP] POST https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/patches/30369/artifacts
⠼ Uploading artifacts... (1.1s)[HTTP] POST https://storage.googleapis.com/shorebird_patch_artifacts/c3722880-f327-4652-b2d8-2765395f0a30%2Fandroid%2Fx86_64%2F30369%2Fdlc.vmcode?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=patch-artifacts-storage-bucket%40code-push-prod.iam.gserviceaccount.com%2F20240122%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240122T160240Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=7dab007381dadaf094c20f19e3343d65cd6d93a0f9c99001c976cc3b273e1e09bba73840f188caa0ae246b21bd85c9e8a2b7fa06e1cfe9451a300e98bb01ce3f99105c1108179d0fe6c85f0bb764b3c6e28a6490ed4f8b8ba5876f51869636ad2f7d71f22241a1ed8b16811064baead0ce4b4e50456c3c43f615f12eb840057fa9e942d2c0e9c9d3362c45ca5d6521ef5588c34a176d158f2534d8b9d45b56c6a1813e75c5fd9c45f4802674ea038b8362cb98fd83fefc7afa642a27944cbb9b279a7b88ef515ca3c18586b92a2f8d5f2c7d8abdc07037830f0c710a2bbab392798df36c484e760f59b3a4e76e26ec6dfc5a760a2832e9cf3f9b06126cd5695b
✓ Uploading artifacts (1.4s)
[HTTP] GET https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/channels
✓ Fetching channels (0.2s)
[HTTP] POST https://api.shorebird.dev/api/v1/apps/c3722880-f327-4652-b2d8-2765395f0a30/patches/promote
✓ Promoting patch to stable (0.2s)

**Comment by bryanoltman** [comment]
Based on our Discord conversation, this seems to be a machine-specific issue.

**Comment by bryanoltman** [comment]
@ClauberBM if you're able to determine what configuration on your machine was causing this, we'd love to know and fix the issue or at least update our docs/warning messages.

**Comment by ClauberBM** [comment]
Hello, I can't say which configuration actually caused this problem, I got around the problem using Ubuntu for WSL 2.0 on Windows

**Comment by JosephKalash** [comment]
same issue here I followed the normal steps to test the service but I always got this error and I don't know what is the problem

**Comment by eseidel** [comment]
> same issue here I followed the normal steps to test the service but I always got this error and I don't know what is the problem

@JosephKalash would you be willing to open a new issue?  We would *love* to help, but will need to learn more to do so.

See also https://docs.shorebird.dev/troubleshooting/#i-created-a-patch-but-its-not-showing-up-in-my-app

**Comment by JosephKalash** [comment]
@eseidel Thank you but it worked. I redo the steps and it worked fine, I think I it was an issue with versions the shorebird dashboard is not tie in with my local project.
