### ISSUE TITLE
feat: Setup flavors using dart-define-from-file

### ISSUE THREAD

**Issue by maxakak1998** [shorebirdtech/shorebird#1633]
My project gets the configuration from json using dart-define-from-file for each 'flavor'. Due to there is no real flavor setup in the native side, i need somehow match our architecture to ShoreBird's flavor. What is the best way to use Shorebird in my project?

For example, the structure will like this:
 ...
 lib/
 dart-defines/
      - dev.json  
      - beta.json
      - prod.json
  ...
Each file will have the configurations such as appId, key, url ...

I have tried to use `shorebird init -- --dart-define-from-file=dart_defines/beta.json` but look like it failed to read from the json. My idea with that command line is init all flavors by each json and then get the all shorebird.yaml then i will combine them to 1 and make it becomes flavors like the same way we are doing in the documentation.

Thanks.

**Comment by bryanoltman** [comment]
If I'm understanding correctly (not 100% positive that I am), this will not currently work. JSON files are assets, and shorebird does not currently support asset updates in patches. We want to eventually (see https://github.com/shorebirdtech/shorebird/issues/318), but that is not currently our focus. Let me know if I've misunderstood the question though!

**Comment by maxakak1998** [comment]
I just only use JSON file when building to APK/IPA, not runtime. The problem is when using `shorebird  init` it will look for the flavor in the native but i'm not using any flavor. My project will read values from JSON file at the build phase and mapping these values to my application variable(appId, bundleId ,...).

Because Shorebird fails to find any flavors, i can not get appId from Shorebird.

Here is the screenshot after using `shorebird init -- --dart-define-from-file=dart_defines/android/beta.json`

So i guess that command line `shorebird init ` does not support dart-define-from-file? Because my build.gradle will fail to run if there is no JSON

![image](https://github.com/shorebirdtech/shorebird/assets/50696626/043b9693-93d0-4d4d-ad88-d9e38d2659b5)

If i can get the app id, maybe i can use it like this

app_id: ee322dc4-3dc2-4324-90a9-04c40a62ae76
flavors:
  internal: ee322dc4-3dc2-4324-90a9-04c40a62ae76
  stable: 904bd3d5-3526-4c1c-a832-7ac23c95302d

**Comment by bryanoltman** [comment]
Flavors in shorebird correspond to different apps (and different app bundle IDs). Does this describe your use case? If so, you'll almost certain want to integrate flavors at the native layer.

If you just want to provide compile-time variables to your app, you can just run `shorebird init` without arguments and pass the `dart-define-from-file` argument when running the release and patch commands.

**Comment by maxakak1998** [comment]
Thanks for your reply.
I want to pass `dart-define-from-file` argument with the `shorebird init`. Any chance for that?

**Comment by bryanoltman** [comment]
You can file a feature request detailing how you would expect this feature to work (the contents of the dart define files, how you would expect this to work, etc.), but I would say it's unlikely to be implemented as I understand it. There is an existing mechanism for specifying flavors that is tied into what Flutter itself uses, and I don't think it would make sense for us to heavily customize that for a one-off use case.
