### ISSUE TITLE
Console does not show subscription edit information for customers whose subscriptions have lapsed

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1635]
A customer's subscription payments have failed, causing them to not have an active subscription with shorebird. We still have their (valid) stripe customer id. The customer would like to update their payment details, but because they don't have an active stripe customer subscription, the console is not providing them with a way to rectify the problem in stripe.

![image](https://github.com/shorebirdtech/shorebird/assets/581764/1fc1f7b1-d433-4683-a49f-f6827329e5ff)

**Comment by eseidel** [comment]
I believe this is now resolved.

**Comment by eseidel** [comment]
Nevermind, it's not merged yet.

**Comment by bryanoltman** [comment]
This was closed by https://github.com/shorebirdtech/_console/pull/121
