### ISSUE TITLE
fix: new iOS "mixed mode" breaks with obfuscation

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1637]
This came in from a customer this morning.  I've not yet reproduced myself.

For those looking for a workaround, you can use our older iOS engine by downgrading to Flutter 3.16.4:
```
shorebird flutter versions use 3.16.4
```

**Comment by eseidel** [comment]
I think this is a dupe of https://github.com/shorebirdtech/shorebird/issues/1619

**Comment by moweiran** [comment]
### I test it. We don't use obfuscation. But it's not working.

`
Shorebird 0.21.1 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.16.4 • revision 7e92b034c5dddb727cf5e802c23cddd39b325a7f
Engine • revision 9472e50354253fde3f2cdb25d8115f7aa6d3c68a
`

The Creash log like below:
`
Crashed: io.flutter.1.ui
0  ???                            0x137b20014 (Missing)
1  App                            0x3957f4 kDartIsolateSnapshotInstructions + 3695988
2  Flutter                        0x18134 EndTransitionDartToCpuIfNeeded + 284
3  ???                            0x10e92fe78 (Missing)
4  ???                            0x10e930ddc (Missing)
5  ???                            0x10e930ccc (Missing)
6  ???                            0x10e931120 (Missing)
7  ???                            0x10e931120 (Missing)
8  ???                            0x10e931120 (Missing)
9  ???                            0x10e931120 (Missing)
10 ???                            0x10e53ab88 (Missing)
11 ???                            0x10e53ae3c (Missing)
12 ???                            0x10e932f34 (Missing)
13 ???                            0x10e931120 (Missing)
14 ???                            0x10e53ab88 (Missing)
15 ???                            0x10e932d40 (Missing)
16 ???                            0x10e931120 (Missing)
17 ???                            0x10e53ab88 (Missing)
18 ???                            0x10e932d40 (Missing)
19 ???                            0x10e53ab88 (Missing)
20 ???                            0x10e53ae3c (Missing)
21 ???                            0x10e932f34 (Missing)
22 ???                            0x10e53ab88 (Missing)
23 ???                            0x10e932dec (Missing)
24 ???                            0x10e53ab88 (Missing)
25 ???                            0x10e932d40 (Missing)
26 ???                            0x10e53ab88 (Missing)
27 ???                            0x10e932d40 (Missing)
28 ???                            0x10e92fe78 (Missing)
29 ???                            0x10e930ddc (Missing)
30 ???                            0x10e53ab88 (Missing)
31 ???                            0x10e53ae3c (Missing)
32 ???                            0x10e932f34 (Missing)
33 ???                            0x10e53ab88 (Missing)
34 ???                            0x10e932dec (Missing)
35 ???                            0x10e53ab88 (Missing)
36 ???                            0x10e932d40 (Missing)
37 ???                            0x10e53ab88 (Missing)
38 ???                            0x10e53ae3c (Missing)
39 ???                            0x10e932f34 (Missing)
40 ???                            0x10e53ab88 (Missing)
41 ???                            0x10e932d40 (Missing)
42 ???                            0x10e53ab88 (Missing)
43 ???                            0x10e932dec (Missing)
44 ???                            0x10e53ab88 (Missing)
45 ???                            0x10e53ae3c (Missing)
46 ???                            0x10e932f34 (Missing)
47 ???                            0x10e53ab88 (Missing)
48 ???                            0x10e53ae3c (Missing)
49 ???                            0x10e932f34 (Missing)
50 ???                            0x10e9309e8 (Missing)
51 ???                            0x10e930ddc (Missing)
52 ???                            0x10e931120 (Missing)
53 ???                            0x10e53ab88 (Missing)
54 ???                            0x10e932dec (Missing)
55 ???                            0x10e53ab88 (Missing)
56 ???                            0x10e53ae3c (Missing)
57 ???                            0x10e29e610 (Missing)
58 ???                            0x10e287a9c (Missing)
59 ???                            0x10e287458 (Missing)
60 ???                            0x10e287420 (Missing)
61 ???                            0x10e29dacc (Missing)
62 ???                            0x10e29d9fc (Missing)
63 ???                            0x10e29d704 (Missing)
64 ???                            0x10e29d5d8 (Missing)
65 ???                            0x10e234e90 (Missing)
66 ???                            0x10e234f84 (Missing)
67 ???                            0x10ea5f4bc (Missing)
68 ???                            0x10ea60c84 (Missing)
69 ???                            0x10e23ae60 (Missing)
70 ???                            0x10e242c70 (Missing)
71 ???                            0x10e242c08 (Missing)
72 ???                            0x10e242ca8 (Missing)
73 App                            0xc298 kDartVmSnapshotInstructions + 33432
74 ???                            0xffffffffe (Missing)
`
[live.astrostar_issue_289a3c868840634daf068a36cb5111f9_crash_session_2f4515fa2d3743aa954700961fd7a2be_DNE_0_v2_stacktrace.txt](https://github.com/shorebirdtech/shorebird/files/13957611/live.astrostar_issue_289a3c868840634daf068a36cb5111f9_crash_session_2f4515fa2d3743aa954700961fd7a2be_DNE_0_v2_stacktrace.txt)

**Comment by moweiran** [comment]
Shorebird 0.21.1 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.16.4 • revision 7e92b034c5dddb727cf5e802c23cddd39b325a7f
Engine • revision 9472e50354253fde3f2cdb25d8115f7aa6d3c68a

**Comment by eseidel** [comment]
> ### I test it. We don't use obfuscation. But it's not working.
> `Shorebird 0.21.1 • git@github.com:shorebirdtech/shorebird.git Flutter 3.16.4 • revision 7e92b034c5dddb727cf5e802c23cddd39b325a7f Engine • revision 9472e50354253fde3f2cdb25d8115f7aa6d3c68a`
> 
> The Creash log like below: `Crashed: io.flutter.1.ui 0 ??? 0x137b20014 (Missing) 1 App 0x3957f4 kDartIsolateSnapshotInstructions + 3695988 2 Flutter 0x18134 EndTransitionDartToCpuIfNeeded + 284 3 ??? 0x10e92fe78 (Missing) 4 ??? 0x10e930ddc (Missing) 5 ??? 0x10e930ccc (Missing) 6 ??? 0x10e931120 (Missing) 7 ??? 0x10e931120 (Missing) 8 ??? 0x10e931120 (Missing) 9 ??? 0x10e931120 (Missing) 10 ??? 0x10e53ab88 (Missing) 11 ??? 0x10e53ae3c (Missing) 12 ??? 0x10e932f34 (Missing) 13 ??? 0x10e931120 (Missing) 14 ??? 0x10e53ab88 (Missing) 15 ??? 0x10e932d40 (Missing) 16 ??? 0x10e931120 (Missing) 17 ??? 0x10e53ab88 (Missing) 18 ??? 0x10e932d40 (Missing) 19 ??? 0x10e53ab88 (Missing) 20 ??? 0x10e53ae3c (Missing) 21 ??? 0x10e932f34 (Missing) 22 ??? 0x10e53ab88 (Missing) 23 ??? 0x10e932dec (Missing) 24 ??? 0x10e53ab88 (Missing) 25 ??? 0x10e932d40 (Missing) 26 ??? 0x10e53ab88 (Missing) 27 ??? 0x10e932d40 (Missing) 28 ??? 0x10e92fe78 (Missing) 29 ??? 0x10e930ddc (Missing) 30 ??? 0x10e53ab88 (Missing) 31 ??? 0x10e53ae3c (Missing) 32 ??? 0x10e932f34 (Missing) 33 ??? 0x10e53ab88 (Missing) 34 ??? 0x10e932dec (Missing) 35 ??? 0x10e53ab88 (Missing) 36 ??? 0x10e932d40 (Missing) 37 ??? 0x10e53ab88 (Missing) 38 ??? 0x10e53ae3c (Missing) 39 ??? 0x10e932f34 (Missing) 40 ??? 0x10e53ab88 (Missing) 41 ??? 0x10e932d40 (Missing) 42 ??? 0x10e53ab88 (Missing) 43 ??? 0x10e932dec (Missing) 44 ??? 0x10e53ab88 (Missing) 45 ??? 0x10e53ae3c (Missing) 46 ??? 0x10e932f34 (Missing) 47 ??? 0x10e53ab88 (Missing) 48 ??? 0x10e53ae3c (Missing) 49 ??? 0x10e932f34 (Missing) 50 ??? 0x10e9309e8 (Missing) 51 ??? 0x10e930ddc (Missing) 52 ??? 0x10e931120 (Missing) 53 ??? 0x10e53ab88 (Missing) 54 ??? 0x10e932dec (Missing) 55 ??? 0x10e53ab88 (Missing) 56 ??? 0x10e53ae3c (Missing) 57 ??? 0x10e29e610 (Missing) 58 ??? 0x10e287a9c (Missing) 59 ??? 0x10e287458 (Missing) 60 ??? 0x10e287420 (Missing) 61 ??? 0x10e29dacc (Missing) 62 ??? 0x10e29d9fc (Missing) 63 ??? 0x10e29d704 (Missing) 64 ??? 0x10e29d5d8 (Missing) 65 ??? 0x10e234e90 (Missing) 66 ??? 0x10e234f84 (Missing) 67 ??? 0x10ea5f4bc (Missing) 68 ??? 0x10ea60c84 (Missing) 69 ??? 0x10e23ae60 (Missing) 70 ??? 0x10e242c70 (Missing) 71 ??? 0x10e242c08 (Missing) 72 ??? 0x10e242ca8 (Missing) 73 App 0xc298 kDartVmSnapshotInstructions + 33432 74 ??? 0xffffffffe (Missing)` [live.astrostar_issue_289a3c868840634daf068a36cb5111f9_crash_session_2f4515fa2d3743aa954700961fd7a2be_DNE_0_v2_stacktrace.txt](https://github.com/shorebirdtech/shorebird/files/13957611/live.astrostar_issue_289a3c868840634daf068a36cb5111f9_crash_session_2f4515fa2d3743aa954700961fd7a2be_DNE_0_v2_stacktrace.txt)

Thank you for the report!

We just released 0.24.0 which fixed several crashers on iOS.  I haven't yet tried to symbolicate the log you provided, but I think it's highly likely we fixed the crasher.  If you're still hitting crashes after releasing (not just patching) with 0.24.0, please let us know, we are happy to even jump on a call and help debug!

**Comment by eseidel** [comment]
We now offer official obfuscation support on iOS:
https://shorebird.dev/blog/obfuscation-on-ios
