### ISSUE TITLE
Smoke Test 3.16.7

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#1639]
- [x] e2e tests
- [ ] framework tests
- [ ] engine tests (https://github.com/shorebirdtech/_build_engine/actions/runs/7548325563/job/20550142802)
- [x] flutter create + shorebird init works

- [x] iOS release
- [ ] iOS patch
- [x] iOS preview

- [x] `shorebird doctor`
    - [X] Win
    - [x] Mac

```
PS C:\Users\micro\Documents\GitHub\test_counter> ..\shorebird\bin\shorebird doctor 
Shorebird 0.21.1 • git@github.com:shorebirdtech/shorebird.git
Flutter • revision 899369f8cc7672fef7c6803e20c8991e61b8d3e6
Engine • revision 1fb88d44a4c4285f48be354c086d78862de6bb7f

✓ Shorebird is up-to-date (3.4s)
✗ Flutter install is correct (9.5s)
  [!] Directory: 'C:\Users\micro\Documents\GitHub\shorebird\bin\cache\flutter\899369f8cc7672fef7c6803e20c8991e61b8d3e6' has local modifications
  [✗] Failed to determine Shorebird Flutter version. FlutterValidationException: Could not detect version number in output
✓ AndroidManifest.xml files contain INTERNET permission (85ms)
✓ Has access to storage.googleapis.com (0.3s)
2 issues detected.
```

- [x] Android release
    - [x] Win
    - [x] Mac
- [x] Android patch
    - [x] Win
    - [x] Mac
- [x] Android preview
    - [x] Win
    - [x] Mac

- [x] iOS Add to App release
- [x] iOS Add to App patch

- [x] Android Add to App release
    - [x] Win
    - [x] Mac
- [x] Android Add to App patch
    - [x] Win
    - [x] Mac

- [x] iOS Flavors release
- [x] iOS Flavors patch
- [x] iOS Flavors preview

- [x] Android Flavors release
    - [x] Win
    - [x] Mac
- [x] Android Flavors patch
    - [x] Win
    - [x] Mac
- [x] Android Flavors preview
    - [x] Win
    - [x] Mac

**Comment by eseidel** [comment]
Windows:
```
warning: unable to access 'dev/integration_tests/ios_app_with_extensions/ios/watch Extension/Assets.xcassets/Complication.complicationset/Graphic Large Rectangular.imageset/.gitattributes': Filename too long
error: unable to create file dev/integration_tests/ios_app_with_extensions/ios/watch Extension/Assets.xcassets/Complication.complicationset/Graphic Large Rectangular.imageset/Contents.json: Filename too long
Updating files: 100% (7857/7857), done.
```

It manages to continue just fine.

**Comment by bryanoltman** [comment]
`patch ios-alpha` is working fine for me after a fresh release, fwiw

**Comment by felangel** [comment]
`patch ios-alpha` is still crashing for me with the latest engine revision. Building a local engine to try to debug in XCode now.
