### ISSUE TITLE
Problem with patches 

### ISSUE THREAD

**Issue by elizacloud** [shorebirdtech/shorebird#1642]
We have released multiple patches, such as 1, 2, 3. Some clients that started updating from patch 1 follow the sequence and update to patch 2, 3, and so on. However, there are other clients that have never been updated. In this case, even though patches have advanced to patch 4, these clients only update to patch 1 and then stop updating.

Flutter 3.16.0
Tools • Dart 3.2.0 • DevTools 2.28.2

**Comment by eseidel** [comment]
Would love to help.  Are you able to share your app_id?  Thanks!
https://docs.shorebird.dev/faq#do-i-need-to-keep-my-app_id-secret

**Comment by elizacloud** [comment]
> Would love to help. Are you able to share your app_id? Thanks! https://docs.shorebird.dev/faq#do-i-need-to-keep-my-app_id-secret

eaf09957-0d98-4280-9932-102748c6a7ed Thanks!

**Comment by bryanoltman** [comment]
Looking at your app in our admin panel and checking our logs, it looks like the following patches are live and being installed by users:

1. 1.0.3+13, patch number 1
2. 1.0.2+12, patch number 2

These are the latest patches for these releases, and the only two releases that have patches. Does this match your expectations?

**Comment by elizacloud** [comment]
> Looking at your app in our admin panel and checking our logs, it looks like the following patches are live and being installed by users:
> 
> 1. 1.0.3+13, patch number 1
> 2. 1.0.2+12, patch number 2
> 
> These are the latest patches for these releases, and the only two releases that have patches. Does this match your expectations?

I encountered the issue in version 1.0.12, where there are two patches. Many clients only updated to patch number 1 and did not update to patch number 2

**Comment by bryanoltman** [comment]
Hmm, I'm seeing 30 installs for patch 2 and 15 installs for patch 1. Have the affected clients quite and restarted their apps?

**Comment by elizacloud** [comment]
> Hmm, I'm seeing 30 installs for patch 2 and 15 installs for patch 1. Have the affected clients quite and restarted their apps?

I received feedback from users that, upon the first entry, the application updated to patch number 1. After restarting the app, they were able to update to patch number 2 to achieve the desired effect. According to my understanding, perhaps I misunderstood; should the app update all patches when launched? Thanks

**Comment by bryanoltman** [comment]
Shorebird checks for and downloads patches on app launch. On the next subsequent app launch, the patch will be applied. There's more info about this at https://docs.shorebird.dev/concepts, but let me know if you have any questions that aren't answered there!
