### ISSUE TITLE
After I use shorebird preview, isShorebirdAvailable is available. But after flutter builds apk, isShorebirdAvailable is not available

### ISSUE THREAD

**Issue by sssolinjie** [shorebirdtech/shorebird#1657]
After I use shorebird preview, isShorebirdAvailable is available. But after flutter builds apk, isShorebirdAvailable is not available

**Comment by jobpassion** [comment]
You should use shorebird command to build apk, do you try "shorebird release android"?

**Comment by eseidel** [comment]
That is correct. When you use `shorebird preview` it uses the build you created with `shorebird release android` which includes the Shorebird updater.  When you build with `flutter build` directly it does not include the shorebird updater.

Please let us know if we can help further.
https://discord.gg/shorebird also reaches us in real-time.
