### ISSUE TITLE
fix: "Runner.app" requires a provisioning profile with the Near Field Communication Tag Reading and Push Notifications features.

### ISSUE THREAD

**Issue by huseyinbedir** [shorebirdtech/shorebird#1663]
I have an application using Flutter flavors. I successfully generated outputs for all flavors using the command shorebird release ios-alpha --flavor xxxx -t lib/xxxx_main.dart and shared them on the store without any issues. However, when I try to create a patch with shorebird patch ios-alpha --flavor xxxx -t lib/xxxx_main.dart, I encounter an error stating 'Runner.app' requires a provisioning profile with the Near Field Communication Tag Reading and Push Notifications features. In the Apple Store, under the Identifiers section, I have defined NFC and Push Notifications for the app ID. I had created a profile for this definition. How can I resolve this issue?
![image](https://github.com/shorebirdtech/shorebird/assets/57250424/322491b8-b084-4b3e-9935-d886df9dd58d)

**Comment by eseidel** [comment]
`when I try to create a patch with shorebird patch ios-alpha --flavor xxxx -t lib/xxxx_main.dart, I encounter an error stating 'Runner.app' requires a provisioning profile with the Near Field Communication Tag Reading and Push Notifications features.`

Is this when running the patch build?

When you patch with shorebird, we build an entire xcarchive, but only actually send the dart App.framework build down to the end user.  The user will then end up running your original release build effectively with the dart code from the new App.framework.

But it sound like this manifests as a problem *building* patch.  @bryanoltman would know what's different about when we build patches vs. building releases.

**Comment by bryanoltman** [comment]
Patch and release should be running the same `flutter build` command for this. @huseyinbedir can you try creating a new release (you can delete it at https://console.shorebird.dev/ after) and patching that immediately after? I'm curious to see if something changed between the release and the patch, and whether releasing still works.

1. Edit pubspec.yaml to change the version number
2. `shorebird release ios-alpha --flavor xxxx -t lib/xxxx_main.dart`
3. `shorebird patch ios-alpha --flavor xxxx -t lib/xxxx_main.dart`

**Comment by huseyinbedir** [comment]
> `flutter build`Bunun için yama ve sürüm aynı komutu çalıştırıyor olmalıdır .@huseyinbedir[Yeni bir sürüm oluşturup (daha sonra https://console.shorebird.dev/](https://console.shorebird.dev/) adresinden silebilirsiniz ) ve hemen ardından yama yapmayı deneyebilir misiniz? Sürüm ile yama arasında bir şeylerin değişip değişmediğini ve sürümün hâlâ işe yarayıp yaramayacağını merak ediyorum.
> 
> 1. Sürüm numarasını değiştirmek için pubspec.yaml'ı düzenleyin
> 2. `shorebird release ios-alpha --flavor xxxx -t lib/xxxx_main.dart`
> 3. `shorebird patch ios-alpha --flavor xxxx -t lib/xxxx_main.dart`

I upgraded to version 1.1.8 and created a shorebird release ios-alpha. Then I entered the shorebird patch ios-alpha command. The result is as follows

![Group 7 (1)](https://github.com/shorebirdtech/shorebird/assets/57250424/d17c4c44-ac18-49b0-8f16-91def996390c)

**Comment by bryanoltman** [comment]
That's really odd. Could you run these commands with the `-v` flag? This will print the commands shorebird is running under the hood and might provide some additional insight.

Can you also share your app ID? It does not need to be kept private.

**Comment by huseyinbedir** [comment]
> That's really odd. Could you run these commands with the `-v` flag? This will print the commands shorebird is running under the hood and might provide some additional insight.
> 
> Can you also share your app ID? It does not need to be kept private.

Shorebird yaml does it need to remain secret ?

![Group 8](https://github.com/shorebirdtech/shorebird/assets/57250424/4569b1b7-6c36-47ba-b94e-45e00503cdc5)

![Ekran Resmi 2024-01-31 11 40 1](https://github.com/shorebirdtech/shorebird/assets/57250424/b9309692-954e-4a22-b896-e053108932a0)

**Comment by eseidel** [comment]
shorebird.yaml does not need to be a secret, no: https://docs.shorebird.dev/faq#do-i-need-to-keep-my-app_id-secret

**Comment by bryanoltman** [comment]
That is really odd! Can you tell me what you see if you run:

```
FLUTTER_STORAGE_BASE_URL=https://download.shorebird.dev /Users/yazilim/.shorebird/bin/cache/flutter/b9b23902966504a9778f4c073a3487fa84dcb2/bin/flutter build ipa -release --flavor=martelekom --target=lib/martelekom main.dart --verbose
```

(This was copied from the image you pasted, so double-check that all of the text is correct. You probably want to copy this from the verbose patch output).

Sharing your shorebird.yaml would also likely be helpful.

**Comment by huseyinbedir** [comment]
> Bu gerçekten tuhaf! Eğer koşarsan ne gördüğünü bana söyleyebilir misin?
> 
> ```
> FLUTTER_STORAGE_BASE_URL=https://download.shorebird.dev /Users/yazilim/.shorebird/bin/cache/flutter/b9b23902966504a9778f4c073a3487fa84dcb2/bin/flutter build ipa -release --flavor=martelekom --target=lib/martelekom main.dart --verbose
> ```
> 
> (Bu, yapıştırdığınız resimden kopyalanmıştır, bu nedenle metnin tamamının doğru olup olmadığını bir kez daha kontrol edin. Muhtemelen bunu ayrıntılı yama çıktısından kopyalamak istersiniz).
> 
> shorebird.yaml dosyanızı paylaşmanız da muhtemelen faydalı olacaktır.

I did as you suggested, but there are 113,981 lines. Instead of sharing all of them here, I can share with you any specific areas you're interested in, or would you like me to send it via email?

app_id: c22a03d8-7d90-4ac2-ade4-16ee83f2c160
flavors:
  XXX: c22a03d8-7d90-4ac2-ade4-16ee83f2c160
  XXX: b49dc8cb-1d5f-4eec-a3f1-257850a51635
  XXX: 1a125cc6-2032-4f86-9be4-62df63cdd721
  XXX: 62ea3108-d8b3-4eb1-b469-27d010c9db4e
  XXX: 5c58f794-97c7-4ec2-8f41-7539047ca38f
  XXX: 91d69bf0-b9f2-4bcf-af63-b6200ab9d886
  XXX: 1783df65-dc0a-4043-96fe-17303cb85f7c
  XXX: 7034867a-470a-489f-a992-c1d00cf54d47
  XXX: 82beb125-6db7-424c-a46a-3ddb482c4bea
  XXX: 3caa643e-0c22-43b7-9854-2c73ff12bc2a
  XXX: 98da59b7-3845-4877-8efd-249ff0fa9d7f
  XXX: 5b02c601-376d-4e40-907d-d1ad08d088dd
  XXX: b5db4f4a-9718-4698-8665-89ca85016e8b
  XXX: 7e5e0739-4917-4a2e-83d2-19ab0b7d15b5
  martelekom: bcb0ff2d-d0db-415f-a86c-95ca5455e7c1
  XXX: 3cbf4ad8-ef38-4907-8cef-3db76d432318

**Comment by bryanoltman** [comment]
Did the command succeed? If not, I'd be looking for a section of logs starting with the first error output. You can email the logs as well.

**Comment by huseyinbedir** [comment]
> Did the command succeed? If not, I'd be looking for a section of logs starting with the first error output. You can email the logs as well.

In the command result, there is a section with the same error again. I sent it to you by e-mail. Thank you for your interest.

**Comment by bryanoltman** [comment]
Hmm, nothing jumps out at me in that log output. The one difference I've noticed is that we aren't supplying the export options plist to the patch build command, which could be the source of your issue. Let me look into that and I'll reply here once I've found something.
