### ISSUE TITLE
fix: Cannot launch preview on an IOS device 

### ISSUE THREAD

**Issue by Schtroumphy** [shorebirdtech/shorebird#1666]
**Description**

When I try to launch an existing preview (Flutter) on my IOS device, it stop at the same step : ''[ 70%] VerifyingApplication..."

**Steps To Reproduce**

1. Create a release for a specific flavor
2. Try ro run the preview of this release on IOS physical device with all required parameters

**Expected Behavior**

The application must be launched.

**Screenshots**

![image](https://github.com/shorebirdtech/shorebird/assets/42738178/84a745c9-cf77-4688-ac1a-d4eb1e7de7af)

**Additional Context**

It's a Flutter application.

**Comment by eseidel** [comment]
I suspect it's the extra flags passed to preview.  Preview runs your app in its unmodified release form.  We probably shouldn't pass along flags after `--` on preview.

**Comment by eseidel** [comment]
I would try just `shorebird preview` with no flags and see if that works?

**Comment by bryanoltman** [comment]
"Unable to find devicectl" suggests that you're running an older version of Xcode that we don't support. If you upgrade to Xcode 15, this problem should go away.

**Comment by bryanoltman** [comment]
"unable to find devicectl" suggests you're trying to deploy to a device running iOS 17+ but don't have Xcode 15 installed. Upgrading to Xcode 15 should fix this.
