### ISSUE TITLE
fix: After patching, it runs and quits immediately[iOS,Android]

### ISSUE THREAD

**Issue by coreanadx** [shorebirdtech/shorebird#1670]
**Description**

1. After patching Android and iOS, a crash occurs when running the app.
2. Android is being updated normally after re-release.
3. Even if iOS is re-released, the same crash occurs and distribution has been discontinued.

**Steps To Reproduce**

1. add patch
2. app re-open

**Expected Behavior**

After patching Android and iOS, a crash occurs when running the app.

**Screenshots**

[Android]
1. Android - patch - 1st
<img width="573" alt="android-1st-patch" src="https://github.com/shorebirdtech/shorebird/assets/133842534/eeb7761d-c499-4d5c-9172-a10da48c513b">

2. Android - patch - 2nd : A crash occurred so I patched it again (same crash occurred)
<img width="571" alt="android-2nd-patch" src="https://github.com/shorebirdtech/shorebird/assets/133842534/738f549a-ecde-48a0-b95d-3ca62d2a1fc0">

3. Android - new release
<img width="914" alt="android-new-release" src="https://github.com/shorebirdtech/shorebird/assets/133842534/7fce6601-34e6-4388-b7ed-c6aa62b8b666">

4. Android - new patch
<img width="794" alt="android-new-patch" src="https://github.com/shorebirdtech/shorebird/assets/133842534/91dc5355-d386-4e0f-ba50-a3d1cc505cc1">
: [Normal operation]

[iOS]
0. When I patched it, a crash occurred so I had to build a new one.
1. iOS - 1st release
<img width="916" alt="ios-1st-release" src="https://github.com/shorebirdtech/shorebird/assets/133842534/3e07bd24-243e-4e54-a2a1-78814fa21ae1">

2. iOS - 1st patch : same crash occurred
<img width="699" alt="ios-1st-patch-1st" src="https://github.com/shorebirdtech/shorebird/assets/133842534/3e02b768-b897-4d1b-ad79-8e0c89eeb84d">

3. iOS - 2nd patch : same crash occurred
<img width="700" alt="ios-1st-patch-2nd" src="https://github.com/shorebirdtech/shorebird/assets/133842534/654992f0-21de-4169-a449-ae18548ffb71">

4. shorebird doctor
<img width="608" alt="shorebird-update" src="https://github.com/shorebirdtech/shorebird/assets/133842534/156dada8-e999-48b2-a065-c975e704ed2e">

5. iOS - 2nd release
<img width="915" alt="ios-2nd-release" src="https://github.com/shorebirdtech/shorebird/assets/133842534/8c12bfab-18c0-488b-8d14-1060c55a1842">

6. iOS - 1st patch :same crash occurred
<img width="695" alt="ios-2nd-patch" src="https://github.com/shorebirdtech/shorebird/assets/133842534/00773c16-c1ea-4c9a-80c8-94d16a660ceb">

**Additional Context**

Please help us make it available on iOS.

**Comment by coreanadx** [comment]
#1637 
fit it

**Comment by eseidel** [comment]
It sounds like the crash is resolved for you?  If not we would very much like to help.  We're happy to jump on a video call and help debug.  We're also reachable every day in real time on discord: https://discord.gg/shorebird.
