### ISSUE TITLE
bug: iOS hybird app crash after patch update

### ISSUE THREAD

**Issue by dangercheng** [shorebirdtech/shorebird#1682]
After downloading the demo code following the instructions on the official website, successfully publish a new patch, the app crashes upon launching after applying the patch update.
 
**Steps To Reproduce:**
1.download from reference code from https://github.com/shorebirdtech/samples/tree/main/add_to_app
2.shorebird init -f
3.shorebird release ios-framework-alpha --release-version 1.0.0+1
4.run release app on device with XCode
5.modify dart and  publish a new patch: shorebird patch ios-framework-alpha --release-version 1.0.0+1
6.restart app download patch
7.restart app again, crashed

**Expected Behavior**
Successfully launched the app and applied the patch update.

**Screenshots**
![image](https://github.com/shorebirdtech/shorebird/assets/5669786/6eec58b8-aed1-4078-ae20-efb24b086b9f)
![image](https://github.com/shorebirdtech/shorebird/assets/5669786/eb119887-101d-4f09-a5b4-8c5226625020)

**Additional Context**
device log:
[IosAddToAppDemo-2024-02-01-182320.txt](https://github.com/shorebirdtech/shorebird/files/14123820/IosAddToAppDemo-2024-02-01-182320.txt)

**Comment by eseidel** [comment]
Thank you!  Looking.

**Comment by eseidel** [comment]
@bryanoltman has a fix and we will be releasing shortly.  Thank you again!
