### ISSUE TITLE
fix: Shorebird with FragmentActivities freeze

### ISSUE THREAD

**Issue by blk-raffy** [shorebirdtech/shorebird#1697]
App ID: 466980f0-810a-4555-8f8d-516d6fb83620

**Description**

I have an app with flutter_stripe integrated. To let stripe works I had to change the MainActivity from FlutterActivity to FragmentFlutterActivity. The app works fine, but when the user interact with widgets that uses FlutterFragmentActivity (like the Card Widget) the apps freeze. This doesn't happen with the plain apk or the plain aab without shorebird.

```kotlin
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}
```

**Steps To Reproduce**

1. Create a project
2. Install flutter_stripe and configure it
3. Enter the app with shorebird aab or apk
4. Let's freeze it

**Expected Behavior**

I have never used FlutterFragmentActivity, I except they works in the main way of the FlutterActivity 

**Screenshots**

N/A

**Additional Context**

I'm using lastest version of shorebird, flutter doctor -v "No issues found"

**Comment by eseidel** [comment]
Looks like you solved the issue?  Let us know if there is anything we should change in Shorebird!  Thank you!

**Comment by blk-raffy** [comment]
Turned out it was a Stripe issue, nothing to change in Shorebird, thanks
