### ISSUE TITLE
fix: shorebird init creates an app flavor for an IOS Notification Service Extension

### ISSUE THREAD

**Issue by xalikoutis** [shorebirdtech/shorebird#1703]
App ID: e789c84d-c5a1-4538-8d5d-21b4d9cfb444

**Description**

Our Flutter project is configured to support FCM images on notification body. Firebase instructs here to create a Notification Service Extension
https://firebase.flutter.dev/docs/messaging/apple-integration#step-1---add-a-notification-service-extension

calling shorebird init creates a flavor for the Notification Service Extension on shorebird.yaml and on shorebird console
**Steps To Reproduce**

So on a flutter ios project supporting Notification Images from FCM

1. setup a Notification Service Extension for the ios project
2. call `shorebird init`
3. shorebird.yaml has a flavor for the Notification Service Extension
4. visit shorebird console on the web
5. see a second app for the Notification Service Extension

**Expected Behavior**

shorebird init should register only a signle app(no flavors)

**Screenshots**

![image](https://github.com/shorebirdtech/shorebird/assets/847472/3305eaa1-ec0b-4180-8f76-4ef85db963bc)
![image](https://github.com/shorebirdtech/shorebird/assets/847472/530186aa-d39e-4f63-8949-2da71563dc3f)

**Additional Context**

**Comment by bryanoltman** [comment]
Thanks for reporting! For what it's worth, this shouldn't interfere with your use of shorebird and you can safely delete the app from the [console](https://console.shorebird.dev/).

**Comment by bryanoltman** [comment]
The shorebird tool uses Xcode schemes to identify flavors (as per https://docs.flutter.dev/deployment/flavors#creating-flavors-in-ios-and-macos). The notification service extension also creates a scheme, which is confusing the shorebird tool. Looking to see if there's a way we can distinguish extension schemes from those that represent flavors.

**Comment by bryanoltman** [comment]
It's possible our non-macOS logic to detect iOS schemes might work correctly here. I added a Notification Service extension to our flavors sample app. `xcodebuild -list` gives me:

```
    Schemes:
        internal
        NotificationService
        Runner
        stable
```

While the contents of `ios/Runner.xcodeproj/xcshareddata/xcschemes` is:

```
⑆ ls
Runner.xcscheme   internal.xcscheme stable.xcscheme
```

**Comment by bryanoltman** [comment]
Frustratingly, adding a new flavor (which I called `beta`) updates the xcschemes directory content to include the NotificationService scheme:

```
⑆ ls
NotificationService.xcscheme beta.xcscheme                stable.xcscheme
Runner.xcscheme              internal.xcscheme
```

**Comment by bryanoltman** [comment]
It looks like the NotificationServcie.xcscheme file contains an `wasCreatedForAppExtension = "YES"` entry, while the others do not. We can probably filter on this.
