### ISSUE TITLE
fix: `shorebird` hangs when run under `fastlane`

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1705]
"""
I included the shorebird command in my fastlane pipeline for ease of use and this is where it never continues after it packages everything up. I then tried running the command outside of fastlane (thinking it might be some directory issue, it occured in the past with different tools), and that's when I found out why it never finished via fastlane. Shorebird asks you if you want to create a new release ("Would you like to continue?"), and that question is not visible if you run the command via fastlane. So just had to add the --force command for the release build that I was doing via fastlane and everything works. 😂
"""

1. We should detect this case (fastlane is pretty common, or was at one point).  And presumably we're headless in that environment (don't have a TERM?)
2. We should discourage use of --force and instead some sort of --no-confirm flag for situations like this we can't detect.

**Comment by eseidel** [comment]
I think the right thing here is for us (or mason_logger) to detect that it's running headless and never hang in confirm.

**Comment by eseidel** [comment]
Got another report of this just now with #1841.

Does anyone know of an example project using fastlane with Flutter that we should work from?

Otherwise I guess we can build one from https://docs.flutter.dev/deployment/cd#fastlane

**Comment by eseidel** [comment]
A workaround for now could be to run:
```
yes | shorebird release android
```
since yes will send "y" any time prompted.

**Comment by vivaan-vama** [comment]
Any update on this ?

**Comment by bryanoltman** [comment]
A fix has been merged to our main branch and will go out in the next release (today or tomorrow)

**Comment by vivaan-vama** [comment]
Thanks for the update! can you confirm what steps we need to take to auto confirm ?

**Comment by bryanoltman** [comment]
None, you will just need to update to the latest version when we release.

**Comment by bryanoltman** [comment]
In the meantime, you can set `CI=true` as an environment variable and it will have the same effect as the new version. Once the new version is released, the environment variable won't be necessary.

**Comment by vivaan-vama** [comment]
Hi, Have you deployed the new release, if yes what exactly i have to pass now ?

**Comment by bryanoltman** [comment]
This has been deployed. It should just work with no changes on your side
