### ISSUE TITLE
"shorebird preview" takes a significant amount of time and does not provide a preview

### ISSUE THREAD

**Issue by GayanLakmalWAD** [shorebirdtech/shorebird#1711]
Shorebird 0.25.1
Flutter Version: 3.16.9
Simulator - iphone 15 pro-max

I waited for more than 30 minutes, and nothing happened.

<img width="429" alt="Screenshot" src="https://github.com/shorebirdtech/shorebird/assets/79825528/e5782449-09cf-45fc-986f-bc00360be4e4">

**Comment by eseidel** [comment]
Hmm, seems like it got stuck.  That's definitely not expected.  Thanks for the report!

You can try with `-v` to see what's going on.

**Comment by GayanLakmalWAD** [comment]
it says "Waiting for iOS device to be connected"

**Comment by eseidel** [comment]
Does `flutter devices` show the device connected?

**Comment by GayanLakmalWAD** [comment]
yes it is,

Found 3 connected devices:
iPhone 15 Pro (mobile)

**Comment by eseidel** [comment]
Hmm.  `shorebird` generally uses `flutter` for most communication with the device.  The only time we communicate directly is via `preview` where we use either ios-deploy or devicectl, depending on the version of XCode installed:
https://github.com/shorebirdtech/shorebird/blob/164ba0ef8973100e08552f8b05bdf49f4ad03687/packages/shorebird_cli/lib/src/commands/preview_command.dart#L354

**Comment by eseidel** [comment]
I presume you're passing `-d` to select the device you want?  I wonder if our code around ios-deploy or devicectl isn't respecting -d.

**Comment by bryanoltman** [comment]
I noticed that you said you were using a simulator in your original report above. Is that the case? `shorebird preview` only works with physical devices, but I would expect a better failure mode than this.

**Comment by bryanoltman** [comment]
After poking locally, I think this is just bad logging on our part. Should be an easy fix.
