### ISSUE TITLE
About Icons.ios_share in a patch.

### ISSUE THREAD

**Issue by Heilum** [shorebirdtech/shorebird#1721]
In a patch, I used the following code:
`icon: Icon(Icons.ios_share,color: Colors.black,),`

the whole patch really worked. But on android devices, the above icon  did not displayed, and on iOS ones, this icon displayed a strange emoji. what happened?

**Comment by eseidel** [comment]
I would expect that 'shorebird patch' also displayed this warning:

https://docs.shorebird.dev/troubleshooting#i-see-a-the-release-artifact-contains-asset-changes-warning-when-running-shorebird-release-asset-changes

'The final file changed above is the MaterialIcons-Regular.otf font file, which can happen if your app uses more or fewer icons from the Dart code. Flutter will automatically "tree shake" your fonts, so if you don't use an icon in your Dart code, it will not be included in the final app. You can disable this behavior with --no-tree-shake-icons at the risk of increasing your app size. This type of warning will also go away once we add [https://github.com/shorebirdtech/shorebird/issues/318](asset patching).'

Let us know if that was not the case or if that doesn't help. Thank you!

**Comment by Heilum** [comment]
thanks your prompt reply, I understood the reason. It really helps
