### ISSUE TITLE
feat: upgrade to Dart 3.3.0 and Flutter 3.19.0

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1723]
Dart 3.3.0 just appeared on stable this morning:
https://github.com/dart-lang/sdk/tree/stable

My sense from experience is that that means Flutter isn't far behind.

We're blocked on fixing https://github.com/shorebirdtech/shorebird/issues/1698 due to https://github.com/dart-lang/sdk/issues/54860 affecting .dill generation, which we currently use upstream Dart for (not our fork).  It would take a bunch of work for us to modify our infrastructure (and Dart code) to vend a patched `dart` binary (we don't test our modified Dart in JIT mode at all currently), so instead we're going to start the upgrade.

Steps I can see:
* Upgrade dart
* Upgrade build_root
* Upgrade flutter/engine
* Upgrade flutter/flutter

There will probably be a bunch of infra/tooling work relating to flutter/engine having moved to use signing for iOS.  We may also need to request a cert from Apple.

**Comment by eseidel** [comment]
Our (needlessly internal) playbook on this: https://github.com/shorebirdtech/_shorebird/wiki/Shorebird-Release-Playbook#update-our-flutter-fork

**Comment by eseidel** [comment]
Flutter Beta:
Flutter: b7e7d46a046ba8a22897a514bf2311a0f81ab198
Engine: 98820f0a7716715df150f6adc5edd3444a088196
Dart: fe4b8016416d22afe75d8225f0c3f753b089c0b1
BuildRoot: 0141e94b34cbd3db77f28796587334857fa985da

**Comment by eseidel** [comment]
Cutler agrees:
```
 dart run bin/cutler.dart  versions --repo=flutter b7e7d46a046ba8a22897a514bf2311a0f81ab198
Using /Users/eseidel/Documents/GitHub as checkouts root.
✓ Checkouts updated! (6.7s)
Flutter b7e7d46a046ba8a22897a514bf2311a0f81ab198:
  flutter   b7e7d46a046ba8a22897a514bf2311a0f81ab198 (3.19.0-0.4.pre)
  engine    98820f0a7716715df150f6adc5edd3444a088196 (3.19.0-0.4.pre)
  dart      fe4b8016416d22afe75d8225f0c3f753b089c0b1 (3.3.0-279.3.beta)
  buildroot 0141e94b34cbd3db77f28796587334857fa985da
```

**Comment by eseidel** [comment]
Smoke test notes:

- [x] e2e tests (https://github.com/shorebirdtech/shorebird/actions/runs/7851915851)
- [ ] engine tests (https://github.com/shorebirdtech/_build_engine/actions/runs/7851898873). Missing Xvfb on the machine.  Presumably we should make our machines run the install_linux.sh as part of CI.
- [ ] flutter create + shorebird init works

- [x] iOS release
- [x] iOS patch
- [x] iOS preview

- [x] `shorebird doctor`
    - [ ] Win
    - [ ] Mac

- [x] Android release
    - [ ] Win
    - [x] Mac
- [x] Android patch
    - [ ] Win
    - [x] Mac
- [x] Android preview
    - [ ] Win
    - [x] Mac

- [x] iOS Add to App release
- [x] iOS Add to App patch

- [x] Android Add to App release
    - [ ] Win
    - [x] Mac
- [x] Android Add to App patch
    - [ ] Win
    - [x] Mac

- [x] iOS Flavors release
- [x] iOS Flavors patch
- [x] iOS Flavors preview

- [x] Android Flavors release
    - [ ] Win
    - [ ] Mac
- [x] Android Flavors patch
    - [ ] Win
    - [ ] Mac
- [x] Android Flavors preview
    - [ ] Win
    - [ ] Mac

**Comment by eseidel** [comment]
We decided to release this as a flutter-only release (no `shorebird` change) for now to avoid encouraging all of our customers to switch to the beta channel, only to have to switch back to stable again soon.

**Comment by felangel** [comment]
See https://github.com/shorebirdtech/shorebird/issues/1698#issuecomment-1939283669 for more info.

**Comment by eseidel** [comment]
```
Flutter 3.19.0:
  flutter   bae5e49bc2a867403c43b2aae2de8f8c33b037e4 (3.19.0)
  engine    04817c99c9fd4956f27505204f7e344335810aed (3.19.0)
  dart      25b3f65bf6264df5bd7cd6aca25cb68d47b9348b
  buildroot 0141e94b34cbd3db77f28796587334857fa985da
  ```

**Comment by eseidel** [comment]
Building engine: https://github.com/shorebirdtech/_build_engine/actions/runs/7921108381

**Comment by eseidel** [comment]
```
dart run bin/cutler.dart validate 3.19.0
Using /Users/eseidel/Documents/GitHub as checkouts root.
✓ Checkouts updated! (16.6s)
Validating 3.19.0
✅ flutter    refs/tags/3.19.0 matches upstream bae5e49bc2a867403c43b2aae2de8f8c33b037e4 (refs/tags/3.19.0)
✅ engine     refs/tags/3.19.0 matches upstream 04817c99c9fd4956f27505204f7e344335810aed (refs/tags/3.19.0)
✅ buildroot  correctly branched
✅ dart       correctly branched
✅ engine     correctly branched
✅ flutter    correctly branched
```
