### ISSUE TITLE
Invalid trust settings.

### ISSUE THREAD

**Issue by JgomesAT** [shorebirdtech/shorebird#1732]
After run  shorebird release ios

I have this error 

Failed to build (128.1s)
    Invalid trust settings.

I don't know way, android work fine

**Comment by eseidel** [comment]
Can you run with `-v`, e.g. `shorebird release ios -v`?  I've not seen this error before.  The internet seems to think it has something to do with keychain and certs: https://www.google.com/search?q=invalid+trust+settings

**Comment by JgomesAT** [comment]
Attach de pub.log
[pub_log.txt](https://github.com/shorebirdtech/shorebird/files/14330094/pub_log.txt)

**Comment by JgomesAT** [comment]
I found the problem, the certificate of apple wasn't  correct, the certificate was in trust mode and needed to be in the System's Default

**Comment by JgomesAT** [comment]
Thanks for all
