### ISSUE TITLE
fix: allow Android release to use subset of available target platforms

### ISSUE THREAD

**Issue by alongjiang903** [shorebirdtech/shorebird#1734]
App ID: (677bc1de-6248-478a-8f0b-d4806151157f)

**Description**

Exception when specifying the --target-platform  android-arm,android-arm64  parameter

**Steps To Reproduce**

1. shorebird release android --artifact apk -- --target-platform android-arm,android-arm64 --dart-define=proxy=true
2. Display result：Platform: android (arm64, arm32, x86_64)
3. Would you like to continue? (y/N) Yes
4. PathNotFoundException: Cannot open file, path = '/Users/xxx/xxx/release/out/lib/x86_64/libapp.so' (OS Error: No such file or directory, errno = 2)

**Expected Behavior**

1. input --target-platform android-arm,android-arm64 output arm64,arm32
2. no error

**Screenshots**

<img width="2773" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/136373873/992db592-ed10-416a-be52-8ffd7ed2d90c">

**Additional Context**

none

**Comment by eseidel** [comment]
It looks like our code needs to detect that the user provided --target-platform and tell the rest of our code not to look for archs that the user didn't provide.

@alongjiang903 in terms of getting past this, you can for now just remove the --target-platform argument and it should succeed.  The aab/apk will include one extra arch for now.

**Comment by alongjiang903** [comment]
But my application doesn't need the x86_64 platform, and it's fine if you don't specify --target-platform

**Comment by alongjiang903** [comment]
Support x86_64, the package volume is larger, my application has removed x86_64 before, not a new application @eseidel

**Comment by eseidel** [comment]
This is where the bug is.  We are using a hard-coded list of target rather than respecting the user's limited set.  But there might be other parts of our code which make the assumption that the app always has all 3 archs:
https://github.com/shorebirdtech/shorebird/blob/f1b897d4ff0e11b8afc297ab70711d800da253eb/packages/shorebird_cli/lib/src/code_push_client_wrapper.dart#L372

I believe it's possible to remove x86_64 from the resulting .aab after the fact with bundletool.

**Comment by alongjiang903** [comment]
<img width="1162" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/136373873/3ad70472-c7d0-407e-9316-c40ae38a8047">
I thought you were following Flutter command line, this bug, will you fix it later? I like your product @eseidel

**Comment by eseidel** [comment]
Correct, it can take any argument. However other parts of our code then assume things about the built product.  In this case, our uploading code is trying to upload each of the libapp.so files for each of the expected architectures and failing when it doesn't find an x64 one.

**Comment by alongjiang903** [comment]
Fix it. Let me know. I'll close this issues. Thank you.

**Comment by eseidel** [comment]
Thanks.  We'll plan to keep this open to track us fixing it.

**Comment by bryanoltman** [comment]
Updated the title to reflect the substance of the issue

**Comment by aga23a** [comment]
> 1. shorebird release android --artifact apk -- --target-platform android-arm,android-arm64 --dart-define=proxy=true

![image](https://github.com/shorebirdtech/shorebird/assets/162312124/a0ea8314-d170-4b1e-a5e9-5bbdbcc55405)

**Comment by bryanoltman** [comment]
@aga23a this is expected given the open state of the issue

**Comment by aga23a** [comment]
> @aga23a this is expected given the open state of the issue

When will this issue be resolved?

**Comment by eseidel** [comment]
Thanks for your patience.  Bryan resolved this today and the fix will go out in our next release (probably early next week).
