### ISSUE TITLE
fix: --dart-define modifier doesn't seem to work when creating IOS releases.

### ISSUE THREAD

**Issue by MonkeyDoDev** [shorebirdtech/shorebird#1744]
App ID: 130984c0-a89c-44a0-972b-f29f9725b216

**Description**

In my app, i pass an API key as part of the build instruction. However, after creating a release with shorebird, when i run shorebird preview on my IOS device i get an error indicating the API key isn't recognised. 

This is not a problem for Android

shorebird release android '--' --dart-define=[apiKey]=[key] - WORKS
shorebird release ios '--' --dart-define=[apiKey]=[key] - DOESN'T WORK

I tried creating a release 3 times just to be sure, and every time the api key wasn't working (btw i tried both '--' and -- with the same result).

Not this is NOT a problem when i create a regular build. It is only when i create a release with shorebird.

**Steps To Reproduce**

1. I created an IOS release with shorebird release ios '--' --dart-define=[apiKey]=[key]
2. i run 'shorebird preview ios'

**Expected Behaviour**

The fully functional app to run on account of the API key being correctly implemented

**Comment by bryanoltman** [comment]
I was unable to reproduce this. I created a test project – can you download it and try to reproduce? https://github.com/bryanoltman/dart_define_test

**Comment by eseidel** [comment]
There were changes in 3.19.0 relating to dart defines on iOS which could be related here: https://github.com/flutter/flutter/issues/138793. (The change the author is referencing isn't *directly* related to this reported issue, but suggests there were changes in the handling of dart defines which could result in other related issues.)

**Comment by MonkeyDoDev** [comment]
Hi Bryan,

I got the following error when creating the release 

***@***.*** dart_define_test % shorebird release ios -- --dart-define=MY_VAR=HELLO
✓ Fetching apps (0.2s)
✗ Failed to build (71.6s)
    Failed Registering Bundle Identifier
    No profiles for 'dev.shorebird.ios-test' were found

Is this because I need to register the app bundle id with my apple developer account or something?

**Comment by bryanoltman** [comment]
Yes, you'll need to update the project to be runnable on your device by choosing a bundle ID you control and an appropriate provisioning profile/cert in Xcode

**Comment by bryanoltman** [comment]
(I would change the bundle ID to one you already own rather than going through the trouble of setting up a new one)

**Comment by MonkeyDoDev** [comment]
Hi Bryan, 

It worked fine from my computer so I tried again with my actual project

Firstly I tried...

flutter run --dart-define=tmdbKey={my api key}

This worked fine… 

Then I tried...

shorebird release ios -- --dart-define={my api key}

This failed exactly as it did the other 3 times… 

I don’t know if it helps but my exact error I get is attached. I thought I’d share it because it’s a dio exception and I know dio has been a naughty package recently.


. ￼

**Comment by bryanoltman** [comment]
I think the attachment might've failed?

**Comment by MonkeyDoDev** [comment]
Must be apple mails infuriating tendency to display images in the email body. 

How about the attached zip?


￼

**Comment by bryanoltman** [comment]
Nope :) Maybe try a Dropbox/Drive link?

**Comment by MonkeyDoDev** [comment]
I swear to god technology has regressed these past 20 years! 

I’ve just tried sending to your GitHub email address from my actual IOS device so hopefully that works. Let me know if not and I’ll work out how to share something on google drive.

**Comment by bryanoltman** [comment]
Alright, got it. It's tough to say what that error might be – I don't think it's shorebird-related, but it's surprising that you'd be getting a 401 with shorebird and not stock flutter. Can you print the actual request that's going out to the console and see if/how that differs between the two builds?

**Comment by bryanoltman** [comment]
For reference, the error:

![IMG_0049](https://github.com/shorebirdtech/shorebird/assets/581764/7fe07d0d-d5a6-4b07-8994-ce5ecb28df33)

**Comment by MonkeyDoDev** [comment]
Hi Bryan,

Apologies for the late response. I had to pick my daughter up from nursery. 

Im afraid I don't know how to print statements to the console when shorebird is previewing. However, I can confirm that the error screen is the exact screen I get in debug mode if I choose not to pass the API key when I run it. 

I have just generated a normal IOS release build without shorebird and submit it to TestFlight and can confirm that the app opened fine and the apiKey was working properly so at this stage I can confirm that nothing is breaking in the vanilla build process. 

The problem literally only occurs when I’m generating and then previewing a release with shorebird , and this happens on IOS only, so I can’t see how this can be anything other than shorebird-related. Or to put it another way… if it’s not shorebirds fault… it’s at the least shorebirds problem! ;) 

Would it help if I added you as a collaborator again on my repo and gave you the apiKey to try yourself? 

Kind regards
Alex

**Comment by bryanoltman** [comment]
Agreed that this is something we should investigate and fix. I'm happy to try your codebase by myself if I can get it configured and running in a reasonable time as well.

Re: printing to the console, any `print` statements will show up in the console output of `shorebird preview`.

**Comment by MonkeyDoDev** [comment]
Hi Bryan,

Ahh I was using Logger statements hence nothing in the console. I can see print statements do work. 

To avoid wasting any more of your time than necessary I’ll do abit of investigation on my end with the print statements to see if I can get to the bottom of it. I’ll get back you when I either have an answer or am at a loss ;) 

Kind regards
Alex

**Comment by bryanoltman** [comment]
Let me know what you find. Happy to help in any way I can!

**Comment by MonkeyDoDev** [comment]
Hi Bryan,

Did you change anything that might have fixed this?

I was having issues updating my IOS release (for which I’ve logged another bug #1746) and so ended up updating my build number and creating a new release. 

This time it WORKED!!! 

I’m pretty sure I didn’t change anything in my build that would have fixed this so I’m wondering if you changes something on the back end? Either that or perhaps what I was doing uploading new releases with the same build number (see bug #1746) was part of the problem.

Anyway - Thats the good news… The bad news is that I experience random crashes when running IOS in preview. 

I have attached a couple of .ips logs from 2 separate sessions where the app crashed… 

Im starting to wonder if shorebird requires a certain minimum level of professionalism in the code to reliably work! Perhaps my app is just too riddled with weirdness! 



￼￼

**Comment by bryanoltman** [comment]
It looks like the mail attachment didn't work again :(

**Comment by bryanoltman** [comment]
> Im starting to wonder if shorebird requires a certain minimum level of professionalism in the code to reliably work! 

It definitely should work anywhere Flutter works, and we're working to make sure that's the case. Bug reports like this are how we get there and are much appreciated 😄

**Comment by bryanoltman** [comment]
Thanks for sending those. Attached them below.

[MonkeyDoDevIps.zip](https://github.com/shorebirdtech/shorebird/files/14377391/MonkeyDoDevIps.zip)

**Comment by bryanoltman** [comment]
For reference, this is for release `1.1.56 (74)` (release id 34216) of app `130984c0-a89c-44a0-972b-f29f9725b216`

**Comment by bryanoltman** [comment]
@MonkeyDoDev it looks like this release was created with Flutter 3.16.9, where this crash is expected. If you upgrade to flutter 3.19.0, this should be resolved.

Edit for more detail:

If you're using the latest version of shorebird (0.26.0), it's possible that previous uses of `shorebird flutter versions use` have stuck you on an old version. You can check this by running `git -C $HOME/.shorebird status` (which should say `flutter.version` has been modified if this is the case) and repair by running `git -C $HOME/.shorebird reset --hard`.

**Comment by MonkeyDoDev** [comment]
Hi Bryan,

Thats odd. I created that build just a couple of hours ago and i'm definitely on Flutter 3.19.0 which ive just confirmed by running Flutter Upgrade and getting the below message. You can see the .ipa files are dated with todays date so I’ve not accidentally sent old crash files… 

Anyhoo I’ve just updated to version 3.19.1 and will try another release tomorrow. 

P.S - I often get that ‘your flutter checkout has local changes’ message and just use ‘—force’ to dismiss it. I have no idea what causes it but am certain ive done no intentional edits to the flutter source files. Whenever I get something weird like that my policy is to blame Xcode because I just have no idea what it’s doing all the time. ;0) - Anyway, im signing off for the evening so have a good day

```
***@***.*** buck_the_critics % flutter upgrade
Your flutter checkout has local changes that would be erased by upgrading. If you want to keep these changes, it is recommended that you stash them via "git stash" or else commit the
changes to a local branch. If it is okay to remove local changes, then re-run this command with "--force".
***@***.*** buck_the_critics % flutter upgrade --force
Upgrading Flutter to 3.19.1 from 3.19.0 in /Users/monkeydev/FlutterDev/flutter...
Building flutter tool...
Resolving dependencies...
Got dependencies.

Upgrading engine...

Flutter 3.19.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision abb292a07e (2 days ago) • 2024-02-20 14:35:05 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
***@***.*** buck_the_critics % 
```

**Comment by bryanoltman** [comment]
Shorebird uses a different Flutter checkout than what is on your path (we have modified the engine to make code push possible). You can see what version shorebird using with `shorebird doctor`. An up-to-date shorebird installation will print

```
Shorebird 0.26.0 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.19.0 • revision 8679396700d040e779463461c7c79ba08d130209
Engine • revision 62fa4e8bb30f56eb658989d3e6a982cb787d79d6
```

**Comment by bryanoltman** [comment]
(To be clear, this confusion is absolutely our fault. The `shorebird flutter versions use` command was a bit of a footgun and is now deprecated because it was leading to this exact kind of situation (regardless of how the user's level of professionalism 😉))

**Comment by MonkeyDoDev** [comment]
Lolz! 

Never mind. I’m happy to report all my problems are solved having updated shorebird and republished with a new build version so I’m a happy sausage

Thanks for your support

**Comment by bryanoltman** [comment]
Great to hear! Don't hesitate to reach out if you run into any other issues, and thanks for your patience
