### ISSUE TITLE
Build does not update if you delete a release and then upload new one with same version number

### ISSUE THREAD

**Issue by MonkeyDoDev** [shorebirdtech/shorebird#1746]
App ID: 130984c0-a89c-44a0-972b-f29f9725b216

**Description**

I have a shorebird release for android with version number 1.1.55+73 which is good for use. So far, so good. 

However, i am having some platform specific difficulty with my IOS version of that release. Because i want my Android and IOS build numbers to be consistent, my working flow whilst fixing/investigating my IOS issues is to 

1. delete the IOS build from that release (which i want to keep because the android version works)
2. create a fixed IOS build with the same version/release number

However, when i do this.. the edits to the IOS build in subsequent submissions are NOT reflected when i run previews.

For example, i added some print logs to help me debug, but when i run preview after i released those changes, i was still seeing the OLD print logs when i run preview. 

So it's as if the old original build i thought i had deleted is actually retained and never overwritten

**Steps To Reproduce**

1. Create a release on both Android and IOS
2. From the shorebird console, delete the IOS version of that release
3. Change some code and create a NEW IOS release with the same version number 

**Expected Behavior**

I would expect the code changes to be reflected when i run preview

**Comment by eseidel** [comment]
Apologies for not replying sooner.  I think the real fix here is https://github.com/shorebirdtech/shorebird/issues/1762?  Let me know if I've misunderstood.

**Comment by eseidel** [comment]
It also occurs to me that if someone has ever made a patch to that release and uploads with a different version of Flutter that would be away to run into https://github.com/shorebirdtech/shorebird/issues/1894.  I guess if we're deleting all patches attached to a release when deleting that won't happen.
