### ISSUE TITLE
add shorebird cache clear command

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#175]
As a developer, I want to be able to clear all cached data used by the shorebird cli so that I can free up space especially if I've accumulated lots of older shorebird engine revisions that aren't being used.

**Comment by eseidel** [comment]
Where is the cache so that someone else might be able to fix this?

**Comment by felangel** [comment]
> Where is the cache so that someone else might be able to fix this?

It's using `applicationConfigHome` which on MacOS is `/Library/Application Support/shorebird`

https://github.com/shorebirdtech/shorebird/blob/0430b2119b2fd764a6c3e5809b9a430fa85d105f/packages/shorebird_cli/lib/src/config/shorebird_config_dir.dart#L5

**Comment by infm5** [comment]
Hey Guys, I'd like to contribute however I have a question:
How are we supposed to carry out this action (clearing Cache) are we planning on to add a command for this purpose? It'd be great if I could get a bit more description.
Thanks
