### ISSUE TITLE
feat: add `--export-options-plist` to `patch ios` command

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1754]
**Description**

The `release ios` command accepts `--export-options-plist` as an option, but the `patch ios` command does not. Although the artifact produced by the patch command is never intended to be "exported", this missing field has caused confusion and has made it difficult for users to build their ios patches.

This is not believed to be a blocker, as `shorebird patch ios -- --export-options-plist=path/to/my.plist` should properly forward the value to the underlying flutter build command.

**Requirements**

Add support for `--export-options-plist`. The value, if provided, should just be passed through to the `buildIpa` function.

**Comment by bryanoltman** [comment]
Added a workaround to the issue description

**Comment by Dario-Maselli** [comment]
Hey @bryanoltman - This may be a blocker for us as I am still struggling to get a patch to work... 

So, the only line that was changed in this patch was:
![GitChange](https://github.com/shorebirdtech/shorebird/assets/117168592/1ad37d15-bd0e-4d51-873a-e99f14cf9ca6)

The Patch Command:
`shorebird patch ios -- --export-options-plist=/Users/builder/export_options.plist --target ./lib/main_staging.dart --flavor staging`

The Console Error:
`[WARN] Your app contains native changes, which cannot be applied with a patch.
    Changed files:
        Products/Applications/Runner.app/Runner`

Edited: I just noticed that the Android patch also outputs this:
`[WARN] Your app contains native changes, which cannot be applied with a patch.
    Changed files:
        base/dex/classes.dex`
        
 Is there something I am missing?

**Comment by bryanoltman** [comment]
This seems unrelated to export options.

It sounds like you may have a dependency that does not produce a stable binary between builds. We've seen this before (I think it was NewRelic?), where the artifact produced by the build included a timestamp for some reason. You can test this theory by running the patch command on the same codebase on which you ran the release command. 

Another line of inquiry: are you tracking your `pubspec.lock` (i.e., is it checked in to git?) If not, it's possible that a dependency containing native code was updated between release and patch.

**Comment by Dario-Maselli** [comment]
@bryanoltman - You are correct, I just ran a patch on the release commit and it showed the same warning/issue.

Our pubspec.lock is tracked but set to update minor version i.e. ^1.0.0

Is there a way to determine what the package is that is causing the timestamps/randomized code or should I lock all pubspec.yaml versions?

Would you like me to create a separate issue and continue there? We are wanting to deploy to production within the next few weeks and need this tested thoroughly on our staging environment. 🙈

**Comment by bryanoltman** [comment]
> Our pubspec.lock is tracked but set to update minor version i.e. ^1.0.0

The pubspec.**lock** should have specific versions (the pubspec.**yaml** specifies version constraints). The pubspec.yaml version constraints are great as long as the package publishers strictly adhere to semver, but… they don't always 🙃 

Can you create a new release and try immediately patching that? That would help to isolate whether the issue is due to an updated dependency or if you have a dependency whose builds aren't stable. 

A new issue sounds like a good idea. We don't have a huge amount of visibility into *what* changed in the binary, but it's possible we might be able to extract version numbers from the frameworks bundled with the apps, which could point in a useful direction
