### ISSUE TITLE
fix: Segmentation fault while installing Shorebird CLI

### ISSUE THREAD

**Issue by rizkiii1540** [shorebirdtech/shorebird#1759]
**Description**
I'm trying to install Shorebird CLI on my Mac. But I get segmentation fault on shared.sh

**Steps To Reproduce**
1. Install Shorebird CLI via terminal
2. See error

**Expected Behavior**
Segmentation fault error occured

**Screenshots**
<img width="1680" alt="Screenshot 2024-02-28 at 04 51 56" src="https://github.com/shorebirdtech/shorebird/assets/35168359/21c35d43-b8e2-4779-9072-fd849f5569ee">

**Additional Context**
- Using sudo and non sudo create the same error.
- Restarting my device doesn't affect anything
- Using Macbook Pro M2, Sonoma 14.3.1, Dart 3.3.0, Flutter 3.19.1

**Comment by eseidel** [comment]
That's very surprising.  I wonder if this could be related to the `git` version on your path.  Are you able to share the output of: `git --version`? e.g.
```
% git --version
git version 2.39.3 (Apple Git-145)
```

**Comment by eseidel** [comment]
I would not recommend using `sudo`.  `sudo` is not required for Shorebird.

**Comment by eseidel** [comment]
You also might want to try removing the `.shorebird` directory in your $HOME folder, to remove any remnants of a past failed installation.

**Comment by rizkiii1540** [comment]
> That's very surprising. I wonder if this could be related to the `git` version on your path. Are you able to share the output of: `git --version`? e.g.
> 
> ```
> % git --version
> git version 2.39.3 (Apple Git-145)
> ```

Same as mine
<img width="398" alt="Screenshot 2024-02-29 at 03 37 15" src="https://github.com/shorebirdtech/shorebird/assets/35168359/af2017d2-2780-4067-aa37-9cc2098e5a84">

> You also might want to try removing the `.shorebird` directory in your $HOME folder, to remove any remnants of a past failed installation.

I've already done that because --force doesn't work. Maybe there is problem with my flutter instalation?

**Comment by eseidel** [comment]
It's hard for me to tell from that log, what exactly is segmentation faulting.  You might be able to see a crash log in Console.app that could tell you.  I can't tell if `git` is crashing or `bash` is crashing for example.

**Comment by rizkiii1540** [comment]
Nevermind. I've found the issue and temporary fix.

My Macbook has [flock](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/flock.2.html) enabled. Flock was failing to acquire the lock, so I just remove the line where it check for flock check.

1. Forked this repo and [install](https://github.com/shorebirdtech/install) repo
2. On forked shorebird repo, at <FLUTTER_ROOT>/bin/internal/shared.sh, there is a function __lock from line 44 to 52.
<img width="759" alt="Screenshot 2024-02-29 at 04 03 30" src="https://github.com/shorebirdtech/shorebird/assets/35168359/0cba84a0-2911-49ce-b88f-933496c65a76">

I remove the line from 45 to 46 so it became like this
<img width="759" alt="Screenshot 2024-02-29 at 04 48 17" src="https://github.com/shorebirdtech/shorebird/assets/35168359/fd9d93cd-8b68-481f-b7ee-3487d4d38a40">

3. On forked install repo. Change the shorebird url to my forked shorebird with updated shared.sh
4. Install as usual but with different url
5. But then it will fails again. Because shorebird trying to pull Flutter from github with flock enabled script
6. Do line 2 but on /Users/{username}/.shorebird/bin/cache/flutter/{FLUTTER_CACHE_VERSION}/bin/internal/shared.sh
7. cd into /Users/{username}/.shorebird/bin and run **./shorebird**
8. add shorebird bin directory to .zshrc and source it
9. Shorebird installed!!
<img width="882" alt="Screenshot 2024-02-29 at 05 00 40" src="https://github.com/shorebirdtech/shorebird/assets/35168359/f0847a3c-b7bd-4b5b-a4b6-70fbf0518f93">

I know it was temporary fix, but at least it installed

**Comment by rizkiii1540** [comment]
Aw. Ma bad. My Macbook doesn't have flock installed. Just install flock with **brew install flock** and install shorebird as usual. It runs perfectly fine. No need to change anything

**Comment by eseidel** [comment]
Very strange, but glad you got past it.  Thanks for the update!
