### ISSUE TITLE
feat: How to use shorebird cli whice upload release ipa to testflight by fastlane

### ISSUE THREAD

**Issue by moweiran** [shorebirdtech/shorebird#1765]
I upload release ipa to testflight by fastlane.

If i use shorebird, how can i run the cmd?

There is my fastlane code before use shorebird.
```ruby
lane :releaseDev do
    Dir.chdir "../.." do
      sh("flutter build ios --release --no-codesign --flavor dev --dart-define=env=dev")
      # sh("shorebird release ios-alpha -f --no-codesign --flavor dev -- --dart-define=env=dev")
    end
    match(
      type: "appstore",
      username: "li@hummingbirdstudio.live",
      app_identifier: "live.astrostar.dev",
    )
    gym(
      scheme: "dev",
      export_method: "app-store",
      clean: true,
      output_name: "AstroStar Dev.ipa"
    )
    uploadToTestflightDev()
  end
```

**Comment by bryanoltman** [comment]
Does this not work? If not, what is the error you're seeing?

We haven't tried using fastlane, but this looks like it should work (although `ios-alpha` has been deprecated and you can just use `ios` now). `shorebird release ios` runs `flutter build ipa --release` under the hood and generates all of the same artifacts in the same places as `flutter build`, so I would expect that it would not matter to the `match` and `gym` steps that the release artifacts were built with Shorebird.

**Comment by bryanoltman** [comment]
Going to close for now due to lack of response. We'd love to add a fastlane guide to our site, but as far as I know, the fastlane configuration you have should work.
