### ISSUE TITLE
fix: Sign in with Apple by firebase_auth not working after shorebird release

### ISSUE THREAD

**Issue by moweiran** [shorebirdtech/shorebird#1769]
App ID: d5055e67-c13a-4453-8d84-e51d9a345fa9

**Description**

My app use the firebase_auth to sign in by apple, but it's not working after i shorebird release.
```
shorebird release ios-alpha -f --no-codesign --flavor dev -- --dart-define=env=dev
```

**Additional Context**

```
Shorebird 0.26.0 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.19.0 • revision 8679396700d040e779463461c7c79ba08d130209
Engine • revision 62fa4e8bb30f56eb658989d3e6a982cb787d79d6
```

**Comment by bryanoltman** [comment]
Can you share more information? When you say "not working", how exactly is it failing? Are you seeing an error message? What method are you using to run the app on your device?

**Comment by bryanoltman** [comment]
Also, I don't think this should be related, but you're using a slightly old version of shorebird. Run `shorebird upgrade` to update.

**Comment by moweiran** [comment]
> Also, I don't think this should be related, but you're using a slightly old version of shorebird. Run `shorebird upgrade` to update.

Normally, It's will popup a dialog to autherize the identity, but now there is no any response(No dialog popup).

**Comment by bryanoltman** [comment]
What about the other questions?

1. Is there any error output in your logs?
2. What method are you using to run the app on your device?
3. Can you tell where things are going wrong (I'd expect to see an error message in the app's logs)

**Comment by moweiran** [comment]
> What about the other questions?
> 
> 1. Is there any error output in your logs?
> 2. What method are you using to run the app on your device?
> 3. Can you tell where things are going wrong (I'd expect to see an error message in the app's logs)

1. Because it's test in testflight, and no logs received. so i don't know what happend.
2. The authorize plugin
```
firebase_core: ^2.25.5
firebase_auth: ^4.17.6
```
My sign in method
```
Future<UserCredential> signInWithApple() async {
    final appleProvider = AppleAuthProvider();
    appleProvider.addScope('email');
    appleProvider.addScope('fullName');

    final userCred =
        await FirebaseAuth.instance.signInWithProvider(appleProvider);
    return userCred;
  }
```

**Comment by bryanoltman** [comment]
Unfortunately that's not a lot to go off of. You can run the release locally using `shorebird preview`. I'd be interested to see what logs that shows.

**Comment by bryanoltman** [comment]
Closing this due to lack of response. Please reopen when you can provide more details that we can use to track this down.

**Comment by eseidel** [comment]
We'd love to help!  We just would need to know more.  We're also reachable via discord 16 hours a day: https://discord.gg/shorebird. Thanks!
