### ISSUE TITLE
fix: app still applies patches automatically when shorebird.yaml contains `auto_update: false`

### ISSUE THREAD

**Issue by aga23a** [shorebirdtech/shorebird#1774]
I have changed shorebird.yaml set auto_update: false, but when verified in preview mode, it will still update automatically.

Environment：

Mac

Shorebird 0.26.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.10.1 • revision 7cd77f78a51576652edc337817152abf4217a257
Engine • revision 13201c941a044e30b59cbb2c8f87c1033ffce661

**Comment by bryanoltman** [comment]
I'm not able to reproduce this. Can you share your `shorebird.yaml` and the steps you took?

**Comment by bryanoltman** [comment]
Closing due to lack of response. Please reopen with reproduction steps and we'll be happy to help!

**Comment by aga23a** [comment]
yes. this is my shorebird.yaml 

```
# This file is used to configure the Shorebird updater used by your app.
# Learn more at https://docs.shorebird.dev
# This file should be checked into version control.

# This is the unique identifier assigned to your app.
# Your app_id is not a secret and is just used to identify your app
# when requesting patches from Shorebird's servers.
app_id: 430acace-56b1-49f7-b559-83dd4f14e766

# auto_update controls if Shorebird should automatically update in the background on launch.
# If auto_update: false, you will need to use package:shorebird_code_push to trigger updates.
# https://pub.dev/packages/shorebird_code_push
# Uncomment the following line to disable automatic updates.
auto_update: false

```

**Comment by bryanoltman** [comment]
That looks right. Did you add `auto_update: false` before or after you released?

**Comment by aga23a** [comment]
> That looks right. Did you add `auto_update: false` before or after you released?

no. I seem to have found the reason.
I modified the flutter version to 3.13.9 to solve this problem.

**Comment by AhmadIzaz** [comment]
I am still facing this issue. I have uncommented and then made the release and when I copy the .yaml file from console. the auto update is commented there. 


Shorebird 1.0.5 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.19.6 • revision 4b22a31bd9911c8317319292a9a103217919649e
Engine • revision ef2c5cd963e481d44741e2a587ecb7ad69629ce1

I have tried creating the shorebird init with force as well and even though I have tried installing the shorebird from the scratch with the curl command and force as well. Below are the command

`curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash -s -- --force`


Then I have also used the code push package also for manual handling. Even though I have the patch on console. When I use that package it returns me false in the answer of isNewPatchAvailableForDownload() but when I do shorebird preview and then it build and shows me the correct changes of the patch on the app and now If I run again this function isNewPatchAvailableForDownload, now it will return me this 

```
05-08 17:55:01.969  1258  2236 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "2acbd986-969a-43d3-ae06-1561e3fedf7d", channel: "stable", release_version: "3.0.99+509", patch_number: None, platform: "android", arch: "aarch64" }

05-08 17:55:02.333  1258  2237 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "2acbd986-969a-43d3-ae06-1561e3fedf7d", channel: "stable", release_version: "3.0.99+509", patch_number: None, platform: "android", arch: "aarch64" }

05-08 17:55:03.455  1258  2237 I flutter : updater::updater: Patch 1 successfully installed.

05-08 17:55:03.460  1258  2237 I flutter : updater::c_api: Update result: Update installed
```

But if I do it before preview command it will show me nothing.
One more thing is, on running the shorebird preview command I get this in logs 

```
05-08 17:50:41.610  1258  1258 I flutter : updater::cache::updater_state: No existing state file found: File /data/user/0/company/files/shorebird_updater/state.json does not exist, creating new state.

05-08 17:50:41.612  1258  1258 I flutter : [INFO:shorebird.cc(173)] Shorebird updater: no active patch.

05-08 17:50:41.613  1258  1258 I flutter : [INFO:shorebird.cc(180)] Shorebird auto_update disabled, not checking for updates.
```

Which from my understanding shows that auto_update is disabled which is true. In shorebird.yaml it is uncommented but then why when I download from shorebird console it shows me auto update is commented. 
I dont know how to explain the situation but it is behaving very weird.

**Comment by eseidel** [comment]
@AhmadIzaz moved to https://github.com/shorebirdtech/shorebird/issues/2045
