### ISSUE TITLE
fix: Patch Fails Immediately After Release (No Code Change)

### ISSUE THREAD

**Issue by Dario-Maselli** [shorebirdtech/shorebird#1778]
App ID: 6989e316-6c49-4d27-bc1f-b0c56d92f17e

**Description**

Using the same code base, in our CodeMagic workflow, I did a release and then a patch on the same commit but it failed with 
`Note: path is pinned to version 1.9.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.` because it is using a higher flutter version (I think).

**Steps To Reproduce**

1. Create codemagic.yaml workflow for releasing and patching
2. Run Release Workflow (Successful)
3. Run Patch Workflow (Failure)

**Expected Behavior**

I expected it to not have any issue as there is nothing different in the code (The packages are even locked off)

**Screenshots**

![Shorebird Error](https://github.com/shorebirdtech/shorebird/assets/117168592/51a8ecfc-9ba0-41e2-9798-22404a0106a9)

**Additional Context**
This was suggested in this issue: https://github.com/shorebirdtech/shorebird/issues/1754

Release command: 
`shorebird release ios --target ./lib/main_staging.dart --flavor staging --flutter-version 3.10.6 --export-options-plist=/Users/builder/export_options.plist`

`shorebird release android --target ./lib/main_staging.dart --flavor staging --flutter-version 3.10.6`

Patch Command:
`shorebird patch ios -- --export-options-plist=/Users/builder/export_options.plist --target ./lib/main_staging.dart --flavor staging`

`shorebird patch android --target ./lib/main_staging.dart --flavor staging`

**Comment by bryanoltman** [comment]
Fixed by https://github.com/shorebirdtech/shorebird/pull/1785
