### ISSUE TITLE
fix: applying iOS patches

### ISSUE THREAD

**Issue by lothemar** [shorebirdtech/shorebird#1781]
App ID: ac8941b6-38d3-459b-9b27-8c209b8bc222

**Description**

Disabled iOS patches still get applied

**Steps To Reproduce**

1. Deactivate patch
2. Install app
3. Restart app
4. Patch is applied

**Expected Behavior**

Patch shouldn't get applied

**Comment by bryanoltman** [comment]
Thanks for the report! Fix incoming.

**Comment by bryanoltman** [comment]
A fix for this has been deployed.

**Comment by eseidel** [comment]
Thank you very much for the report @lothemar!  (And than you for the quick fix @bryanoltman!)
