### ISSUE TITLE
fix: iOS patches broke our riverpod providers

### ISSUE THREAD

**Issue by lothemar** [shorebirdtech/shorebird#1782]
App ID: ac8941b6-38d3-459b-9b27-8c209b8bc222

**Description**

Applying shorebird patches breaks some of our AsyncValue providers on iOS only. App runs fine on first startup. On app restart(when shorebird applies the patch), providers fail.

**Steps To Reproduce**

1. Launch app
2. Restart app
3. Call provider
4. Provider fails to load data

**Expected Behavior**

Shorebird shouldn't affect providers

TBF, it might be unrelated to shorebird but disabled patches still get applied so can't isolate this ATM 100%

**Comment by bryanoltman** [comment]
I'm not sure we have enough information to help here. Can share sample code (ideally a small Flutter app) that reproduces the issue?

**Comment by lothemar** [comment]
This should get closed as I haven't been able to reproduce this. Will reopen if reproduced, otherwise no point in wasting time on this

**Comment by eseidel** [comment]
Thank you!  Let us know if you see it again and we're happy to help.
