### ISSUE TITLE
Patch builds fail if app cannot build with latest version of Flutter

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1784]
1. A user created a release with Flutter version A
2. Shorebird updated to Flutter version B
3. The user's app does not build with Flutter version A due to dependency version conflicts
4. User cannot patch their release because our patch commands build the app with Flutter version B to determine the release version, even if a release version is provided as an argument to the patch command.

See https://discord.com/channels/1030243211995791380/1215306109137584128/1216795988237222100 for context.

**Comment by mfurkanyuceal** [comment]
I'm still having the same problem. I can get a release with the same project code, but I cannot patch.
I guess that the flutter version in the patch process does not match the Flutter version of the application we released.
Shorebird 0.26.4
Flutter 3.16.9
<img width="715" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/22933926/4b08e9ad-8078-43b1-8748-e2bcc7c3c60f">
<img width="1295" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/22933926/be464944-e97c-4d7e-a129-24a7adea2963">

**Comment by bryanoltman** [comment]
@mfurkanyuceal You will need to provide a release version to the patch command (ex: `shorebird patch android --release-version=1.2.3+4`) for this to work. Shorebird builds the app with its version of Flutter to determine the release version, and providing a release version will skip this step and fix your issue.
