### ISSUE TITLE
feat: Support for Shorebird in Mainland China

### ISSUE THREAD

**Issue by iamdennisme** [shorebirdtech/shorebird#1788]
I've seen from other issues that shorebrid's service has already migrated from Google Storage to Google Cloud. However, the stability of Google Cloud in mainland China is still not high enough. Have you considered offering new mirror services or private deployments recently? Looking forward to your reply.

here are some related issues.
https://github.com/shorebirdtech/shorebird/issues/435
https://github.com/shorebirdtech/shorebird/issues/1423

**Comment by bryanoltman** [comment]
I believe this is a duplicate of https://github.com/shorebirdtech/shorebird/issues/435 and/or https://github.com/shorebirdtech/shorebird/issues/485. Closing in favor of those.
