### ISSUE TITLE
fix: `shorebird preview` fails for some phones

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1789]
```
 Exception: Unable to clear app data:
Exception occurred while executing 'clear':
java.lang.SecurityException: PID 11658 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package xxx.yyy
        at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:3890)
        at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:2321)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:268)
```

We've had this report a few times.

**Comment by eseidel** [comment]
The original design goal of adding this to `shorebird preview` was to reset the app back to a "fresh from store" state (no patches installed).  But it may not be possible to do that on some phones.

I guess one thing we could do is catch this error and explain it to the dev.

**Comment by acdrill** [comment]
Hi, I'm experiencing an error related to shorebird preview. I'm using Shorebird Preview on Pixel 4 API 30 (android-x86 emulator) from IntelliJ AVD Manager. The command downloads the app into the emulator, the app opens for a bit before it immediately crashes. May I ask if I'm missing something or is this a persistent issue?

This is the output in the terminal. 

✓ Fetching apps (1.0s)
Which app would you like to preview? moneyx_client (dev)
✓ Fetching releases (0.3s)
Which release would you like to preview? 2.4.0+2
✓ Using staging track (4.8s)
✓ Extracting metadata (1.4s)
✓ Building apks (18.4s)
✓ Installing apks (25.8s)
✓ Starting app (2.7s)
--------- beginning of main

--------- beginning of system

--------- beginning of crash

**Comment by eseidel** [comment]
> Hi, I'm experiencing an error related to shorebird preview. I'm using Shorebird Preview on Pixel 4 API 30 (android-x86 emulator) from IntelliJ AVD Manager. The command downloads the app into the emulator, the app opens for a bit before it immediately crashes. May I ask if I'm missing something or is this a persistent issue?

Sorry to hear that.  Unfortunately Flutter release builds (and thus Shorebird) do not work on x86: https://github.com/shorebirdtech/shorebird/issues/1173 https://github.com/shorebirdtech/shorebird/issues/1327

The underlying issue is that the Dart VM does not support AOT compilation on x86.  I recommend using an x64 or ARM emulator.

**Comment by bryanoltman** [comment]
This is a duplicate of https://github.com/shorebirdtech/shorebird/issues/1740, closing
