### ISSUE TITLE
feat: move to new linking pipeline

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1803]
We need to move to our new "sorted_pool" linker pipeline at the Shorebird CLI and Flutter CLI level.

Things to do:
1. Get a local engine build of Fluter using sorted_pool
2. Compare the changes we made to the sorted_pool branch for test.sh:

```
dart pkg/aot_tools/bin/aot_tools.dart link --base=$BEFORE.aot --patch=$AFTER.aot --analyze-snapshot $BUILD_DIR/analyze_snapshot --output $AFTER.vmcode
```
Is now replaced by:

```
# Analyze the base and patch snapshots and dump link data
# --no-pp-hash tells the SubgraphHasher to exclude the PP loads from the hash.
# The .link files are used for object pool ordering hints in an optimized patch snapshot.
$BUILD_DIR/analyze_snapshot --dump_link_data --no-pp-hash --out=$BEFORE.link $BEFORE.aot
$BUILD_DIR/analyze_snapshot --dump_link_data --no-pp-hash --out=$AFTER.link $AFTER.aot

# Re-generate the patch snapshot, now using the link data.
$BUILD_DIR/gen_snapshot --snapshot-kind=app-aot-elf --deterministic --dedup_instructions \
    --base_link_data=$BEFORE.link --patch_link_data=$AFTER.link --elf=${AFTER}_optimized.aot $AFTER.aot.dill

dart pkg/aot_tools/bin/aot_tools.dart link --base=$BEFORE.aot --patch=${AFTER}_optimized.aot --analyze-snapshot $BUILD_DIR/analyze_snapshot --output $AFTER.vmcode
```

This will require both changing `shorebird` to run some of these extra commands, as well as changing the backend bits of `flutter` (to support plumbing these additional options down to gen_snapshot.  We could teach gen_snapshot to read from the environment if easier?

**Comment by bryanoltman** [comment]
The first line (`$BUILD_DIR/analyze_snapshot --output $AFTER.vmcode`) seems wrong – should it just be removed?

**Comment by eseidel** [comment]
This is done!
