### ISSUE TITLE
fix: [WARN] SHOREBIRD_TOKEN needs to be updated before the next major release.

### ISSUE THREAD

**Issue by tyxinger** [shorebirdtech/shorebird#1808]
App ID: f8cf5095-6466-42bf-a2b8-3d17340c7d45

**Description**

When I run this on the Azure Pipeline I get a warning.
<img width="880" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/12806185/bcaa1618-a86b-422f-ab8e-94e9bf574803">
I tried to obtain the token through the `shorebird login:ci` again, but I still encountered the same warning.

**Steps To Reproduce**

I get this warning every time I run the `shorebird release` or `shorebird patch`.

**Expected Behavior**

So far, this warning has not had any bad impact on me. I just want to determine how I can eliminate it.

**At last**
I am a Chinese user, my english is shit, but I like your products very much, best wishes

**Comment by bryanoltman** [comment]
The log output explains what you need to do to fix: Run `shorebird login:ci` to obtain a new token for your CI pipeline, and use it for the `SHOREBIRD_TOKEN` environment variable.

**Comment by bryanoltman** [comment]
My mistaken, I missed that you had run `shorebird login:ci`. Did you update the `SHOREBIRD_TOKEN` variable in your CI?

**Comment by tyxinger** [comment]
> My mistaken, I missed that you had run `shorebird login:ci`. Did you update the `SHOREBIRD_TOKEN` variable in your CI?

yes, I have tried using new token, but I thought of a problem. The shorebird running on CI is the latest, which is inconsistent with the shorebird version I used to obtain the token locally. I will test whether this is the reason.

**Comment by bryanoltman** [comment]
Please let us know if you continue to experience this issue. Going to close the issue for now.

**Comment by rafaelfernandesx** [comment]
I'm having the same problem on codemagic, my installed version is the same as codemagic.
I'm using Microsoft authentication.

<img width="1394" alt="image" src="https://github.com/user-attachments/assets/ccb9a277-29f3-443c-9a68-390db3dd359e">

**Comment by bryanoltman** [comment]
It looks like you need to update your token in codemagic, as per the error message in the screenshot

**Comment by rafaelfernandesx** [comment]
I did this 3 times, but the error persists :(

> It looks like you need to update your token in codemagic, as per the error message in the screenshot

**Comment by bryanoltman** [comment]
Did you copy the new token to codemagic? Simply running `shorebird login:ci` isn't sufficient

**Comment by rafaelfernandesx** [comment]
> Did you copy the new token to codemagic? Simply running `shorebird login:ci` isn't sufficient

Yes, I generated the code using "shorebird login:ci" then I took it, encoded it in base64 and put it in the codemagic environment variables.
I did this a few times

**Comment by rafaelfernandesx** [comment]
I did some more tests now using --verbose and it returns this error:
<img width="1046" alt="image" src="https://github.com/user-attachments/assets/12c83c61-e9ec-4038-bab7-66f78108db1e">

Remembering that my authentication is with the Microsoft account, it seems that it is authenticating with Google, but I don't know if it is the same authentication.

this is the local and codemagic version of shorebird:
1.2.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.24.1 • revision 01eadfbfbbe78b64aed76ea9f422eb432fd339cb
Engine • revision 8978a5e50daa39aa1180d57c7ec991e787d7f545
