### ISSUE TITLE
fix: Build fails in Azure Pipeline

### ISSUE THREAD

**Issue by tyxinger** [shorebirdtech/shorebird#1809]
App ID: f8cf5095-6466-42bf-a2b8-3d17340c7d45

**Description**

I can't build release or patch in Azure Pipeline after the `--force` is canceled.
I have noticed `Note: the --force flag is not required for use in CI environments.`, But I still encounter obstacles when running in the pipeline, While running I encountered `Would you like to continue?` to confirm again, which caused me to run a timeout (over an hour) in the pipeline because I couldn't enter Y in CI.

**Steps To Reproduce**
1. Run `shorebird login:ci` on local machine
2. Use `export SHOREBIRD_TOKEN` set shorebird token in Azure Pipeline.
3. Run `shorebird release android --artifact apk --flutter-version 3.19.0` in Azure Pipeline.

**Expected Behavior**

Can be used normally in Azure pipeline.

**Comment by bryanoltman** [comment]
Working on a fix so you won't need to do this, but a workaround for now is to define `CI` as an environment variable for your pipeline.

**Comment by tyxinger** [comment]
> Working on a fix so you won't need to do this, but a workaround for now is to define `CI` as an environment variable for your pipeline.

How do I need to define this variable? Can you provide the bash command?

**Comment by bryanoltman** [comment]
We've made an update in our latest release that should fix the original issue without any changes on your side. Let us know if this problem persists for you.
