### ISSUE TITLE
feat: provide a way for devs to track progress of rollouts

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#181]
We don't currently provide any way for devs to track progress of a patch rollout.
* How many devices have downloaded the patch?
* How many have reported success?
* How many have reported failure?
etc.

**Comment by eseidel** [comment]
We will end up doing this as part of https://github.com/shorebirdtech/shorebird/issues/497. We get regular requests for such.

**Comment by eseidel** [comment]
We're starting to spec out what implementing progressive rollouts would look like.  We'd be very interested in your feedback if you have any.  See https://github.com/shorebirdtech/shorebird/issues/497 or ping us on Discord: https://discord.gg/shorebird to be involved.

**Comment by bryanoltman** [comment]
I believe this is fixed as written—users can see patch downloads and installs in the console.
