### ISSUE TITLE
feat: Flutter 3.19.4

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1815]
Smoke tests:

- [x] e2e tests (https://github.com/shorebirdtech/shorebird/actions/runs/8396480779)
- [x] engine tests (https://github.com/shorebirdtech/_build_engine/actions/runs/8396768392)
- [x] flutter create + shorebird init works

- [x] iOS release
- [x] iOS patch
- [x] iOS preview

- [x] `shorebird doctor`
    - [x] Win
    - [x] Mac

- [ ] Android release
    - [x] Win
    - [ ] Mac
- [ ] Android patch
    - [x] Win
    - [ ] Mac
- [ ] Android preview
    - [x] Win
    - [ ] Mac

- [x] iOS Add to App release
- [x] iOS Add to App patch

- [ ] Android Add to App release
    - [ ] Win
    - [x] Mac
- [ ] Android Add to App patch
    - [ ] Win
    - [x] Mac

- [x] iOS Flavors release
- [x] iOS Flavors patch
- [x] iOS Flavors preview

- [x] Android Flavors release
    - [x] Win
    - [x] Mac
- [x] Android Flavors patch
    - [x] Win
    - [x] Mac
- [x] Android Flavors preview
    - [x] Win
    - [x] Mac

**Comment by bryanoltman** [comment]
This has been released.
