### ISSUE TITLE
fix: Patch progress stuck on "Downloading release artifacts..."

### ISSUE THREAD

**Issue by rizkijuliansyaham** [shorebirdtech/shorebird#1819]
App ID: 07cd66fe-e347-4bb8-a732-71980e94daad

**Description**

after I made changes but what was changed did not have a dependency on native, when making a patch, the process was stuck at:

Downloading release artifacts... (it's been more than 20 minutes)

When I am verbose and try to open one of the get functions, a response like this appears:

{"code":"upgrade_required","message":"The current version is not supported. Please upgrade to the latest version and try again.","details":"Missing x-version header."}

is this a bug? or do you have to do a new release (can't be patched)?

**Steps To Reproduce**

1. only use  shorebird patch android --target ./lib/main.dart --verbose

**Comment by bryanoltman** [comment]
It looks like you might have an old version of shorebird. What does `shorebird doctor` print?

**Comment by eseidel** [comment]
`shorebird` version and `flutter` versions are unrelated.  Shorebird is designed so that it should always be possible to use the latest `shorebird` version, even if you use older versions of `flutter` to build your app.  We have an "loose coupling" between `shorebird` and `flutter` since `shorebird`'s version is tied to the version of our servers where as `flutter`'s version is set by the developer's code.

**Comment by rizkijuliansyaham** [comment]
![image](https://github.com/shorebirdtech/shorebird/assets/37908533/d22755dc-48fb-46cf-9c60-65f217273316)

is there must update to latest?  @bryanoltman 
![image](https://github.com/shorebirdtech/shorebird/assets/37908533/f5f95d8b-0c8a-4d15-9820-60c26dc63eb4)

**Comment by bryanoltman** [comment]
You should definitely strive to stay on the latest version of shorebird. I don't believe the error you saw is caused by being out of date, but please upgrade to the latest version and share the output of the failing command if upgrading doesn't fix the problem.

**Comment by rizkijuliansyaham** [comment]
after shorebird upgrade, patching run normally, thanks @bryanoltman
