### ISSUE TITLE
`shorebird release android --flutter-version=3.16.5` command not found?

### ISSUE THREAD

**Issue by ITApexGroup** [shorebirdtech/shorebird#1828]
This command not found

 shorebird release android --flutter-version=3.16.5

**Comment by eseidel** [comment]
Seems to work for me?
```
% shorebird release android --flutter-version=3.16.5
⠋ Building release with Flutter 3.16.5 (4e8a7c746a)... (3.2s)
```

Can you make sure you've run `shorebird upgrade`?

`shorebird doctor` should be able to tell you if Shorebird is set up correctly.

Thanks!

**Comment by eseidel** [comment]
Hmm, maybe `shorebird` itself isn't found?  You might want to try re-installing?  Sounds like maybe `shorebird` wasn't added to your path?

https://docs.shorebird.dev/

**Comment by bryanoltman** [comment]
Based on https://github.com/shorebirdtech/shorebird/issues/1850, it looks like this was resolved. Closing, please reopen if you're still having this problem.
