### ISSUE TITLE
fix: Unable to update to open patches other than the latest patch pack

### ISSUE THREAD

**Issue by aga23a** [shorebirdtech/shorebird#1829]
App ID:  63d51886-3075-4407-9f08-e4b594b69a19

For example: there are three patches in the background: pathc#1 patch#2
I closed patch#2, the release package can not be directly upgraded to patch#1

![image](https://github.com/shorebirdtech/shorebird/assets/162312124/7cbc1616-cd15-49b0-ae63-eb7b5fd44a5d)

**Steps To Reproduce**

1. create a release
2. create patch 1
3. create patch 2
4. deactivate patch 2
5. run shorebird preview

**Expected Behavior**

 the release package can upgraded to patch#1.

**Comment by eseidel** [comment]
Thanks.  I agree that's the expected behavior.  @bryanoltman is looking now.
