### ISSUE TITLE
We need the --force flag.

### ISSUE THREAD

**Issue by soonie-hub** [shorebirdtech/shorebird#1841]
We've been building local workflows for Flutter development and app deployment. Currently, we find that the --force flag is essential in our CI tasks running on a local server. It would be appreciated if we could reconsider re-enabling this option.

**Comment by felangel** [comment]
Hi @willbsoon 👋 
Thanks for opening an issue!

We have removed the `--force` flag but have added:
  - `--allow-native-diffs` to allow native file changes
  - `--allow-asset-diffs` to allow asset changes
  
Let us know if that helps 👍

**Comment by soonie-hub** [comment]
@felangel 
Thank you for your response. It appears that you are discussing the use of the `shorebird patch` command with reference to those flags. However, it seems there's no option to suppress prompts even with those flags. Moreover, the necessity for the --force flag extends beyond just `patch` to also include `release`. In our current workflow, where we use `flutter build` followed by Fastlane for uploading files to the store, switching to `shorebird release` introduces prompts that halt subsequent operations. Therefore, we need a method to employ the --force option for `releases` as well to ensure our processes run uninterrupted.

**Comment by eseidel** [comment]
Ah yeah, we have an issue where we're still showing prompts under `fastlane` and shouldn't.  We can look next week, thanks for reporting: https://github.com/shorebirdtech/shorebird/issues/1705

**Comment by soonie-hub** [comment]
@eseidel Thank you for the prompt response and for acknowledging the issue regarding prompts under Fastlane. Looking forward to seeing how issue #1705 progresses. Thanks again for your support!

**Comment by eseidel** [comment]
I'm going to dupe this against #1705 for now and we can open an new issue once we resolve that if it doesn't fix your issue, sound good?
