### ISSUE TITLE
Device serial number

### ISSUE THREAD

**Issue by sssolinjie** [shorebirdtech/shorebird#1846]
Does Android automatically obtain the device serial number upon startup? This is causing my app to fail the review process.

shorebird.yaml
```yaml
# auto_update controls if Shorebird should automatically update in the background on launch.
# If auto_update: false, you will need to use package:shorebird_code_push to trigger updates.
# https://pub.dev/packages/shorebird_code_push
# Uncomment the following line to disable automatic updates.
auto_update: false
```

**Comment by bryanoltman** [comment]
Shorebird does not collect any user- or device-identifying information.

**Comment by bryanoltman** [comment]
Could you share the rejection message/reason you received?

**Comment by eseidel** [comment]
Would love to see the rejection message if you're able to share.
