### ISSUE TITLE
`shorebird release ios` build takes a long time

### ISSUE THREAD

**Issue by ITApexGroup** [shorebirdtech/shorebird#1850]
shorebird release ios command a long time 
<img width="617" alt="Screenshot 2024-04-02 at 23 18 59" src="https://github.com/shorebirdtech/shorebird/assets/59428338/2dc7b1ce-55d3-482f-a4f0-1aefcc7266b0">

**Comment by eseidel** [comment]
10 minutes definitely seems excessive.  Did it successfully complete?  I might try re-running with `-v`.

**Comment by eseidel** [comment]
A guess might be that pod-install hung?

**Comment by ITApexGroup** [comment]
<img width="686" alt="Screenshot 2024-04-02 at 23 30 46" src="https://github.com/shorebirdtech/shorebird/assets/59428338/d28129bf-d729-4778-9eb2-f4962aeb4681">

**Comment by bryanoltman** [comment]
Does this happen every build or just the first time? If only on the first time, this is expected because our fork of Flutter needs to download dependencies before it can build the app.

**Comment by GuilhermeZety** [comment]
![Captura de Tela 2024-04-09 às 17 11 45](https://github.com/shorebirdtech/shorebird/assets/90266977/94d1fd4e-a098-4297-ad27-0828c081747a)
Why is the version release taking so long?
Not only in the IOS version but also in Android you have the same problem.

is the first release of this project with shorebird

**Comment by bryanoltman** [comment]
@GuilhermeZety You can run the command with -v to see verbose output, which should show what step is slow for you.

**Comment by GuilhermeZety** [comment]
@bryanoltman It looks like it got stuck in the build
![Captura de Tela 2024-04-09 às 17 24 07](https://github.com/shorebirdtech/shorebird/assets/90266977/ae08f4ad-482b-4786-87d2-fec85d108e35)

**Comment by bryanoltman** [comment]
Have you completed a successful release prior to this? On the first run, Flutter will download the artifacts it needs to build, which can take some time if you have a slow network connection (you can use Activity Monitor or `top` to see this)

**Comment by GuilhermeZety** [comment]
@bryanoltman 
I previously generated an appbundle with flutter normally and it was as you can see above.

Scenario summary: I just installed shorebird and this was the first project with the stable version that I configured with it, I had already used previous versions and they worked the first time.

(Generated with Google Translate)

![Captura de Tela 2024-04-09 às 17 36 37](https://github.com/shorebirdtech/shorebird/assets/90266977/8709fc0d-3fe2-4852-aa4a-470831e3519c)

**Comment by bryanoltman** [comment]
It looks like you've run `flutter build`, but that's distinct from `shorebird release` in that Shorebird uses its own version of Flutter, which will need to download a separate set of artifacts. Have you been able to complete a `shorebird release` command? What is your app id?

**Comment by GuilhermeZety** [comment]
@bryanoltman
`app_id: 3d5422f3-dcb0-4514-9e8b-e9c5e8b8a067`

The `shorebird release` command in this project has not yet

![Captura de Tela 2024-04-09 às 17 41 48](https://github.com/shorebirdtech/shorebird/assets/90266977/eb8927a8-1e13-44a8-ba03-fac107707890)

**Comment by bryanoltman** [comment]
You may need to let it run for a bit. I can't tell what OS you're using, but do you see increased network activity while you're waiting?

**Comment by GuilhermeZety** [comment]
@bryanoltman 
I'm back, I'm going to try to wait longer building here, the problem is that it's already reached 1300sec of build 😅;

I'm currently using a macbook air M1 with Sonoma 14.3.1

**Comment by GuilhermeZety** [comment]
@bryanoltman 
I ran it this morning and it was quick, it worked!

I can't say if at the time it was internet instability or something like that since at the time yesterday the internet was working normally

**Comment by bryanoltman** [comment]
Great! Closing the issue. If anyone else runs into this, please reopen with details.

**Comment by AmrAbdElHamed26** [comment]
> Does this happen every build or just the first time? If only on the first time, this is expected because our fork of Flutter needs to download dependencies before it can build the app.



I am currently using Flutter version 3.24, and it takes a long time — up to 3 hours — for the initial release build for android. After that, I stop the process because it takes too long.

Is it normal for it to take this much time?

**Comment by eseidel** [comment]
> > Does this happen every build or just the first time? If only on the first time, this is expected because our fork of Flutter needs to download dependencies before it can build the app.
> 
> I am currently using Flutter version 3.24, and it takes a long time — up to 3 hours — for the initial release build for android. After that, I stop the process because it takes too long.
> 
> Is it normal for it to take this much time?

3 hours is definitely not normal, no.  Is this with Flutter or Shorebird or both?

**Comment by AmrAbdElHamed26** [comment]
I initiated my app in the dashboard and then used the 
>> shorebird release android . 

It started the process and then asked me to continue. The long delay happens during the 'Creating artifacts' stage.

**Comment by eseidel** [comment]
> I initiated my app in the dashboard and then used the
> 
> > > shorebird release android .
> 
> It started the process and then asked me to continue. The long delay happens during the 'Creating artifacts' stage.

Does the delay happen when you use `flutter build aab --release` (without Shorebird)?

**Comment by felangel** [comment]
> I initiated my app in the dashboard and then used the
> 
> > > shorebird release android .
> 
> It started the process and then asked me to continue. The long delay happens during the 'Creating artifacts' stage.

You can pass the `--verbose` flag to see which commands specifically are taking a long time. I suspect it's just the `flutter build appbundle --release` command that's taking a while to run.

**Comment by AmrAbdElHamed26** [comment]
> > I initiated my app in the dashboard and then used the
> > > > shorebird release android .
> > 
> > 
> > It started the process and then asked me to continue. The long delay happens during the 'Creating artifacts' stage.
> 
> Does the delay happen when you use `flutter build aab --release` (without Shorebird)?

No, I made a new release, but it takes a long time.

but why doesn't the shorebird release android command work when I add signingConfig signingConfigs.release?

![image](https://github.com/user-attachments/assets/6193c43c-6bc2-44e1-98c2-9eb2a4065dfa)

**Comment by eseidel** [comment]
> > > I initiated my app in the dashboard and then used the
> > > > > shorebird release android .
> > > 
> > > 
> > > It started the process and then asked me to continue. The long delay happens during the 'Creating artifacts' stage.
> > 
> > 
> > Does the delay happen when you use `flutter build aab --release` (without Shorebird)?
> 
> No, I made a new release, but it takes a long time.
> 
> but why doesn't the shorebird release android command work when I add signingConfig signingConfigs.release?
> 
> ![image](https://private-user-images.githubusercontent.com/86882938/370634553-6193c43c-6bc2-44e1-98c2-9eb2a4065dfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczODEwNzUsIm5iZiI6MTcyNzM4MDc3NSwicGF0aCI6Ii84Njg4MjkzOC8zNzA2MzQ1NTMtNjE5M2M0M2MtNmJjMi00NGUxLTk4YzItOWViMmE0MDY1ZGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5NTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMjUyMmEyZjU4MmU4Yjk2MjA2ZGE4YjU3YzU2OTIwNDdlNDNmY2NlMDZmNDU4OGZlNzZiMTlkMzAxNTRiODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SqkPKhP6HzvybAipiareuUty8_aPpy5SgrDNO78DkSo)

Can you share the error?  I'm not sure what "does not work" means in this case.  Thanks!

We also probably should start a separate issue for Android since this issue is closed (and I don't want your comments to get forgotten). thank you!
