### ISSUE TITLE
feat: shorebird patch with specific flutter version

### ISSUE THREAD

**Issue by komiljonovshohjahon** [shorebirdtech/shorebird#1858]
**Description**

I can build a release using `shorebird release android --flutter-version=3.16.9`
But when trying to patch using `shorebird patch android` getting an issue with the latest flutter issue that does not match some of my packages. I am using fvm to work on my project, so decided to build with a specific version of flutter.
I could not find a way to patch with another version of flutter than the latest stable.

**Requirements**

- [  ] Need to be able to run `shorebird patch android --flutter-version=3.16.9`

**Additional Context**
**shorebird flutter version:** 
Shorebird 0.28.1 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.19.5 • revision 8b1c8eaba52f22e8298b26c97145b2d5a49181e3
Engine • revision 0bdaff54cf7f6f5da4418813f7d6075d3654e353

**Log:**
shorebird patch android                          
✓ Fetching apps (0.6s)
✗ Failed to build: Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

../../../../.pub-cache/hosted/pub.dev/pluto_grid-7.0.2/lib/src/manager/shortcut/pluto_grid_shortcut.dart:33:39: Error: The argument type 'RawKeyEvent' can't be assigned to the parameter type 'KeyEvent'.
 - 'RawKeyEvent' is from 'package:flutter/src/services/raw_keyboard.dart' ('../../../../.shorebird/bin/cache/flutter/8b1c8eaba52f22e8298b26c97145b2d5a49181e3/packages/flutter/lib/src/services/raw_keyboard.dart').
 - 'KeyEvent' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../../../.shorebird/bin/cache/flutter/8b1c8eaba52f22e8298b26c97145b2d5a49181e3/packages/flutter/lib/src/services/hardware_keyboard.dart').
      if (action.key.accepts(keyEvent.event, state)) {
                                      ^
../../../../.pub-cache/hosted/pub.dev/pluto_grid-7.0.2/lib/src/manager/shortcut/pluto_grid_shortcut.dart:33:46: Error: The argument type 'RawKeyboard' can't be assigned to the parameter type 'HardwareKeyboard'.
 - 'RawKeyboard' is from 'package:flutter/src/services/raw_keyboard.dart' ('../../../../.shorebird/bin/cache/flutter/8b1c8eaba52f22e8298b26c97145b2d5a49181e3/packages/flutter/lib/src/services/raw_keyboard.dart').
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../../../.shorebird/bin/cache/flutter/8b1c8eaba52f22e8298b26c97145b2d5a49181e3/packages/flutter/lib/src/services/hardware_keyboard.dart').
      if (action.key.accepts(keyEvent.event, state)) {
                                             ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/shoh/.shorebird/bin/cache/flutter/8b1c8eaba52f22e8298b26c97145b2d5a49181e3/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1442

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/shoh/.shorebird/bin/cache/flutter/8b1c8eaba52f22e8298b26c97145b2d5a49181e3/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Gradle task bundleRelease failed with exit code 1
 (82.3s)

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

**Comment by komiljonovshohjahon** [comment]
Found the solution here:
https://github.com/shorebirdtech/shorebird/issues/1807#issuecomment-2015349116

**Comment by eseidel** [comment]
Do you remember where you looked for that information?  It's likely we need to update our docs to explain this in more places?

**Comment by komiljonovshohjahon** [comment]
I just viewed this link, which is for building the app: https://docs.shorebird.dev/flutter-version
I tried running another command using that flag for a specific flutter version.

**Comment by komiljonovshohjahon** [comment]
> Do you remember where you looked for that information? It's likely we need to update our docs to explain this in more places?

I just viewed this link, which is for building the app: https://docs.shorebird.dev/flutter-version#use-a-different-flutter-versions
I tried running another command using that flag for a specific flutter version.
