### ISSUE TITLE
fix: Platform Not Detected

### ISSUE THREAD

**Issue by specOper99** [shorebirdtech/shorebird#1878]
**Description**

The builds using shorebird when the code has some logic depends on the Platform (iOS, Android, etc..) have a big problem
I didn't make a lot of inspection and troubleshooting but the thing I know is:
The platform that comes out from shorebird build is NOT Android nor iOS

note: when making the build with `flutter build` the error disappears

**Steps To Reproduce**

1. Make a build either Android, iOS with any fictionality that need to detect the platform
2. Run App
3. See error

**Expected Behavior**

The expected behaviour is to have the functionality on each platform performs as the code is written

**Comment by felangel** [comment]
Hi @specOper99 👋 
Thanks for opening an issue!

Are you able to provide a link to a minimal reproduction sample along with the exact steps you took and the error you saw? Thanks!

**Comment by eseidel** [comment]
Yeah, we'd love to help, just need a bit more information.  Thank you!

**Comment by eseidel** [comment]
We'd love to help, but would need more information.  Closing for now, please feel empowered to re-open if you have more details!
