### ISSUE TITLE
docs: Overview says we can update dependencies, but it's not clear about plugins

### ISSUE THREAD

**Issue by feinstein** [shorebirdtech/shorebird#1879]
The overview docs [here](https://docs.shorebird.dev/overview) say:

>3. Make changes to your app's Dart code. This could be a bug fix, a new feature, or anything else, and is not limited to your app's UI – this can include updated dependencies as well.

When it says `this can include updated dependencies as well` I imagine pure dart dependencies, but many dependencies are packages with plugins that will install native code, so maybe it would be good to add a note in the docs if devs should be cautious when adding plugin dependencies that include native code.

**Comment by eseidel** [comment]
Any native code changes (whether via a plugin or otherwise) will trigger a warning in the tool and will not be sent down via Shorebird.

e.g. https://docs.shorebird.dev/troubleshooting#unexpected-native-changes

**Comment by feinstein** [comment]
Good to know :)
