### ISSUE TITLE
feat: skip confirmation when create a new release

### ISSUE THREAD

**Issue by minhtritc97** [shorebirdtech/shorebird#1881]
Hello everyone, I have a question
--force flag has been removed, how I can skip confirmation "would you like to continue" when create a new release

![image](https://github.com/shorebirdtech/shorebird/assets/48729090/4cba259b-fd1c-4a7a-8780-c9267f7b2fdf)

**Comment by felangel** [comment]
Hi @minhtritc97 👋 
`--force` was removed in favor of:

- `--allow-asset-diffs`: Patch even if asset diffs are detected.
- `--allow-native-diffs`: Patch even if native code diffs are detected.

Hope that helps 👍

**Comment by eseidel** [comment]
If you are seeing unexpected changes you have to skip, we'd love to help diagnose.

**Comment by minhtritc97** [comment]
thanks for supporting

**Comment by bryanoltman** [comment]
To clarify, are you just asking to skip the "would you like to continue" prompt?

**Comment by minhtritc97** [comment]
> To clarify, are you just asking to skip the "would you like to continue" prompt?

yes, I need that

**Comment by eseidel** [comment]
@felangel is the right response here just the CI=true flag?

**Comment by felangel** [comment]
> @felangel is the right response here just the CI=true flag?

If you want to just skip all prompts then yes 👍

**Comment by eseidel** [comment]
I guess another approach would be the "yes" command which is designed to help with this sort of thing.  I don't know if other tools have a --no-confirm or similar.

e.g.
`yes | shorebird release android`
