### ISSUE TITLE
feat: shorebird doctor --fix should fix the pubspec.yaml file

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#1888]
**Description**

When running `shorebird doctor --fix` in a project where has a `shorebird.yaml` file, but don't have all the changes needed (shorebird.yaml file on the pubspec.yaml and android internet permission), the command just adds the android permission, it should also change the pubspec.yaml to add the shorebird.yaml file to the assets.

**Requirements**

- [ ] add the shorebird.yaml file to the assets.

**Comment by eseidel** [comment]
I very much appreciate you filing these frictions as you find them, thank you!
