### ISSUE TITLE
fix: shorebird login in firfox show 'bad gateway'

### ISSUE THREAD

**Issue by dev-hann** [shorebirdtech/shorebird#1903]
App ID: (insert your app ID here)

**Description**

**Steps To Reproduce**
1. install shorebird in ubuntu
2. try login shorebird through firefox
3. click login url and select google id just bad gateway

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by bryanoltman** [comment]
Sorry you're running into this. Can you provide more information (the URL itself, where you're located, output of `shorebird doctor`, etc.) that might help us?

**Comment by dev-hann** [comment]
oh, after upgrade shorebird works well. thanks!
