### ISSUE TITLE
feat: more aggressively update `shorebird` to latest version

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1910]
Maybe just always require `shorebird` to auto-update?

Our system is designed so that a newer `shorebird` should always work with an older `flutter` (but not the other way around).  It should always be OK to update `shorebird`.  Should we just force upgrade users?

This came up in a recent customer incident where the customer was making releases with a 6mo old version of `shorebird` which surprised us that was even possible.

**Comment by bryanoltman** [comment]
Discussed offline: we decided that the shorebird CLI should be usable for all patch builds within a minor release version (e.g., 1.1.1, 1.1.2, 1.1.3 would all be usable, 1.0.0 would require an upgrade). The current best idea for how to do this is to provide an `x-cli-version` header that the server validates in the same way that it validates the `x-version` header.

**Comment by bryanoltman** [comment]
From https://github.com/shorebirdtech/shorebird/issues/2179:

> This would help us get rid of the entire class of "my shorebird was old" failure cases. In general shorebird and api.shorebird.dev are tightly coupled so we don't support old versions of shorebird and should be much more aggressive about updating. I think auto-updating would be fine.
