### ISSUE TITLE
fix: App crashing after patch installation

### ISSUE THREAD

**Issue by Ahtsham0715** [shorebirdtech/shorebird#1928]
Issue Statement: 
The release you are trying to patch was built with a different version of Flutter.

Release Flutter Revision: 931d8d0d82f0c1a29731ca7601100804d09b3f33
Current Flutter Revision: 47571af6a3acdebedf88255099ff1de1c3324049.

I have built a release with older version of the flutter and now when I upgraded the flutter to latest version and build a patch, it installed correctly but app crashing on startup.
here is the log am getting on crash.
[FATAL:flutter/runtime/dart_vm_initializer.cc(89)] Error while initializing the Dart VM: Wrong full snapshot version, expected '93099564aca8020b8fdcf35b1155dbdb' found '3eda3cd112d4dbe04d80281af1ee5708'
Is there a way to install a previous version of flutter in shorebird if deleted accidentally

**Comment by eseidel** [comment]
This was https://github.com/shorebirdtech/shorebird/issues/1894, the fix for which went out with 1.0.1.

Please let us know if we can help. :)
