### ISSUE TITLE
feat: ability to revoke CI tokens generated by `login:ci`

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1941]
**Description**

This would involve us implementing a layer of token management on our side instead of treating CI tokens as raw credentials.

**Requirements**

- [ ] Ability to render a token issued by `login:ci` invalid without the user needing to reset the password for the account used to generated the token

**Additional Context**

A customer asked for this on Discord https://discord.com/channels/1030243211995791380/1230886476439359488

**Comment by eseidel** [comment]
We should move to issuing our own (secret, revokable) session tokens for CI, separate from the OAuth system.  Ideally those tokens would also have minimal permissions separate from what a human account holder would.

**Comment by eseidel** [comment]
This is related to https://github.com/shorebirdtech/shorebird/issues/1722

**Comment by eseidel** [comment]
Tracking this as part of https://github.com/shorebirdtech/shorebird/issues/1722.
