### ISSUE TITLE
fix: Because shorebird_cli depends on googleapis_auth from git which doesn't exist

### ISSUE THREAD

**Issue by EngALAlfy** [shorebirdtech/shorebird#1944]
**Description**

A clear and concise description of what the bug is when install shorebird in windows 10 by 

```
Set-ExecutionPolicy RemoteSigned -scope CurrentUser # Needed to execute remote scripts
iwr -UseBasicParsing 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex
```

Got error 

Because shorebird_cli depends on googleapis_auth from git which doesn't exist
  (Could not find git ref '647f96d5ffdae63e41aeea091c34acfffff533e7' (fatal: bad
  object 647f96d5ffdae63e41aeea091c34acfffff533e7)),

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

![image](https://github.com/shorebirdtech/shorebird/assets/61562847/5b11171f-8dab-4a2d-a306-d15710eec38b)

**Additional Context**

**Comment by bryanoltman** [comment]
We've had a couple reports of this. I'm not exactly sure the cause, but the commit it's saying it could not find definitely exists (https://github.com/shorebirdtech/googleapis.dart/commit/647f96d5ffdae63e41aeea091c34acfffff533e7)

**Comment by bryanoltman** [comment]
I wonder if our fork of `googleapis.dart` is confusing pub. @EngALAlfy, if you remove all `googleapis` folders in your pub cache `~/.pub-cache/hosted/pub.dev/` and try this again, does that fix the issue?

**Comment by EngALAlfy** [comment]
Yes I have remove all related files and folders in C:\Users\alalfy\AppData\Local\Pub\
It is work thanks

**Comment by bryanoltman** [comment]
Seems like we should consider unforking the repository. Thanks for the report! We'll try to address this next week.

**Comment by eseidel** [comment]
Do you by chance use PUB_HOSTED_URL?
