### ISSUE TITLE
feat: build release using --no-tree-shake-icons

### ISSUE THREAD

**Issue by scalz** [shorebirdtech/shorebird#1959]
**Description**
Hello, could you add an option for using --no-tree-shake-icons when creating a release please ?

**Requirements**

- Can build release without tree shake icons

**Additional Context**

None

**Comment by eseidel** [comment]
`shorebird release -- --no-tree-shake-icons` should work.  The `--` is used to indicate that any further arguments should be passed down to the underlying `flutter build` command which `shorebird release` uses.

**Comment by scalz** [comment]
It worked. Awesome!

Thank you

**Comment by Pietervdw** [comment]
If anyone stumbles onto the problem where the `shorebird release -- --no-tree-shake-icons` command gives errors. The syntax is

`
shorebird release android '--' --no-tree-shake-icons
`

😊

**Comment by eseidel** [comment]
Yeah, it's unfortunate, the extra quote around `--` are needed in powershell.  I believe all other shells leave the `--` alone and don't require the quotes.

**Comment by Pietervdw** [comment]
Running into a weirdness on Windows.
I need to disable icon tree shaking and also build an APK. How would I do that?

 I tried:

`shorebird release android --artifact apk --no-tree-shake-icons`

`shorebird release android --no-tree-shake-icons --artifact apk`

`shorebird release android '--' --no-tree-shake-icons --artifact apk`

Any suggestions would be most welcome please.

Thank you!

**Comment by eseidel** [comment]
`shorebird release android --artifact apk '--' --no-tree-shake-icons`
Should work.

**Comment by eseidel** [comment]
Really we should just fix https://github.com/shorebirdtech/shorebird/issues/318 and make this all go away.  We've just been busy with other things. 😦

**Comment by Pietervdw** [comment]
> Really we should just fix [#318](https://github.com/shorebirdtech/shorebird/issues/318) and make this all go away. We've just been busy with other things. 😦

#318 Would be awesome. But willing to wait for such awesomeness.😊

I can confirm `shorebird release android --artifact apk '--' --no-tree-shake-icons` works! 

Thank you Eric. You guys and shorebird are fantastic!
