### ISSUE TITLE
iOS crash on startup in version package

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1969]
@eseidel @felangel After sending the patch iOS yesterday, we also experienced crash on startup. It was coming from the version package and was stuck on the splash screen. Have you made any changes that interfere with the version number?

`FlutterError - FormatException: Not a properly formatted version string. Error thrown .`

```
Fatal Exception: FlutterError
0  ???                            0x0 Version.parse (version.dart)
1  ???                            0x0 Upgrader.isUpdateAvailable + 530 (upgrader.dart:530)
2  ???                            0x0 Upgrader.shouldDisplayUpgrade + 442 (upgrader.dart:442)
3  ???                            0x0 State.widget + 925 (framework.dart:925)
4  ???                            0x0 UpgradeAlertState.checkVersion + 136 (upgrade_alert.dart:136)
5  ???                            0x0 UpgradeAlertState.build.<fn> + 124 (upgrade_alert.dart:124)
6  ???                            0x0 StreamBuilder.build + 437 (async.dart:437)
7  ???                            0x0 _StreamBuilderBaseState.build + 120 (async.dart:120)
8  ???                            0x0 StatefulElement.build + 5592 (framework.dart:5592)
9  ???                            0x0 ComponentElement.performRebuild + 5480 (framework.dart:5480)
10 ???                            0x0 StatefulElement.performRebuild + 5643 (framework.dart:5643)
11 ???                            0x0 Element.rebuild + 5196 (framework.dart:5196)
12 ???                            0x0 BuildOwner.buildScope + 2904 (framework.dart:2904)
13 ???                            0x0 WidgetsBinding.drawFrame + 989 (binding.dart:989)
14 ???                            0x0 RendererBinding._handlePersistentFrameCallback + 448 (binding.dart:448)
15 ???                            0x0 SchedulerBinding._invokeFrameCallback + 1386 (binding.dart:1386)
16 ???                            0x0 SchedulerBinding.handleDrawFrame + 1311 (binding.dart:1311)
17 ???                            0x0 SchedulerBinding._handleDrawFrame + 1169 (binding.dart:1169)
```

_Originally posted by @ismail-mufin in https://github.com/shorebirdtech/shorebird/issues/1957#issuecomment-2073224414_

**Comment by eseidel** [comment]
Moved this out into its own bug (since the other one was a crash in C++).

I'm not aware of any changes to our version handling.  Patches shouldn't change versions, but it's possible something else went wrong.

@ismail-mufin Are you still experiencing an issue here?  Can we help?

**Comment by must-ismail** [comment]
@eseidel Thank you for taking care of this, since the app is in production we suppressed the error with try-catch in upgrader package. But I don't know if it's still there.

We have been sending patches since Shorebird iOS was stable, this is the first time this error has occurred.

**Comment by eseidel** [comment]
I think without more data it's hard for us to take action here.  If you still see this in your logs, please let us know, we would love to help!
