### ISSUE TITLE
feat: shorebird console should show basic patch install analytics

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#197]
I'm not even sure if we need to record said analytics ourselves, but we do need to make it possible for devs to report these back to something?  By exposing state from the dart api?

e.g.
* How many times have devices requested a patch (some sort of patch request history?)
* How many times have devices marked a patch good (known good patches?)
* How many times have devices marked a patch bad (known bad patches?)

We shouldn't do anything here before feedback from a live customer, mostly taking notes for myself.

**Comment by felangel** [comment]
> We shouldn't do anything here before feedback from a live customer, mostly taking notes for myself.

Do we want this to be in the todo column? Is it ready to be worked on?

**Comment by eseidel** [comment]
TT: "It would be nice to have some statistics in the backend to see the install rate."

**Comment by eseidel** [comment]
Related to https://github.com/shorebirdtech/shorebird/issues/181

**Comment by sam17** [comment]
Likely related to this.

Is there a way to check what patch number is running on an app?

In react-native codepush world, there was a jspack number which we sent in all analytics events like mixpanel. It was super critical for RCA on issues and tracking user experiences.

**Comment by eseidel** [comment]
> Likely related to this.
> 
> Is there a way to check what patch number is running on an app?
> 
> In react-native codepush world, there was a jspack number which we sent in all analytics events like mixpanel. It was super critical for RCA on issues and tracking user experiences.

Yes: https://pub.dev/documentation/shorebird_code_push/latest/shorebird_code_push_io/ShorebirdCodePush/currentPatchNumber.html

**Comment by eseidel** [comment]
We're recording this information now.  We're just not displaying it anywhere.  The remaining work is to display this in the console.

**Comment by felangel** [comment]
As of yesterday the console displays the second bullet point (How many times have devices marked a patch good (known good patches?). I'm thinking it might make sense to add a graph of patch installs over time for the current billing period, wdyt?

**Comment by felangel** [comment]
We now show patch installs over time per release 🎉 



![Image](https://github.com/shorebirdtech/shorebird/assets/8855632/679548ff-d13b-4ff6-91f2-578562929965)

**Comment by sam17** [comment]
Thats amazing!

But slightly weird ordering of dates?

![Screenshot 2023-09-27 at 5 42 12 PM](https://github.com/shorebirdtech/shorebird/assets/1422630/6891db1a-b104-49da-92ff-ca6646365b53)

**Comment by felangel** [comment]
> Thats amazing!
> 
> But slightly weird ordering of dates?
> 
> ![Screenshot 2023-09-27 at 5 42 12 PM](https://user-images.githubusercontent.com/1422630/270974071-6891db1a-b104-49da-92ff-ca6646365b53.png)

Good call will take a closer look shortly.

**Comment by felangel** [comment]
Should be fixed now (date labels are omitted to reduce clutter but can be seen on hover) 🎉 

<img width="1065" alt="Screenshot 2023-09-27 at 12 13 00 PM" src="https://github.com/shorebirdtech/shorebird/assets/8855632/9c42bbf3-0917-45af-a351-afd7b04afc95">

**Comment by felangel** [comment]
@eseidel as discussed I'm going to work on other items while we wait for customer feedback. Not sure if we want to keep this issue open or close it and open subsequent issues based on specific customer asks?

**Comment by eseidel** [comment]
Lets just close this generic one and open new smaller ones when we have requests.
