### ISSUE TITLE
feat: `shorebird release` should switch to the system flutter version automagically

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1972]
Right now `shorebird release` will either use its default flutter version (the latest one release with Shorebird), or you can override that with `--flutter-version`.  This remains confusing for users.  We should probably just default `--flutter-version` to whatever `flutter --version` (the system flutter) says.

**Comment by bryanoltman** [comment]
For cases where we only support a relatively high minimum version (the current state of iOS), is the expectation that `shorebird release ios` would fail if the user does not have 3.19.5 or higher installed?

**Comment by eseidel** [comment]
> For cases where we only support a relatively high minimum version (the current state of iOS), is the expectation that `shorebird release ios` would fail if the user does not have 3.19.5 or higher installed?

I think so?  We're about to compile their flutter code with 3.19.5 anyway.  It feels like any time we're compiling their code with a version of Flutter they don't expect, we're just setting ourselves up for implicit confusion.
