### ISSUE TITLE
fix: shorebird release android with multi dimensional, multi word flavor breaks

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#1973]
**Description**

When trying to release an app with multi dimensional and multi word flavor, for example: `stable` + `playStore` = `stablePlayStore`, the `shorebird release` command breaks.

**Steps To Reproduce**

1. Go to the multi dimensional sample app
2. Run `shorebird release android --flavor stablePlayStore`
3. See error

**Expected Behavior**

Release should work

**Screenshots**

**Additional Context**

This issue is happening because of a bug upstream in the flutter tool, there is an issue filled for it: https://github.com/flutter/flutter/issues/147261

**Comment by eseidel** [comment]
Since there is nothing for us to do here once the upstream is resolved, I think we can just close this and point users to the usptream issue.
