### ISSUE TITLE
ci: e2e workflow should run in a matrix using multiple flutter revisions

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#1976]
We currently don't run e2e against older supported Flutter versions. We should probably update e2e to run in a matrix using the latest stable flutter revision as well as at least one older flutter revision to ensure bugs like #1975 don't creep in in the future.

**Comment by erickzanardo** [comment]
Fixed by https://github.com/shorebirdtech/shorebird/pull/2340
