### ISSUE TITLE
fix: patch e2e workflow is hanging

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#1979]
Since we switched over to linux the patch e2e workflow never completes.
See https://github.com/shorebirdtech/shorebird/actions/runs/8837197393/job/24265545832 as an example.

**Comment by bryanoltman** [comment]
Fixed with https://github.com/shorebirdtech/shorebird/commit/8d38ea7954d4ebcef61b298fd4e0772ccda94312
