### ISSUE TITLE
feat: consolidate release and patch commands

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1988]
**Description**

We currently have `patch` and `release` super-commands with subcommands for each release platform. There are currently four (android, ios, aar, xc-framework) for each. They all follow roughly the same pattern, meaning that any change to our general release or patch logic needs to be made and tested four times. Even when extracting this logic into dependencies, this is still very cumbersome. This structure also prevents us from allowing users to patch multiple platforms at a time.

**Requirements**

- [ ] There is a single `patch` command that accepts "target platforms" argument
- [ ] There is a single `release` command that accepts a "target platforms" argument

**Comment by eseidel** [comment]
This is now done (and being released shortly).
