### ISSUE TITLE
fix: shorebird release fails when using SkSL warm up

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#1990]
App ID: any

**Description**

When using the SkSL warm up and trying to release to shorebird, the build breaks

**Steps To Reproduce**

1. Follow: https://docs.flutter.dev/perf/shader#how-to-use-sksl-warmup to generate the warm up jsons
2. shorebird release android --artifact apk -- --bundle-sksl-path generated.json

```
✗ Failed to build: Expected Flutter c4cd48e186460b32d44585ce3c103271ab676355, but found e4434d7a212b29a8ee8ffaf8e2c453c753904933
The SkSL bundle was produced with a different engine version. It must be recreated for the current Flutter version.
Target aot_android_asset_bundle failed: Exception: SkSL bundle was invalid


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/erick/projects/shorebird/shorebird/bin/cache/flutter/aee5222c0d52012f089564a8395826d56e7c2fe8/bin/flutter'' finished with non-zero exit value 1
```

**Expected Behavior**

Build should work since running the same command with the flutter tool, it works

**Comment by erickzanardo** [comment]
```
The SkSL bundle was produced with a different engine version. It must be recreated for the current Flutter version.
Target aot_android_asset_bundle failed: Exception: SkSL bundle was invalid
```

This seems to be the root cause! Since the .json were generated using the system flutter, when trying to release with the shorebird's engine, it breaks due revision mismatch.

I am not sure how we will be fixing this yet. But a simple workaround is to manually edit the generated json and change the `engineRevision` field to the engine revision of your shorebird installation, which you can get by running `shorebird doctor`

**Comment by eseidel** [comment]
The "safe" way would be to keep a list of equivalencies between Shorebird engine revisions and their flutter counterpart and re-write the engine revision of the .json assuming it matches the expected upstream revision.  Our `cutler` tool already knows how to do the mappings to some degree (it used to be public and could be again, it just happens to be in a repo which is private for other reasons atm):
https://github.com/shorebirdtech/_build_engine/tree/main/cutler

**Comment by erickzanardo** [comment]
Sounds like a good idea! Should we at least for now write up some docs? Or maybe do a checking in our CLI that will identify that the user is using sksl and warn to such docs?

**Comment by eseidel** [comment]
My guess is that since this is the first request for such and that impeller is on-by-default on iOS, this bug is probably sufficient docs for now?  I don't know what the status of turning impeller on on Android by default is, but my guess is that it's happening this year.

**Comment by eseidel** [comment]
That said, feel free to follow your nose.  If you think it's important, you'd probably be the one writing docs anyway. :) But yes, the solution is probably to modify the engine version in the .json.  The way to do that safely it so make sure the flutter engine version used to generate it matches the version of flutter engine the version of flutter shorebird is using.  It's a bit complicated to do that matching, which is why I'm a bit hesitant to write docs for a feature which is on its way out unless there are more requests.

**Comment by erickzanardo** [comment]
> My guess is that since this is the first request for such and that impeller is on-by-default on iOS, this bug is probably sufficient docs for now? I don't know what the status of turning impeller on on Android by default is, but my guess is that it's happening this year.

sounds good, lets monitor how this goes, at least now we know the reason and people we have some instructions here.

**Comment by eseidel** [comment]
I think it's likely that Flutter will remove sksl warmup later this year.
