### ISSUE TITLE
feat: Add automated license scanning

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1996]
I've done license scanning of our Dart dependencies a couple times with:
https://pub.dev/packages/dart_license_checker

There appear to be other similar tools, e.g.
https://pub.dev/packages/license_checker
and
https://verygood.ventures/blog/very-good-cli-license-checker

Would like our CI to fail if any package depends on a non-allowed license.

**Comment by erickzanardo** [comment]
Fixed by #2190
