### ISSUE TITLE
fix: Failed to obtain access credentials. Error: invalid_request Missing required parameter: refresh_token Status code: 400 (85ms)

### ISSUE THREAD

**Issue by ahmadkasimeng** [shorebirdtech/shorebird#2002]
App ID: c4056573-0221-41fd-902a-fccb61bc4bd9

**Description**

When github actions run it fails at the patching (or release) stage and throws this warn and error 
[WARN] SHOREBIRD_TOKEN needs to be updated before the next major release.
Run `shorebird login:ci` to obtain a new token.
⠋ Fetching apps...
✗ Failed to obtain access credentials. Error: invalid_request Missing required parameter: refresh_token Status code: 400 (85ms)

**Steps To Reproduce**

Whatever I do to fix it I can't I followed the documentation searched whether it was also issued before, made sure of verison compatibility and nothing worked! 

**Expected Behavior**

The patch should just work!

**Screenshots**

![image](https://github.com/shorebirdtech/shorebird/assets/128233976/5bc15fbf-acb7-4d2c-8b23-a65cfac349f9)

**Additional Context**

**Comment by bryanoltman** [comment]
[WARN] SHOREBIRD_TOKEN needs to be updated before the next major release.
Run shorebird login:ci to obtain a new token.

Does this still happen if you update your CI token?

**Comment by ahmadkasimeng** [comment]
> [WARN] SHOREBIRD_TOKEN needs to be updated before the next major release. Run shorebird login:ci to obtain a new token.
> 
> Does this still happen if you update your CI token?

When I run ``login:ci`` it gives me the same token over and over however many times I write this command and authenticate with my google account, the token does not change. There was a similar issue (#1808) but the issuer didn't verify the CLI versions on both the local machine on which he requested the CI token and the CI CLI. I have the same version!

** My Local Machine **
![image](https://github.com/shorebirdtech/shorebird/assets/128233976/13c88ccd-e2f0-4755-ac34-bb71b084004f)


** CI CLI ** 
![image](https://github.com/shorebirdtech/shorebird/assets/128233976/55419185-82cd-41c7-a1b7-a7b4b93c59ef)

**Comment by bryanoltman** [comment]
Right, you need to add that token to your CI the same way you did when you first ran `login:ci`

**Comment by ahmadkasimeng** [comment]
> Right, you need to add that token to your CI the same way you did when you first ran `login:ci`

I already did that, ALOT and it didn't work, this is the workflow file:
`name: Shorebird Android

on:
  push:
    branches:
      - master

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}


jobs:
  shorebird_android:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🐦 Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1


      - name: 🚀 Use Shorebird
        run: shorebird --version

      - name: Check Shorebird
        run: shorebird doctor


      - name: 🚀 Shorebird Patch
        uses: shorebirdtech/shorebird-patch@v0
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        with:
          args: -- --no-tree-shake-icons
          platform: android


      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk


`
Of course I set up the Environment secrets and made sure multiple times of the token namings.
![image](https://github.com/shorebirdtech/shorebird/assets/128233976/20f828bd-c72d-40f6-8325-18b84d3e5022)

**Comment by bryanoltman** [comment]
Hmm, are you using Google or Microsoft to login?

**Comment by ahmadkasimeng** [comment]
> Hmm, are you using Google or Microsoft to login?

Google, my email is gombizombi1@gmail.com, a weird one yes! 😄

**Comment by bryanoltman** [comment]
I'm not able to reproduce this issue locally. Can you base64 decode the CI token you get (`echo $SHOREBIRD_TOKEN | base64 --decode`) and verify that it has the following format (**DO NOT post it here**):

```json
{"refresh_token":"SOME_REFRESH_TOKEN","auth_provider":"google"}
```

**Comment by ahmadkasimeng** [comment]
> I'm not able to reproduce this issue locally. Can you base64 decode the CI token you get (`echo $SHOREBIRD_TOKEN | base64 --decode`) and verify that it has the following format (**DO NOT post it here**):
> 
> ```json
> {"refresh_token":"SOME_REFRESH_TOKEN","auth_provider":"google"}
> ```

![image](https://github.com/shorebirdtech/shorebird/assets/128233976/cf8b2156-3249-41b9-a47d-3e78cc62c7d2)

it seems like that the token isn't even accessable or what?!

**Comment by bryanoltman** [comment]
Yeah, it looks like the SHOREBIRD_TOKEN env var is not properly set

**Comment by ahmadkasimeng** [comment]
> Yeah, it looks like the SHOREBIRD_TOKEN env var is not properly set

This is not my first time seeting up environmet variables though, I worked on lots of prjects with Flutter, Python and Others, and I have not met and issue like this! Also I showed you the picture of the Environment Secrets, and there is nothing wrong... What do you think I should do next? Should I try it with another project with flutter? Because this is the first project with it WITH github actions, the local CLI works finethough.

**Comment by bryanoltman** [comment]
I would consult the docs for using secrets in Github actions https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions

**Comment by ahmadkasimeng** [comment]
Thanks! for the great help! This is simply resolved by using the repostory secerts. I used the environment without setting them up correctly 😢
