### ISSUE TITLE
fix: Failed to link AOT files:

### ISSUE THREAD

**Issue by aloRanking** [shorebirdtech/shorebird#2014]
App ID: bd67c34c-c2a6-413d-b7bf-32024db04d8a

**Description**

I ran "shorebird patch android" and "shorebird patch ios"successfully the first time. I tried running "shorebird patch iOS" the next time but ran into failed to link AOT files. "shorebird patch android" has no issue the second time.

<img width="1409" alt="Screenshot 2024-05-05 at 06 41 07" src="https://github.com/shorebirdtech/shorebird/assets/23122626/d4a90807-3af7-42ce-9072-754635ace3d1">
 

Crash log.
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=SEGV_MAPERR(1), si_addr=0x8b9248
Aborting reentrant request for stack trace.

Unhandled exception:
Exception: gen_snapshot failed
#0      SnapshotGenerator.generateAotElfSnapshot (package:aot_tools/src/snapshot_generator.dart:37:7)
#1      LinkCommand._generateOptimizedPatchSnapshot (package:aot_tools/src/commands/link_command.dart:262:24)
#2      LinkCommand.run (package:aot_tools/src/commands/link_command.dart:134:40)
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#5      new Future.sync (dart:async/future.dart:305:31)
#6      CommandRunner.run (package:args/command_runner.dart:122:14)
#7      main.<anonymous closure> (file:///home/gha/.engine_checkout/engine/src/third_party/dart/pkg/aot_tools/bin/aot_tools.dart:9:57)
#8      _rootRun (dart:async/zone.dart:1399:13)
#9      _CustomZone.run (dart:async/zone.dart:1301:19)
#10     _runZoned (dart:async/zone.dart:1804:10)
#11     runZoned (dart:async/zone.dart:1747:10)
#12     LoggerOverrides.runZoned (package:aot_tools/src/logger.dart:28:18)
#13     runWithLogger (package:aot_tools/src/logger.dart:18:26)
#14     main (file:///home/gha/.engine_checkout/engine/src/third_party/dart/pkg/aot_tools/bin/aot_tools.dart:9:26)
#15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#16     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by kishanPortpro** [comment]
I am also getting the same issue. Does anyone know the any work around to help me to fixed this issue ?

**Comment by felangel** [comment]
We’ll take a closer look shortly and get back to you. In the meantime any information you can provide such as the output of `shorebird doctor -v` and the type of change you made in the patch would be super helpful, thanks!

**Comment by kishanPortpro** [comment]
Hey @felangel  Thanks for your response. It seems like this issue is no longer coming in new version as I've uploaded successfully 3 patchs on IOS so. Still If I get anything related to this in future I'll send you the log.
Thanks!

**Comment by eseidel** [comment]
Thank you!  Please let us know if you ever see anything like this again, we'd love to help!
