### ISSUE TITLE
fix: iOS hangs on Creating artifacts

### ISSUE THREAD

**Issue by camillo-rinaldi** [shorebirdtech/shorebird#2043]
App ID: 13b4d9b1-87d9-40f6-97fc-41ac09d0f56f

**Description**

`shorebird release ios` hangs on Creating artifacts

**Screenshots**

![image](https://github.com/shorebirdtech/shorebird/assets/106631497/f93e8d3f-14c0-4298-936f-6deeb0d85503)

![image](https://github.com/shorebirdtech/shorebird/assets/106631497/88745f70-396d-4aa9-86b2-1da22d1f0975)

![image](https://github.com/shorebirdtech/shorebird/assets/106631497/fd82a925-668d-4bf0-8a16-0312d7c998c7)

**Comment by eseidel** [comment]
Fascinating.  Thank you.

**Comment by LukasGasp** [comment]
Hi,
I've got the same error for Android. Running updates and reauthenticating did not fix it.
Is there anything I can provide you with? There is no workaround yet, right?

**Comment by eseidel** [comment]
Could be related: https://github.com/shorebirdtech/shorebird/issues/2160

**Comment by erickzanardo** [comment]
@camillo-rinaldi would mind running the patch command with the `-v` flag and the log with us, so we can check either or not this issue is related to #2160?

**Comment by eseidel** [comment]
@erickzanardo is working in this area now, trying to help us get better logs from failures like these.

**Comment by eseidel** [comment]
See also https://github.com/shorebirdtech/shorebird/issues/2211.

**Comment by eseidel** [comment]
We've significantly improved our logging since this.  We would love any updates you could provide if this is now fixed for you.

Thank you again for the report!
