### ISSUE TITLE
fix: app still applies patches automatically when shorebird.yaml contains auto_update: false

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2045]
From https://github.com/shorebirdtech/shorebird/issues/1774#issuecomment-2100719225:

I am still facing this issue. I have uncommented and then made the release and when I copy the .yaml file from console. the auto update is commented there. 

```
Shorebird 1.0.5 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.19.6 • revision 4b22a31bd9911c8317319292a9a103217919649e
Engine • revision ef2c5cd963e481d44741e2a587ecb7ad69629ce1
```

I have tried creating the shorebird init with force as well and even though I have tried installing the shorebird from the scratch with the curl command and force as well. Below are the command

`curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash -s -- --force`

Then I have also used the code push package also for manual handling. Even though I have the patch on console. When I use that package it returns me false in the answer of isNewPatchAvailableForDownload() but when I do shorebird preview and then it build and shows me the correct changes of the patch on the app and now If I run again this function isNewPatchAvailableForDownload, now it will return me this 

```
05-08 17:55:01.969  1258  2236 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "2acbd986-969a-43d3-ae06-1561e3fedf7d", channel: "stable", release_version: "3.0.99+509", patch_number: None, platform: "android", arch: "aarch64" }

05-08 17:55:02.333  1258  2237 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "2acbd986-969a-43d3-ae06-1561e3fedf7d", channel: "stable", release_version: "3.0.99+509", patch_number: None, platform: "android", arch: "aarch64" }

05-08 17:55:03.455  1258  2237 I flutter : updater::updater: Patch 1 successfully installed.

05-08 17:55:03.460  1258  2237 I flutter : updater::c_api: Update result: Update installed
```

But if I do it before preview command it will show me nothing.
One more thing is, on running the shorebird preview command I get this in logs 

```
05-08 17:50:41.610  1258  1258 I flutter : updater::cache::updater_state: No existing state file found: File /data/user/0/company/files/shorebird_updater/state.json does not exist, creating new state.

05-08 17:50:41.612  1258  1258 I flutter : [INFO:shorebird.cc(173)] Shorebird updater: no active patch.

05-08 17:50:41.613  1258  1258 I flutter : [INFO:shorebird.cc(180)] Shorebird auto_update disabled, not checking for updates.
```

Which from my understanding shows that auto_update is disabled which is true. In shorebird.yaml it is uncommented but then why when I download from shorebird console it shows me auto update is commented. 
I dont know how to explain the situation but it is behaving very weird.

_Originally posted by @AhmadIzaz in https://github.com/shorebirdtech/shorebird/issues/1774#issuecomment-2100719225_

**Comment by eseidel** [comment]
I'm not really sure what's being asked here.

1. the shorebird.yaml provided by the console is for convenience (in case you manage to lose the one generated by `shorebird init`).
2. Re-installing shorebird should not be necessary.
3. isNewPatchAvailableForDownload returning false, may be for a variety of reasons.  We'd have to discuss that in more detail.
4. Preview showing `Shorebird auto_update disabled` is correct.  That means that it correctly found the auto_update: false in the shorebird.yaml and disabled auto-updating (you would then have to use package:shorebird_code_push to trigger updating).

How can we help?

**Comment by AhmadIzaz** [comment]
So do you mean the behavior where I uncommented the auto_update: false in my shorebird.yaml and then made the android release and then checked the shorebird.yaml from the console and the flag is commented there is correct ?

**Comment by AhmadIzaz** [comment]
What If I make the release with auto_update:false commented and then uncomment it and make a patch. Will it update the auto_update:false uncommented in the console as well ?

In short, is it compulsory to make the auto_update:false uncomment before making the release for shorebird console ?

**Comment by felangel** [comment]
> What If I make the release with auto_update:false commented and then uncomment it and make a patch. Will it update the auto_update:false uncommented in the console as well ?
> 
> In short, is it compulsory to make the auto_update:false uncomment before making the release for shorebird console ?

The shorebird.yaml in the console is just there if you accidentally lose yours. It’s not meant to be in sync with your actual shorebird.yaml.

You should only uncomment auto_update: false if you want to use package:shorebird_code_push to manage checking for updates manually.

**Comment by AhmadIzaz** [comment]
Okay I got your that point. One more thing

Does uncommenting before or after making release create any difference ? Or Should I strictly uncomment and then makes a release. Lets say I have a release where auto_update is commented and now I want uncommented. So should I just create a patch and it will automatically be updated ?

**Comment by AhmadIzaz** [comment]
> Okay I got your that point. One more thing
> 
> Does uncommenting before or after making release create any difference ? Or Should I strictly uncomment and then makes a release. Lets say I have a release where auto_update is commented and now I want uncommented. So should I just create a patch and it will automatically be updated ?

**Comment by felangel** [comment]
> Okay I got your that point. One more thing
> 
> Does uncommenting before or after making release create any difference ? Or Should I strictly uncomment and then makes a release. Lets say I have a release where auto_update is commented and now I want uncommented. So should I just create a patch and it will automatically be updated ?

You need to make your change to the shorebird.yaml before releasing. Patching does not support changing assets currently.

**Comment by AhmadIzaz** [comment]
Okay got it. Thank you so much. I am gonna test now again. Will get back to you

**Comment by AhmadIzaz** [comment]
Apologies, but one more clarification needed, Is it compulsory to run the preview command to check the changes? Like what if i just run the app from Xcode or Flutter CLI for android or iOS. The changes are supposed to be seen in that case as well ?
Because currently I am facing that changes are being shown after I run the preview command. Also this screenshot I shared below explain like you dont need to rerun but does this means it should run atleast once ? Thanks in advance. 

<img width="721" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/23280743/81c30575-dd44-47df-a9d2-2012aeee976f">

**Comment by eseidel** [comment]
`shorebird preview` is not compulsory.  It's just a convenience.  What `shorebird preview` does is download the release artifacts from when you ran `shorebird release` and installs those on the connected device.  This makes it easy to get the right version of the app matching what your users have installed so that you can test staged patches locally.

**Comment by AhmadIzaz** [comment]
@eseidel @felangel thank you so much guys. You can close this issue as it was just a misunderstanding that if I make the auto_update:false uncomment it will reflect on the console as well. I am not sure if it mentioned somewhere or I missed that point in the documentation. Thanks again.
