### ISSUE TITLE
Does shorebird modify the `libapp.so`, to achieve hot-upgrade

### ISSUE THREAD

**Issue by gintominto5329** [shorebirdtech/shorebird#205]
Hello,

Im a flutter dev,
Since yesterday, im checking out flutter-engine's source code, 
to implement hot-upgrade, for my android app, 
we use flutter-web-canvaskit for ios app.

#### Plan
Our plan is to replace the `libapp.so`, with newer versions,
by modifying `class FlutterLoader`'s [`void ensureInitializationComplete(`](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java#L221) function, which loads the native libraries, `libflutter.so`(as `icu-native-lib`), and `libapp.so`(as `aot-shared-library`), to add the following **algo**, and re-build the engine:
```
int //
  latestAppVersion = HTTP.get("http://.../app.android.version.txt").parseInt(),
  availableAppVersion = File(pathToVersionTxtAssetFile).read().parseInt();

if (latestAppVersion > availableAppVersion) {
  File(appFilesDirPath + "/" + "app.so").write(HTTP.get("http://.../app.android.so"));
  shellArgs.add("app.so");
} else {
  shellArgs.add(flutterApplicationInfo.aotSharedLibraryName);
}
```

#### May I ask:
- Is the above approach correct?
I know this may be in-secure, we assure you, I'll ensure the security, and not upgrade to major versions, just for minor emergency fixes,
- Do shorebird, do the same?
- Where may I find the actual build commands, used to build flutter-engine, for the official flutter releases.

Please do not worry, about generalizing this info publicly, 
I will delete this, after getting a reply from the team,

thanks,

**Comment by eseidel** [comment]
Hi there.  All of our code is public at https://github.com/shorebirdtech including our changes to the Flutter engine.  The build commands we use for the Flutter engine are currently in shorebird/scripts/build_engine.sh I believe, but they're likely to move soon.

All of this is public information, no need to delete anything.  Best of luck.
