### ISSUE TITLE
fix(shorebird_code_push): downloadUpdateIfAvailable does not throw exception when download fails.

### ISSUE THREAD

**Issue by aga23a** [shorebirdtech/shorebird#2058]
App ID: a06c1422-5791-4487-958f-5ce9efc6e635

**Description**

I downloaded a valid patch package through shorebirdCodePush.downloadUpdateIfAvailable(), but it failed to download successfully, but no exception was thrown, causing the application to think that the download was successful and execute restartApp, so the application kept downloading and restarting in a loop.

**Steps To Reproduce**

1. Execute shorebirdCodePush.isNewPatchAvailableForDownload() to determine whether there is a new patch package
2. If the result returns true, execute shorebirdCodePush.downloadUpdateIfAvailable() to download the patch package.
3. After waiting for the download to complete successfully, execute restartApp()
4. Because downloadUpdateIfAvailable failed to download, but no exception was thrown, resulting in a loop of downloading patch packages and restarting the application.

**Expected Behavior**

I want shorebirdCodePush.downloadUpdateIfAvailable() to be executed. An exception will be thrown if the download fails.

**Screenshots**
<img width="1416" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/162312124/149596f1-bb7f-4099-ae27-f068e13bdd2a">
<img width="1244" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/162312124/fbb12138-a924-4d53-8955-d5ef481563cb">

**Additional Context**

The current device is a real device and the Android version is 4.4.4

**Comment by aga23a** [comment]
The download of the patch package times out, and the application cannot capture the download error.

<img width="678" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/162312124/65c0c914-6b7c-4564-9911-8b2c4c615675">

**Comment by bryanoltman** [comment]
4.4.4 is a very old Android version that is no longer supported by Google and only supported by Flutter on a best-effort basis. I'm not sure we can address the Permission Denied error, but we can update our package to throw an exception if a download fails. Updating the title of the issue to reflect this.

**Comment by aga23a** [comment]
Sounds good, this is a good solution

> 4.4.4 is a very old Android version that is no longer supported by Google and only supported by Flutter on a best-effort basis. I'm not sure we can address the Permission Denied error, but we can update our package to throw an exception if a download fails. Updating the title of the issue to reflect this.

**Comment by aga23a** [comment]
What is the minimum Android version supported by shorebird?

**Comment by eseidel** [comment]
We match Flutter/Google's support range: https://docs.flutter.dev/reference/supported-platforms

**Comment by aga23a** [comment]
> We match Flutter/Google's support range: https://docs.flutter.dev/reference/supported-platforms

Okay, I see. Thanks~

**Comment by eseidel** [comment]
A workaround would be to call `isNewPatchReadyToInstall` after downloadUpdateIfNecessary to see if it successfully completed.
https://pub.dev/documentation/shorebird_code_push/latest/shorebird_code_push/ShorebirdCodePush/isNewPatchReadyToInstall.html

**Comment by felangel** [comment]
We just released [v2.0.0-dev of `package:shorebird_code_push`](https://pub.dev/packages/shorebird_code_push/versions/2.0.0-dev.2) which should address these issues.

You can learn more about what's new in our [blog post](https://shorebird.dev/blog/shorebird-code-push-v2).

Let us know if there's anything else we missed or you think can be improved, closing this for now 👍
