### ISSUE TITLE
feat: use same patch number when patching multiple platforms in a single command

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#2068]
**Description**

Shorebird `1.1.0` introduced the ability to make a patch for multiple platforms. The patch number is not unified though.

Since we are releasing everything in a single command, would make up for a more organized workflow if the patches would be the same across platforms

**Requirements**

- [ ] Single patch number for patches across platform generated in a single command.

**Comment by eseidel** [comment]
I think this is a dupe of https://github.com/shorebirdtech/shorebird/issues/1382?
