### ISSUE TITLE
fix: Issue with --android-artifact apk Argument in Shorebird Release After Upgrading to Version 1.1.0

### ISSUE THREAD

**Issue by JedTsai33** [shorebirdtech/shorebird#2070]
**Description**

After upgrading to version 1.1.0, the --artifact option has been changed to --android-artifact. However, when using the command shorebird release android --android-artifact apk, an error occurs stating "Invalid argument(s): Could not find an option named 'split-per-abi'." When using shorebird release android --android-artifact aab, the package is built successfully. Could you suggest any solutions to resolve the error occurring with the --android-artifact apk argument?

**Comment by thousmile** [comment]
I also encountered such a situation

```shell
PS D:\code\FlutterProjects\flutter_demo_1> shorebird release android --android-artifact apk --release-version 1.0.1
Invalid argument(s): Could not find an option named "split-per-abi".

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
C:\Users\molly\AppData\Roaming\shorebird\logs\1715343825651_shorebird.log

PS D:\code\FlutterProjects\flutter_demo_1>
```

**Comment by eseidel** [comment]
The change to --android-artifact was an error, which will be fixed in 1.1.1 in a few minutes.

**Comment by eseidel** [comment]
`--artifact` support should be restored now in 1.1.1.

**Comment by eseidel** [comment]
`shorebird` does not support `--split-per-abi`, but the `--artifact` error should now be gone. Let us know if that's not the case.
https://github.com/shorebirdtech/shorebird/pull/1255

**Comment by JedTsai33** [comment]
Upgrading to version 1.1.2, testing can now generate apk using --artifact. Thank you for your assistance.
