### ISSUE TITLE
feat: add instructions to tag commit after releasing

### ISSUE THREAD

**Issue by dickermoshe** [shorebirdtech/shorebird#2078]
**Description**

Let me describe an issue I came across multiple times when using shorebird.
It's not an issue that shorebird can fix, just mitigate.

Shorebird can't change native code. This means that developers have to be aware of what packages they add/update if they would like to push patches. What has happened to me many time is the following:

1. Release with shorebird, forget to tag release.
2. Start working on another feature.
3. Have an issue with Flutter, delete `pubspec.lock` file
4. Reinstall dependencies, some package that has binary code updates, can't use code push. Don't know what version was installed during release, so can't go back to original code.

This has happened to me multiple time, I'm assuming the above will happen to many people.

It would be really nice if the following showed after release:
```console
Tag this commit with `release+patch`
```
Or if shorebird saved the used dependencies and offered a downloadable `pubspec.yaml` & `pubspeb.lock` from the online console.

**Comment by bryanoltman** [comment]
I worry telling all users to tag the commit will make it seem like that is part of the Shorebird release/patch workflow, and I'm not sure we want to update Shorebird for a workflow that may not be shared among all users.

We also try very hard not to store code or anything that we don't absolutely need to patch (which includes the shorebird yaml). It might make sense for you to wrap the call to shorebird in a script that does this for you?
