### ISSUE TITLE
"Login system" not working after adding Shorebird

### ISSUE THREAD

**Issue by hasimyerlikaya** [shorebirdtech/shorebird#2081]
App ID:  
e769cd53-c6a4-46f7-9c68-ac5f76fba2a0

Hi,
I ran into a critical issue with the last version I released using Shorebird. I have no idea what the problem is, but I'm pretty sure it's Shorebird.

After releasing the app, it was rejected by Apple. Because the login system was not working. I encountered the same problem in my own tests and I can't identify the problem.

There is an error capture system in the app but no logs are generated. I couldn't find a way to detect the bug, so I had to release a new version without using Shorebird. 

When Shorebird supported Flutter 3.19.5 there was no problem. After Flutter 3.19.6 support came, this problem occurred.

Version of the app: 2.8.2+102
I thought you might want to check it out.

**Comment by bryanoltman** [comment]
We'd love to help. Do you see this issue when using Flutter 3.19.6 without Shorebird?

**Comment by hasimyerlikaya** [comment]
No, I don't have any problems.
I just published without Shorebird, and Apple has approved. 
Everything works fine now.

I think the Shorebird release had a network problem. Because I could not get any errors. 
If the problem was with my code, I could get at least an error report.

**Comment by bryanoltman** [comment]
Can you try running with `shorebird preview`? That will show you logs

**Comment by hasimyerlikaya** [comment]
Yeah, I will do that and will share logs.

**Comment by hasimyerlikaya** [comment]
I have tested three releases. 
It seems the last version of Flutter and Shorebird is working.
I could not find the reason for the error. 

- I use --dart-define-from-file argument to build the app with a config file that contains the base URL and tokens.
- After checking the releases for Android, I found that there is an error with Firebase on Version 2.8.2+102. I attached Logcat logs. This has nothing with login failure. But I think it might give an idea.
- I have no idea what the cause is. If there is anything that I can do more of, I would like to try it.


**Version: 2.8.3+103 - Working**
Shorebird 1.1.4
Flutter 3.19.6
```
✓ Fetching releases (0.5s)
Which release would you like to preview? 2.8.3+103
✓ Fetching runner artifact (0.2s)
✓ Downloading release (4.6s)
✓ Using production track (6ms)
✓ Using device Haşim’s iPhone (1.2s)
✓ Installing app (9.3s)
✓ Launching app (1.4s)
SANITY CHECK: Running precompiled code.
Using App.framework from /private/var/containers/Bundle/Application/C5F01F23-5381-4072-930E-69D3EC82F1C3/ios_2.8.3+103.app/Frameworks/App.framework
ASSET PATH /var/containers/Bundle/Application/C5F01F23-5381-4072-930E-69D3EC82F1C3/ios_2.8.3+103.app/Frameworks/App.framework/flutter_assets
No existing state file found: File /private/var/mobile/Containers/Data/Application/AFBAE0FA-1D76-4BED-9014-9BF85BDCCED8/Library/Application Support/shorebird/shorebird_updater/state.json does not exist, creating new state.
[INFO:shorebird.cc(173)] Shorebird updater: no active patch.
[INFO:shorebird.cc(177)] Starting Shorebird update
Sending patch check request: PatchCheckRequest { app_id: "e769cd53-c6a4-46f7-9c68-ac5f76fba2a0", channel: "stable", release_version: "2.8.3+103", patch_number: None, platform: "ios", arch: "aarch64" }
[INFO:FlutterViewController.mm(243)] CPU::Id(): simarm64
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
base_app_snapshot_instructions or base_app_snapshot_data is set but no link table is available, ignoring base snapshot.
Update thread finished with status: No update
```


**Version:2.8.2+102 - Not Working**
Flutter 3.19.6
```
✓ Fetching releases (0.5s)
Which release would you like to preview? 2.8.2+102
Which platform would you like to preview? iOS
✓ Fetching runner artifact (0.3s)
✓ Downloading release (3.8s)
✓ Using production track (6ms)
✓ Using device Haşim’s iPhone (1.2s)
✓ Installing app (11.9s)
✓ Launching app (1.5s)
SANITY CHECK: Running precompiled code.
Using App.framework from /private/var/containers/Bundle/Application/63EF13C5-DA7B-43F4-B29F-00CC80D18F2F/ios_2.8.2+102.app/Frameworks/App.framework
ASSET PATH /var/containers/Bundle/Application/63EF13C5-DA7B-43F4-B29F-00CC80D18F2F/ios_2.8.2+102.app/Frameworks/App.framework/flutter_assets
[INFO:shorebird.cc(173)] Shorebird updater: no active patch.
[INFO:shorebird.cc(177)] Starting Shorebird update
Sending patch check request: PatchCheckRequest { app_id: "e769cd53-c6a4-46f7-9c68-ac5f76fba2a0", channel: "stable", release_version: "2.8.2+102", patch_number: None, platform: "ios", arch: "aarch64" }
[INFO:FlutterViewController.mm(243)] CPU::Id(): simarm64
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
base_app_snapshot_instructions or base_app_snapshot_data is set but no link table is available, ignoring base snapshot.
Update thread finished with status: No update
```

**Android - Firebase log for Version: 2.8.2+102**
```
Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
FirebaseApp initialization unsuccessful

```

**Version:2.8.1+101 Working**
Flutter 3.19.5
```
✓ Fetching releases (0.5s)
Which release would you like to preview? 2.8.1+101
Which platform would you like to preview? iOS
✓ Fetching runner artifact (0.3s)
✓ Downloading release (3.6s)
✓ Using production track (6ms)
✓ Using device Haşim’s iPhone (1.1s)
✓ Installing app (11.1s)
✓ Launching app (1.4s)
SANITY CHECK: Running precompiled code.
Using App.framework from /private/var/containers/Bundle/Application/E64E48B9-4F61-4647-BDC5-12D4E10DD49E/ios_2.8.1+101.app/Frameworks/App.framework
ASSET PATH /var/containers/Bundle/Application/E64E48B9-4F61-4647-BDC5-12D4E10DD49E/ios_2.8.1+101.app/Frameworks/App.framework/flutter_assets
release_version changed 2.8.2+102 -> 2.8.1+101, creating new state
[INFO:shorebird.cc(173)] Shorebird updater: no active patch.
[INFO:shorebird.cc(177)] Starting Shorebird update
Sending patch check request: PatchCheckRequest { app_id: "e769cd53-c6a4-46f7-9c68-ac5f76fba2a0", channel: "stable", release_version: "2.8.1+101", patch_number: None, platform: "ios", arch: "aarch64" }
[INFO:FlutterViewController.mm(243)] CPU::Id(): simarm64
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
base_app_snapshot_instructions or base_app_snapshot_data is set but no link table is available, ignoring base snapshot.
Update thread finished with status: No update
```

[logcat.zip](https://github.com/shorebirdtech/shorebird/files/15317728/logcat.zip)

**Comment by bryanoltman** [comment]
Things that might be helpful:

1. Could you better explain what the actual problem is—what exactly do you mean by "the login system was not working"?
2. Do you have logs from a successful vs failed login (presuming some kind of error occurs and is logged)?
3. Can you share the `shorebird` commands you're running? It's possible you got unlucky when releasing `2.8.2+102` using Shorebird `1.1.0` – we've fixed several bugs since then, and if the release following that is working, there's a good chance the issue was caused by one of those bugs.

**Comment by hasimyerlikaya** [comment]
There were no errors in opening the app or any visual errors. Only during the login process the app shows a notification that an error occurred. I don't know the status of the other screens as I can't login.

The problem here is that normally the app has a complete error tracking system. When this error occurs, it should log an error to Sentry. Even this log does not occur. So probably the app can't use the internet connection at all.

When I compiled with Flutter commands and not with Shorebird, I was able to release the application without such a problem. It seems that there is a problem when compiling with Shorebird.

Shorebid was updated shortly after that error and with the latest version, there is no problem at the moment. 

`shorebird release ios -- --dart-define-from-file=config/config_prod.json`

This is the command and I don't think there is a problem with the command, because I have already released a few versions using this command. It was only during the release of 2.8.2 that this error occurred. 

Maybe it could be something caused by bugs like you said.

**Comment by bryanoltman** [comment]
Would you expect to see this behavior if `--dart-define-from-file=config/config_prod.json` were omitted from the release command? If so, this was an issue that was present in versions 1.1.0 and 1.1.1 and was fixed in 1.1.2 https://github.com/shorebirdtech/shorebird/releases/tag/v1.1.2

**Comment by hasimyerlikaya** [comment]
Yes exactly, the url and tokens for the API and Sentry were in this file. 
I think we found the cause of the problem.

We can close this issue as there is no problem now.

**Comment by bryanoltman** [comment]
Great! Glad we solved it, and sorry for the inconvenience. Let us know if you have any other issues!

**Comment by hasimyerlikaya** [comment]
I've learned a lot from this and I thank you for your help.
Shorebird is a project I care a lot about, I wish you success. 🙂
