### ISSUE TITLE
fix: Unable to generate release aar (shorebird release aar --release-version 1.0.0+1)

### ISSUE THREAD

**Issue by vineetpal88** [shorebirdtech/shorebird#2091]
App ID: com.shout.dating

I am implementing a shorebird for hybrid android app. I imported flutter module in my android app.
I open PowerShell and go to flutter module and run this command (shorebird release aar --release-version 1.0.0+1) but this command give me error:
PS D:\shoutproject\DatingFlutterCode3Shore\datingapp\shout2> shorebird release aar --release-version 1.0.28+29
✓ Fetching apps (0.6s)
⠸ Building aar with Flutter 3.19.6 (4b22a31bd9)... (16.4s)Failed to build aar: Instance of 'ArtifactBuildException'
![Screenshot 2024-05-14 134028](https://github.com/shorebirdtech/shorebird/assets/6236248/446cd02f-7047-4e04-80b0-86f1af0f7f22)

**Comment by vineetpal88** [comment]
@bryanoltman @erickzanardo Can you please help me on this?

**Comment by bryanoltman** [comment]
Does `flutter build aar` work with Flutter 3.19.6?

**Comment by vineetpal88** [comment]
aftr running flutter build aar got this error:
PS D:\shoutproject\DatingFlutterCode3Shore\datingapp\shout2> flutter build aar

Running Gradle task 'assembleAarDebug'...                           7.4s

You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying
Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugin
s with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply


FAILURE: Build failed with an exception.

Where:
Initialization script 'D:\flutter_sdk\flutter_windows_3.13.1-stable\flutter\packages\flutter_tools\gradle\aar_init_script.gradle' line: 129

What went wrong:
Failed to notify build listener.
assert moduleProject != null
         |             |
         null          false

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

Get more help at https://help.gradle.org/

BUILD FAILED in 7s


Gradle task assembleAarDebug failed with exit code 1.

**Comment by bryanoltman** [comment]
After some discussion on Discord, @vineetpal88 mentioned that they have integrated Flutter into their Android app using the "Module source code" method mentioned in https://docs.flutter.dev/add-to-app/android/project-setup#integrate-your-flutter-module. Shorebird does not yet support this mode of hybrid Android app.

**Comment by erickzanardo** [comment]
@bryanoltman should we close this issue in favor of a new one specific about adding this mode that we don't support?

**Comment by bryanoltman** [comment]
@erickzanardo yeah, I think that'd be best

**Comment by erickzanardo** [comment]
Closing this in favor of #2168
