### ISSUE TITLE
feat: Update Flutter to 3.22

### ISSUE THREAD

**Issue by maheshj01** [shorebirdtech/shorebird#2107]
**Description**

Please update shorebird to use the latest flutter 3.22, Additionally it would be nice if shorebird could support using the flutter sdk directly from github

**Requirements**

- [ ] Checklist of requirements to be fulfilled

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by eseidel** [comment]
Thanks!  We normally try to update to the latest flutter within a couple hours of release.  This one had a couple extra changes that needed to be made, so it took a day longer.  Flutter 3.22.0 support should be released in Shorebird in a few more hours.  We're testing the build now.
