### ISSUE TITLE
fix: delete app fails

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2116]
App ID: b3be02c7-97a8-4135-be71-814cc43d096e

It shows up in my list, but when I choose delete:
<img width="1114" alt="Screenshot 2024-05-16 at 10 22 12 AM" src="https://github.com/shorebirdtech/shorebird/assets/478541/77c482db-33ab-4b2b-b7ad-31305f9faffb">

I get an "insufficient permissions" error.

<img width="218" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/478541/ce6f6235-8539-4050-8f52-ea45fb6aa1db">

I presume it's not my app, I'm just a collaborator?  Not sure how I remove myself.

**Comment by eseidel** [comment]
I can't tell if I'm a collaborator because it just says:

https://console.shorebird.dev/apps/b3be02c7-97a8-4135-be71-814cc43d096e?tab=collaborators

<img width="736" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/478541/c188a3f9-f668-42bc-9909-91a8e5f478e7">

**Comment by felangel** [comment]
Yeah so in this case your account is on the hobby plan (which is why we block collaborator access) and you were added as a collaborator to an app which you don't own (therefore can't delete). We can definitely improve the ux in this case 👍

**Comment by eseidel** [comment]
This will go away when we re-write how we do teams.  I think we can close this in favor of https://github.com/shorebirdtech/shorebird/issues/739.
