### ISSUE TITLE
fix: shorebird patch was only able to share <32% has the effect of damaging other functions in the application

### ISSUE THREAD

**Issue by rizkijuliansyaham** [shorebirdtech/shorebird#2120]
App ID: 07cd66fe-e347-4bb8-a732-71980e94daad

**Description**

After I changed several functions that did not touch native changes (packages were included in the previous iOS release), the patch process showed results

"[WARN] shorebird patch was only able to share 29.4% of dart code with the released app."

I thought it would continue to run normally, but after the patch was installed, my application, which had previously saved session data on SQLite, had an error and immediately logged out, when I tried to log in again, an error appeared indicating a SQLite error.

**Steps To Reproduce**

I just carried out the ios patch process as usual

**Expected Behavior**

Expectations will run normally because there is only a slight change in 1 function

**Screenshots**

![WhatsApp Image 2024-05-17 at 09 58 12_9c4fe9fa](https://github.com/shorebirdtech/shorebird/assets/37908533/3217a3a4-4a19-42b8-8642-771531f9b261)

**Comment by felangel** [comment]
Hi @rizkijuliansyaham 👋 
Thanks for opening an issue! We're aware of this and are working hard to address it. See #1892 for more information 👍

**Comment by aloRanking** [comment]
add similar issue. after patching iOS. users app freezes on the splash screen. I had to quickly deactivated the patch.

<img width="644" alt="Screenshot 2024-05-13 at 19 35 19" src="https://github.com/shorebirdtech/shorebird/assets/23122626/9a672ad2-51d4-48fc-9d36-acea67cc6f4d">
<img width="518" alt="Screenshot 2024-05-13 at 19 37 37" src="https://github.com/shorebirdtech/shorebird/assets/23122626/baa62014-a065-4319-8645-06ab2d8b4b6d">


Thank you for everything you have been doing.

**Comment by eseidel** [comment]
I very much appreciate the feedback.  We're very close on having this resolved. As felix notes, we're tracking it on https://github.com/shorebirdtech/shorebird/issues/1892.

Right now in the wild we see about half of our customers having an excellent experience on iOS and about half of them having a poor (performance after patching) experience like you have here.  We're quite confident that we should be able to get to the state of all customers having an excellent experience soon.

**Comment by erickzanardo** [comment]
@rizkijuliansyaham we have recently released new versions of Shorebird that should increase the linking percentage. If you can upgrade and try again, we hope that you will see better results! Would love to get a feedback from you if you find time to try.

**Comment by eseidel** [comment]
Closing this in favor of https://github.com/shorebirdtech/shorebird/issues/1892.
