### ISSUE TITLE
when i run `shorebird release android --flutter-version 3.19.6`

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2132]
when i run `shorebird release android --flutter-version 3.19.6`
while output
```
 Failed to build: The current Flutter SDK version is 3.14.0-9.0.pre.2302.
Because my_app depends on flutter_markdown >=0.6.20 which requires Flutter SDK version >=3.16.0, version solving failed.
```

```
bin/cache/flutter/6d047e401941206daf11740c523ffa3364a2385b/bin/flutter --version 
Flutter 3.14.0-9.0.pre.3707 • channel [user-branch] • unknown source
Framework • revision 6d047e4019 (5 days ago) • 2024-05-15 15:27:44 -0500
Engine • revision c600950be8
Tools • Dart 3.4.0 • DevTools 2.34.3
```

_Originally posted by @Yongle-Fu in https://github.com/shorebirdtech/shorebird/issues/2114#issuecomment-2121799350_

**Comment by eseidel** [comment]
@yongle-fu. Let's move here, since the problem you're reporting is with `shorebird release` rather than `shorebird patch`.

Sounds like `--flutter-version` isn't working for you?

**Comment by Yongle-Fu** [comment]
Thank you so much! I found the reason for the issue. I fork the `shorebird_flutter` to Gitlab repository without pushing the new tags.

It appears that `flutter_tools` parses the `gitTagVersion` and writes to `frameworkVersion`.
```dart
final String frameworkVersion = gitTagVersion.frameworkVersionFor(frameworkRevision);
```

**Comment by eseidel** [comment]
@Yongle-Fu it sounds like you're using a fork of Shorebird?

**Comment by eseidel** [comment]
Sounds like this is resolved, closing for now.
