### ISSUE TITLE
fix: update flutter version warning in `shorebird doctor`

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2136]
```
✓ Shorebird is up-to-date (3.1s)
✗ Flutter install is correct (2.1s)
  [!] The version of Flutter that Shorebird includes and the Flutter on your path are different.
        Shorebird Flutter: 3.22.0
        System Flutter:    3.19.5
```

Maybe it should say "the version of Flutter on your path is not the latest Flutter stable"

But probably we should really just fix `shorebird release` to default to whatever version is on your path rather than warning about it.

Maybe then also make `shorebird release` warn (lightly) when using older --flutter-versions that there are newer versions of Flutter that may have more fixes from shorebird.

**Comment by wubaibin** [comment]
<img width="562" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/30898947/e44cf687-fa90-4e13-997b-d6d072de9ac5">
I sometimes need to switch versions when switching projects, but this always gives an error. Do I have to keep both versions the same? Or can I switch Shorebird Flutter versions

**Comment by eseidel** [comment]
I think we can remove this warning.  `shorebird` works with older versions of Flutter (back to 3.10.x: https://docs.shorebird.dev/flutter-version/), it's just older versions of Flutter don't always have all the latest fixes from Shorebird.  But I don't think we need to warn in doctor about this anymore with our `--flutter-version` support on `shorebird release`.
