### ISSUE TITLE
docs: explain how to use shorebird in a non-default location

### ISSUE THREAD

**Issue by arnzuk** [shorebirdtech/shorebird#2140]
Hi,

Looks like shorebird does not recognize non ascii characters in path on Windows machine. How to change shorebird cache path?

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin class 'FlutterAppPluginLoaderPlugin'.
   > Could not read script 'C:\Users\Arnoldas**Å½**ukauskasARP\.shorebird\bin\cache\flutter\6d047e401941206daf11740c523ffa3364a2385b\packages\flutter_tools\gradle\src\main\groovy\native_plugin_loader.groovy' as it does not exist.

**Comment by eseidel** [comment]
Feels related to https://github.com/shorebirdtech/shorebird/issues/2020.  We clearly need to improve our path handling a bit.

**Comment by eseidel** [comment]
Curious: does `flutter` work for you with projects within your home directory?  In our testing, it seems that non-ascii characters confuse `flutter` itself (which is unfortunate).

**Comment by eseidel** [comment]
Possibly related to https://github.com/flutter/flutter/issues/149162

**Comment by eseidel** [comment]
Amazingly Flutter's windows install instructions warns against paths and non-ascii chars in paths:
<img width="960" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/478541/8bbb434d-9b1d-4226-bf0f-a818c5af6291">

**Comment by christopherfujino** [comment]
> Possibly related to [flutter/flutter#149162](https://github.com/flutter/flutter/issues/149162)

it looks to me like that is just coincidentally a similar bug in another tool (there impellerc).

**Comment by eseidel** [comment]
I tested locally by taking a stock flutter (not shorebird) copying it (to `flutter2`) and then renaming `flutter2` to `test_flutter木`  and I also get failures from gradle when trying to run flutter out of `test_flutter木`

Even powershell seems confused by the 木.

This is the log from running a test within powershell within visual studio code:

```
PS C:\Users\micro> .\test_flutter?\bin\flutter create foo
Creating project foo...
Resolving dependencies in `foo`...
Downloading packages...
Got dependencies in `foo`.
Wrote 129 files.
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd foo
  $ flutter run

Your application code is in foo\lib\main.dart.

PS C:\Users\micro> cd .\foo\
PS C:\Users\micro\foo> ..\test_flutter?\bin\flutter run
Launching lib\main.dart on sdk gphone x86 64 in debug mode...

FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\micro\foo\android\settings.gradle' line: 20

* What went wrong:
Error resolving plugin [id: 'dev.flutter.flutter-plugin-loader', version: '1.0.0']
> Included build 'C:\Users\micro\test_flutter�?�\packages\flutter_tools\gradle' does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Running Gradle task 'assembleDebug'...                             15.1s
Error: Gradle task assembleDebug failed with exit code 1
```

**Comment by eseidel** [comment]
My sense is that as much as we would like to help, this is a deeper problem with `flutter` or `gradle` that is out of scope for us at the moment.  The only recommendation I have it to move your shorebird folder out of your home directory to a directory that only has ascii characters in the path.

Will leave this open for us to warn about this limitation during installation.  Ideally we'd figure out what the `flutter` or `gradle` bug tracking this is and link to such from such a warning, but I think we have to move on to other issues for now.  Thank you for reporting!

**Comment by eseidel** [comment]
Filed https://github.com/flutter/flutter/issues/149194 with Flutter and linked to some of the gradle issues there.

**Comment by eseidel** [comment]
I think we can close this for now.

**Comment by arnzuk** [comment]
> My sense is that as much as we would like to help, this is a deeper problem with `flutter` or `gradle` that is out of scope for us at the moment. The only recommendation I have it to move your shorebird folder out of your home directory to a directory that only has ascii characters in the path.
> 
> Will leave this open for us to warn about this limitation during installation. Ideally we'd figure out what the `flutter` or `gradle` bug tracking this is and link to such from such a warning, but I think we have to move on to other issues for now. Thank you for reporting!

Thanks for your efforts. Could you write how to move shorebird out of home directory?

**Comment by arnzuk** [comment]
> Curious: does `flutter` work for you with projects within your home directory? In our testing, it seems that non-ascii characters confuse `flutter` itself (which is unfortunate).

I installed flutter outside home directory. It is in c:\flutter

**Comment by eseidel** [comment]
I'll re-open to have us update our docs about moving shorebird.
