### ISSUE TITLE
fix: shorebird init deletes two files on network failure

### ISSUE THREAD

**Issue by marcorossitb** [shorebirdtech/shorebird#2141]
**Description**

When I run `shorebird init` inside my flutter project (after I did the login), it fails telling me:
```
[HTTP] POST https://oauth2.googleapis.com/token
Failed to obtain access credentials. Error: invalid_grant Bad Request Status code: 400
```

I noticed that just after running the init command these two files are being deleted:
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/example/<flutter_project_name>/MainActivity.kt

Inside the AndroidManifest.xml file there is the INTERNET permission so I suppose maybe that's the issue but I don't understand why my AndroidManifest.xml file is being deleted.

**Steps To Reproduce**

1. Go to the flutter project folder
2. Run shorebird login
3. Run shorebird init

**Expected Behavior**

`shorebird init` should successfully initialize my flutter project with Shorebird.

**Screenshots**

**Additional Context**

We're using fvm to handle flutter versions but atm I don't think this is a problem for my issue.

Log file attached
[1716479459995_shorebird.log](https://github.com/shorebirdtech/shorebird/files/15419340/1716479459995_shorebird.log)

**Comment by eseidel** [comment]
I wouldn't expect`shorebird init` to ever delete files.  😬 

Looks like the oauth login is failing `shorebird login`.  Are you by chance behind a proxy such that your network can't reach Google's oauth?

**Comment by eseidel** [comment]
In any case, we'd love to help.  What I understand from this message:
```
[HTTP] POST https://oauth2.googleapis.com/token
Failed to obtain access credentials. Error: invalid_grant Bad Request Status code: 400
```
is that the Google oauth is failing.  `shorebird login` uses OAuth (with Google or Microsoft) to get an oauth token (which is a way of those services attesting to you having logged in as some account with them).

We we use the same oauth mechanism as `pub login` or `firebase login` which involves starting a local server and opening a page in your browser which walks you though log-in with one of these providers and then posts the result to the local server.  So it's likely networking trouble which is causing this, either between your computer and Google.com, or maybe even a local firewall (preventing the local server).

I don't know w/o more information though.  But given that it's struggling to connect to oauth2.googleapis.com my guess is that there is something on your network between your computer and Google preventing this.

**Comment by marcorossitb** [comment]
Ok I tried to logout and login with my company VPN active (yesterday I tried without it) and now the init command completes successfully with no issue detected. Sorry for opening this 'noise' issue.

PS: I still see the two files mentioned above being deleted when the `init` command fails. By the way, I think it is a 'no-problem' because if `init` command fails, there are other reasons behind the failure that have to be solved before.
When the command is executed correctly, this problem doesn't occur.

Thank you very much Eric

**Comment by eseidel** [comment]
Going to re-open to look at the file deletion.

**Comment by bryanoltman** [comment]
This is indeed very surprising. The log makes it looks like we didn't get to the point of checking the AndroidManifest.xml for internet permission. Shorebird should also never touch your native Android code, so that is surprising as well. I'll try to reproduce this locally and see what I can find. Thanks for the detailed report!

**Comment by bryanoltman** [comment]
Having some trouble reproducing this. Would you mind running the login and init commands you mentioned above with the `-v` flag and sharing the output?

**Comment by bryanoltman** [comment]
I'm especially confused that `shorebird login` would succeed but `shorebird init` would show you the error `Failed to obtain access credentials. Error: invalid_grant Bad Request Status code: 400`

**Comment by marcorossitb** [comment]
So, I think there are two different issues here I encountered:

1. **Android files deletion**:
My first problem was the 'init' command failing, the two android files were deleted because 'init' command didn't finish in a success way.
Now that I initialized Shorebird in my flutter project properly, If I try to re-run the 'init' command it correctly says to me: `A "shorebird.yaml" file already exists and seems up-to-date. ...` AND the two android files keep being deleted . I have to undo the git changes to restore them.
Video here: 

https://github.com/shorebirdtech/shorebird/assets/100197915/2b38e673-1765-4623-8215-ff9060ebc532

2. @bryanoltman I'm not sure if it makes sense to running the login and init commands again because the issue I had was solved by logging out and logging in again.
One thing I can add to the context: I logged in to Shorebird cli the first time about 7 months ago, since then I never tried to init a project until last week. Again, logging out and logging in solved the init procedure.

**Comment by bryanoltman** [comment]
That is bizarre. Would you do me a favor and try running `shorebird init -v`? I'm curious what step would be deleting those files (it will almost certainly be a `gradlew` command, but I legitimately have no idea why that would delete anything)

**Comment by marcorossitb** [comment]
Video:

https://github.com/shorebirdtech/shorebird/assets/100197915/3e1e88be-ecdb-4597-b17c-d4a488740980

And log:
[1716972861229_shorebird.log](https://github.com/shorebirdtech/shorebird/files/15481673/1716972861229_shorebird.log)

**Comment by erickzanardo** [comment]
I am starting to get suspicious from this section of the log:

```
stderr:
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply
```

But I am having a hard time replicating this error locally. By looking at site that it suggests (https://flutter.dev/go/flutter-gradle-plugin-apply), seems that this error should happen in flutter projects created with flutter prior to version `3.16`. But I have tried with flutter `3.13.0` and I don't seem to be able to replicate it.

@marcorossitb would you mind sharing with us which Flutter were your project created? And which version is your shorebird CLI?

**Comment by marcorossitb** [comment]
I think the same thing, because yesterday I was trying to update gradle (so I was in a branch without Shorebird) and those files were eliminated (and created again) during my tests.
 
Our Flutter project was created 2 years ago with Flutter version: 2.2.3. Over the years we updated the version; today we're using 3.19.6. By the way, since our Flutter project is quite 'old' we have dependencies that aren't updated (also some internal packages).

I don't think you guys need to spend much more time on this issue because, as I said in a previous comment, my main issue was solved and I'm able to use Shorebird. This problem about the two Android files being eliminated is something related to Android e Gradle dependencies/configuration we have.

Shorebird CLI version: 1.1.6

For further context:
my buildscript block inside android/build.gradle file:

```
buildscript {
    ext.kotlin_version = '1.8.0'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

android/gradle/wrapper/gradle-wrapper.properties:

```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip
```

**Comment by erickzanardo** [comment]
It is very important to us to understand the cause of an issue, so we can make sure that nobody is blocked from using shorebird! So I really thank you for all the information and efforts to help us dig this up.

Since you are not blocked by the issue, and everything indicates that this is caused by an older gradle configuration, I am going to close this.

But feel free to add more comments if you, or anyone else with similar problems, face this issue again.

Thanks!
