### ISSUE TITLE
fix: logger progress, confirm, prompt, etc. output not captured in log files

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#2147]
`ShorebirdLogger` writes info, detail, error, etc to a log file, but output from prompts, confirms, progress, etc. are not captured. The logs would be more helpful if they were an exact copy of what the user sees when running a command with the -v flag.

**Comment by bryanoltman** [comment]
It's possible adding a stdout/stderr hook to `mason_logger` might be the solution here? @felangel wdyt?

**Comment by erickzanardo** [comment]
Or maybe `mason_logger` could support mirroring its output to a file? That would remove the need of `ShorebirdLogger` to even existing.

**Comment by felangel** [comment]
> Or maybe `mason_logger` could support mirroring its output to a file? That would remove the need of `ShorebirdLogger` to even existing.

Yeah that’s an interesting idea. Feel free to throw up an issue/proposal on mason 👍

**Comment by erickzanardo** [comment]
> Yeah that’s an interesting idea. Feel free to throw up an issue/proposal on mason 👍

Done: https://github.com/felangel/mason/issues/1338
