### ISSUE TITLE
If release exists but is not previewable on one or more platforms, explain in `shorebird preview` output

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#2154]
**Description**

If we don't have any sideloadable release artifacts for a platform, we don't display it as an option in `shorebird preview`. This can be confusing if, for example, a release is available on Android and iOS, only iOS devices are available, but the iOS release is not previewable (due to not being signed).

This would make situations like https://github.com/shorebirdtech/shorebird/issues/2153 more understandable.

**Comment by erickzanardo** [comment]
Solved by #2278
