### ISSUE TITLE
[shorebird] failed to generate shorebird configuration.

### ISSUE THREAD

**Issue by abh0440** [shorebirdtech/shorebird#2156]
Exception: Cannot find shorebird.yaml in /Users/aaa/Documents/Projects/pay-app/build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app/Frameworks/App.framework/flutter_assets/shorebird.yaml.

**Comment by bryanoltman** [comment]
We'd love to help, but it's not clear what you were doing that led you to this issue. Can you provide more info?

**Comment by erickzanardo** [comment]
Closing this in favor of https://github.com/shorebirdtech/shorebird/issues/2212 so we can track this issue in a single place.
