### ISSUE TITLE
feat: support Flutter 3.22.1

### ISSUE THREAD

**Issue by pawlowskim** [shorebirdtech/shorebird#2157]
**Description**

Add support for flutter 3.22.1

**Requirements**

- [x] Bump flutter version

**Additional Context**

Currently there is support for 3.22.0. But this version is bugged and fails to generate translations properly: https://github.com/dart-lang/sdk/issues/55758

It's getting annoyed when you rely on code generation and you need constantly manually generate the translations because of bug.

**Comment by eseidel** [comment]
Yeah, we're quite a bit later than normal on this one.  I expect we'll do this tomorrow.  Thanks for the reminder.

**Comment by eseidel** [comment]
@bryanoltman is doing the roll now, should be released in a couple hours.

**Comment by erickzanardo** [comment]
Shorebird `1.1.7` is still pointing to Flutter `3.22.0`

```
Shorebird 1.1.7 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.22.0 • revision f97740f758b5b145d687909bd09714c80875d772
Engine • revision fb9c410814a76272bdc5a66d5c3d7843b28b5ddb

✓ Shorebird is up-to-date (1.4s)
✓ Flutter install is correct (0.6s)
✓ Has access to storage.googleapis.com (0.2s)

No issues detected!
```

I believe we still need to roll out the new flutter version and publish a new shorebird version

**Comment by bryanoltman** [comment]
@erickzanardo Correct. We're currently waiting for the engine artifacts to compile. Once those are done, we need to update https://github.com/shorebirdtech/flutter to point to the new engine version, and then update the CLI to point to that updated Flutter.
