### ISSUE TITLE
More loudly inform users if they are not using the latest version of Shorebird CLI

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#2179]
We could also just update for them?

**Comment by eseidel** [comment]
This would help us get rid of the entire class of "my shorebird was old" failure cases.  In general `shorebird` and `api.shorebird.dev` are tightly coupled so we don't support old versions of `shorebird` and should be much more aggressive about updating.  I think auto-updating would be fine.

**Comment by bryanoltman** [comment]
Dupe, closing in favor of https://github.com/shorebirdtech/shorebird/issues/1910
