### ISSUE TITLE
feat: A way to pass a build number and version to shorebird build

### ISSUE THREAD

**Issue by aikins01** [shorebirdtech/shorebird#2197]
**Description**

So let's say I am not obeying semver or using my own versioning style, there isn't a way i know of currently to pass the versioning information to shorebird, it just assumes and picks the version info from pubspec, so using it in a CI pipeline with custom versioning is somehow hard because let's say i use fastlane with my custom versioning, or even if i use semver I can't pass that to shorebird in my pipelines

**Comment by eseidel** [comment]
Shorebird doesn't actually read out of the pubspec.yaml, but from the Info.plist or AndroidManifest.xml from within the compiled app itself.  We do this because sometimes developers have custom versioning setups in their build setups, so we want to read exactly the same version information which is presented to the stores.

So in short, if you're able to get the stores to reflect your versioning scheme in their reported numbers, Shorebird should respect it.  If for some reason that breaks with Shorebird, please let us know, we'd love to work with you to fix!

**Comment by aikins01** [comment]
I thought the commands to build and patch were shorebird build/patch [ios/android] which does its own build so I'm pretty sure you're right but the issue still stands I'm passing the versioning info to flutter to build for the store in my CD pipeline like

`flutter build appbundle --build-number 117 --build-name 27.10.14 --target lib/main.dart`

so I don't get if build and patch with shorebird will work

**Comment by eseidel** [comment]
`shorebird release` and `shorebird patch` are the commands you'll want to use:
https://docs.shorebird.dev/code-push/release/
https://docs.shorebird.dev/code-push/patch/

There is a hidden `shorebird build` command, but use of such is not recommended.

`shorebird release android -- --build-number 117 --build-name 27.10.14 --target lib/main.dart` should "just work".  You can use `--` to indicate that you want the rest of the arguments passed directly to `flutter build` (skipping `shorebird`'s argument parsing).

**Comment by aikins01** [comment]
What are the disadvantages,
because using just `shorebird release` gets me `1.4.0+1` and that's not my version built for the stores so patches don't work, a bit confusing to me

**Comment by eseidel** [comment]
`shorebird build` doesn't tell our servers about the built app, so it can't later be patched.  `shorebird release` actually uses `shorebird build` under the covers, so you don't need to call it directly.

The command I listed above, should build with your intended release number:
`shorebird release android -- --build-number 117 --build-name 27.10.14 --target lib/main.dart`

You can pass any argument you would normally pass to `flutter` to `shorebird`, just pass it after the `--`

**Comment by aikins01** [comment]
Alright, awesome! thanks I thought the disadvatage was with the release command instead

**Comment by eseidel** [comment]
My understanding from the above is there isn't anything for us to change? If there are docs that would have helped you, or ways you believe we could improve the product here, please let us know.
