### ISSUE TITLE
fix: previous patch was installed after recent patch had been installed.

### ISSUE THREAD

**Issue by hayatshin** [shorebirdtech/shorebird#2198]
I'm not sure, but from my device I guess my app, that had been patched the most recent one, went behind previous patch again.

<img width="1044" alt="스크린샷 2024-06-04 오후 11 14 32" src="https://github.com/shorebirdtech/shorebird/assets/82467520/cc409b33-1285-4093-be0d-0faaeecc9deb">

patch 6 is the most recent one, and submitted this patch 1 day ago.
And previous patches became 'inactive'.
(patch 5 was also submitted 1 day again but, of course, before patch 6)

<img width="1060" alt="스크린샷 2024-06-04 오후 11 15 36" src="https://github.com/shorebirdtech/shorebird/assets/82467520/274e41f7-5fdd-49d3-accd-f0a96b20afe0">

But if you see my Insight page, patch 5 is also installed on 6/4 either even though patch 5 became inactive on 6/3.

1.
Inactive patch can be installed?

2.
And I wonder if it can be also possible scenario that user's app get patch 6, and **later**, patch 5 or patch 4 overrides the recent patch. Or previous patch overrides the recent one then the recent one overrides again.. something like this. 

3.
I found that deletion of previous patch is possible now from console in reply of this below post.
https://github.com/shorebirdtech/shorebird/issues/1380

But I can't find any button yet. Is this right information?

**Comment by eseidel** [comment]
What's happening here is that we report install events with a lag (on next launch after install).  And we record the *server time* (in utc) when we received the install event, not the install time on the device.  We just need to fix this, since you're not the only person who's found this confusing.

https://github.com/shorebirdtech/updater/issues/131
https://github.com/shorebirdtech/shorebird/issues/1761

**Comment by hayatshin** [comment]
@eseidel Thanks for the fast reply. 
Then should I submit patch once again for user to get the most recent patch, or if we wait, user will get the most recent one at the end? 
Since another 1 day pasted and even the most recent patch installation becomes 0 (maybe all installation work is finished), my device function is not updated as the most recent patch version.

<img width="1040" alt="스크린샷 2024-06-05 오전 9 13 50" src="https://github.com/shorebirdtech/shorebird/assets/82467520/8c945cbb-e312-447e-92bb-e597e763bb3f">

**Comment by eseidel** [comment]
As soon as you submit patch 2, patch 1 is immediately disabled.  No user will get a new download of patch 1.  However you might still see patch 1 install events (possibly days or weeks later, depending on how often users launch the app) due to users who has installed patch 1, but not yet restarted their app (since we only send events to our server during patch checks, which happen only during app start).  We should fix this since you're not the only person who has found this confusing.

**Comment by hayatshin** [comment]
@eseidel But my device is not updated as the most recent version of patch and even I tried once again yesterday, but still app is not updated. my App Id is 9eec7268-5f03-4b98-830a-7f465cde0773. Can you check this..?

+) I realized that another app is updated but my app is not updated even I killed my app and restart it several times.
Is there any circumstance that shorebird patch can not be applied?

**Comment by eseidel** [comment]
@hayatshin I would love to help, but I'm not sure I understand what is being asked.

> @eseidel But my device is not updated as the most recent version of patch and even I tried once again yesterday, but still app is not updated. my App Id is 9eec7268-5f03-4b98-830a-7f465cde0773. Can you check this..?

Sounds like you're suggesting that the app is not updating as you expect?
https://docs.shorebird.dev/troubleshooting/ discusses some common failures.  Looking at the logs from the device might help.  There is definitely more debugging information we could expose in the console to help.

The most common reason why a patch isn't applied is that the patch is made against a different binary than is installed on the device.  `shorebird release` saves off a private copy of your built app on our servers that then is used by `shorebird patch` to compare against when making the patch file.  That patch file is then only valid for *exactly* binaries matching the one saved with `shorebird release`.  If somehow a different binary was distributed to the stores then patches won't apply (and will log a failure message in the device logs explaining why).

**Comment by erickzanardo** [comment]
@hayatshin just checking if Eric's advise helped on realizing why the patch wasn't applied or if you still feel this is an issue/need help?

**Comment by hayatshin** [comment]
@erickzanardo yes you can close this issue

**Comment by erickzanardo** [comment]
> @erickzanardo yes you can close this issue

Thanks for reporting back!
