### ISSUE TITLE
feat: Check for Flutter version match when running `shorebird doctor`

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#220]
**Description**

Shorebird uses a specific version of Flutter (the latest stable channel). This may be different than what the user has installed on their system. `shorebird doctor` should show an error (or at least a very loud warning) if these versions do not match.

**Requirements**

- [ ] `shorebird doctor` checks that shorebird's Flutter version and the "system" Flutter version are the same
- [ ] `shorebird doctor` raises a warning/error if they are not

**Additional Context**

See https://github.com/shorebirdtech/shorebird/blob/eb4d8223946a96a2d787ee05faa234a88ebbf0b3/packages/shorebird_cli/lib/src/command_runner.dart#L77-L92 for where this check currently happens.

**Comment by eseidel** [comment]
`shorebird doctor` can give a warning, but the warning might be more important to give in `shorebird build` (or any time we build)?  Not sure. Will just have to try and see how it feels in the field.

**Comment by bryanoltman** [comment]
Agreed – we'll probably want to be loud about this in multiple places (basically everywhere)
