### ISSUE TITLE
fix: `shorebird patch ios` sometimes erroneously reports native changes

### ISSUE THREAD

**Issue by Badar25** [shorebirdtech/shorebird#2210]
App ID: 4ec0aa9c-332b-40bf-9b75-0118c39cc8a0

**Description**  
This is the second time I've encountered this issue. When I upload a build with Shorebird, release it, and then attempt to push a patch after a few days, I receive an error stating that there are native changes in runner.app. However, I haven't made any changes to the native code; all my modifications were on the Dart side. I'm wondering what could be causing this problem.

**Steps To Reproduce** 

**Expected Behavior**

A dart side changes should push the code as no native changes were made. (iOS)

**Screenshots**
<img width="942" alt="Screenshot 2024-06-10 at 8 02 07 PM" src="https://github.com/shorebirdtech/shorebird/assets/122623475/4e6efb8d-38cf-49d3-83ea-d84713efa4ac">

**Additional Context**

FYI, I'm selecting the exact build numbers from available list.

**Comment by Badar25** [comment]
Android side is working fine

**Comment by eseidel** [comment]
Thank you for the clarification.  I would not expect `shorebird release android` to take any longer than `flutter build aab` does (since `shorebird release android` just calls `flutter build aab` under the covers.  Something else must be going wrong inside our wrapper.

**Comment by eseidel** [comment]
We've seen this happen when the version of xcode changes, or when the path to the project changes.  Not sure if either of those could have happened here.

**Comment by Badar25** [comment]
No no, nothing has been changed at all.

**Comment by erickzanardo** [comment]
Related to #2065

**Comment by eseidel** [comment]
We could provide more information, e.g. https://github.com/shorebirdtech/shorebird/issues/2226

**Comment by Badar25** [comment]
Now I'm facing the same issue in android as well
<img width="1009" alt="Screenshot 2024-06-13 at 4 44 05 PM" src="https://github.com/shorebirdtech/shorebird/assets/122017969/231a96f0-f193-409e-ad46-7837867cf654">

**Comment by Badar25** [comment]
I just want to clarify one thing that I haven't changed anything not my Android studio nor XCode and not even Flutter version. I have even pushed a patch few days ago but now after changing a simple code there I'm seeing this.

Please tell me if I'm missing something?

**Comment by bryanoltman** [comment]
It's possible that a dependency was updated between the release and the patch. If you create a new release and immediately patch it, do you see this warning?

**Comment by Badar25** [comment]
No i dont see that at that time

**Comment by bryanoltman** [comment]
So it seems likely that a dependency with native components changed in between the release and the patch (presuming you did not change any Kotlin/Java code yourself). Do you track your pubspec.lock file in source control? If not, doing so will help you better understand when dependencies are changing.

**Comment by bryanoltman** [comment]
We've had another report of this https://discord.com/channels/1030243211995791380/1251192724640497749 (app id: `cd8b0f16-7090-4d88-bfa2-42d0fd649b8d`) for iOS. The user shared their release and patch xcarchive files, along with pubspec and pod (+lock) files. In an attempt to reproduce, I created a new flutter app and copied their pubspec file, and ran patch immediately after release. No warnings were shown.

**Comment by bryanoltman** [comment]
Files are available on the shorebird drive at https://drive.google.com/drive/folders/1jFtpZUGEuqKinoEifpiaN_5x6ryMnfpQ (internal only)

**Comment by bryanoltman** [comment]
With the following pubspec, I'm seeing native changes reported roughly half the time (even when running `shorebird patch ios` back-to-back for the same release):

```yaml
name: native_ios_changes
description: "A new Flutter project."
publish_to: none
version: 1.0.0+46

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  package_info_plus: ^8.0.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - shorebird.yaml
```

After removing the signatures from the release and patch mach o files, the diff is still very noisy in Hex Fiend: ![Screenshot 2024-06-17 at 3 16 35 PM](https://github.com/shorebirdtech/shorebird/assets/581764/2365afcf-ab53-4703-9f86-d7cd2726ff40)

I'm starting to look in [XMachOViewer](https://github.com/horsicq/XMachOViewer). The closest thing I have to a lead right now is that with this diff (and with others that I've seen), one mach-o file will have a `___chkstk_darwin` entry in the symbol table and the other will not

![Screenshot 2024-06-17 at 4 45 01 PM](https://github.com/shorebirdtech/shorebird/assets/581764/ed91067d-4d49-4a9e-990d-37077323b83a)

**Comment by eseidel** [comment]
These are the changes: https://gist.github.com/eseidel/7f9aee57fc1f756cc3d0313b85e7b9f3

**Comment by bryanoltman** [comment]
This has been fixed by https://github.com/shorebirdtech/shorebird/issues/2257, which will go out in our next Shorebird CLI release.
