### ISSUE TITLE
[shorebird] failed to generate shorebird configuration.

### ISSUE THREAD

**Issue by PhaHoeun** [shorebirdtech/shorebird#2212]
```
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Xcode build done.                                           99.4s
[shorebird] failed to generate shorebird configuration.
Exception: Cannot find shorebird.yaml in /Users/macos/Workspace/dihrms-mobile-webview/build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app/Frameworks/App.framework/flutter_assets/shorebird.yaml.
Please file an issue at: https://github.com/shorebirdtech/shorebird/issues/new

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

Exited (1).
```

**Comment by eseidel** [comment]
With 4 other reports like this, we clearly have something going wrong here.  🤔  https://github.com/shorebirdtech/shorebird/issues/2206 https://github.com/shorebirdtech/shorebird/issues/1914 https://github.com/shorebirdtech/shorebird/issues/2131 https://github.com/shorebirdtech/shorebird/issues/2212

**Comment by eseidel** [comment]
Thank you for the report!

**Comment by PhaHoeun** [comment]
Sorry! I couldn't find the solution. Could you drop it here?

**Comment by eseidel** [comment]
> Sorry! I couldn't find the solution. Could you drop it here?

You didn't do anything wrong. :) I was just linking to other issues with the same cause so we could find them all when we went to fix this.  I expect we should be able to fix it later this week. Sorry for the trouble!

**Comment by PhaHoeun** [comment]
Thank you!

**Comment by erickzanardo** [comment]
Hey @PhaHoeun , can you share exactly which command where you running when you got that error?

And if you still facing the issue, could you rerun the command with the `-v` flag and share the full logs?

Thanks

**Comment by PhaHoeun** [comment]
This error appeared after I check-out my git to new branch. I try to uninstall shorebird from my MacBook then reinstall. It's worked.

**Comment by PhaHoeun** [comment]
> Hey @PhaHoeun , can you share exactly which command where you running when you got that error?
> 
> And if you still facing the issue, could you rerun the command with the `-v` flag and share the full logs?
> 
> Thanks

When running my project on simulator.

**Comment by bryanoltman** [comment]
Shorebird doesn't support running on simulators. Does this still happen if you try running on a physical device?

**Comment by eseidel** [comment]
We'd love to help more. If you're still interested in pursuing with us Discord might be a more immediate venue: https://discord.gg/shorebird.
