### ISSUE TITLE
fix: run xcodebuild archive fails with shorebird wrapper but not with flutter build

### ISSUE THREAD

**Issue by zphoenixz** [shorebirdtech/shorebird#2213]
# Description
### Running 
`xcodebuild archive -workspace /Users/vagrant/git/apps/mobile/ios/Runner.xcworkspace -scheme staging -configuration Release-staging -xcconfig /var/folders/7l/DDD/3614073906/temp.xcconfig -archivePath /var/folders/7l/DDD/T/xcodeArchive5/Runner.xcarchive -allowProvisioningUpdates -authenticationKeyPath /var/folders/7l/DDD/T/AuthKey_CCC.p8 -authenticationKeyID BBB -authenticationKeyIssuerID AAA -destination generic/platform=iOS`

### after 
`shorebird release ios --flutter-version 3.22.1 --flavor staging --target lib/main_staging.dart --no-codesign -- --build-number=1`
Produces error log
getting The sandbox is not in sync with Podfile.lock

```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/vagrant/Library/Developer/Xcode/DerivedData/Runner-gpnyuywmbkdtfmhbirltompooamc/Build/Intermediates.noindex/ArchiveIntermediates/staging/IntermediateBuildFilesPath/Runner.build/Release-staging-iphoneos/OneSignalNotificationServiceExtension.build/Script-5675D3EB7794E33E28263CC9.sh (in target 'OneSignalNotificationServiceExtension' from project 'Runner')
    cd /Users/vagrant/git/apps/mobile/ios
    /bin/sh -c /Users/vagrant/Library/Developer/Xcode/DerivedData/Runner-gpnyuywmbkdtfmhbirltompooamc/Build/Intermediates.noindex/ArchiveIntermediates/staging/IntermediateBuildFilesPath/Runner.build/Release-staging-iphoneos/OneSignalNotificationServiceExtension.build/Script-5675D3EB7794E33E28263CC9.sh
diff: /Users/vagrant/git/apps/mobile/ios/Pods/Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
...
....
note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
warning: Run script build phase 'Copy Firebase Config' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
warning: Run script build phase 'Crashlytic Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-Core' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-C++' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'BoringSSL-GRPC' from project 'Pods')
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Copy\ dSYMs /Users/vagrant/Library/Developer/Xcode/DerivedData/Runner-gpnyuywmbkdtfmhbirltompooamc/Build/Intermediates.noindex/ArchiveIntermediates/staging/IntermediateBuildFilesPath/Pods.build/Release-staging-iphoneos/flutter_unity_widget.build/Script-773B04A426ECE8171934383559C6B40C.sh (in target 'flutter_unity_widget' from project 'Pods')
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/vagrant/Library/Developer/Xcode/DerivedData/Runner-gpnyuywmbkdtfmhbirltompooamc/Build/Intermediates.noindex/ArchiveIntermediates/staging/IntermediateBuildFilesPath/Runner.build/Release-staging-iphoneos/OneSignalNotificationServiceExtension.build/Script-5675D3EB7794E33E28263CC9.sh (in target 'OneSignalNotificationServiceExtension' from project 'Runner')
(2 failures)
```
### But if you do it the normal way
`flutter build ios --flavor staging --target lib/main_staging.dart --build-number=1 --no-codesign`

It succeeds.

# Expected Behavior

shorebird shouldn't affect xcodebuild archive output

# Screenshots

described above
# Additional Context
Running in Bitrise WF.
Flutter 3.22.1
Shorebird 1.1.10

**Comment by bryanoltman** [comment]
Shorebird using `flutter build ipa`, not `flutter build ios`. I'd be curious if you saw the same issue running `flutter build ipa`. (Not a solution, just trying to diagnose the issue). Is [this answer](https://stackoverflow.com/a/63332765) useful?

**Comment by zphoenixz** [comment]
> Shorebird using `flutter build ipa`, not `flutter build ios`. I'd be curious if you saw the same issue running `flutter build ipa`. (Not a solution, just trying to diagnose the issue). Is [this answer](https://stackoverflow.com/a/63332765) useful?

I tried running pod install even cleaning pods and installing again, still same issue

I haven’t tested build ipa

**Comment by bryanoltman** [comment]
`shorebird release ios` creates an xcarchive in the build directory. Is that usable? I haven't seen the `xcodebuild archive` as part of a workflow before, so maybe I'm misunderstanding something.

**Comment by zphoenixz** [comment]
> `shorebird release ios` creates an xcarchive in the build directory. Is that usable? I haven't seen the `xcodebuild archive` as part of a workflow before, so maybe I'm misunderstanding something.

Would you suggest to remove `--no-codesign` and then also remove the `xcodebuild archive` step? 

I am not that much familiar with ios ci, what I want to achieve is to have a properly signed file to upload to firebase distribution and appstore, currently working on a Bitrise WF, and of course I also want to keep shorebird code push capabilities

**Comment by bryanoltman** [comment]
`shorebird release ios` with `--no-codesign` should sign your app for you. The CI will need to be able to locate your certs, etc. I'm not personally familiar with Bitrise. I'm guessing you're following [getting started with Flutter apps](https://devcenter.bitrise.io/en/getting-started/quick-start-guides/getting-started-with-flutter-apps.html)?

**Comment by zphoenixz** [comment]
> `shorebird release ios` with `--no-codesign` should sign your app for you. The CI will need to be able to locate your certs, etc. I'm not personally familiar with Bitrise. I'm guessing you're following [getting started with Flutter apps](https://devcenter.bitrise.io/en/getting-started/quick-start-guides/getting-started-with-flutter-apps.html)?

Understood, so there is no way to just do flutter build ios with shorebird?

**Comment by zphoenixz** [comment]
I am closing this issue in the meantime since it seems to be more related with the unnecessary archive step than with the export step

**Comment by halldorlogi** [comment]
@zphoenixz where you able to achieve your goal of uploading a Shorebird release build to Firebase Distribution via Bitrise?
I am running into the same issues as you are with the "The sandbox is not in sync with the Podfile.lock".
Just curious if you found a way past this.
