### ISSUE TITLE
fix: Using shorebird causes an exception when installing the app

### ISSUE THREAD

**Issue by lzwt** [shorebirdtech/shorebird#2214]
App ID: (insert your app ID here)
90539087-cb91-4e3c-8f5b-a1112000cbf6

**Description**
When I do not use shorebird to generate apk, I have no problem installing apk in my app. When I use shorebird to generate apk installation, I will fail to install apk

**Expected Behavior**
install success

**Comment by erickzanardo** [comment]
Can you share more info? Does it have an error message? Or some logs?

If you do shorebird preview, does it works?

**Comment by eseidel** [comment]
We have seen similar reports of exceptions during install. They've typically been `adb` errors.  One possible cause is the app already being installed, but signed with a different key https://github.com/shorebirdtech/shorebird/issues/2113.

**Comment by eseidel** [comment]
We would love to help, but we would need more info.  If you have more info to share, please feel empowered to reopen with more info.
