### ISSUE TITLE
feat: pay-as-you-go

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2223]
Our current pricing model was designed to be maximally simple to implement.  We offer a few tiers, all monthly pre-paid.  We don't attempt to roll credits over between months and do not support invoicing.

So far it's worked OK, but I think many users would prefer some sort of "pay as you go" rather than our current pre-committed usage model.  This would also imply post-usage billing/invoicing as well as presumably keeping some kind of pre-committed discounts (possibly at our current prices).

I don't think this is blocking many users from adopting the product, but I do think it's needless friction for some.

**Comment by eseidel** [comment]
Bryan and I wrote up a design doc this morning and he's now exploring what this would take for us to implement.

**Comment by eseidel** [comment]
Bryan has configured some prototype stripe plans and coded up the backend job which reports usage to stripe. He's currently working through remaining issues on our server side and console.  We still have some decisions before launch, but I suspect we could launch PAYG as soon as next week.

**Comment by eseidel** [comment]
We've built "pay as you go" support for Shorebird, it's in "beta".  If you'd like to try it out (instead of our current public plans), please email us at contact@shorebird.dev

**Comment by eseidel** [comment]
We're also more generally welcoming of feedback on our billing approach in general.  What we have today (pre-paid monthly billing) was just what we threw together as quick as we could about a 18 months ago when launching our first product.  Now with our 1.0 out, and thousands of customers happily using Shorebird every month across iOS and Android, we're working on re-doing some of the guts of our billing infrastructure.  If you have feedback as to how you'd prefer to purchase Shorebird that's always very welcome. Bryan and I can be reached directly via contact@shorebird.dev.

**Comment by eseidel** [comment]
Bryan has been re-working our billing system over the last couple weeks to support more advanced billing cases.  (Currently we only support pre-paid monthly batches of patches.)  We're considering supporting either invoicing for "overages" (with a limit), or being able to buy "patch installs" in blocks of credits (with longer than 1mo expiry).  I'd be curious if any of those interested in pay as you go have an opinion as to which would fit better for your billing needs.

**Comment by bryanoltman** [comment]
This is now live
