### ISSUE TITLE
fix: usage of Github Actions + Fastlane + Shorebird

### ISSUE THREAD

**Issue by fabio-guerreiro** [shorebirdtech/shorebird#2239]
App ID: e2e1fe08-2572-4131-95a2-293a51e7350d

**Description**

We're currently using Github action and fastlane to release our app.

Currently, our setup to build and upload our app to TestFlight is the following:
```ruby
    Dir.chdir "../.." do
      sh("flutter build ios --release --no-codesign --split-debug-info=build/symbols --obfuscate")
    end
    
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
    )
    upload_to_testflight(itc_provider: "SOME_PROVIDER", api_key_path: 'path_to_key')
```

What would be the equivalent using Shorebird?

**Additional Context**

We've tried the following:
```ruby
    Dir.chdir "../.." do
      sh("shorebird release ios --no-codesign -- --release")
    end
```
However, we're not seeing the resulting `.ipa` as we do after the `build_app` step. Do we need the extra step of `build_app` before uploading to TestFlight? 

Thanks for any help and keep the good work!

**Comment by erickzanardo** [comment]
Hey 👋 

I am unsure why your lane is not finding the ipa. But either way, I would suggest you checking out the Fastlane guide that @bryanoltman wrote yesterday (fresh from the oven!).

Hopefully it will make your fastlane configuration simpler and solve the issue

https://docs.shorebird.dev/ci/fastlane/

**Comment by bryanoltman** [comment]
We just added a fastlane plugin yesterday! The source is at https://github.com/shorebirdtech/fastlane-plugin-shorebird/, and you can read the guide at https://docs.shorebird.dev/ci/fastlane/. When using the `upload_to_testflight` step, I needed to provide a path to my ipa, which you can see illustrated in the guide.

**Comment by bryanoltman** [comment]
Going to close because I think this has been addressed, but please feel free to reopen if not or to open a new issue if you run into any problems.
