### ISSUE TITLE
feat: Using `Icons.xxx` in a patch will cause assets changes

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#2246]
**Description**

If you uses a material icon in a patch that didn't had used it before, generating a patch that uses an icon will trigger assets changes.

This makes sense since Flutter's tree shaking will not include things that aren't being used, but since all that was changed in the patch is dart code, this might confuse the user.

I am unsure what is solution here, maybe docs, maybe we handle this specific case with a specific message, or maybe this will just go away by doing Asset support (#318)

**Additional Context**

To see this happening:

1- Create an app and have your `main.dart` as follows:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello, World!')
        ),
      ),
    ),
  );
}
```
2- Generate the release
3- Apply this change

```diff
     const MaterialApp(
       home: Scaffold(
         body: Center(
-          child: Text('Hello, World!')
+          child: Icon(Icons.cyclone),

         ),
       ),
     ),
```

4- Generate a patch
5- See the warning
![Screenshot 2024-06-14 at 14 01 49](https://github.com/shorebirdtech/shorebird/assets/835641/55019b3f-eef9-433e-a518-a67b1c1aa4a5)

**Comment by bryanoltman** [comment]
This is known and expected https://docs.shorebird.dev/troubleshooting/#i-see-a-the-release-artifact-contains-asset-changes-warning-when-running-shorebird-release-asset-changes

**Comment by erickzanardo** [comment]
> This is known and expected https://docs.shorebird.dev/troubleshooting/#i-see-a-the-release-artifact-contains-asset-changes-warning-when-running-shorebird-release-asset-changes

Right! I didn't know we had this section in the docs. I guess we can close this then, sorry for the confusion.
