### ISSUE TITLE
fix:  Shorebird preview --platform ios No iOS 17+ device found, looking for devices running iOS 16 or lower 

### ISSUE THREAD

**Issue by Khaled-Eldeeb-BW** [shorebirdtech/shorebird#2256]
App ID: 0368e2c5-a11b-4e69-afdc-6014b74836c1

**Description**

When using shorebird preview and selecting ios and prod flavor, it shows the following 

<img width="826" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/119858148/96c948d4-00f7-43ac-8793-84a04aa96d14">

**Steps To Reproduce**

1. run shorebird preview 
2. select prod flavor 
3. select the latest release version
4. select IOS

**Expected Behavior**

To run on the running 17.5 simulator instance I have or atleast let me choose which simulator to run on

**Additional Context**

I have just upgraded xcode to use IOS 17.5 and Simulator 17.5

**Comment by Khaled-Eldeeb-BW** [comment]
Shorebird 1.1.11 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.22.2 • revision c20374bd2ceb8bdff113cce13a4bb6180021d958
Engine • revision 14449967f2149612759c8c2fd7527dc3114d3934

**Comment by Khaled-Eldeeb-BW** [comment]
"xcrun devicectl list devices"  doesnt show any devices but  "xcrun simctl list devices"    shows 


`
khaledeldeeb@Khaleds-MacBook-Pro BluworksFlutter % xcrun devicectl list devices -v         
Using verbose logging.
No devices found.

Command Completed, took 1.008 seconds

khaledeldeeb@Khaleds-MacBook-Pro BluworksFlutter % xcrun simctl list devices      

== Devices ==
-- iOS 17.5 --
    iPhone SE (3rd generation) (40BB8EB6-7282-46B8-9ED9-B6E36CC35A78) (Shutdown) 
    iPhone 15 (4F6B477D-836C-460F-B57F-78BA128FFE84) (Shutdown) 
    iPhone 15 Plus (89A3688E-4DD2-4AE2-976E-13851175CA9F) (Shutdown) 
    iPhone 15 Pro (5BA487CD-17C3-423F-BA35-FC3680FBA87C) (Booted) 
    iPhone 15 Pro Max (640F8666-A52F-4DD2-A535-D4C3FDA7A476) (Shutdown) 
    iPad (10th generation) (BE756B9C-C1A3-4E93-AEAE-E35AD9EEEB05) (Shutdown) 
    iPad mini (6th generation) (BED28D34-207C-481C-9DAF-B6075C0B01B2) (Shutdown) 
    iPad Air 11-inch (M2) (E0C3C42A-C043-4458-99AF-2CA09E14C9A8) (Shutdown) 
    iPad Air 13-inch (M2) (31E852BB-00B5-49EC-9FE3-8FEFF0925519) (Shutdown) 
    iPad Pro 11-inch (M4) (6A1E6044-F44B-45CD-8D9C-DD0D0A9FDC78) (Shutdown) 
    iPad Pro 13-inch (M4) (AA70AFF8-3732-4DAE-A253-BAE3D546D7D5) (Shutdown) 
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-17-0 --
    iPhone SE (3rd generation) (1C56398C-8E53-4F6D-97D4-B821DC664577) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPhone 15 (2C499AE1-A630-4A42-B11C-11862024044B) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPhone 15 Plus (88DB9EF5-6406-4619-B506-464530412D4A) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPhone 15 Pro (BC6FDEC3-CC0C-450F-BBF0-F217A7FD1D7C) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPhone 15 Pro Max (1DEB5343-3DA0-4FA2-B0C9-201242AD0DDE) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    ipad pro 2nd gen 12.9 inch (22E4523C-2337-4726-BB07-945AE70F6C8E) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    ipad pro 2nd gen (3AA88AE2-9F45-4C5F-8722-4C00C9861FE1) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPad mini (6th generation) (0B6A3687-ED22-4870-92FC-677C86941C46) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    ipad pro 6th gen (4D6B6A4C-9FB0-4FF1-8B80-3DC6F8D0DF02) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-17-4 --
    Iphone Khaled (FBEFF7D8-5B5E-495C-A627-5917A6D327BB) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPhone SE (3rd generation) (87882140-6FBF-4287-800F-2D56A92A4E37) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPhone 15 (F77F9A7B-0E56-4BD4-A62D-65BF1DA3C98F) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPhone 15 Plus (BC24ACA9-71F9-4C3A-8233-DD16431F6DA7) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPhone 15 Pro (36F42BA4-E6E3-46D5-A058-B4D46B68FAD8) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPhone 15 Pro Max (6A9DEEE0-E146-430D-8ABD-AFDE0B647D44) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPad Air (5th generation) (8C152D5B-319B-486A-95A3-6A823ECE64BB) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPad (10th generation) (F00E6E7E-689E-4602-93D0-86C2718C8108) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPad mini (6th generation) (BD98CD81-EF7E-495D-9D96-9BEB3101ACE2) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPad Pro (11-inch) (4th generation) (237B057E-6E7D-408F-BF46-B55ED5870FFC) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPad Pro (12.9-inch) (6th generation) (0B62ACEF-65C6-4F18-87D4-780EB92119E3) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPad Air 11-inch (M2) (399D4F60-02D1-4801-BFDC-9A75BABC783A) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPad Air 13-inch (M2) (7DFC2FD0-EF0D-4DDB-81E3-C10B73E3F403) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPad Pro 11-inch (M4) (703A8201-CBC3-4DEA-AFD8-17B0D758A68E) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
    iPad Pro 13-inch (M4) (E13942EA-2556-47BD-9130-BD2BD8FA4623) (Shutdown) (unavailable, runtime profile not found using "System" match policy)
`

**Comment by eseidel** [comment]
I suspect this was https://github.com/shorebirdtech/shorebird/issues/1851?
