### ISSUE TITLE
fix: we should not run pub upgrade while also checking pubspec.lock into version control

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#2263]
**Description**

As discussed on Discord, we shouldn't run pub upgrade in the installed CLI since we have pubspec.lock included in it.

By doing the upgrade we "override" the lock and we will have users using newer dependencies than the ones that we tested before releasing.

https://github.com/shorebirdtech/shorebird/blob/main/third_party/flutter/bin/internal/shared.sh#L26

**Comment by eseidel** [comment]
Yup, I'd recommend we fix that (and the ps1 version) to use pub get instead and leave a comment as to why (we use pubspec.lock where as `flutter` does not).  FYI @bryanoltman
