### ISSUE TITLE
fix: shorebird patch was only able to share 26.6% of Dart code with the released app

### ISSUE THREAD

**Issue by bazl-E** [shorebirdtech/shorebird#2287]
shorebird patch --platforms=ios,android --flavor=dev --target=./lib/main_dev.dart
✓ Fetching apps (1.5s)
✓ Fetching releases (0.4s)
Which release would you like to patch? 1.0.6+7
✓ Fetching xcarchive artifact (0.5s)
✓ Downloading xcarchive (6.5s)
✓ Building patch with Flutter 3.22.2 (7cab65034f) (291.7s)
✓ Verifying patch can be applied to release (1.2s)
✓ Extracting release artifact (0.6s)
✓ Linking AOT files (98.3s)
[WARN] shorebird patch was only able to share 26.6% of Dart code with the released app.
This means the patched code may execute slower than expected.
https://docs.shorebird.dev/status#link-percentage-ios

✓ Generating patch diff base (0.6s)

🚀 Ready to publish a new patch!

📱 App: easify-flutter (dev) (c662a3f3-eb1a-4218-8390-c0fa7b36e885)
🍧 Flavor: dev
📦 Release Version: 1.0.6+7
🕹️  Platform: ios [arm64 (2.79 MB)]
🟢 Track: Production
🔗 Running 26.6% on CPU
🔍 Debug Info: /Users/bazie/Documents/Iocod/Projects/easify/build/patch-debug.zip

The changes were only dart code changes, I can't share the code samples here as security issues

**Comment by eseidel** [comment]
Thank you for the report.  We have a bunch more fixes coming for this in the next few days.  See https://github.com/shorebirdtech/shorebird/issues/1892

I'm going to assume we can track this as https://github.com/shorebirdtech/shorebird/issues/1892, but please feel free to re-open if needed.

**Comment by eseidel** [comment]
We just released v1.4.14 which should include linker improvements for iOS patches. Let us know if you're still seeing low linking warnings when using Shorebird CLI v1.4.14 (you'll need to re-release and patch to take advantage of the new linker improvements).
