### ISSUE TITLE
fix: Initial download only installs release app, meaning users don't see the patched version initially

### ISSUE THREAD

**Issue by Jonny1987** [shorebirdtech/shorebird#2296]
App ID: (insert your app ID here)

**Description**

It would be better if the patched version was bundles with the release version somehow, so that it is installed at the same time, meaning new users see the patched version of the app, not the release version. Is that possible?

**Expected Behavior**

New users should see the most up to date version of the app when they first install it

**Screenshots**

**Additional Context**

**Comment by eseidel** [comment]
The released version which comes from the store can't be changed by Shorebird.  The only way to change the initial download from the store is to make a new release with the store.

It is possible to gate usage of the app on being up to date by calling out to package:shorebird_code_push as part of your login screen or similar.
https://docs.shorebird.dev/update-strategies/

**Comment by eseidel** [comment]
Closing for now, please feel welcome to reopen if I've not sufficiently addressed the question.
