### ISSUE TITLE
fix: shorebird can't detect Android studio when installed via jetbrains toolbox app

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#2297]
**Description**

Our Android Studio detection code is failing to detect android studio when it is installed via [Jetbrains Toolbox App](https://www.jetbrains.com/toolbox-app/).

**Expected Behavior**

Shorebird should detect Android Studio when installed via Jetbrains toolbox app

**Additional Context**

Reported on [discord](https://discord.com/channels/1030243211995791380/1255948959181049896).

**Comment by eseidel** [comment]
Presumably it installs it in a different location and we don't have that location on our list of known locations?
https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/android_studio.dart
vs flutter:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart

**Comment by erickzanardo** [comment]
@eseidel yeah, here is where the flutter tool have the path for the toolbox: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart#L211
