### ISSUE TITLE
feat: provide minimal docker images for building Android patches  

### ISSUE THREAD

**Issue by FluffyDiscord** [shorebirdtech/shorebird#2298]
**Description**

I am using Gitlab as my CI/CD of choice with dind. This means that the code that runs my jobs is inside a Docker image. Right now I am using, as previously without Shorebird, the `ghcr.io/cirruslabs/flutter` image, and installing Shorebird additionally with `curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash`.

This takes some precious time, that could be shaved off by providing Docker image with prepared shorebird installation.

This fairly high effort, low gain feature request.

**Requirements**

- [ ] Provide docker images

**Additional Context**

**Comment by bryanoltman** [comment]
Given that the install script just clones a git repo, a docker image is likely overkill. This would probably be better as a CI step. We have https://github.com/shorebirdtech/setup-shorebird for GitHub, and I'm sure GitLab supports similar, although I'm unfamiliar with GitLab.

**Comment by bryanoltman** [comment]
I the suggestion above doesn't address the issue that would be solved by a docker container, but the benefit of providing this vs. the initial infra setup and continued maintenance burden isn't something that makes a lot of sense for us to take on.
