### ISSUE TITLE
fix: Can't upload new release, requires flavor (iOS)

### ISSUE THREAD

**Issue by DETR1SE** [shorebirdtech/shorebird#2299]
App ID: 3cc112f9-c208-4c3a-a422-3543be97fcce

**Description**

After shorebird update can't upload new release, requires flavor. Before shorebird update it wasn't requiring providing flavor. 

```
example@example example-flutter % shorebird release ios
The project has flavors (example-prod, example-dev), but no --flavor argument was provided
```

**Steps To Reproduce**

1. shorebird release ios

**Comment by bryanoltman** [comment]
Can you share your `shorebird.yaml` file?

**Comment by bryanoltman** [comment]
Your project was configured with two flavors. You need to provide the flavor you wish to release. If you don't want to use flavors anymore, you can delete the flavors section from your `shorebird.yaml`.
