### ISSUE TITLE
feat: When patch deactivates, go back to old patch

### ISSUE THREAD

**Issue by must-ismail** [shorebirdtech/shorebird#2303]
**Description**

When we deactivate the patch, the previous patch becomes "Active". However, users who downloaded the last deactivated patch will not go back to the active patch.

**Additional Context**

By adding a selectbox when deactivating, we can choose which patch to activate and whether to force users to do so.

Especially when there is a problem with iOS, we have to deactivate the patch and re-release the old patch. This forces users who have already downloaded it to download it again and creates additional work for us.

**Comment by felangel** [comment]
Hi 👋 
This sounds like a duplicate of #126

**Comment by must-ismail** [comment]
Hi @felangel 
Oh, yes. it seems duplicate.
So maybe this will give you ideas when you developing it.

Thank you!
