### ISSUE TITLE
fix: ✗ Error uploading xcarchive: ClientException with SocketException: Write failed (OS Error: Broken pipe, errno = 32),

### ISSUE THREAD

**Issue by bazl-E** [shorebirdtech/shorebird#2311]
Would you like to continue? (y/N) Yes
✓ Fetching releases (2.1s)
✓ Updating release status (0.4s)
✗ Error uploading xcarchive: ClientException with SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = storage.googleapis.com, port = 60837, uri=https://storage.googleapis.com/shorebird_release_artifacts/c4cda63f-1202-41e1-bbe1-493147762097%2Fios%2Fxcarchive%2F68919%2FRunner.xcarchive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=patch-artifacts-storage-bucket%40code-push-prod.iam.gserviceaccount.com%2F20240701%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240701T122148Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=65569d337ef216d03b10b656da19e30e6758c5814daab98c59b97c37eda7c97cd83f1726836e0b153f29869b92e906690ba9c3f70562f441141ced3edd19077fcfaefa04d5c72b2e39a037d6a425d8078abe411091b8528936779af67f4787532effde116d799f3c3123fb9a9fbe4908f590ef41219be12b58485e3e0fb5e4753b6c55d095702c23af25f44b0bd6fd4ef450d12f4816bc7f28d33746522e8eb34f44e9ef7fd4c562fcd0102335384be0d8882e54e13d9d5b56f46b8

bazie@Bazis-MacBook-Pro easify % shorebird doctor                                                  
Shorebird 1.1.13 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.22.2 • revision 7cab65034f8575e81d58774a91b99405ce2a2f7a
Engine • revision 28ed3b6c5fc12806e757067fdccb3614b4bd2ac1

✓ Shorebird is up-to-date (1.6s)
✓ Flutter install is correct (0.5s)
✓ AndroidManifest.xml files contain INTERNET permission (37ms)
✓ Has access to storage.googleapis.com (0.7s)
✓ shorebird.yaml found in pubspec.yaml assets (11ms)

No issues detected!

**Comment by bryanoltman** [comment]
This looks like the result of an unstable internet connection. You should try running the command again and it should succeed.

**Comment by bazl-E** [comment]
it was a network error
