### ISSUE TITLE
feat: shorebird init --name=my_app

### ISSUE THREAD

**Issue by heitor598** [shorebirdtech/shorebird#2312]
I have a white label model, where shorebird.yaml already exists in my project, for each new app that I customize I check in my backend if there is already an app id, if not I create an app id, replace it in shorebird .yaml and save it to my database. The idea is to do this using a Dart script or something similar.

shorebird init --name=my_app would help me a lot.

Reply to "How should we refer to this application? (shorebird_test)" via a parameter

**Comment by xalikoutis** [comment]
Hahah cant believe it, i opened shorebird github issues to register the same feature request.
We also have a white label app, it will be a great feature for us, and also a stopper right now

**Comment by dsmyrnaios** [comment]
+1

**Comment by bryanoltman** [comment]
This is a surprisingly popular issue! We know of some customers using shorebird for white label apps, but I don't think we fully understand what a workflow for one of these apps looks like (how do you manage releases and patches, for example)? If one or more authors of white label apps wouldn't mind letting us know, that would be really helpful!

**Comment by heitor598** [comment]
@bryanoltman  In my case, before generating a patch, I obtain the application ID in my back-end using a unique identifier for each App.

**Comment by xalikoutis** [comment]
Our white label app case works as the following for the build system

1. pass the client_id
2. clone app repo (single source for everyone)
3. inject assets, string, colors, confs etc based on client_id from our backend (somewhere here backend should now shorebird app ID to create the yaml file)
4. change sign keys
5. build
6. deploy to clients store

So we don't have a repo source for each client, but a single for everyone
Shorebird appId should be fetched from our Backend and add it in shorebird.yaml file at build time as mentioned above.

How do we add shorebird for existing clients?
the flow with current shorebird version

1. for each client
2. change name in pubspec.yaml to the client apps name
3. `shorebird init`
4. read appID from shorebird.yaml
5. push appID to Backend
6.remove shorebird.yaml

proposed flow
1. for each client
2. `shorebird init --name=client 1`
3. read appID from shorebird.yaml
4. push appID to Backend

even better

1. to run `shorebird init --name=client 1 ` outside repo
2. `shorebird init --name=client 1 ` returns the appId in sdtout (dont write shorebird.yaml)

much even better
create http apis to handle everything related to shorebird
POST /init
DELETE /delete/:appid
etc

**Comment by bryanoltman** [comment]
@xalikoutis When you say "DELETE /delete/:appid", what are you hoping that will do? Deleting the app will make it completely unpatchable.

Edit: I think I understand, you were just providing an example. We do have https://github.com/shorebirdtech/shorebird/tree/main/packages/shorebird_code_push_client, which is open source and used by our CLI. We haven't tried to use it outside of the CLI or designed it with that use case in mind, so you may find it hard to use.

**Comment by bryanoltman** [comment]
Question: if this operation is being scripted already, would something like the following work? Assuming you have a script to update the `name` field in the app's pubspec.yaml:

```
update_name_in_pubspec.sh "new_app_name"
shorebird init -f
```

This will create a new shorebird app named `new_app_name` and will work today.

**Comment by bryanoltman** [comment]
Also, fwiw, `shorebird init -f` will give you a new app id, although the app will have the same name.

**Comment by felangel** [comment]
Just merged #2316 to allow you to specify the display name via a command-line arg:
e.g. `shorebird init --display-name="my super cool app" --force`

Closing for now but let us know if there's anything else we can do to help 👍

**Comment by felangel** [comment]
This is now available in v1.1.15 of Shorebird CLI 🎉

**Comment by xalikoutis** [comment]
> @xalikoutis When you say "DELETE /delete/:appid", what are you hoping that will do? Deleting the app will make it completely unpatchable.
> 
> Edit: I think I understand, you were just providing an example. We do have https://github.com/shorebirdtech/shorebird/tree/main/packages/shorebird_code_push_client, which is open source and used by our CLI. We haven't tried to use it outside of the CLI or designed it with that use case in mind, so you may find it hard to use.

Hi Bryan,
Lets say that a client cancels subscription plan for our white label, we clean everything out, firebase projects, keys, stores, why not shorebird.

Hahaha i am on that the last 2 days [shorebird_code_push_client] but i am having difficulty on making work.
`CodePushClient(httpClient);` needs an httpclient i assume with the proper bear token. I saw what shorebird_cli does currently i am investigating how shorebird_cli auths and handles token and refresh. If there is an easier way please tell me

Also shorebird_code_push_client readme needs to be corrected, because it points to an older version of the library.

**Comment by xalikoutis** [comment]
Done

```import 'dart:io';
import 'package:http/http.dart' as http;
import 'package:shorebird_cli/src/auth/auth.dart';
import 'package:shorebird_code_push_client/shorebird_code_push_client.dart';


void main(List<String> arguments) async {
  Map<String, String> env = Platform.environment;
  final token = env['SHOREBIRD_TOKEN'];
  if(token == null) {
    print('SHOREBIRD_TOKEN environment variable not set');
    exit(1);
  }
  var citoken = CiToken.fromBase64(token);
  http.Client? _httpClient = http.Client();
  var client = AuthenticatedClient.token(httpClient: _httpClient, token: citoken);
  CodePushClient codePushClient = CodePushClient(httpClient: client);
  var app = await codePushClient.createApp(displayName: 'test app');

  print(app.id);
}
