### ISSUE TITLE
feat: CLI patch with activate flag option

### ISSUE THREAD

**Issue by narutepw** [shorebirdtech/shorebird#2313]
**Description**

I want to patch release with deactivate the patch as default. So I can upload patch in advanced and able to control when user able to download the patch.

Ex. to upload patch with deactivate as default

```
shorebird patch android --activate false
```

Ex. to upload patch with activate as default

```
shorebird patch android --activate true
```

**Comment by eseidel** [comment]
Staging might do what you need? https://docs.shorebird.dev/guides/staging-patches/

**Comment by bryanoltman** [comment]
I believe staging patches is the answer here. Closing, please reopen if that isn't the case.
