### ISSUE TITLE
fix: shorebird login failed

### ISSUE THREAD

**Issue by zyq9613** [shorebirdtech/shorebird#2321]
App ID: (insert your app ID here)

**Description**

after install shorebird success, run shorebird login ,inset right email and  internet right connect Google，

ClientException with SocketException: Operation timed out (OS Error: Operation timed out, errno = 60), address = oauth2.googleapis.com, port = 58015, uri=https://oauth2.googleapis.com/token
**Steps To Reproduce**

1. after install shorebird success
2. run shorebird login
3. inset right email and  internet right connect Google
4. faid

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by eseidel** [comment]
This would suggest that your computer might not be able to reach `oauth2.googleapis.com`.

I'd try `curl` to confirm, e.g.:

```
curl -I oauth2.googleapis.com
HTTP/1.1 404 Not Found
Date: Mon, 08 Jul 2024 16:56:15 GMT
Content-Type: text/html; charset=UTF-8
Server: ESF
Content-Length: 1561
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
```

**Comment by eseidel** [comment]
Assuming this is resolved for you, please don't hesitate to re-open if we can help!
