### ISSUE TITLE
fix: give instructions when encountering exit code -1073741515

### ISSUE THREAD

**Issue by ashrafFathallaMasrpay** [shorebirdtech/shorebird#2329]
App ID: (masrpay-UserApp)

when make shorebird patch android  give me Failed to create diff (exit code -1073741515).
  stdout: 
  stderr:  (1.4s)

2024-07-09T16:34:43.386162 
If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also [file an issue](https://github.com/shorebirdtech/shorebird/issues/new/choose) if you think this is a bug. Please include the following log file in your report:
C:\Users\AshrafFathalla\AppData\Roaming\shorebird\logs\1720531892399_shorebird.log

**Comment by eseidel** [comment]
See also https://github.com/shorebirdtech/shorebird/issues/1487

**Comment by eseidel** [comment]
I think we should write a "troubleshooting" guide or teach `shorebird doctor` to look for the missing dll.

**Comment by eseidel** [comment]
Or probably easier is to just look for the "-1073741515" exit code on windows (either via doctor or just when running any binary) and suggest the need to install https://www.microsoft.com/en-us/download/details.aspx?id=52685

Specifically the error is that VCRUNTIME140.dll is missing on the machine.

e.g. some prose we could use:

```
patch.exe exited with -1073741515.  This indicates that the Microsoft C++ runtime (VCRUNTIME140.dll) could not be found.

The C++ Runtime can be installed from microsoft at:
https://www.microsoft.com/en-us/download/details.aspx?id=52685
```

**Comment by ashrafFathallaMasrpay** [comment]
shorebird init take more time without any response 
PS D:\agent> shorebird init
✓ No product flavors detected. (4.1s)
? How should we refer to this app? (agent) AgentApp

**Comment by erickzanardo** [comment]
> shorebird init take more time without any response 
> 
> PS D:\agent> shorebird init
> 
> ✓ No product flavors detected. (4.1s)
> 
> ? How should we refer to this app? (agent) AgentApp
> 
> 

Does the command hangs without finishing? Could you run it with the verbose flag and share the logs?

Also, I don't think this is related to the original issue, so if you could open a new one specific about this other problem, with the verbose log, it would be great!
