### ISSUE TITLE
feat: add flutter version string to different version releases message

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#2349]
**Description**

When adding a second release to an existing release, and accidentally using a different flutter version than the one originally used, we give a message explaining the error and reference the Flutter version just by its revision, we should also add the flutter string version (e.g. 3.22.1) to it, for improved readability.

**Additional Context**

Today:

```
....
  Existing release built with: 2f366bd7c9cdb59a1231fdb13c985be48f47149b
  Current release built with: 72996fba5d330551d694c6e09189e215c09b1c5b
```

Suggestion:

```
....
  Existing release built with: 3.22.1 (2f366bd7c9)
  Current release built with: 3.22.2 (72996fba5d)
```

**Comment by eseidel** [comment]
Go for it!  There are a bunch of cases where we previously only showed the hash and now with the new data you've saved we could show the version string.  The Admin panel is another.
