### ISSUE TITLE
fix:  Shorebird Patch ios Command Fails with Invalid Kernel Binary Error 

### ISSUE THREAD

**Issue by hurab** [shorebirdtech/shorebird#2355]
Description: When attempting to apply a patch using the Shorebird CLI on an iOS platform, the command fails during the linking of Ahead-Of-Time (AOT) compiled files. The error message indicates an issue with loading a Kernel binary due to an invalid size indication. This prevents the patch from being successfully applied to the release.
Steps to Reproduce:

<img width="1082" alt="Screenshot 2024-07-14 at 3 09 40 AM" src="https://github.com/user-attachments/assets/439156f6-617d-4d7e-b5b7-f840a973c4d4">

Shorebird Patch android working fine.

Device: Macbook M1

**Comment by bryanoltman** [comment]
Can you share the output of `shorebird doctor`?

**Comment by hurab** [comment]
> shorebird doctor

<img width="1061" alt="Screenshot 2024-07-15 at 7 48 00 PM" src="https://github.com/user-attachments/assets/7151eca4-182c-404f-a1cc-69e47c0346a3">

**Comment by bryanoltman** [comment]
Could you share the log file specified in the error message at the end of the failed command?

**Comment by hurab** [comment]
[shorebird_error.txt](https://github.com/user-attachments/files/16237993/shorebird_error.txt)

**Comment by hurab** [comment]
> Could you share the log file specified in the error message at the end of the failed command?

[Uploading 1721062854357_shorebird.log…]()

**Comment by bryanoltman** [comment]
I think the upload failed somehow—that's just a link to this issue.

**Comment by hurab** [comment]
> I think the upload failed somehow—that's just a link to this issue.
[1721062854357_shorebird.log](https://github.com/user-attachments/files/16238391/1721062854357_shorebird.log)

**Comment by eseidel** [comment]
I believe this is another instance of artifacts getting corrupted, which we will be releasing a fix for later this week.

https://github.com/shorebirdtech/shorebird/pull/2335

The fix for now is to run `shorebird cache clean`.  Sorry for the disruption.

**Comment by eseidel** [comment]
Failing lines:
```
2024-07-15T20:09:20.033956 No checksum provided for patch, skipping file corruption validation
2024-07-15T20:09:20.420572 No checksum provided for aot-tools.dill, skipping file corruption validation
2024-07-15T20:09:20.421240 [Process.run] /Users/hurab/.shorebird/bin/cache/flutter/853d13d954df3b6e9c2f07b72062f33c52a9a64b/bin/dart run /Users/hurab/.shorebird/bin/cache/artifacts/aot-tools/fb6b1af0c3f03aa2d60b8e176e915501e41116bb/aot-tools.dill link --help
2024-07-15T20:09:21.001991 Exited with code 253
2024-07-15T20:09:21.003338 
stderr:
Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.
```

That looks consistent with the fix we're shipping in the next release.
