### ISSUE TITLE
fix: hang after patch on iOS (iPhone 15 only?)

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2358]
App ID: ca1d622b-77a4-4c50-81be-d24592a1af7c

User reports hitting a hang after patching on iOS.  They mentioned that it worked on several test devices, but hung on the iPhone 15?

https://discord.com/channels/1030243211995791380/1030243213002412164/1262111326046519387

They're happy to provide more information and reachable via email or Discord.

**Comment by bryanoltman** [comment]
I'm not sure if this is actionable. The user mentioned that they met with Eric, so going to close this.
