### ISSUE TITLE
fix: Information exposure???

### ISSUE THREAD

**Issue by sxm5220** [shorebirdtech/shorebird#2362]
![组 195@4x](https://github.com/user-attachments/assets/67e1c1ce-86d7-4a8f-9de8-91c1f3bd016d)
When using Android Studio to observe any running Flutter Demo, opening an Alpha version app of a closed testing track on Google Play that includes Shorebird functionality will display this information in the Android Studio console. Is it safe for this information to be exposed? @eseidel

**Comment by sxm5220** [comment]
Is it possible that the print output was not used in the kDebugMode? 🤔

**Comment by eseidel** [comment]
Thanks for the report. All of that information is safe to be public.

https://docs.shorebird.dev/faq/#do-i-need-to-keep-my-app_id-secret

**Comment by sxm5220** [comment]
Shorebird is so cool! 👍
