### ISSUE TITLE
docs:  Add documentations about using fast lane with android

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#2363]
**Description**

Right now, our documentation about using [fastlane](https://docs.shorebird.dev/ci/fastlane/) contains only instructions about iOS.

We could also add some notes and instructions on how it could be used on android too.

**Requirements**

- [ ] Improve our fastlane docs to include instructions about Android

**Additional Context**

This has been requested on discord: https://discord.com/channels/1030243211995791380/1030243213002412164/1262610005144637533

**Comment by bryanoltman** [comment]
Our updated guide should be sufficient for Android, I think (hoping it's obvious that users can plug in "android" instead of "ios")

**Comment by lailai0715** [comment]
The documentations are not comprehensive enough as I encounter error as below

**What I've run:**

```
lane :release_shorebird do
  shorebird_release(platform: "android")
end
```

**Error encountered after running `fastlane`:**

```
: Called from Fastfile at line 65
[18:52:22]: ```
[18:52:22]:     63:         # )
[18:52:22]:     64:
[18:52:22]:  => 65:         shorebird_release(platform: "android")
[18:52:22]:     66:         
[18:52:22]: ```
[18:52:22]: Exit status of command 'shorebird release android' was 70 instead of 0.
The project has flavors (dev, production, staging), but no --flavor argument was provided
Instance of 'ValidationFailedException'

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also [file an issue](https://github.com/shorebirdtech/shorebird/issues/new/choose) if you think this is a bug. Please include the following log file in your report:
/Users/mypc/Library/Application Support/shorebird/logs/1737024740771_shorebird.log
```

Should provide extra guidance on how to config with --flavor and build with APK artifact
