### ISSUE TITLE
fix: Grey screen on iOS with Shorebird preview/release

### ISSUE THREAD

**Issue by bosgid** [shorebirdtech/shorebird#2364]
App ID: f098a04d-c372-4d8b-ab17-f096d55bcc18

**Description**

In my app, after logging in and accepting permissions, I am met with a grey screen instead of my home page.
This only occurs on iOS and only occurs on Shorebird previews and releases. Running `flutter run` works fine.
It is only when Shorebird is involved and is run on iOS that I get this grey screen.

I have set up two flavors: `internal` and `stable`. I am seeing this issue with both flavors. Flutter run works fine when running a specific flavor or none at all.

There are no logs or messages (even with `shorebird preview --verbose`) shown at all so there is nothing to guide me towards the cause of the error.

**Steps To Reproduce**

1. `shorebird preview`
2. Select stable flavor (issue present on all flavors though)
3. Select release `1.4.0+28` (issue present on all releases though)
4. Wait for app to install and open
5. Tap "Let's Go" on Welcome screen
6. Go through intro slides and tap button to continue
7. Log in with organisation pin: 3AWJG
8. Accept camera permissions
9. Accept location permissions and await GPS location acquisition
10. Complete onboarding
11. Land on grey screen - app is now stuck

**Expected Behavior**

Expected to land on a Sites page with a list of organisation sites after the onboarding instead of a grey screen

**Screenshots**

<img src="https://github.com/user-attachments/assets/6e21463e-75d6-49d6-a0e5-b2f6d410422d" alt="IMG_B9385D460C59-1" width="300"/>

**Additional Context**

I have a suspicion that the modified Flutter engine may be having issues with an SDK we have added to the app for offline functionality. This is the [PowerSync Flutter SDK](https://pub.dev/packages/powersync), but it doesn't seem to be an issue on Android...

**Comment by tristdrum** [comment]
Hi shorebird team! @bosgid and I are so pumped about your tech! 

Been watching for months and this is our first attempt! Sorry if we're missing something! We've tried all I can think of.

**Comment by bryanoltman** [comment]
Interesting! Sorry you're running into this. A few questions:

1. No logs at all shown in `shorebird preview` seems very wrong. You should at least see that Shorebird is checking for an update. You're seeing absolutely nothing?
2. Is this happening without any patches? I see that the version 1.4.0+28 has an iOS patch on the stable flavor but not on the internal flavor.

**Comment by tristdrum** [comment]
1. We saw shorebird checking for an update ✅

**Comment by tristdrum** [comment]
2. That's my understanding, yes. We just want a release to work on iOS (no patches required). This will be the first release for users (currently shorebird is not in the wild versions of our app yet)

**Comment by bryanoltman** [comment]
That's really concerning. I'm doubtful that the issue has to do with an interaction between any of our modifications and another package, but I would check that a release build created without shorebird (`flutter build ipa --release`) does not also exhibit this behavior. `flutter run` uses a development build, which will be different than a non-Shorebird Flutter release.

**Comment by bosgid** [comment]
Really appreciate the help and responses! So I have tried a flutter build and I released it to TestFlight and it seems the grey screen issue appeared... So it looks like that something is happening whenever the app goes through a release since `shorebird preview` always seems to preview an app that has gone through a release (`shorebird release`), whereas, `flutter run` shows a debug version of the app that has not been released yet. I think the issue may be how our flavors are set up in XCode...

**Comment by bosgid** [comment]
Managed to get it working 🥳 In the end it was the PowerSync SDK... After downgrading to a previous version, I was able to avoid the grey screen. Seems it was not necessary to bother you guys with this issue 😅  Sorry about that!

**Comment by eseidel** [comment]
Thank you for the report and follow-up!
