### ISSUE TITLE
fix: `shorebird release android` fails if `--target-platforms` is passed after `--`

### ISSUE THREAD

**Issue by lwj1994** [shorebirdtech/shorebird#2371]
App ID: 45db7979-a583-40f3-af2c-c1f566ec2665

**Description**

why setted --artifact apk，still build aab?

if run  `flutter build apk` is ok.

**Steps To Reproduce**
run
```shell
shorebird release android --artifact apk --flutter-version 3.22.3 -- --obfuscate --split-debug-info build/debugInfo --target-platform android-arm64 --dart-define=isProduction=true --dart-define=onlyBuildArm64=true
```

[1721566071009_shorebird.log](https://github.com/user-attachments/files/16324505/1721566071009_shorebird.log)

**Comment by bryanoltman** [comment]
This will work if you move `--target-platform android-arm64` to before the `--`, so:

`shorebird release android --artifact apk --flutter-version 3.22.3 --target-platform android-arm64 -- --obfuscate --split-debug-info build/debugInfo  --dart-define=isProduction=true --dart-define=onlyBuildArm64=true`

We should update the CLI to catch arg if it's passed after the `--`.

**Comment by bryanoltman** [comment]
Reopening so we don't forget to fix the issue of failing to recognize `--target-platforms` when passed after `--`

**Comment by eseidel** [comment]
We should probably either do this or close it.  I've not seen it come up since.

**Comment by bryanoltman** [comment]
We haven't gotten around to doing this and it has not come up since the bug was filed, so going to close for now. Please reopen and let us know if this would help you.
