### ISSUE TITLE
fix:  How do we specify the flutter version while releasing a patch. 

### ISSUE THREAD

**Issue by ABHINANDRK** [shorebirdtech/shorebird#2374]
App ID: (insert your app ID here)

**Description**

How can we specify the Flutter version while releasing a patch? Below is the command I used for patching:

`shorebird patch android --allow-native-diffs -v --flavor $(build_env) -- -t lib/main_$(build_env).dart`

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by bryanoltman** [comment]
You can't—patches are required to use the same Flutter version as their release. You can specify a release version to patch using the `--release-version` option (e.g., `shorebird patch android --release-version=1.2.3+4`), or choose one when prompted by the patch command.
