### ISSUE TITLE
`shorebird release ios` hanging building Flutter (app.dill in unexpected place?)

### ISSUE THREAD

**Issue by aswinsubhash** [shorebirdtech/shorebird#2378]
In my Macbook Flutter version is 3.19.4 but i am using FVM for my project to use the latest v3.22.3.

When i use shorebird patch ios command Building patch with Flutter 3.22.3 running endlessly [image given below]

So my question is "Is it because of the version i am using on local?"

The app is not published in app store yet, uploaded to testflight only right now

Also while doing shorebird init I didnt got any warnings too. So what was the issue here??
![Screenshot 2024-07-24 at 3 12 09 PM](https://github.com/user-attachments/assets/56848d1b-ac70-41a1-ae5a-11fcd6fadab3)

**Comment by Aswinjiitak** [comment]
![Screenshot 2024-07-24 at 3 33 52 PM](https://github.com/user-attachments/assets/31b5ed21-83c3-4066-afbd-d820bada53f4)

**Comment by eseidel** [comment]
We've seen hangs like this when part of the compile toolchain crashes, `xcodebuild` will then hang, hanging `flutter` and `shorebird`.  I'd start by making sure you have the latest version of `shorebird` with `shorebird upgrade`.

**Comment by aswinsubhash** [comment]
Today i just upgraded the shorebird to 1.1.22 and tried to patch the release i done using 1.2.20 and failed, Should i need to do another version release now to test the patch??
![Screenshot 2024-07-25 at 9 27 18 AM](https://github.com/user-attachments/assets/483c6cbe-0451-426c-b606-3ef65966e6df)

**Comment by eseidel** [comment]
We've made the fix, but not yet released it.

The actual error is that it can't read that .dill file (the very first line).  The crash is what we fixed.

Why it can't read the .dill file, is unclear.  It may be that we find the .dill files in kinda hacky ways.  One thing to try is to run:

`ls Anshin-Kun/rental_anshin_kun_inspector/.dart_tool/flutter_build/5b1ae61cc1f23be0e04d6ddc116d436b` and see what's in that directory.

**Comment by eseidel** [comment]
I expect we'll release the crash fix either Thursday (tomorrow) or Friday this week, that won't resolve the missing .dill file, but it will resolve the build hanging.

**Comment by eseidel** [comment]
Another command you might try is running:
`find Anshin-Kun/rental_anshin_kun_inspector/.dart_tool | grep dill` and see what it lists.

**Comment by eseidel** [comment]
I'm also a bit confused as to why the .dart_tool directory is so deep.  I would have expected the .dart_tool directory to have been at the root of the project.  🤔

**Comment by aswinsubhash** [comment]
I tired both commands and it shows "No such file or directory"

![Screenshot 2024-07-25 at 10 17 03 AM](https://github.com/user-attachments/assets/ec7e89f2-7cf6-457d-a53f-d49a4586bc03)

**Comment by aswinsubhash** [comment]
Initially, I thought this issue was only present on my system, but one of our coworkers is also facing the same issue. That’s why I was concerned about this.

**Comment by eseidel** [comment]
Note to self, more of the discussion is on Discord too: https://discord.com/channels/1030243211995791380/1265612642878361651

Thanks.  I believe there are two separate things happening here.

1. Is gen_snapshot is crashing when the path is missing.  This is triggering ReportCrash (mac os's crash reporting tool) and for whatever reason xcodebuild is then hanging.  We've fixed gen_snapshot crashing on a missing file, that fix should go out soon, but won't resolve the whole issue here.
2. Something about this build environment is putting app.dill in a funny place.  We're not yet sure why.  But discussing on Discord.

**Comment by aswinsubhash** [comment]
Here is the shorebird doctor console @eseidel 
![Screenshot 2024-07-26 at 9 29 59 AM](https://github.com/user-attachments/assets/1ba941a9-8633-4506-b67a-e268627a1ba6)

**Comment by eseidel** [comment]
Thanks.  I believe this is fixed by https://github.com/shorebirdtech/shorebird/pull/2387 which will ship tomorrow.

**Comment by aswinsubhash** [comment]
Thank you! I will check that tomorrow and update here @eseidel

**Comment by bryanoltman** [comment]
1.1.23 has shipped.

**Comment by aswinsubhash** [comment]
Thank you all! For this superb fix  @eseidel @bryanoltman @felangel 
<img width="616" alt="Screenshot 2024-07-27 at 3 46 13 PM" src="https://github.com/user-attachments/assets/a06a8486-c769-4bfd-b279-34ce2ef61377">
