### ISSUE TITLE
fix: Shorebird fails to detect Flutter version after update

### ISSUE THREAD

**Issue by jakubkrapiec** [shorebirdtech/shorebird#2380]
App ID: 4939d96c-df26-4d98-8e5c-a7926fc2c4ea

**Description**

After updating to Shorebird 1.1.21, `shorebird doctor` fails to detect Flutter version with `FlutterValidationException` (on the screenshot below). This occurs both on Windows and macOS. I assume it's not safe to release with an unknown Flutter version, so currently it's a release blocker for us.

**Steps To Reproduce**

1. Run `shorebird upgrade`
2. `shorebird doctor` will fail

**Expected Behavior**

Flutter version is detected properly.

**Screenshots**

`shorebird doctor`:
<img width="860" alt="image" src="https://github.com/user-attachments/assets/770e8538-bb80-46c1-b676-f546351b39f8">

Attempted release:
<img width="482" alt="image" src="https://github.com/user-attachments/assets/918f996c-2cc8-4871-a129-47b54a83dba1">

**Comment by bryanoltman** [comment]
Thanks for the report! Your release should work fine, we (I) forgot to do some bookkeeping to our Flutter repo. If you'd like to make this go away, you can `rm -rf ~/.shorebird/bin/cache` and that should fix the problem.
