### ISSUE TITLE
fix: Shorebird code push downloads the patch but shows the the patch is not ready for installation

### ISSUE THREAD

**Issue by stn91-git** [shorebirdtech/shorebird#2385]
Discord thread: https://discord.com/channels/1030243211995791380/1265667108940021882

**Description**
I'm trying to use shorebird code push to download patch on demand. Currently when we open the app it downloads the app and when the user re-launches the app the patches gets installed. We wanted to reduce this cycle to only one launch. With the package shorebird code push we were planning to download the latest patch by sending a notification and download the new patch. When the user opens the app it will install the latest patch. Hence reducing the cycle to just one launch. 

The problem is the patch gets downloaded and when I check if the patch is ready to install it gives me false. 

**Steps To Reproduce**

1. Make a release with shorebird release android.
2. Install the app. Open the app and terminate the app.
3. I'm using firebase to trigger the notification, when the notification is recieved the code to dowload the patch and install runs.
4. I don't see any error being logged.

below code is runned when the notification is recived.

```dart
    final updateAvailable =
        await shorebirdCodePush.isNewPatchAvailableForDownload();
    if (updateAvailable) {
      await shorebirdCodePush.downloadUpdateIfAvailable();
      final isNewPatchReadyToInstall =
          await shorebirdCodePush.isNewPatchReadyToInstall();
      if (isNewPatchReadyToInstall) {
       // Restart.restartApp;
        return "Patch Ready to Install";
      } else {
        return "Patch not Ready to Install";
      }
    } else {
      return "No Update Available";
    }
    
```

**Expected Behavior**

When I send the notification the patch should be downloaded and when I open the app  the downlaoded patch should be installed.

**Comment by bryanoltman** [comment]
This should be fixed with releases created using shorebird 1.1.23
