### ISSUE TITLE
fix: shorebird preview get this error .

### ISSUE THREAD

**Issue by ITApexGroup** [shorebirdtech/shorebird#2388]
<img width="1211" alt="Screenshot 2024-07-26 at 11 01 57" src="https://github.com/user-attachments/assets/dbc7c37f-fa46-42d5-be85-62e0c3e5ca34">

**Comment by parajuliamit** [comment]
I don't think it's an issue of shorebird.
Please refer to this [StackOverflow discussion](https://stackoverflow.com/questions/24755341/unable-to-get-android-permission-clear-app-user-data).

**Comment by bryanoltman** [comment]
As @parajuliamit mentioned, I don't think there's anything Shorebird can do here.
