### ISSUE TITLE
fix: isNewPatchAvailableForDownload only returns true.

### ISSUE THREAD

**Issue by gonggamdev03** [shorebirdtech/shorebird#2389]
App ID: 766c735c-a6e9-41cb-8642-1e7cbfb42f55

After the shorebird update, I called isNewPatchAvailableForDownload and it only returns true even after the patch is complete.
nextPatchNumber cannot be imported.

**Comment by parajuliamit** [comment]
+1

**Comment by bryanoltman** [comment]
This has been fixed in version 1.1.23

**Comment by eseidel** [comment]
To see the fix will require making a new release with 1.1.23 (the fix is in the Flutter engine itself so a new release is required).
