### ISSUE TITLE
feat: add search bar and pagination in shorebird web console

### ISSUE THREAD

**Issue by xalikoutis** [shorebirdtech/shorebird#2398]
**Description**

Hi currently we have onboard 325 apps (white label) . Web console displays all these apps in a single list without the ability to search for an app name or even some table pagination. We use ctrl+f(find) to search for an app
**Requirements**

- [x]  Add a search bar on the top of shorebird web console
- [ ] paginate the listview of the apps

**Comment by bryanoltman** [comment]
Closing as complete now that the search bar has been added
