### ISSUE TITLE
feat: Warn users if patches are very large

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#240]
**Description**

Big patches are unfriendly to the user's data plan and may result in bad app behavior. We should let developers know if their patches are above some TBD size

Further: we may also want to warn if the patch diverges too much from what has been submitted to the app store to prevent users from running afoul of app store guidelines, although I'm not sure how we would define or measure how divergent a given patch is.

**Comment by eseidel** [comment]
We show users patch sizes.  We also now have link percentages, so we could guess (or soon will be able to guess when we make linking better), how much they've changed.  I'm not sure this bug is serving much purpose being open for now though.  closing.
