### ISSUE TITLE
fix: slow performance while patching on IOS, shorebird version 1.1.25 and flutter 3.22.3

### ISSUE THREAD

**Issue by amrebada** [shorebirdtech/shorebird#2406]
App ID: fcad3e6b-111d-44b2-aa1b-bdda4842d081

**Description**

When updating the code, the patch works well on Android but results in very slow performance on iOS upon re-running the app.

**Steps To Reproduce**

1. updating dart code 
2. gets 40% of sharing code
<img width="859" alt="Screenshot 2024-08-08 at 5 58 31 PM" src="https://github.com/user-attachments/assets/0df3ce8b-3001-4679-ba79-da9c4f251268">

**Expected Behavior**

IOS app working fine after installing the patch

**Additional Context**

https://github.com/shorebirdtech/shorebird/issues/1892#issuecomment-2275918108

**Comment by felangel** [comment]
Are you able to share your `build/patch-debug.zip` as well as describe the type of changes you made? If you prefer you can also reach out directly to us on [Discord](https://discord.gg/shorebird).

**Comment by eseidel** [comment]
I don't think we support Flutter 3.22.3 anymore.  We made a bunch of improvements for iOS as part of 3.24.x, I'd strongly recommend upgrading if you can.

As Felix notes, we'd love to help, but will need to learn more, including seeing a patch-debug.zip.  Thanks!
