### ISSUE TITLE
Shorebird Preview failing on staging environment in flutter android

### ISSUE THREAD

**Issue by yash-scapia** [shorebirdtech/shorebird#2410]
App ID: (insert your app ID here)

**Description**

Trying to `shorebird preview` on **staging** environment, but it is failing on the `installing APKs` step.
Attaching the stack trace for the above issue and the log file

**Screenshots**

<img width="1116" alt="image" src="https://github.com/user-attachments/assets/879f5086-e580-4c23-ae04-c11fc00dd427">

[1723208340987_shorebird.log](https://github.com/user-attachments/files/16561497/1723208340987_shorebird.log)

**Comment by eseidel** [comment]
Looks like the error is "Connection Refused".  I would check to make sure that `adb install` or other adb command work.  It's possible the device is not connected?

**Comment by WangSire** [comment]
I have also encountered this kind of problem, should be the signature problem, how to solve it? Expect a solution

**Comment by felangel** [comment]
Seems related to https://stackoverflow.com/questions/76209055/cannot-reach-adb-server-attempting-to-reconnect. If you're still having issues can you please share a link to a reproduction sample? Thanks!

**Comment by eseidel** [comment]
Would love to help, but we'd need more information.  Please don't hesitate to reach out if we can be of service.  We're reachable every day on https://discord.gg/shorebird, where we also have live-translation from/to any language so you can type there in whatever language is most comfortable to you.
