### ISSUE TITLE
Create workflow to build signed appbundle for Time Shift

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#242]
We were blocked on doing this last week because GHA do not support apple Silicon.  However we now support other host platforms as of our next release so this should 🤞 be possible now?

**Comment by eseidel** [comment]
I believe @bryanoltman is working us towards this incrementally.

**Comment by bryanoltman** [comment]
Yep, Apple silicon is no longer the blocker. This should be fully possible now, just some stuff to figure out around running authenticated shorebird commands from a GHA

**Comment by Mastersam07** [comment]
Are you looking at passing the **_credentials.json_** in a step on the GHA after getting it locally on running `shorebird login`?

I tried that approach, but Shorebird couldn't find the credentials.json file on GHA for some reason. Perhaps the wrong file path?

**Comment by felangel** [comment]
I managed to get a GitHub workflow which publishes a patch for time_shift so this should be possible now:

https://github.com/shorebirdtech/time_shift/actions/runs/5338365085/jobs/9675642940

**Comment by eseidel** [comment]
We do patches, but not releases I think?

**Comment by eseidel** [comment]
We're slowly moving away from Time Shift as a useful example.  https://github.com/shorebirdtech/shorebird/issues/1750 is probably a better way to track this desire.
