### ISSUE TITLE
fix:  first time running shorebird release took a long time before showing "fetching apps"

### ISSUE THREAD

**Issue by nateshmbhat** [shorebirdtech/shorebird#2422]
App ID: 007a2cb9-86ee-4f73-90db-1d3322af1863

**Description**
I ran shorebird release on a starter flutter app and i was confused why nothing is happening, i cancelled and re-ran the command again few times, every time no response. then i waited for like 10 minutes and then it proceeded normally as expected and the rest of the console messages showed up.

This only happened for 1st time release happened, then after that i'm not able to repro this issue 

**Steps To Reproduce**
i don't know how to repro this.

**Expected Behavior**

`shorebird release` doesn't get stuck for such long times

**Comment by bryanoltman** [comment]
I believe this is because we're downloading bundletool in the background. We should probably show a progress spinner or similar.
