### ISSUE TITLE
feat: create APK from past Shorebird release

### ISSUE THREAD

**Issue by nateshmbhat** [shorebirdtech/shorebird#2423]
App ID: 007a2cb9-86ee-4f73-90db-1d3322af1863

**Description**

I ran `shorebird release` to create a release which created the aab file. now i want to get the apk for this release , the only way I know is running `shorebird release android --artifact apk` but this fails saying existing release version 1.0.0+1 already exists.

**Expected Behavior**
Provide some way to create release artifact multiple times even if its already released.

**Additional Context**

```
➜  flutter_codepush_poc shorebird release android
✓ Fetching apps (0.6s)
✓ Building app bundle with Flutter 3.24.0 (a44a61357b) (3.5s)
✓ Release version: 1.0.0+1 (1.1s)
✓ Fetching releases (0.4s)

🚀 Ready to create a new release!

📱 App: flutter_codepush_poc (007a2cb9-86ee-4f73-90db-1d3322af1863)
📦 Release Version: 1.0.0+1
🕹️  Platform: android
🐦 Flutter Version: 3.24.0 (a44a61357b)

Would you like to continue? (y/N) Yes
✓ Fetching releases (0.4s)
✓ Creating release (0.9s)
✓ Updating release status (0.4s)
⠋ Creating artifacts... (41.8s)
✓ Creating artifacts (89.1s)
✓ Updating release status (2.7s)

✅ Published Release 1.0.0+1!
Your next step is to upload the app bundle to the Play Store:
/Users/natesh.bhat/Desktop/isha/flutter_codepush_poc/build/app/outputs/bundle/release/app-release.aab

For information on uploading to the Play Store, see:
https://support.google.com/googleplay/android-developer/answer/9859152?hl=en

To create a patch for this release, run shorebird patch --platforms=android --release-version=1.0.0+1

Note: shorebird patch --platforms=android without the --release-version option will patch the current version of the app.

➜  flutter_codepush_poc 
➜  flutter_codepush_poc shorebird release android --artifact apk
✓ Fetching apps (1.2s)
✓ Building app bundle with Flutter 3.24.0 (a44a61357b) (3.7s)
✓ Building APK with Flutter 3.24.0 (a44a61357b) (3.4s)
✓ Release version: 1.0.0+1 (1.1s)
✓ Fetching releases (0.4s)
It looks like you have an existing android release for version 1.0.0+1.
Please bump your version number and try again.

You can manage this release in the Shorebird Console

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
/Users/natesh.bhat/Library/Application Support/shorebird/logs/1723882237520_shorebird.log
```

**Comment by bryanoltman** [comment]
I agree this would be a good feature to have in the CLI. For now, you can download the aab from the release detail page on the [Shorebird console](https://console.shorebird.dev/apps/05fca845-8407-4f5a-8c32-ed4c7af1144b/releases/83526) and use `bundletool` to create an APK. [This StackOverflow answer](https://stackoverflow.com/a/57149405/144755) provides steps to do so.

<img width="520" alt="Screenshot 2024-08-18 at 9 27 30 AM" src="https://github.com/user-attachments/assets/1eb8cdde-c003-48d8-a8c0-402d064144b2">


About:

> create release artifact multiple times

I don't think this is actually what you're asking for, but just to be clear, you don't want to do this. Builds that are not identical to the original release cannot be patched.

**Comment by eseidel** [comment]
I suspect we should just do this.  It comes up pretty often.  e.g. `shorebird download-apk` or something.

**Comment by IndigoSoftwares21** [comment]
shorebird release android --artifact=apk

**Comment by eseidel** [comment]
`shorebird releases get-apks` is the command for getting past apks from an aab in storage (it calls bundletool for you).
