### ISSUE TITLE
fix: JWT issuer and user issuer do not match.

### ISSUE THREAD

**Issue by YunFeng-Huang** [shorebirdtech/shorebird#2432]
Choose an auth provider Microsoft
The Shorebird CLI needs your authorization to manage apps, releases, and patches on your behalf.

In a browser, visit this URL to log in:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=4fc38981-4ec4-4bd9-a755-e6ad9a413054&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A60143&scope=openid+email+offline_access&code_challenge=lnPsAUxdZw4vJmnAzA3xSpDq0mIfwaNo45mbtKa9Hew&code_challenge_method=S256&state=oHqzUn3kMF1T8QjTl6tLfxynBBttz_d1

Waiting for your authorization...
JWT issuer and user issuer do not match.

**Comment by bryanoltman** [comment]
Once you have logged in to Shorebird using one authentication method, you must use that authentication method moving forward. Without knowing what your email address is, my best guess is that you logged in using Google auth and now trying to use Microsoft auth for the same email, which is not supported.
