### ISSUE TITLE
fix: shorebird release android --artifact apk throws an error

### ISSUE THREAD

**Issue by Sheikh-X** [shorebirdtech/shorebird#2434]
App ID: (67e9fb3567c0)

**Description**

The command fails with the below error 

Gradle task bundleRelease failed with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:500:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildAab (package:flutter_tools/src/android/gradle.dart:245:5)
           <asynchronous suspension>
           #3      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:178:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>

**Steps To Reproduce**

Run "shorebird release android --artifact apk"

**Expected Behavior**

A .aab and apk file as the output.

**Screenshots**

**Additional Context**
I tried "flutter build apk" and it built an apk successfully, same with using "flutter build appbundle"

[1724238254295_shorebird.log](https://github.com/user-attachments/files/16690636/1724238254295_shorebird.log)

**Comment by eseidel** [comment]
The error is:
```
IO  : Writing 932903 characters to text file /Users/afeez/.pub-cache/log/pub_log.txt.
[+1072 ms] [+1770 ms] ../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
[   +4 ms] [   +1 ms]   final UnmodifiableUint8ListView bytes;
[        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^^^^^
[+3191 ms] [+3122 ms] ../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
[        ] [        ]   final UnmodifiableUint8ListView bytes;
[        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
[        ] [        ]     return Guid(UnmodifiableUint8ListView(guid));
[        ] [        ]                 ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
[        ] [        ]   factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
[        ] [        ]                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
[        ] [        ]     return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
[        ] [        ]                 ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [   +2 ms] Target kernel_snapshot_program failed: Exception
```

Because Shorebird by default uses the latest flutter stable (in this case 3.24.0) and it looks like your project isn't expecting that (and is hitting an upgrade error with Dart 3.5.0).

If you'd like to update to Flutter 3.24.0 that will solve the bug.  Otherwise you can also build with `shorebird release --fluter-version=3.22.3` which will build you with an older flutter.

See also https://shorebird.dev/blog/dart-3.5.0/ for when you hit this during upgrade.  You'll need to `dart pub upgrade` after running `flutter upgrade` to work around this upgrade error in 3.5.0

**Comment by Sheikh-X** [comment]
> shorebird release --fluter-version=3.22.3

shorebird release --fluter-version=3.22.3shorebird release --fluter-version=3.22.3

The solution worked but there is a spelling error, it should be  "shorebird release --flutter-version=3.22.3" in case you have the same issue and find yourself here.

**Comment by ZotInfo** [comment]
> The error is:
> 
> ```
> IO  : Writing 932903 characters to text file /Users/afeez/.pub-cache/log/pub_log.txt.
> [+1072 ms] [+1770 ms] ../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
> [   +4 ms] [   +1 ms]   final UnmodifiableUint8ListView bytes;
> [        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^^^^^
> [+3191 ms] [+3122 ms] ../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
> [        ] [        ]   final UnmodifiableUint8ListView bytes;
> [        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^^^^^
> [        ] [        ] ../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
> [        ] [        ]     return Guid(UnmodifiableUint8ListView(guid));
> [        ] [        ]                 ^^^^^^^^^^^^^^^^^^^^^^^^^
> [        ] [        ] ../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
> [        ] [        ]   factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
> [        ] [        ]                               ^^^^^^^^^^^^^^^^^^^^^^^^^
> [        ] [        ] ../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
> [        ] [        ]     return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
> [        ] [        ]                 ^^^^^^^^^^^^^^^^^^^^^^^^^
> [        ] [   +2 ms] Target kernel_snapshot_program failed: Exception
> ```
> 
> Because Shorebird by default uses the latest flutter stable (in this case 3.24.0) and it looks like your project isn't expecting that (and is hitting an upgrade error with Dart 3.5.0).
> 
> If you'd like to update to Flutter 3.24.0 that will solve the bug. Otherwise you can also build with `shorebird release --fluter-version=3.22.3` which will build you with an older flutter.
> 
> See also https://shorebird.dev/blog/dart-3.5.0/ for when you hit this during upgrade. You'll need to `dart pub upgrade` after running `flutter upgrade` to work around this upgrade error in 3.5.0

this command save my life, but need a correction:
`shorebird release android --flutter-version=3.22.3`

change 3.22.3 for your local flutter version
