### ISSUE TITLE
feat: Inquiry About Operation Logs and Release Restoration in Shorebird Console

### ISSUE THREAD

**Issue by JedTsai33** [shorebirdtech/shorebird#2449]
Could you please confirm whether the Shorebird Console provides operation logs and if it's possible to restore removed release records?

**Comment by bryanoltman** [comment]
We do not have this functionality. Depending on how long ago the release was deleted, there is a chance we might be able to restore the release. What is your app id and the release version?

**Comment by JedTsai33** [comment]
Thank you for your assistance. The information is as follows:

app_id: 0d0f0c04-ad74-4b44-8296-615763f510e4
Release version: 7.1.5+7105

flavor_id:
ff_hgw: cdac2070-9cb6-49aa-aea5-23f73cf86c04
ff_jsa: e568dc04-2458-4319-9375-eb1449a79d13
ff_bo8: 9439239d-b0ae-47bf-ac33-6e193e6e8006
ff_myb: a80b6d60-c219-4700-bff3-9a9354b3d5ed
ff_zs: 1d5b214f-56ac-48f7-92d8-25deceba9c85
ff_wbo: 1bb8f406-241d-41a3-b969-9d76339e8437
ff_yg: 201683ac-570b-45e3-bd5e-7dba7bc135f1
ff_yt8: 30f92376-e2a7-4de4-b5f8-b416a84c0ea2

**Comment by bryanoltman** [comment]
Unfortunately, we will not be able to recover these releases. Did you delete them by accident?

**Comment by cykingsley** [comment]
We have not deleted it before, so we would like to ask for help to understand the deletion process to confirm the reason and take action to prevent it from happening again.

**Comment by bryanoltman** [comment]
The only way releases can be deleted is in the Shorebird console. There is only one account with the permissions to do this (bao****22@gmail.com, redacted for privacy).

**Comment by JedTsai33** [comment]
Got it, thank you for your assistance.
