### ISSUE TITLE
fix: Gradle not detected on mac 

### ISSUE THREAD

**Issue by zakblacki** [shorebirdtech/shorebird#2451]
Steps to reproduce :  `shorebird doctor -v `

```
`g-besoin@MacBook-Air-de-G-Besoin ~ % shorebird doctor -v
Shorebird 1.2.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.24.1 • revision 01eadfbfbbe78b64aed76ea9f422eb432fd339cb
Engine • revision 8978a5e50daa39aa1180d57c7ec991e787d7f545

Logs: /Users/g-besoin/Library/Application Support/shorebird/logs
Android Toolchain
  • Android Studio: /Applications/Android Studio.app/Contents
  • Android SDK: /Users/g-besoin/Library/Android/sdk
  • ADB: /Users/g-besoin/Library/Android/sdk/platform-tools/adb
  • JAVA_HOME: /Applications/Android Studio.app/Contents/jbr/Contents/Home
  • JAVA_EXECUTABLE: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
  • JAVA_VERSION: openjdk version "17.0.11" 2024-04-16
                  OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
                  OpenJDK 64-Bit Server VM (build 17.0.11+0-17.0.11b1207.24-11852314, mixed mode)
                  
  • Gradle: not detected

✓ Shorebird is up-to-date (1.6s)
✓ Flutter install is correct (0.8s)
✓ Has access to storage.googleapis.com (0.4s)

No issues detected!
g-besoin@MacBook-Air-de-G-Besoin ~ % 
`
```
I have also tested on root path project :  I get `Gradle : Unknown` 

and on root/android/ `Gradle : not detected`

**Comment by felangel** [comment]
@zakblacki does this happen if you execute `shorebird doctor` in the root of a newly created flutter project?

`flutter create example`
`cd example`
`shorebird doctor`

**Comment by zakblacki** [comment]
> @zakblacki does this happen if you execute `shorebird doctor` in the root of a newly created flutter project?
> 
> `flutter create example` `cd example` `shorebird doctor`

`shorebird doctor` on new root project result : 

<img width="256" alt="image" src="https://github.com/user-attachments/assets/2b23fd4f-cc8f-4828-8495-cfa197c64485">


Edit : But `shorebird doctor -v` took a long time to return result it was stuck loading  

<img width="349" alt="image" src="https://github.com/user-attachments/assets/ff716435-8cd7-4cbf-bfda-0b0112193d5c">

I'm still getting Gradle : unknown 

```
Logs: /Users/g-besoin/Library/Application Support/shorebird/logs
Android Toolchain
  • Android Studio: /Applications/Android Studio.app/Contents
  • Android SDK: /Users/g-besoin/Library/Android/sdk
  • ADB: /Users/g-besoin/Library/Android/sdk/platform-tools/adb
  • JAVA_HOME: /Applications/Android Studio.app/Contents/jbr/Contents/Home
  • JAVA_EXECUTABLE: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
  • JAVA_VERSION: openjdk version "17.0.11" 2024-04-16
                  OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
                  OpenJDK 64-Bit Server VM (build 17.0.11+0-17.0.11b1207.24-11852314, mixed mode)
                  
  • Gradle: unknown

```

**Comment by eseidel** [comment]
Looks like our code is looking for a file:
`android/gradlew` in the project.  Presumably that's not there for this project?
https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/executables/gradlew.dart#L122

`flutter create .` will add any files missing from the project (including gradlew). But I'm not sure how `flutter build apk` works if `android/gradlew` isn't in the project.

**Comment by zakblacki** [comment]
> Looks like our code is looking for a file: `android/gradlew` in the project. Presumably that's not there for this project? https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/executables/gradlew.dart#L122
> 
> `flutter create .` will add any files missing from the project (including gradlew). But I'm not sure how `flutter build apk` works if `android/gradlew` isn't in the project.

Update : I did `flutter create . `  which downloaded some missing files, now   
return `• Gradle: 7.6.3` on root project. 
Edit : this only worked for flutter example project 

But please note that running `shorebird doctor -v` on root project is taking some of time to load is this normal ?
Edit 2 : this is solved after adding missing files 

Also calling `shorebird doctor -v` on desktop path is still returning  `Gradle: not detected`. 
does it works only on project root ? does it not detect global https://gradle.org/install/

**Comment by felangel** [comment]
This is happening because older versions of flutter generated the gradlew as part of running `flutter build apk` whereas newer versions of flutter apps include the gradlew as part of `flutter create`.

Let us know if that helps!

**Comment by SunlightBro** [comment]
```console
flutter create test_shorebird_doctor_v
cd test_shorebird_doctor_v
shorebird doctor -v
```

```console
Shorebird 1.4.8 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.24.4 • revision de629bcb9c96360eb3ca20fcc045263c19b1a33d
Engine • revision edb175f4b6894b63d8217952f0e4f59adb97a7e2

Logs: /Users/sunbro/Library/Application Support/shorebird/logs
Android Toolchain
  • Android Studio: /Applications/Android Studio.app/Contents
  • Android SDK: /Users/sunbro/Library/Android/sdk
  • ADB: /Users/sunbro/Library/Android/sdk/platform-tools/adb
  • JAVA_HOME: /Applications/Android Studio.app/Contents/jbr/Contents/Home
  • JAVA_EXECUTABLE: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
  • JAVA_VERSION: openjdk version "21.0.3" 2024-04-16
                  OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
                  OpenJDK 64-Bit Server VM (build 21.0.3+-79915917-b509.11, mixed mode)
                  
  • Gradle: unknown

URL Reachability
✓ https://api.shorebird.dev OK (0.3s)
✓ https://console.shorebird.dev OK (0.4s)
✓ https://oauth2.googleapis.com OK (0.1s)
✓ https://storage.googleapis.com OK (0.1s)
✓ https://cdn.shorebird.cloud OK (0.1s)

Network Speed
✓ GCP Upload Speed: 3.39 MB/s (1.7s)
✓ GCP Download Speed: 12.35 MB/s (1.5s)

✓ Shorebird is up-to-date (0.9s)
✓ Flutter install is correct (0.9s)
✗ AndroidManifest.xml files contain INTERNET permission (40ms)
  [✗] android/app/src/main/AndroidManifest.xml is missing the INTERNET permission.
✗ shorebird.yaml found in pubspec.yaml assets (4ms)
  [✗] No shorebird.yaml found in pubspec.yaml assets
2 issues detected.
2 issues can be fixed automatically with shorebird doctor --fix.
```

[1730294171698_shorebird.log](https://github.com/user-attachments/files/17573406/1730294171698_shorebird.log)

**Comment by bryanoltman** [comment]
Is the inability to detect gradle causing any issues beyond the `shorebird doctor` output?

**Comment by SunlightBro** [comment]
Sry for late response.
No issues as gradle is found, but the version does not get matched/parsed.

when I run `./gradlew --version`
```console
------------------------------------------------------------
Gradle 8.7
------------------------------------------------------------

Build time:   2024-03-22 15:52:46 UTC
Revision:     650af14d7653aa949fce5e886e685efc9cf97c10

Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.3 (JetBrains s.r.o. 21.0.3+-79915917-b509.11)
OS:           Mac OS X 14.6.1 aarch64
```

[gradlew.dart#L125-L134](https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/executables/gradlew.dart#L125-L134)
```dart
  /// Return the version of the gradle wrapper at [projectRoot].
  Future<String> version(String projectRoot) async {
    final result = await _run(['--version'], projectRoot);

    // Tries to match version string in the output (e.g. "Gradle 7.6.3")
    final versionPattern = RegExp(r'Gradle (\d+\.\d+\.\d+)'); 
    final match = versionPattern.firstMatch(result.stdout.toString());

    return match?.group(1) ?? 'unknown';
  }
```

This will not match `Gradle 8.7` and return unknown.
```diff
-  final versionPattern = RegExp(r'Gradle (\d+\.\d+\.\d+)');
+  // make patch number optional
+  final versionPattern = RegExp(r'Gradle (\d+\.\d+(\.\d+)?)');
```

But to be honest I was never great at regex, so this pattern could have flaws as well.

**Comment by bryanoltman** [comment]
@SunlightBro ~~Not exactly the right regex, but plenty to go on~~. Thanks for the help! Just pushed a PR to fix this.

Correction: that was the right regex 🙃
