### ISSUE TITLE
fix: console doesn't support HTTPS

### ISSUE THREAD

**Issue by feinstein** [shorebirdtech/shorebird#2465]
I am getting this warning on Firefox sometimes:

<img width="970" alt="image" src="https://github.com/user-attachments/assets/9bf34076-63a4-46f6-9550-b56adfe40766">

**Comment by eseidel** [comment]
Hmm, I have that same setting enabled in Chrome and it seems to work fine:

![image](https://github.com/user-attachments/assets/e17804d8-17c9-40e9-9dac-2d305cc71bdb)


<img width="330" alt="image" src="https://github.com/user-attachments/assets/7e633b0f-95f3-4d75-94fc-59fabbc5bbf6">

Are you able to see which URLs FF thinks are being loaded over http?

**Comment by eseidel** [comment]
I just grepped through the console sources and the only usage of "http" is either for localhost tests, or in the xmlns definition for xlink in svg files 🤣   As far as I can tell, everything on that site is done via https.

**Comment by feinstein** [comment]
It's really weird bc I got this error twice, but I can't reproduce it at will

**Comment by eseidel** [comment]
If you ever see it again, we would *love* to know!
