### ISSUE TITLE
fix:  app freeze at the splash screen after android patch

### ISSUE THREAD

**Issue by anything-good** [shorebirdtech/shorebird#2472]
App ID: 46bc1f29-7bd9-4068-96db-49bd43527b2a

**Description**

I made a android patch without changing any dependencies yet I get warning that my patch contain a native changes and if I accept that a publish the patch and download it on my device after I restart the app belong to your icon display and the app freezes at the splash screen so I reverted my code back to the version I used to make the last active patch with but I still I can the same warning and even after I accepted and published the patch the same error happening my application after it restarted it.

my log: 
 shorebird patch android
✓ Fetching apps (0.8s)
✓ Fetching releases (0.5s)
Which release would you like to patch? 1.0.0+2
✓ Fetching aab artifact (0.3s)
✓ Downloading aab (15.7s)
✓ Building patch with Flutter 3.22.1 (2f366bd7c9) (86.0s)
✓ Verifying patch can be applied to release (0.1s)
[WARN] Your app contains native changes, which cannot be applied with a patch.
    Changed files:
        base/dex/classes.dex

If you don't know why you're seeing this error, visit our troubleshooting page at https://docs.shorebird.dev/troubleshooting
Continue anyways? (y/N) Yes
[WARN] Your app contains asset changes, which will not be included in the patch.
    Added files:
        base/assets/flutter_assets/assets/icons/cards.svg
        base/assets/flutter_assets/assets/icons/spell.svg
        base/res/drawable-hdpi-v4/notification_oversize_large_icon_bg.png
        base/res/layout/ime_base_split_test_activity.xml
        base/res/layout/ime_secondary_split_test_activity.xml
    Changed files:
        base/assets/flutter_assets/AssetManifest.bin
        base/assets/flutter_assets/AssetManifest.json
        base/assets/flutter_assets/NOTICES.Z
        base/assets/flutter_assets/fonts/MaterialIcons-Regular.otf
        base/res/drawable-anydpi-v21/ic_call_answer.xml
        base/res/drawable-anydpi-v21/ic_call_answer_video.xml
        base/res/drawable-anydpi-v21/ic_call_decline.xml
        base/res/drawable-v21/launch_background.xml
        base/res/drawable/notification_tile_bg.xml
        base/res/layout-v21/notification_template_custom_big.xml
        base/res/layout-v21/notification_template_icon_group.xml
        base/res/layout/notification_template_big_media.xml
        base/res/layout/notification_template_big_media_custom.xml
        base/res/layout/notification_template_big_media_narrow.xml
        base/res/layout/notification_template_big_media_narrow_custom.xml
        base/res/layout/notification_template_lines_media.xml
        base/res/layout/notification_template_media.xml
        base/res/layout/notification_template_media_custom.xml
        base/res/layout/notification_template_part_time.xml
Continue anyways? (y/N)

**Comment by bryanoltman** [comment]
With both native and asset changes in your patch, this is not at all surprising. Our [concepts](https://docs.shorebird.dev/concepts/#what-types-of-changes-can-be-included-in-a-patch) page explains what can and cannot be applied in a patch. Ignoring these warnings may cause your app to crash or behave in unexpected ways.
