### ISSUE TITLE
feat: Make it possible to make a collaborator "admin" from the console

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2477]
Currently giving Admin permissions to an app requires customers to reach out to contact@shorebird.dev.

We could pretty trivially expose a button to do this in the console.

**Comment by felangel** [comment]
@bryanoltman I believe we can close this now?

**Comment by bryanoltman** [comment]
Yep.

Closed by https://github.com/shorebirdtech/_console/pull/239.
