### ISSUE TITLE
fix: shorebird release android

### ISSUE THREAD

**Issue by Ibrahiemhm** [shorebirdtech/shorebird#2489]
App ID: (insert your app ID here)

**Description**
[1726980336536_shorebird.log](https://github.com/user-attachments/files/17088322/1726980336536_shorebird.log)

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by bryanoltman** [comment]
In the log, you can see `Type 'UnmodifiableUint8ListView' not found`. This is due to the Dart 3.5.0 upgrade, which we detail how to deal with in this blog post: https://shorebird.dev/blog/dart-3.5.0/
