### ISSUE TITLE
feat: Show a high level indicator that a release has been patched

### ISSUE THREAD

**Issue by ScottMacDougall** [shorebirdtech/shorebird#2493]
**Description**

From the list of releases on the console, there's no indication that a release has had patches created for it, and what their current status is (staging, live, etc). This would be useful when there is a large list of releases, and you want to go to your last release that had patches applied to look at any statistics. At the simplest level, it could just be a bubble on the platform icon to indicate the number of patches that exist in any state (or just live) for that platform.

**Requirements**

- [ ] Add an indicator that patches exist for a particular release for Android
- [ ] Add an indicator that patches exist for a particular release for iOS

**Additional Context**

<img width="953" alt="Screenshot 2024-09-23 at 1 02 17 PM" src="https://github.com/user-attachments/assets/1833b0a7-e4c6-461c-8765-76892477d4f7">

**Comment by eseidel** [comment]
Makes sense.  Felix and Bryan are looking at making our console better right now, so this is very timely thank you!

**Comment by felangel** [comment]
Just deployed the change to production, let me know if you encounter any issues 👍
