### ISSUE TITLE
fix: test updates on preview version during development 

### ISSUE THREAD

**Issue by MUHA-NDONG** [shorebirdtech/shorebird#2496]
App ID: (9cc3b1c5-817e-4fff-af6f-a932f417980b)

**Description**

The issue I'm facing is I made releases during development, and patched it. So when I preview it and wait for the automatic download for the new updates after changing a little text it still doesn't download the new updates. I'm actually on development so I'm testing for development not for production. So i made 5 releases and only two versions are showing they have downloads when i go to the downloads section of shorebird dashboard which tracks number of downloads and those versions i made a commit before doing their releases. I waited for so long and i didn't see any downloads on the dashboard of shorebird so i went on to create other releases without doing commits, so when i came to those two versions which are 1.0.0+3 and 1.0.0+4, they had one downloads but i have already moved on to release other patches to test whether the app will automatically download new updates. I'm using windows.
**Steps To Reproduce**

**Expected Behavior**
The app should automatically download the new changes when i create a new releases for new changes and automatically updates the app with new changes patched.

**Screenshots**
![Screenshot (112)](https://github.com/user-attachments/assets/f82cffcc-891e-49df-b7ae-4b142201674f)
![Screenshot (113)](https://github.com/user-attachments/assets/663c8565-41d8-4d42-9219-3ee233f0b958)
![Screenshot (114)](https://github.com/user-attachments/assets/3452ea5e-40c6-463e-9efd-3
![Screenshot (117)](https://github.com/user-attachments/assets/3eb32fd0-22b6-459c-bd37-8f8c8699f74a)
![Screenshot (118)](https://github.com/user-attachments/assets/91235591-ca23-4dc4-b844-a714563ec6eb)
![Screenshot (119)](https://github.com/user-attachments/assets/14cd8d1b-1214-400e-b8cd-2422abeb9b61)
![Screenshot (120)](https://github.com/user-attachments/assets/ef2fdcb1-fe8f-45d8-952b-211227fa3d61)
![Screenshot (121)](https://github.com/user-attachments/assets/991abc3d-da3e-4b50-a3f3-c2fe10831946)
![Screenshot (122)](https://github.com/user-attachments/assets/2adada95-a728-422e-bca3-9d4ab6462400)
![Screenshot (123)](https://github.com/user-attachments/assets/777a3214-ee6a-4972-a958-5fd9cb5027e5)
![Screenshot (124)](https://github.com/user-attachments/assets/d8f87c56-0fd9-466e-b1f3-dce32b9948e9)
06b8195c5f3)
![Screenshot (115)](https://github.com/user-attachments/assets/e0372242-bb74-45a1-b0a5-c83240a7f358)

**Additional Context**

**Comment by bryanoltman** [comment]
>  it still doesn't download the new updates

Presuming this is the issue, what does the log output of `shorebird preview` show you? I would expect to see PatchCheckRequests being made. If you could share the full log of what you see when running `shorebird preview`, that would be very helpful.

Re: the charts, that data is not real-time.

**Comment by MUHA-NDONG** [comment]
> > it still doesn't download the new updates
> 
> Presuming this is the issue, what does the log output of `shorebird preview` show you? I would expect to see PatchCheckRequests being made. If you could share the full log of what you see when running `shorebird preview`, that would be very helpful.
> 
> Re: the charts, that data is not real-time.

![Screenshot (125)](https://github.com/user-attachments/assets/eadaab86-8801-42d5-a6d7-09496154c8f0)

**Comment by bryanoltman** [comment]
And after restarting the app, you aren't seeing the new patch?

**Comment by MUHA-NDONG** [comment]
Yeah I'm not seeing the new patch

**Comment by bryanoltman** [comment]
Can you share the logs after killing and restarting the app? You should be able to keep the same `shorebird preview` session running.

**Comment by MUHA-NDONG** [comment]
![Uploading Screenshot (126).png…]()

**Comment by MUHA-NDONG** [comment]
> Can you share the logs after killing and restarting the app? You should be able to keep the same `shorebird preview` session running.

![Screenshot (126)](https://github.com/user-attachments/assets/606bc41b-1317-4595-a4c4-8a5a57e909f0)

**Comment by bryanoltman** [comment]
That shows that your app has successfully installed and is running patch 1. What are you expecting to see in your app that you aren't seeing?

**Comment by MUHA-NDONG** [comment]
why is it running patch 1 when i released a patch for 1.0.0+6

**Comment by bryanoltman** [comment]
The logs you shared show you running release version 1.0.0+5

**Comment by MUHA-NDONG** [comment]
yeah i actually fixed it. The problem was i was creating a new release for every patch i was doing. So I created a new release 1.0.0+6 and patched on that same version and the changes i made was updated and it worked. Thanks for you concern
