### ISSUE TITLE
fix: Cannot build android release

### ISSUE THREAD

**Issue by dtilhoo** [shorebirdtech/shorebird#2497]
App ID: 7327e370-e8f1-477e-844f-bdcc8a00acf8

Android release build fails with Flutter 3.24.3. I am using dart defines also. appbundle and apks are built with no issues when using flutter build command but with shorebird it fails.

[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.6.5)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.93.1)
[√] Connected device (4 available)
[√] Network resources

[1727258187908_shorebird.log](https://github.com/user-attachments/files/17129018/1727258187908_shorebird.log)

**Comment by bryanoltman** [comment]
Can you share the exact command you ran?

**Comment by dtilhoo** [comment]
@bryanoltman shorebird release android -- --dart-define xxx. i also tried the command without the --, shorebird release android --dart-define xxx but i got the same error

**Comment by bryanoltman** [comment]
It looks like you're hitting this https://github.com/flutter/flutter/issues/105535#issuecomment-1154306373

What version of flutter are you using locally?

**Comment by bryanoltman** [comment]
https://stackoverflow.com/questions/63335694/this-application-cannot-tree-shake-icons-fonts also seems relevant

**Comment by eseidel** [comment]
Looks like:
```
[ +106 ms] [  +31 ms] Target aot_android_asset_bundle failed: Error: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.
```
is the error.

Let us know if Bryan's suggestions don't help.

**Comment by dtilhoo** [comment]
@eseidel  shorebird release android --no-tree-shake-icons  --dart-define xxx doesn't work.

Returns Could not find an option named "no-tree-shake-icons".

What's the command to add no-tree-shake-icons with shorebird?

**Comment by dtilhoo** [comment]
Worked with  shorebird release android '--' --no-tree-shake-icons --dart-define.  Thank you guys :)
