### ISSUE TITLE
feat: support HarmonyOS

### ISSUE THREAD

**Issue by ronaldoandjames** [shorebirdtech/shorebird#2500]
it is a new mobile os made by huawei inc.

**Comment by eseidel** [comment]
It would be fun to add Harmony OS support, however upstream Flutter doesn't support Harmony OS to my knowledge?

Are you aware of a version of Flutter ported to Harmony OS?  If so, we'd be happy to consider adding support.

**Comment by ronaldoandjames** [comment]
sure. here it it:
https://gitee.com/openharmony-sig/flutter_flutter

it's based on flutter 3.7.12

Eric Seidel ***@***.***>于2024年10月5日 周六上午3:34写道：

**Comment by eseidel** [comment]
Thanks!  Shorebird currently only works with Flutter 3.10 and later (on Android) and Flutter 3.24.0 and later on iOS.  I'm interested in supporting Harmony OS, but I suspect we will need to get a bit bigger before we can do so.

**Comment by eseidel** [comment]
I don't see any path for us to take action on this soon, so closing this for now.

I'd be very interested in adding this eventually!

**Comment by eseidel** [comment]
https://gitee.com/harmonycommando_flutter/flutter is another fork, I'm not sure which is "official".

**Comment by ronaldoandjames** [comment]
this fork is not official, but it is based on a newer flutter version.
maybe this can be  adapted to shorebird?😀
Eric Seidel ***@***.***>于2024年11月28日 周四下午12:30写道：
