### ISSUE TITLE
feat: Hybrid App iOS using Option A

### ISSUE THREAD

**Issue by arthurmonteiroalvesmelo** [shorebirdtech/shorebird#2502]
**Description**

Flutter can't handle [common dependencies with xcframeworks](https://github.com/flutter/flutter/issues/130220). If both the host app and the Flutter module's plugin define the same pod dependency and you integrate Flutter module using this option, errors result. These errors include issues like Multiple commands produce 'CommonDependency.framework'.

To work around this issue, link every plugin source in its podspec file from the Flutter module to the host app's Podfile. Link the source instead of the plugins' xcframework framework. The next section explains how to [produce that framework](https://github.com/flutter/flutter/issues/114692).

**Requirements**

Add the Option A support using Shorebird.

**Additional Context**

Datadog `native-hybrid-app` is an example (https://github.com/DataDog/dd-sdk-flutter/tree/develop/examples/native-hybrid-app)
of this approach using the datadog plugin in the flutter module and the datadog pod in Podfile. If you try to use datadog using the Option B or C, the error `Multiple commands produce 'DatadogCore.framework` will happen.

**Comment by eseidel** [comment]
Agreed.  Currently tracking this via https://github.com/shorebirdtech/shorebird/issues/1198, but let me know if we missed something. Thanks!

**Comment by arthurmonteiroalvesmelo** [comment]
@eseidel thank you
