### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by ITApexGroup** [shorebirdtech/shorebird#2505]
Shorebird patch ios . I get this error 
<img width="1204" alt="Screenshot 2024-10-01 at 17 11 48" src="https://github.com/user-attachments/assets/6514330f-6e52-410a-b2ad-d3be786e608e">

**Comment by ITApexGroup** [comment]
![Uploading Screenshot 2024-10-01 at 17.14.10.png…]()

**Comment by eseidel** [comment]
Thanks.  Are you able to share the log it links to?

**Comment by eseidel** [comment]
We would love to help, but will require more information.  The screenshot above cuts of the top of the stack trace.  The log that it mentions would give a fuller picture of what happened.

**Comment by bryanoltman** [comment]
Closing as unactionable. Please reopen if you're able to provide more information.
