### ISSUE TITLE
feat: Using ShoreBird with SeverPod

### ISSUE THREAD

**Issue by Princewil** [shorebirdtech/shorebird#2509]
I think this is more of an enquiry. 

How do I use shorebird with [Severpod](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://serverpod.dev/&ved=2ahUKEwibkZfggviIAxUiT0EAHf45DmQQFnoECBcQAQ&usg=AOvVaw3Xe2MMNDREB5WTDD7Bb911) considering Serverpod creates three flutter files.

**Comment by eseidel** [comment]
The standard Shorebird instructions should work just fine:

https://docs.shorebird.dev/

If Serverpod offers you multiple main files, you can use `-t` to pass the main.dart file you are trying to run, e.g.:

`shorebird release -t lib/main_prod.dart`

**Comment by Princewil** [comment]
Thanks
