### ISSUE TITLE
feat: Shorebird status page

### ISSUE THREAD

**Issue by must-ismail** [shorebirdtech/shorebird#2526]
**Description**

It would be good if Shorebird provided a status page (status.shorebird.dev) like many SaaS services do.

Website, consol, API health and uptime status could be shared here. We can check patch download availability and easily get notified when there is issue.

**Comment by felangel** [comment]
We have a basic one up at https://shorebird.statuspage.io/
Let us know if that helps!

**Comment by bryanoltman** [comment]
Closing as "fixed", as I think what Felix shared is what the original request is asking for. Please reopen if this is not the case.
