### ISSUE TITLE
feat: Switch to multipart file uploads for release artifacts

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#2533]
We believe this will make our release artifact upload process faster/more robust

Related to https://github.com/shorebirdtech/shorebird/issues/2532

**Comment by bryanoltman** [comment]
I think we may actually already do this? https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_code_push_client/lib/src/code_push_client.dart#L185-L189

**Comment by felangel** [comment]
Yeah it does look like we're already doing this as per #1464. We could refactor to support resumable uploads but that seems like it should be a different issue. Closing for now.
