### ISSUE TITLE
fix: Shorebird Engine not available, using no-op implementation.

### ISSUE THREAD

**Issue by dphans** [shorebirdtech/shorebird#2543]
App ID: `bf30caaa-43d4-43be-901d-cb35f83ba480`

**Description**

Manually update using `shorebird_code_push` package, but when I check for availability by using:

```dart
final _shorebirdCodePush = ShorebirdCodePush();
final isAvailable = _shorebirdCodePush.isShorebirdAvailable();
```

The debug print following error:

```
flutter: [ShorebirdCodePush]: Shorebird Engine not available, using no-op implementation.
```

**Screenshots**

<img width="1728" alt="Screenshot 2024-10-16 at 22 03 55" src="https://github.com/user-attachments/assets/33138660-0492-403e-ba19-b339ab02bf3e">

**Additional Context**

```
flutter --version
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (5 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3
```

```
shorebird doctor
Shorebird 1.4.0 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.24.3 • revision 5a6dc546e8ecd01fe3b9527f082ff2d6864374f9
Engine • revision 033ec57900456ca7f8cd4bb59c2773a8ce27cb5d

✓ Shorebird is up-to-date (2.1s)
✓ Flutter install is correct (1.4s)
✓ Has access to api.shorebird.dev (0.9s)
✓ Has access to storage.googleapis.com (0.5s)
✓ shorebird.yaml found in pubspec.yaml assets (4ms)

No issues detected!
```

```
Mac OS 15.0.1 (arm - m2 max)
```

**Comment by bryanoltman** [comment]
This error message means the app you're running was not built using `shorebird release`. You can test these builds using `shorebird preview`.

**Comment by dphans** [comment]
But when I run following script to create a release:

```
shorebird release --platforms=ios
```

An error occurred (I've attached log below):

```
~/Desktop/flutter_codepush
shorebird release --platforms=ios
✓ Fetching apps (1.2s)
✗ Failed to build:
 (82.5s)

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
...1729091913301_shorebird.log
```

[shorebird_flutter_3.24.3_release_issue.log](https://github.com/user-attachments/files/17398132/shorebird_flutter_3.24.3_release_issue.log)


I already set automatic signing in xcode project with development team.

**Comment by bryanoltman** [comment]
The underlying error seems to be:

```
[   +1 ms] Encountered error while creating the IPA:
[        ] error: exportArchive Failed Registering Bundle Identifier
           error: exportArchive No profiles for 'com.example.flutterCodepush' were found

[        ] Try distributing the app in Xcode: "open /Users/dphans/Desktop/flutter_codepush/build/ios/archive/Runner.xcarchive"
```

**Comment by bryanoltman** [comment]
I think the real issue here is that you're unable to release and we did not print a helpful error message. I filed https://github.com/shorebirdtech/shorebird/issues/2544 to track that.

**Comment by dphans** [comment]
> I think the real issue here is that you're unable to release and we did not print a helpful error message. I filed #2544 to track that.

The logger shown the helpful message, cause it too large so I've split into log file (a `--verbose` one). Sorry my fault.

**Comment by dphans** [comment]
Sorry cause of AppStore connect side, I closed this issue now 🙏

**Comment by bryanoltman** [comment]
Not your fault! We definitely could make that easier to solve. I've opened a PR to make the cause of this kind of failure more obvious https://github.com/shorebirdtech/shorebird/pull/2545
