### ISSUE TITLE
fix: App doesn't launch with new patch if it was installed during a terminated state

### ISSUE THREAD

**Issue by AhmedLSayed9** [shorebirdtech/shorebird#2548]
**Description**

If new patch was installed when the app is terminated (i.e: using a notification), It's installed successfully:
```
10-16 09:20:45.375 15292 15629 I flutter : updater::updater: Patch 1 successfully downloaded. It will be launched when the app next restarts.
10-16 09:20:45.375 15292 15629 I flutter : updater::c_api: Update result: Update installed
```
Then, when I open the app, I get the following log:
```
10-16 09:21:22.239 15292 15292 I flutter : updater::updater: Reporting successful launch.
```
But the app isn't launched with the new patch and I need 1 more restart.

**Comment by bryanoltman** [comment]
`Reporting successful launch` doesn't necessarily mean a patch is running. just that the shorebird updater was able to successfully initialize and check for an update. Especially with notifications, this may happen multiple times during a single app run.

The app is not actually in a terminated when responding to a notification (it gets woken up). I suspect what you're seeing is that the app is started, the patch is downloaded and installed, and not terminated again until you restart it the second time.

**Comment by AhmedLSayed9** [comment]
> `Reporting successful launch` doesn't necessarily mean a patch is running. just that the shorebird updater was able to successfully initialize and check for an update. Especially with notifications, this may happen multiple times during a single app run.
> 
> The app is not actually in a terminated when responding to a notification (it gets woken up). I suspect what you're seeing is that the app is started, the patch is downloaded and installed, and not terminated again until you restart it the second time.

The patch is already downloaded and installed when the app was terminated (and got woken up), when I launch the app again after that it should be launched with the new patch, right?

**Comment by bryanoltman** [comment]
When you boot the app after that, it should use the new patch. If you're opening the app via a notification, it was likely booted to respond to the notification and not terminated between then and when you open it.

**Comment by AhmedLSayed9** [comment]
> When you boot the app after that, it should use the new patch.

Exactly. That's what I'm expecting but It doesn't launch with the new patch. I open it normally not via the notification.

**Comment by bryanoltman** [comment]
Right, but you aren't _booting_ the app when opening from a notification. It is already booted and running in the background.

**Comment by bryanoltman** [comment]
The full flow that you're seeing looks like this:

1. notification is received
2. patch is downloaded
3. (app continues running)
4. you open the app. The patch is downloaded at this point, but because the app has not restarted, the app is not running the patch
5. you kill the app
6. the app boots from the new patch

**Comment by AhmedLSayed9** [comment]
Nope, the app was terminated not in the background.

so, the flow looks like this:

1. app is terminated
2. notification is received
3. app woken up and patch is downloaded
4. opening the app from a terminated state
5. the app is not running the patch (1 more restart needed to boot the new patch)

**Comment by bryanoltman** [comment]
> 3. app woken app and patch is downloaded
> 4. opening the app from a terminated state

What is terminating your app between these steps?

**Comment by AhmedLSayed9** [comment]
Do you mean if I receive a notification when the app is terminated, it'll be woken up and stay in that state?

**Comment by bryanoltman** [comment]
Until either you or the OS terminate it, yes.

**Comment by bryanoltman** [comment]
The exact behavior depends on the specific OS (and are generally not clearly articulated by the vendors), but generally, apps usually only terminated by the OS in the short-term if resources (e.g., memory) are required.

**Comment by AhmedLSayed9** [comment]
Alright.
I'll give it another try and back with a feedback, Thanks!

Do you know if there's a way to terminate the app manually?

**Comment by bryanoltman** [comment]
Discussions for this on [iOS](https://developer.apple.com/documentation/xcode/reduce-terminations-in-your-app#Understand-termination-reasons) and [Android](https://developer.android.com/guide/components/activities/process-lifecycle) (see "cached process" at the bottom)

**Comment by bryanoltman** [comment]
> Do you know if there's a way to terminate the app manually?

We use the restart package in the https://pub.dev/packages/shorebird_code_push example app for this.

**Comment by AhmedLSayed9** [comment]
Alright.

Closing the app using `force quit` before opening it made it launch with the new patch successfully, so yes the app was staying awake after receiving my notification.

Using `Restart.restartApp()` from restart package inside `firebaseMessagingBackgroundHandler` doesn't help.

**Comment by Flattih** [comment]
@AhmedLSayed9 Hi Ahmed, can you help me with the most effective solution you have found for this situation?

**Comment by AhmedLSayed9** [comment]
> [@AhmedLSayed9](https://github.com/AhmedLSayed9) Hi Ahmed, can you help me with the most effective solution you have found for this situation?

I haven’t yet found a way to terminate the app when receiving an OTA update notification in `firebaseMessagingBackgroundHandler`.
Also, Data only messages are classed as "low priority" and aren’t guaranteed to be delivered anyway.

So far what I'm doing:
- In foreground, I'm using a notification (will update this to use remote config instead) to check and download an update if necessary, then show a dialog that asks the user to restart the app.
- In background handler, I'm using a notification to check and download an update if necessary.
- At the start of the app, I'm checking if there's an update available, then download it and ask the user to restart the app. (This serves as a guard for previous steps, as they're not guaranteed)

**Comment by Flattih** [comment]
Yes, I wish the terminate problem could be solved. I solved it with shorebird code push and terminate restart packages, thanks.

**Comment by eseidel** [comment]
There was a discussion today on discord (https://discord.gg/shorebird) suggesting that https://pub.dev/packages/terminate_restart works much better for folks than package:restart_app.

**Comment by AhmedLSayed9** [comment]
Thanks @eseidel 
I'll give it a try!
