### ISSUE TITLE
TRUSTED_TESTERS.md and `shorebird doctor` are inconsistent re: permissions

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#255]
TRUSTED_TESTERS.md says I need both:

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

But doctor only checks for one?

I think we only need one?

**Comment by bryanoltman** [comment]
https://github.com/shorebirdtech/time_shift/blob/main/android/app/src/main/AndroidManifest.xml only contains the INTERNET permission. Not sure which is correct.
