### ISSUE TITLE
fix: Android patch failing with exit code 70

### ISSUE THREAD

**Issue by josiahsrc** [shorebirdtech/shorebird#2550]
App ID: f2feb796-ca62-4bd7-955b-9ef95b40bdea

**Description**

Android patch command failing with exit code 70. Android build command is working fine, but the patch is failing. iOS is working flawlessly.

**Steps To Reproduce**

(The project set up I have is quite involved. I can add these steps if the logs don't help).

**Expected Behavior**

I expect the patch to work.

**Screenshots**

<img width="1430" alt="image" src="https://github.com/user-attachments/assets/783766e1-2ccc-4367-af0c-2a481a630970">

**Additional Context**

I am using [background geolocation](https://github.com/transistorsoft/flutter_background_geolocation) and just recently updated my android configuration as per flutter's upgrade guide to the [new dependency setup](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply). I did this a while back, unsure of when android started failing. **Android was working at some point in time**

Here are the logs for this failure

[shorebird.log](https://github.com/user-attachments/files/17403619/shorebird.log)

Any ideas what the issue is? Thank you Shorebird team!!

**Comment by bryanoltman** [comment]
```
[        ] Execution failed for task ':app:signProdReleaseBundle'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.FinalizeBundleTask$BundleToolRunnable
[        ]    > java.lang.NullPointerException (no error message)
```

It looks like there was an error signing the app. Do you have your keystore configured correctly? 

I don't think it will help here, but if you're ever experiencing an issue and see the notice about a new version of Shorebird being available, the first thing to try is running `shorebird upgrade` to see if we've already fixed the bug.

**Comment by josiahsrc** [comment]
Sorry for the late reply. You're right, this was an issue with the keystore. I updated my runner to populate the keystore, and this all worked correctly.

Some feedback: It would be helpful to show an error noting that the keystore file is missing, the above error wasn't very clear on what was wrong.
