### ISSUE TITLE
fix: After updating shorebird, it has been stuck in Extractingbundletool.jar, and does not execute further.

### ISSUE THREAD

**Issue by zyq9613** [shorebirdtech/shorebird#2551]
linxi@Mac-mini kx_flutter_verticalscreen % shorebird patch android --staging --verbose
Updating Flutter...
Cloning into '/Users/linxi/.shorebird/bin/cache/flutter/5a6dc546e8ecd01fe3b9527f082ff2d6864374f9'...
remote: Enumerating objects: 43494, done.
remote: Total 43494 (delta 0), reused 0 (delta 0), pack-reused 43494 (from 1)
Receiving objects: 100% (43494/43494), 25.21 MiB | 10.27 MiB/s, done.
Resolving deltas: 100% (2059/2059), done.
remote: Enumerating objects: 2012, done.
remote: Counting objects: 100% (545/545), done.
remote: Compressing objects: 100% (468/468), done.
remote: Total 2012 (delta 109), reused 77 (delta 77), pack-reused 1467 (from 1)
Receiving objects: 100% (2012/2012), 339.09 KiB | 1.23 MiB/s, done.
Resolving deltas: 100% (124/124), done.
remote: Enumerating objects: 6945, done.
remote: Counting objects: 100% (4783/4783), done.
remote: Compressing objects: 100% (4084/4084), done.
remote: Total 6945 (delta 1627), reused 699 (delta 699), pack-reused 2162 (from 1)
Receiving objects: 100% (6945/6945), 13.17 MiB | 9.45 MiB/s, done.
Resolving deltas: 100% (2136/2136), done.
Updating files: 100% (8621/8621), done.
HEAD is now at 5a6dc546 chore: roll engine to `033ec57900456ca7f8cd4bb59c2773a8ce27cb5d` (improve aot_tools error reporting)
Shorebird Engine • revision 033ec57900456ca7f8cd4bb59c2773a8ce27cb5d
Downloading Darwin arm64 Dart SDK from Flutter engine 033ec57900456ca7f8cd4bb59c2773a8ce27cb5d...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 78.2M  100 78.2M    0     0  2034k      0  0:00:39  0:00:39 --:--:-- 2844k
Building flutter tool...
Resolving dependencies...
Downloading packages...
Got dependencies.
Flutter 3.24.4-0.0.pre.5 • channel [user-branch] • unknown source
Framework • revision 5a6dc546e8 (2 weeks ago) • 2024-09-30 13:34:43 -0500
Engine • revision 033ec57900
Tools • Dart 3.5.3 • DevTools 2.37.0
Building Shorebird...
Resolving dependencies...
Downloading packages...
Got dependencies.
[HTTP] GET https://storage.googleapis.com/download.shorebird.dev/shorebird/033ec57900456ca7f8cd4bb59c2773a8ce27cb5d/patch-darwin-x64.zip
✓ Downloading patch... (0.8s)
⠸ Extracting patch...... (1.0s)[Process.start] chmod +x /Users/linxi/.shorebird/bin/cache/artifach
✓ Extracting patch... (1.1s)
[HTTP] GET https://github.com/google/bundletool/releases/download/1.17.1/bundletool-all-1.17.1.jar
✓ Downloading bundletool.jar... (1.6s)
⠼ Extracting bundletool.jar...... (229.9s)

**Comment by eseidel** [comment]
Thank you very much for the report.  @bryanoltman and @felangel are investigating related hangs as we speak.

**Comment by bryanoltman** [comment]
@zyq9613 can you update to the latest version of shorebird and try running this again?

**Comment by eseidel** [comment]
I suspect that this was related to network delays from Windows Defender?

**Comment by zyq9613** [comment]
I think it's my network. I tried it many times and solved it.
thanks
