### ISSUE TITLE
fix : Inquiry Regarding Missing Features on Shorebird Admin Panel

### ISSUE THREAD

**Issue by JedTsai33** [shorebirdtech/shorebird#2552]
App ID: 0d0f0c04-ad74-4b44-8296-615763f510e4

**Description**

In the Shorebird admin panel, the options to remove releases and patches are no longer available. May I ask if there are adjustments being made to the admin panel functionalities?

**Comment by eseidel** [comment]
I believe they got moved under Settings.

<img width="712" alt="image" src="https://github.com/user-attachments/assets/3bf940c0-6b8c-40ef-b41e-07d8c0099f37">

**Comment by JedTsai33** [comment]
If I just want to delete a release from a specific flavor, or delete only the Android or iOS release within the release, how should I do it?

**Comment by felangel** [comment]
> If I just want to delete a release from a specific flavor, or delete only the Android or iOS release within the release, how should I do it?

You can do this by navigating to the release details and clicking on the settings tab. Then when you click the delete button you’ll be prompted to select which platforms to delete.

**Comment by JedTsai33** [comment]
I got it, thank you for your help.
