### ISSUE TITLE
fix: Patch process stuck at "Downloading release artifacts"

### ISSUE THREAD

**Issue by JioBani** [shorebirdtech/shorebird#2553]
App ID: 1263fead-0a8b-42ed-8a7c-d14b2d846f8f

**Description**

I tried to run the following command to patch, but it doesn't progress beyond the "Downloading release artifacts" step:
shorebird patch --platforms=android --release-version=0.0.1+3

**Steps To Reproduce**

1. Modify the code(complex changes including FCM integration, notification permission settings, and other native modifications)
2. Run shorebird release android --artifact apk
3. Modify the code (changing a Column to a ListView).
4. Run shorebird patch --platforms=android --release-version=0.0.1+3
5.  Downloading release artifacts... (never end)

**Expected Behavior**

The patch command should complete successfully.

**Screenshots**

![image](https://github.com/user-attachments/assets/0e880712-a05c-4f17-889d-28faef4e96ea)

**Additional Context**

[shorebird doctor]                                             
Shorebird 1.4.1 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.24.3 • revision 5a6dc546e8ecd01fe3b9527f082ff2d6864374f9
Engine • revision 033ec57900456ca7f8cd4bb59c2773a8ce27cb5d

URL reachability:
✓ https://api.shorebird.dev OK (0.5s)
✓ https://console.shorebird.dev OK (0.7s)
✓ https://oauth2.googleapis.com OK (0.2s)
✓ https://storage.googleapis.com OK (66ms)
✓ https://cdn.shorebird.cloud OK (0.2s)

✓ Shorebird is up-to-date (1.9s)
✓ Flutter install is correct (2.3s)
✓ AndroidManifest.xml files contain INTERNET permission (71ms)
✓ Has access to api.shorebird.dev (0.2s)
✓ Has access to storage.googleapis.com (15ms)
✓ shorebird.yaml found in pubspec.yaml assets (16ms)

No issues detected!

**Comment by JioBani** [comment]
Oh my, I successfully downloaded the release artifacts in 62 minutes.. I'm sorry, I didn't expect it to take this long and still work. After running the command, posting the issue, and having a meal, I still had some time left.

![image](https://github.com/user-attachments/assets/4fb68c67-b965-42ff-8ed6-ce474af1c660)

**Comment by eseidel** [comment]
Thanks for the report.  It definitely should not take 62 minutes to download artifacts. 😦

**Comment by bryanoltman** [comment]
Excuse the crude highlighting, but one thing that's very interesting here is that the aab (which I would expect to be quite a bit larger than any of the other release artifacts) downloads in 3.7s while the full set of release artifacts takes 100x that 🤔 

![377799525-4fb68c67-b965-42ff-8ed6-ce474af1c660](https://github.com/user-attachments/assets/d5a72056-bca9-4a2f-9283-c544d0f7e49a)

Both steps use this utility to download the file, so will need to dig a bit deeper here (https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/artifact_manager.dart#L57).

**Comment by local-dev-HW** [comment]
I too have been experiencing the same phenomenon since last week. It takes at least 2000s~3000s on average.

**Comment by eseidel** [comment]
We had one person report on Discord that the delay went away when they moved from running inside Powershell to another shell.  I don't understand why that would be the case, but that's one theory to try.  Felix and Bryan continue to investigate.

**Comment by bryanoltman** [comment]
We just released version 1.4.4, which adds download progress to the CLI output. I'd be curious to know what users who are hitting this issue see (does it stall out at a certain percentage? does the download even begin?)

**Comment by bryanoltman** [comment]
Another question for those experiencing this issue: which version of Flutter do you have installed?

**Comment by local-dev-HW** [comment]
![화면 캡처 2024-10-23 112216](https://github.com/user-attachments/assets/65bc4e53-3dae-41c9-828c-dc4f153cbb3d)

![화면 캡처 2024-10-23 112707](https://github.com/user-attachments/assets/9eaf96e3-d17e-4c42-8148-acb746e43dae)

If you do the second patch right after the first patch, the time will be shortened. 

If you patch again after a certain period of time, it will take a long time again. 

flutter version is 3.24.1

**Comment by jakubkrapiec** [comment]
In my case it takes so much time because downloading the release artifacts progresses incredibly slowly (although consistently), even though I have fast internet connection. In the Task Manager it looks like Shorebird downloads a few kBs and then pauses for a few seconds before resuming. I only have this issue on Windows, Shorebird on macOS works flawlessly.

**Comment by bryanoltman** [comment]
I had been able to reproduce this (follow my journey in https://github.com/shorebirdtech/shorebird/issues/2532), but after installing the latest windows update (2024-10 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5044380)), I am not able to reproduce. Do you have that update installed, by any chance?

**Comment by felangel** [comment]
Fwiw I also spent some time trying to reproduce the download speed issue on windows and couldn't reproduce on my machine
```
PSVersion: 5.1.22621.4249
Windows 11 Pro
Version 23H2
OS build 22631.4317
```

**Comment by JioBani** [comment]
Here is the OS environment at the time the issue occurred:


```
Edition: Windows 10 Home
Version: 22H2
OS Build: 19045.5011
Experience: Windows Feature Experience Pack 1000.19060.1000.0
```

Currently, Shorebird and several packages have been updated, so I will apply the patch again and provide the Flutter and Shorebird environment details to check if the same issue occurs.

**Comment by jakubkrapiec** [comment]
After updating Windows (with said update) and Shorebird, the problem still exists on my machine.

**Comment by bryanoltman** [comment]
@jakubkrapiec :( 

If you disable windows defender while you're experiencing the issue (see https://github.com/shorebirdtech/shorebird/issues/2532#issuecomment-2432876890), does it resolve?

**Comment by bryanoltman** [comment]
This issue seems to have disappeared? Closing for now.
