### ISSUE TITLE
feat: allow adding a name and/or comment to patches for additional context

### ISSUE THREAD

**Issue by acoutts** [shorebirdtech/shorebird#2569]
**Description**

In our workflow we deploy patches on merges to our main branch and the jobs are setup so that as long as there are no changes to native / asset files, it will kick off a shorebird patch in staged form. We prefer to manually test / activate the patches later. The problem is our console looks like this:

![Screenshot 2024-10-23 at 9 53 30 AM](https://github.com/user-attachments/assets/0077f868-fe64-4e46-9292-4645e922d88d)

We have no way to know what patches correspond to what git commits / changes so when it comes time to revert or activate it is very hard to know what you are rolling back or activating.

**Requirements**

- [ ] Add a new argument to the patch command to add a comment or name to the patch
- [ ] Display this extra context in the shorebird console
- [ ] Stretch: link github project and allow direct association to commits / PRs.

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by eseidel** [comment]
Makes total sense.

**Comment by felangel** [comment]
Seems like a duplicate of #1288

**Comment by acoutts** [comment]
Indeed that sounds pretty similar. Shall i close this then?

**Comment by bryanoltman** [comment]
Closing as a duplicate of https://github.com/shorebirdtech/shorebird/issues/1288
