### ISSUE TITLE
feat(shorebird_cli): release command should upload artifact to play store

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#257]
**Description**

We currently provide the user with a path to the built `.aab` file and a link with play store upload instructions. We should do this step for them if possible, and a provide helpful error if we try and fail (e.g., due to the developer having an improperly configured play store listing).

**Requirements**

- [x] `shorebird release` uploads the built `.aab` to the Play store.

**Comment by eseidel** [comment]
Another way to think about this is fastlane integration, which yes, we should offer.

I think as we start to wire up GitHub Actions for time_shift it's a good time to think about wiring up things like this as well.

**Comment by nosovk** [comment]
In common for more or less big IOS projects fastlane is only a one option to build reliable build track. Because of tricky process of signing etc users usually stick to fastlane just to solve onboard\offboard issues on a project.

**Comment by eseidel** [comment]
I suspect we're most likely to lead with docs.  https://github.com/shorebirdtech/docs/issues/233

**Comment by eseidel** [comment]
I don't anticipate us doing this soon, closing for now.
