### ISSUE TITLE
fix: shorebird taking build info from the wrong xcarchive for iOS release

### ISSUE THREAD

**Issue by brendansiow** [shorebirdtech/shorebird#2575]
App ID: bbbc22d3-7147-4c9e-85e9-ae138aed281d

The Shorebird CLI is pulling build information from the wrong .xcarchive file when `${PRODUCT_NAME}` is set, and different `.xcarchive` files are generated based on the build scheme in Xcode. This causes commands like `shorebird release ios --flavor staging --build-name=1.1.3 --build-number=2` to display the incorrect build name and build number when Shorebird attempts to upload the data to the Shorebird Console. The issue occurs because the Shorebird CLI uses the `production.xcarchive` build information instead of the `staging.xcarchive` build that was just built with the command.

**Steps To Reproduce**

1. Set the ${PRODUCT_NAME} in the Xcode settings for a `staging` scheme.
2. Run shorebird release with the production flavor and specify `--build-name=1.0.0 --build-number=1`.
3. Run shorebird release with the staging flavor and specify `--build-name=1.0.1 --build-number=1`.
4. Shorebird will display a confirmation of the build name and build number before proceeding with the upload to the Shorebird Console.
5. The displayed build name and build number do not match what was specified for the staging build. Instead, the production.xcarchive is used, resulting in 1.0.0+1.

**Expected Behavior**

The build name and build number should match the values specified in the arguments for the `staging` build.

**Screenshots**
The screenshots here doesn't use the versions mentioned in the steps.

1. The build was generated with the specified `build-name` and `build-number`, but the wrong release version was shown and uploaded.
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/f8f29a8f-3b28-41f7-b0e6-3469528ef9d7">
<br/><br/>
2. The `production.xcarchive` here contains the release version used by the Shorebird CLI, but this was not built using the command shown above.<br/><br/>
<img width="684" alt="image" src="https://github.com/user-attachments/assets/4c585d71-189f-4852-87c2-80e0bee8f0f6">
<br/><br/>
3. The `staging.xcarchive` here contains the correct release version. The `--verbose` flag confirms that the Flutter build command is executed correctly, but when Shorebird uploads the artifact, it uses the `production.xcarchive` version.<br/><br/>
<img width="706" alt="image" src="https://github.com/user-attachments/assets/29cd15a0-7c85-4be0-ac46-d0159d215d99">

**Additional Context**

None

**Comment by brendansiow** [comment]
could be a duplicate issue of https://github.com/shorebirdtech/shorebird/issues/2576

**Comment by bryanoltman** [comment]
Ha! You beat me to it. Closing https://github.com/shorebirdtech/shorebird/issues/2576 as the dupe.

**Comment by bryanoltman** [comment]
This should be fixed in version 1.4.6. Thanks for reporting!
