### ISSUE TITLE
feat(shorebird_cli): doctor command should have subcommands to fix issues

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#259]
**Description**

Currently, `shorebird doctor` will list issues, but doesn't always provide info about how to resolve them. In addition to providing tips about resolving issues, doctor should also expose a `fix` subcommand attempts to resolve as many detected issues as possible for the user.

As a concrete example, if any AndroidManifest.xml files are missing the INTERNET permission, `shorebird doctor fix` would add `<uses-permission android:name="android.permission.INTERNET" />` to those files.

**Requirements**

- [ ] `shorebird doctor fix` subcommand is added
- [ ] subcommand makes changes, warns user to verify those changes before committing

**Comment by eseidel** [comment]
It currently doesn't tell me how to fix:

```
✗ AndroidManifest.xml files contain INTERNET permission (98ms)
  [✗] C:\Users\micro\Documents\GitHub\win_test\android\app\src\main\AndroidManifest.xml is missing the INTERNET permission.
```

**Comment by bryanoltman** [comment]
This ended up being a flag instead of a subcommand (`shorebird doctor --fix` instead of `shorebird doctor fix`), but this is resolved by https://github.com/shorebirdtech/shorebird/pull/405
