### ISSUE TITLE
feat: Install a specific Shorebird version

### ISSUE THREAD

**Issue by alberto-sf** [shorebirdtech/shorebird#2591]
**Description**

We have a big monorepo with many sub-packages and thus we're not always on latest Flutter. For example, right now the latest Flutter version is `3.24.4` but we're on `3.24.1`.

We have noticed that the latest shorebird version (`1.4.7`) breaks our CI pipeline (it breaks while building the iOS app). We would like to try to install a previous shorebird version (`1.4.6` for example) which should work again. However, we weren't able to find a command to install a specific Shorebird version. The install script points to `stable` so we always grab the latest version.

We would like to be able to somehow specify the shorebird version when installing the tool. 

**Requirements**

- [ ] Checklist of requirements to be fulfilled

**Additional Context**

As a temporary fix, we've forked the install script and updated `install.sh` to point to the previous release rather than `stable`

**Comment by felangel** [comment]
It sounds like the real bug here is that the latest version of shorebird breaks your iOS builds. Can you provide some more context regarding what’s breaking? You can still release and patch with older Flutter versions even when using the latest version of the Shorebird CLI, you just need to make sure to pass the `--flutter-version` flag to the release command.

**Comment by opanitch** [comment]
hey @felangel - I am on @alberto-sf's team as well and can provide some additional context.

here is the log from the first error we encountered after the `1.4.7` update.  We run our CI/CD via CodeMagic, using Flutter v3.24.1, and have tried using the `--flutter-version` flag

`shorebird release ios --flutter-version=3.24.1 --flavor development -t lib/main/main_development.dart --build-number=1831 -- --export-options-plist=ios/EnterpriseExportOptions.plist --release`

<details>
<summary>Code Snippet</summary>

```sh
IO  : Writing 1155342 characters to text file /Users/builder/.pub-cache/log/pub_log.txt.
[   +9 ms] Error (Xcode): Sandbox: rsync(25138) deny(1) file-write-create /Users/builder/Library/Developer/Xcode/DerivedData/Runner-eofjgqofdizcvkgieeconrzixyec/Build/Intermediates.noindex/ArchiveIntermediates/development/BuildProductsPath/Release-development-iphoneos/XCFrameworkIntermediates/EmbraceIO/Embrace.framework/.PrivacyInfo.xcprivacy.zygEw7

[   +1 ms] Encountered error while archiving for device.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:722:7)
           <asynchronous suspension>
           #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:427:50)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
```

</details>

We already have `ENABLE_USER_SCRIPT_SANDBOXING` set to `NO`

**Comment by opanitch** [comment]
might be a related issue: https://github.com/shorebirdtech/shorebird/issues/2590

**Comment by opanitch** [comment]
after attempting to downgrade to shorebird v1.4.6, we're now getting this error: https://stackoverflow.com/questions/79137784/after-updating-xcode-flutter-run-fails-with-memory-order-relaxed-semantic-issue

not sure if it's related

**Comment by bryanoltman** [comment]
I'd be curious to know if the underlying `flutter build` command works with non-shorebird flutter. If you run the `shorebird release` command with `-v`, you should see an invocation of `flutter build ipa` using Shorebird's version of Flutter. Would you mind trying that with non-Shorebird Flutter?

**Comment by opanitch** [comment]
unrelated, created a PR to the install script to add the ability to specify Shorebird version while troubleshooting:
https://github.com/shorebirdtech/install/pull/35

am waiting for my CD run to complete

**Comment by nguyendai-reddevil** [comment]
same issue, i want to install version 0.18.4 but can't do it

**Comment by bryanoltman** [comment]
> same issue, i want to install version 0.18.4 but can't do it

I would love to hear more about why. 0.18.4 came out almost a year ago and does not still work (you can test this yourself by navigating to the shorebird checkout and running `git checkout v0.18.4`)

**Comment by bryanoltman** [comment]
@opanitch any update?

**Comment by bryanoltman** [comment]
Closing due to lack of response. If you're still having issues, please reopen or file another bug and we'll be happy to help.

**Comment by joshuadeguzman** [comment]
Hey Shorebird team.

Great work on the new release!

It seems like the latest version of Shorebird 1.5.2 also broke our build, this happened few times already whenever there's a new shorebird update and there's a Flutter SDK mismatch. Right now the error is this from our CI:

```
✓ Fetching releases (0.1s)
✓ Updating release status (0.1s)
⠋ Uploading artifacts...FileSystemException: Cannot open file, path = '/var/folders/00/9j8kyjwn2cdcdnlxlcpqr5gh0000gn/T/xwqkjG/Runner.xcarchive/Products/Applications/Runner.app/Frameworks/sqflite.framework/sqflite_darwin_privacy.bundle/Info.plist' (OS Error: Too many open files, errno = 24)

If you aren't sure why this command fail
```

Is there a way we could lock Shorebird CLI version instead back to when it was working for us? (~ 1.4.6)

We're forced to do two things to keep our CI running:
- Keep our Flutter SDK and other libraries/tools up-to-date, something we have to balance with prioritization
- Remove Shorebird just to get by a release out but lose code push capabilities

Let us know if you have any thoughts.

**Comment by eseidel** [comment]
Thanks @joshuadeguzman!  We're looking right now.

**Comment by eseidel** [comment]
We're releasing a fix for "too many files" right now. It's a but in package:archive which we will follow up with them about.

**Comment by eseidel** [comment]
Apologies for the disruption @joshuadeguzman, the bug with package:archive is filed and a release of shorebird reverting to an older package:archive is out now in 1.5.2.
