### ISSUE TITLE
fix: shorebird patch command process has some null value on installing flutter step

### ISSUE THREAD

**Issue by Hamza-Nasser** [shorebirdtech/shorebird#2597]
**Steps To Reproduce**

1. Create a shorebird Android release
2. Create a shorebird patch to that release
4. See the process of patching and notice some step with the name "Installing Flutter null (<hash>)"

**Expected Behavior**

Maybe I should see the flutter version being installed and not see the null value

**Screenshots**

![image](https://github.com/user-attachments/assets/af3c3026-8147-4dfe-842a-6a4ca1a59afa)

**Additional Context**

I have encountered this issue while releasing and patching with flavor, but I'm not sure if it can be produced if it runs without specifying 
a flavor

**Comment by bryanoltman** [comment]
This looks like Shorebird isn't recognizing your Flutter checkout as version 3.24.4. If you run `shorebird cache clear` and try again, do you still see this?

**Comment by Hamza-Nasser** [comment]
Thanks, I just upgraded shorebird, and it now recognize my Flutter version
