### ISSUE TITLE
fix: `shorebird release ios` flutter build step takes a long time

### ISSUE THREAD

**Issue by zhanglijie5997** [shorebirdtech/shorebird#2598]
➜  flutter_fpg git:(feature/Init_Project) ✗ yes | shorebird release ios --export-method ad-hoc
✓ Fetching apps (1.3s)
⠧ Building ipa with Flutter 3.24.4 (de629bcb9c)... (867.8s)

Stuck here, unable to continue execution

**Comment by bryanoltman** [comment]
Could you run the same command with the `--verbose` flag and share the result? That will give us better insight into what is taking so long.

**Comment by eseidel** [comment]
Felix also improved the output for iOS builds yesterday in Shorebird 1.4.8, so `shorebird upgrade` might improve the output.

**Comment by MohiuddinM** [comment]
I am facing the same problem, when building ios in Github actions. It gets stuck at the `Building ipa with Flutter 3.24.4 (de629bcb9c)...[Process.run] /Users/runner/.shorebird/bin/cache/flutter/de629bcb9c96360eb3ca20fcc045263c19b1a33d/bin/flutter build ipa --release`.

**Comment by MohiuddinM** [comment]
@eseidel Can the team add ability to use an older version of shorebird (as a quick fix)? The current release is completely broken for IOS releases in Github actions.

**Comment by bryanoltman** [comment]
I think it's more likely something to do with a change in flutter version than it is with shorebird, so downgrading shorebird wouldn't fix the issue. You can pass `--flutter-version=1.2.3` to the release command to pick a different version of flutter.

**Comment by MohiuddinM** [comment]
@bryanoltman It can also be helpful if you increase logging in the step it gets stuck on. I can then post the logs here so you can reproduce the issue.

**Comment by MohiuddinM** [comment]
From the current logs, it looks like it gets stuck on https://github.com/shorebirdtech/shorebird/blob/6704e56666dff10e1bc002a18838a7337245c008/packages/shorebird_cli/lib/src/shorebird_process.dart#L55

**Comment by bryanoltman** [comment]
@MohiuddinM that's the function our CLI uses to launch any kind of external process, so I think you're correct re: that being the last thing the shorebird CLI does before hanging, but also why I don't think the shorebird CLI itself is the problem, but rather something else that the shorebird CLI is interfacing with. 

Can you try running this locally with the following?

```
FLUTTER_STORAGE_BASE_URL=https://download.shorebird.dev /path/to/shorebird/bin/cache/de629bcb9c96360eb3ca20fcc045263c19b1a33d/bin/flutter build ipa --release
```

**Comment by MohiuddinM** [comment]
Can you change Process.run to Process.start (like the android ones), so the inner logs from the process will also get printed in "realtime", instead of being printed at the end of the process.

**Comment by MohiuddinM** [comment]
> @MohiuddinM that's the function our CLI uses to launch any kind of external process, so I think you're correct re: that being the last thing the shorebird CLI does before hanging, but also why I don't think the shorebird CLI itself is the problem, but rather something else that the shorebird CLI is interfacing with.
> 
> Can you try running this locally with the following?
> 
> ```
> FLUTTER_STORAGE_BASE_URL=https://download.shorebird.dev /path/to/shorebird/bin/cache/de629bcb9c96360eb3ca20fcc045263c19b1a33d/bin/flutter build ipa --release
> ```

I ran this cmd locally, and it finishes normally

**Comment by bryanoltman** [comment]
Hmm, so that suggests it might be an issue with the CI machine. Is it running the same version of macOS and Xcode as you're using locally to successfully build?

**Comment by MohiuddinM** [comment]
> Hmm, so that suggests it might be an issue with the CI machine. Is it running the same version of macOS and Xcode as you're using locally to successfully build?

I am using `macos-latest-xlarge` on Github actions. Both local machine and action runner use xcode 16

**Comment by bryanoltman** [comment]
FWIW, I locally compared stock Flutter to Shorebird's Flutter on a build that was taking a while, and, at least for me, there's no appreciable difference in performance:

Flutter:` build ipa --release  32.17s user 11.48s system 26% cpu 2:47.37 total`
Shorebird flutter: `build ipa --release  32.33s user 9.47s system 24% cpu 2:47.28 total`

**Comment by MohiuddinM** [comment]
I tested with new release and the last log message I see is: `⠹ Building app bundle with Flutter 3.24.5 (e8206cf2e7) Archiving sc... (36.7s)`

messages before that are:
```
⠋ Building app bundle with Flutter 3.24.5 (e8206cf2e7)...[Process.start] /Users/runner/.shorebird/bin/cache/flutter/e8206cf2e76e3a4e0c8e062c20bb563cae39a1f1/bin/flutter build ipa --release --verbose
⠙ Building app bundle with Flutter 3.24.5 (e8206cf2e7) Collecting s... (27.5s)
⠹ Building app bundle with Flutter 3.24.5 (e8206cf2e7) Archiving sc... (36.7s)
```

**Comment by bryanoltman** [comment]
Would you mind seeing how long `flutter build ipa --release` takes? I would be surprised if it was not comparable to that step of the Shorebird release process

**Comment by MohiuddinM** [comment]
I found the issue. It was with the action runner not configured properly. Using the steps from https://docs.github.com/en/actions/use-cases-and-examples/deploying/installing-an-apple-certificate-on-macos-runners-for-xcode-development fixed the problem.
