### ISSUE TITLE
fix: Error Occurred When Building iOS App with GitHub Actions and Shorebird

### ISSUE THREAD

**Issue by JedTsai33** [shorebirdtech/shorebird#2604]
App ID: 0d0f0c04-ad74-4b44-8296-615763f510e4

**Description**

While using GitHub Actions to package an app, I encountered an error. Here’s the command I ran:
`shorebird release ios --flutter-version=3.22.2`
Error message:
`Failed to build: Downloading Darwin x64 Dart SDK from Flutter engine 2a9f67b0f346843fbb79666dc2d23064250d82b4...`
Could you please advise on how to resolve this issue?

**Comment by bryanoltman** [comment]
Can you share the full output of the command?

**Comment by JedTsai33** [comment]
We have already found a solution to the issue.
Thank you for your assistance.

**Comment by bryanoltman** [comment]
Great! What ended up being the problem?

**Comment by bryanoltman** [comment]
Was it [this Discord thread](https://discord.com/channels/1030243211995791380/1303280760006119424)?
