### ISSUE TITLE
fix: error on ios release

### ISSUE THREAD

**Issue by StrugInc** [shorebirdtech/shorebird#2609]
**Description**

When running shorebird release ios getting a long log with error at the end.
When running shorebird release android it is building normally

**Steps To Reproduce**

Log file size is more than 35 MB, so I cannot attach.
I am leaving as Google Drive shared link. - https://drive.google.com/file/d/1H1K3ItSdyUovbEqKNnmYgPj2bczZoQDX/view?usp=sharing

**Comment by didiabel** [comment]
@StrugInc  When you archive with xcode, does it fail aswell?, 

if so maybe a `flutter clean` could work, 
or maybe pods need to be refreshed `cd ios && pod install`

hope this helps

**Comment by bryanoltman** [comment]
@StrugInc This seems like the relevant chunk of the log message:

```
                   /bin/sh -c /Users/shoh/Library/Developer/Xcode/DerivedData/Runner-dbnbstvbwjdmfkdxodkgxghqyoli/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh
               Unhandled exception:
               Null check operator used on a null value
               #0      Context.embedFlutterFrameworks (file:///Users/shoh/.shorebird/bin/cache/flutter/b42f87c03b529db7c8fd0028206f3dbdb5dc4858/packages/flutter_tools/bin/xcode_backend.dart:237:68)
               #1      Context.run (file:///Users/shoh/.shorebird/bin/cache/flutter/b42f87c03b529db7c8fd0028206f3dbdb5dc4858/packages/flutter_tools/bin/xcode_backend.dart:61:9)
               #2      main (file:///Users/shoh/.shorebird/bin/cache/flutter/b42f87c03b529db7c8fd0028206f3dbdb5dc4858/packages/flutter_tools/bin/xcode_backend.dart:17:5)
               #3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
               #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
               Command PhaseScriptExecution failed with a nonzero exit code
```

Given that the error is originating from Flutter itself, I'm curious whether a non-Shorebird Flutter build would work. Could you try running `flutter build ipa --release` and sharing the results?

**Comment by StrugInc** [comment]
Just checked `flutter build ipa --release` has some issues, need to tackle. Too long log.
I will try something out, if still does not work, then I may open a new issue maybe.
Update: I am thinking might be issue with the latest Xcode 16.2.
Thanks all
