### ISSUE TITLE
fix: same flutter-version arg producing different Flutter version error

### ISSUE THREAD

**Issue by josecleiton** [shorebirdtech/shorebird#2611]
App ID: com.wework.user_app

**Description**

Error when building to Android with `--flutter-version=3.24.4`

`shorebird release android  --flutter-version=3.24.4`

```
A release with version 2.0.10+324401598 already exists but was built using a different Flutter revision.
  Existing release built with: 3.24.4 (de629bcb9c)
  Current release built with: 3.24.4 (b42f87c03b)
```

**Steps To Reproduce**

1. Build an iOS version with 3.24.4 flutter-version argument
2. Try to do an Android build with 3.24.4 flutter-version arg

**Expected Behavior**

Generate build in both platforms with same flutter-version arg. 

**Additional Context**

On the 4th at 18:00 UTC I managed to build using 3.24.4 as an argument, the flutter commit used to build in both platforms was `de629bcb9c`.

**Comment by eseidel** [comment]
Yeah, I recall this happened once before.  You can pass the exact hash if needed. e.g.

`shorebird release android  --flutter-version=b42f87c03b`

**Comment by eseidel** [comment]
What happened is that we released a new version of Shorebird's Flutter in between when you made your iOS build and your Android build.  Since you're using the same release numbers for both iOS and Android (a common and supported thing to do) it's enforcing that they use the same exact hash of Flutter.

**Comment by josecleiton** [comment]
But this is the expected behavior? I've been using `fvm` string version to build shorebird releases

**Comment by josecleiton** [comment]
> Yeah, I recall this happened once before. You can pass the exact hash if needed. e.g.
> 
> `shorebird release android --flutter-version=b42f87c03b`

```
✓ Fetching apps (0.8s)
Version b42f87c03b not found. Please ttps://github.com/shorebirdtech/shorebird/issues/new?assignees=&labels=feature&projects=&template=feature_request.md&title=feat%3A+pen an issue to request a new version.
Use `shorebird flutter versions list` to list available versions.
If you aren't sure why this command failed, re-run with the --verbose flag to see more information.
```

**Comment by eseidel** [comment]
Try `--flutter-version=b42f87c03b529db7c8fd0028206f3dbdb5dc4858`, it's possible we don't support short hashes?

**Comment by eseidel** [comment]
> But this is the expected behavior? I've been using `fvm` string version to build shorebird releases

The error is expected, yes.  I think we could have better behavior here and avoid the error (e.g. by resolving to the correct hash so long as it has the same version number name).

**Comment by josecleiton** [comment]
I managed to make it work with flutter version as an argument, what happened was that the android build used the most up-to-date version of shorebird. While the iOS build machine, which does not use docker, was on the previous version of shorebird cli.

Thank you, @eseidel, for the fast response on this one.

**Comment by eseidel** [comment]
Thanks Jose!
