### ISSUE TITLE
iOS App rejected by apple for violating Guideline 2.5.1 - Performance - Software Requirements | Flutter 3.24.x seems to use non-public or deprecated APIs

### ISSUE THREAD

**Issue by 01vs99** [shorebirdtech/shorebird#2616]
Has Shorebird fixed this issue?  https://github.com/flutter/flutter/issues/158423

**Comment by eseidel** [comment]
It looks like Google is rushing out a fix.  As soon as Google releases a hotfix to Flutter stable, we'll roll Shorebird's Flutter within a couple hours.

The Google Flutter team typically releases on Wednesdays, but given that this is a P0 it could come any day.  Lets check back in 24 hours and see, but my guess is we'll have a new Flutter tomorrow and thus Shorebird will roll as well.

**Comment by eseidel** [comment]
https://github.com/flutter/flutter/blob/master/CHANGELOG.md is the changelog to watch.

**Comment by 01vs99** [comment]
Thank you for your reply.

**Comment by jmagman** [comment]
@eseidel 3.24.5 has the fix.

**Comment by eseidel** [comment]
Yup, we're about to release an updated Shorebird for 3.24.5. Thank you!
