### ISSUE TITLE
Using shorebird's flutter sdk caused an Android compilation error

### ISSUE THREAD

**Issue by xing5933** [shorebirdtech/shorebird#2618]
Why use the following link:
https://download.shorebird.dev/download.flutter.io/io/flutter/x86_64_debug/1.0.0-77c540fd84d436ec9d2798fff806bdcaea0ca980/x86_64_debug-1.0.0-77c540fd84d436ec9d2798fff806bdcaea0ca980.pom

The downloaded file is:
x86_64_debug-1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa.pom

The version in the pom file is: 1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa

Resulting in a compilation error: 
Could not resolve io.flutter:x86_64_debug:1.0.0-77c540fd84d436ec9d2798fff806bdcaea0ca980.
inconsistent module metadata found. Descriptor: io.flutter:x86_64_debug:1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa Errors: bad version: expected='1.0.0-77c540fd84d436ec9d2798fff806bdcaea0ca980' found ='1.0.0-db49896cf25ceabc44096d5f088d86414e05a7aa'

**Comment by bryanoltman** [comment]
It looks like you're trying to make a debug build. Shorebird only supports release builds (not debug or profile)

**Comment by bryanoltman** [comment]
If this isn't the case, can you provide more information? Where is that link coming from? How did you arrive at this issue?

**Comment by xing5933** [comment]
> It looks like you're trying to make a debug build. Shorebird only supports release builds (not debug or profile)

Thanks, I see.

**Comment by bryanoltman** [comment]
Sounds like that was the issue? Please reopen this bug if you're still experiencing this issue.
