### ISSUE TITLE
feat: Added support for the command `flutter build ios`

### ISSUE THREAD

**Issue by YiQiuYes** [shorebirdtech/shorebird#2625]
**Description**

Shorebird only implements `flutter build ipa` https://github.com/shorebirdtech/shorebird/blob/fe4cbbd8c0c7d6abaaef4dd632e351d6075b41af/packages/shorebird_cli/lib/src/artifact_builder.dart#L30

**Requirements**

- Please add `flutter build ios` command support

**Comment by bryanoltman** [comment]
You're correct that we use `flutter build ipa` for `shorebird release ios`, because shorebird is only for builds that will be distributed to end users. Could you say more about why you're asking for this feature? What is your use case?

**Comment by YiQiuYes** [comment]
I misunderstood the command, thanks for the reply
