### ISSUE TITLE
error: pathspec 'xxxxxx?' did not match any file(s) known to git

### ISSUE THREAD

**Issue by zakblacki** [shorebirdtech/shorebird#2626]
I had issue with my flutter recently. so I downloaded latest stable version 3.24.5
upon checking shorebird commands I received the following error : 

>  error: pathspec '`e8206cf2e76e3a4e0c8e062c20bb563cae39a1f1`?' did not match any file(s) known to git

Note : I'm using mac

Flutter doctor -v results log : 

```
    `[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1 24B83 darwin-arm64, locale
    en-DZ)
    • Flutter version 3.24.5 on channel stable at
      /Users/g-besoin/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (5 days ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

    [✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/g-besoin/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/g-besoin/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/g-besoin/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.13+10-LTS-268)
    • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

    [✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

    [✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

     [✓] VS Code (version 1.95.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

    [✓] Connected device (3 available)
     • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.1 24B83 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 130.0.6723.117

    [✓] Network resources
    • All expected network resources are available.

   • No issues found!
```
`

```

**Comment by bryanoltman** [comment]
Can you share the command that produced the error you're seeing? Also, what do you mean when you say you "downloaded latest stable version 3.24.5"?

**Comment by zakblacki** [comment]
> Can you share the command that produced the error you're seeing? Also, what do you mean when you say you "downloaded latest stable version 3.24.5"?

any shorebird command for example `shorebird doctor` or `shorebird upgrade` will results in the provided output.

> error: pathspec 'e8206cf2e76e3a4e0c8e062c20bb563cae39a1f1?' did not match any file(s) known to git


I was not able to update my flutter using `flutter upgrade` so I downloaded last version from [here](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.24.5-stable.zip)

then I delete previous flutter folder and replaced with this new one. 
now just in case it's related I should mention that I  have also installed recently [flock](https://getflocked.dev) which is the newest fork of flutter but I doubt it's related. 

Note : Before that  I was using shorebird v1.4.10 and flutter 3.24.2 without any issue.

**Comment by eseidel** [comment]
The ? at the end is definitely not expected.  It's trying to load: https://github.com/shorebirdtech/flutter/commits/e8206cf2e76e3a4e0c8e062c20bb563cae39a1f1

**Comment by eseidel** [comment]
That value comes from https://github.com/shorebirdtech/shorebird/blob/main/bin/internal/flutter.version, but I don't see anything wrong with the value in that file.

And it's read this way: https://github.com/shorebirdtech/shorebird/blob/fe4cbbd8c0c7d6abaaef4dd632e351d6075b41af/packages/shorebird_cli/lib/src/shorebird_env.dart#L77

**Comment by zakblacki** [comment]
> https://github.com/shorebirdtech/flutter/commits/e8206cf2e76e3a4e0c8e062c20bb563cae39a1f1

Yes I'm assuming "?" is the cause no idea how it came there 
I'm will reinstall as last resort

**Comment by eseidel** [comment]
If you run `cat ~/.shorebird/bin/internal/flutter.version` does it show the `?`?

**Comment by zakblacki** [comment]
> If you run `cat ~/.shorebird/bin/internal/flutter.version` does it show the `?`?

No well I reinstalled so for now resolved 
<img width="351" alt="image" src="https://github.com/user-attachments/assets/ca46b9a3-f16f-4606-bf07-13b536ec6ba4">

**Comment by zakblacki** [comment]
Follow up : 

[here ](https://discord.com/channels/1030243211995791380/1308005855077339197)

It seems it was results of editing git config on mac `git config --global core.autocrlf true `
