### ISSUE TITLE
feat: warn if `shorebird_code_push` version is incompatible with Flutter version

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#2628]
**Description**

`package:shorebird_code_push` version 2.0 uses APIs that were only introduced in Flutter 3.24.5. We should warn users who are trying to use this version of `shorebird_code_push` with an older version of Flutter and advise them to downgrade.

This should not be a problem in the other direction (`shorebird_code_push` < 2 and a newer version of Flutter) as the old APIs should still work.

**Comment by felangel** [comment]
You mean we should advise them to upgrade right? That shouldn’t really be an issue since we upped the package’s flutter version constraint as part of 2.0

**Comment by bryanoltman** [comment]
I was referencing the `shorebird_code_push` version, but they could upgrade their Flutter version as well. Probably providing both options would be good, as we don't know which would be the easiest for them.
