### ISSUE TITLE
fix: patches doesn't install

### ISSUE THREAD

**Issue by DETR1SE** [shorebirdtech/shorebird#2636]
App ID: 799b6c08-83f9-4116-9fb2-62acbca21ac1

**Description**

We released app in shorebird and then in app marketplaces, after that created patch and these patches doesn't apply in our app for both platforms.

auto update is enabled

shorebird version: 1.4.12
flutter version: 3.24.5

**Comment by eseidel** [comment]
The most common cause of such is sending a different binary to the stores than the one produced by Shorebird.
https://docs.shorebird.dev/troubleshooting/#the-build-uploaded-to-the-play-storeapp-store-is-not-the-build-shorebird-is-using-for-patches

If you use `shorebird preview` to view these versions do the patches correctly apply?
