### ISSUE TITLE
"Runner.app" requires a provisioning profile with the Associated Domains feature.

### ISSUE THREAD

**Issue by aswinsubhash** [shorebirdtech/shorebird#2651]
![Screenshot 2024-12-03 at 3 58 55 PM](https://github.com/user-attachments/assets/584d0c35-1a39-4188-bb8a-bbd8c43891ac)
![Screenshot 2024-12-03 at 3 59 41 PM](https://github.com/user-attachments/assets/3c90e1e8-5f38-46eb-abaa-6da457a09de2)
I am encountering this issue despite using a provisioning profile with associated domains for the Shorebird iOS release. Shorebird 1.4.13

**Comment by bryanoltman** [comment]
I updated our iOS releasing docs to address this today. Take a look at the iOS section [here](https://docs.shorebird.dev/code-push/release/), specifically the bit that talks about managing signing in Xcode or using an export options plist

**Comment by JAMES084** [comment]
Issue still facing even after following the above doc for Shorebird iOS release.
Shorebird version: 1.4.14.

Based on the doc the command didn't execute "--export-options" could not be found
![Screenshot 2024-12-06 at 12 14 40 PM](https://github.com/user-attachments/assets/9ae85e0f-43c0-4fee-a304-32f880bd88de)

When giving "--export-options-plist" it started executing but the build eventually failed.
![Screenshot 2024-12-06 at 12 23 33 PM](https://github.com/user-attachments/assets/962d8dcd-6eba-4fd5-8a37-3b228a7a1bfb)
 
Shorebird log file attached for your reference.
[1733467868977_shorebird.log](https://github.com/user-attachments/files/18034215/1733467868977_shorebird.log)

ExportOptions.plist file
![Screenshot 2024-12-06 at 12 55 18 PM](https://github.com/user-attachments/assets/0f6dc805-6900-4c45-abe6-31b7b5a27e1c)

**Comment by bryanoltman** [comment]
> Based on the doc the command didn't execute "--export-options" could not be found

Sorry about that! I just pushed a fix now, and that should be live soon

> When giving "--export-options-plist" it started executing but the build eventually failed.

This isn't a shorebird-specific thing—I expect `flutter build ipa --release` would fail for the same reason. You'll likely have a better time trying to debug using that command.

**Comment by aswinsubhash** [comment]
Since we got the solution, Im closing this issue, 
Thank you for the support
