### ISSUE TITLE
Code Magic Error - "Failed to refresh credentials"

### ISSUE THREAD

**Issue by Ikami-Mercy** [shorebirdtech/shorebird#2653]
Hi Shorebird Team,

I'm encountering an issue while using Shorebird in our Code magic pipeline. The error message reads:

⠋ Fetching apps...Failed to refresh credentials.  
Try logging out with shorebird logout and logging in again.  

Could you please help me troubleshoot or provide guidance on how to resolve this issue?

**Comment by eseidel** [comment]
Hmm.  That might suggest that the SHOREBIRD_TOKEN you're using has expired.
https://docs.shorebird.dev/ci/generic/

Our CI token system is pretty basic at the moment, so there are probably things we could do to improve there.

Let us know if creating a new SHOREBIRD_TOKEN does not fix the problem?

**Comment by Ikami-Mercy** [comment]
@eseidel T Yes that was the issue. I regenerated a new shorebird token and the issue was resolved.
Thank you.
