### ISSUE TITLE
feat: make macOS releases previewable

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#2654]
**Description**

It's not immediately clear what the best way to do this is, but macOS prevents running downloaded apps without a really annoying visit to the System Preferences security pane. To see

1. Download the app.zip from [here](https://console.cloud.google.com/storage/browser/shorebird_release_artifacts/b98ac807-cd22-40e5-87fc-bd22e5cb113c/macos/app/136688?project=code-push-prod&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22)))
2. Unzip
3. Attempt to open
4. See this
![Screenshot 2024-12-04 at 5 16 17 PM](https://github.com/user-attachments/assets/a776cc82-49de-481f-9b49-b1d7659baf70)
5. Open System Settings.app and open the Privacy & Security pane
6. Scroll to the bottom
7. Select "open anyway"

This is way more cumbersome than it should be. The proper solution might be to sign macOS apps before uploading them.

**Comment by eseidel** [comment]
Yeah, you're just building a demo of the mac experience, we'll definitely refine it over time.
