### ISSUE TITLE
package:shorebird_code_push 1.x crashes with newer Flutter versions?

### ISSUE THREAD

**Issue by sssolinjie** [shorebirdtech/shorebird#2673]
update error, app_id: de3c0af9-b1df-4a3c-9694-5400674772ce

on: Invalid argument(s): Failed to lookup symbol 'shorebird_check_for_update': undefined symbol: shorebird_check_for_update
12-10 18:18:52.594 14770 14822 E flutter : #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33)
12-10 18:18:52.594 14770 14822 E flutter : #1      UpdaterBindings._shorebird_check_for_updatePtr (package:shorebird_code_push/src/generated/updater_bindings.g.dart:2147)
12-10 18:18:52.594 14770 14822 E flutter : #2      UpdaterBindings._shorebird_check_for_update (package:shorebird_code_push/src/generated/updater_bindings.g.dart)
12-10 18:18:52.594 14770 14822 E flutter : #3      UpdaterBindings.shorebird_check_for_update (package:shorebird_code_push/src/generated/updater_bindings.g.dart)
12-10 18:18:52.594 14770 14822 E flutter : #4      Updater.checkForUpdate (package:shorebird_code_push/src/updater.dart:23)
12-10 18:18:52.594 14770 14822 E flutter : #5      _RemoteRunner._run (dart:isolate:1090)
12-10 18:18:52.594 14770 14822 E flutter : #6      _RemoteRunner._remoteExecute (dart:isolate:1084)
12-10 18:18:52.594 14770 14822 E flutter : #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
12-10 18:18:52.594 14770 14822 E flutter : #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
12-10 18:18:52.594 14770 14822 E flutter :

**Comment by eseidel** [comment]
This is presumably running package:shorebird_code_push in a build that does not include the shorebird updater.  But it shouldn't error like this, I don't think.  🤔

**Comment by gutzy** [comment]
This happened to me when I tried creating a new release after updating shorebird **without updating my shorebird_code_push dependency**. When auto_update is off and you implement your update code yourself, your app will break despite working in your dev environment because the Shorebird updater implementation has changed a lot in recent months.

**Comment by felangel** [comment]
> This happened to me when I tried creating a new release after updating shorebird **without updating my shorebird_code_push dependency**. When auto_update is off and you implement your update code yourself, your app will break despite working in your dev environment because the Shorebird updater implementation has changed a lot in recent months.

Can you provide some detailed reproduction steps? Thanks!

**Comment by zyq9613** [comment]
I had the same problem.My shorebird_code_push version is ^1.1.3, does it have to be updated to 2.0.0

**Comment by gutzy** [comment]
That's just it - my version was also ^1.1.3, updating shorebird doesn't update shorebird_code_push (don't know if it can/should) and doesn't support the old version

**Comment by eseidel** [comment]
Sounds like we somehow broke using the 1.x shorebird_code_push package with newer Flutter engine builds?

**Comment by sssolinjie** [comment]
> 听起来好像我们在使用 1.x shorebird_code_push 包与较新的 Flutter 引擎版本时出现了问题？

yes.

> 就是这样 - 我的版本也是 ^1.1.3，更新 shorebird 不会更新 shorebird_code_push（不知道是否可以/应该）并且不支持旧版本

**Comment by felangel** [comment]
Just took a closer look and it looks like we accidentally replaced the `shorebird_check_for_update` export instead of adding a new export. I'll work on a fix shortly -- sorry for the inconvenience!

**Comment by felangel** [comment]
Planning to ship the fix in the next shorebird_cli release later today

**Comment by felangel** [comment]
The release is queued up: https://github.com/shorebirdtech/shorebird/pull/2723
Needs to be smoke tested so it likely won't go out until tomorrow morning. Apologies for the inconvenience!

**Comment by felangel** [comment]
This should be fixed now in v1.5.4 of Shorebird CLI. You'll need to re-release in order to use the fixed Flutter revision.
