### ISSUE TITLE
fix: shorebird login in macos after manually install 

### ISSUE THREAD

**Issue by ghost** [shorebirdtech/shorebird#2675]
i have success install the shorebird in my local mac, however, when I try to `shorebird login`, it give me the link for the auth, but when I click or paste the link in my chrome, the link says 400 error invalid request

![image](https://github.com/user-attachments/assets/1b852b9d-cc8f-4053-9128-f61864068648)

![image](https://github.com/user-attachments/assets/3940d2b0-8da6-46f9-8d9d-c96e0b8da615)

but when I want to login with my windows laptop, it have no problem

can someone help me? I will treat you a delicious TEH TARIK from malaysia

**Comment by kuangruan** [comment]
> 我在本地 Mac 中成功安装了 Shorebird，但是，当我尝试时，它给了我身份验证的链接，但是当我在 chrome 中单击或粘贴链接时，链接显示 400 错误无效请求`shorebird login`
> 
> ![image](https://private-user-images.githubusercontent.com/88936459/394998803-1b852b9d-cc8f-4053-9128-f61864068648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODA0NzgsIm5iZiI6MTczMzk4MDE3OCwicGF0aCI6Ii84ODkzNjQ1OS8zOTQ5OTg4MDMtMWI4NTJiOWQtY2M4Zi00MDUzLTkxMjgtZjYxODY0MDY4NjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA1MDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YWY2ZmIzZmE1MzY2OWFkOTY4MGU2ZTE4ODhhNzRhYjAyMTA1NWI0YTEzZDgwZTQ1OTU3OTFhOTMzNjM5ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QcsevP8yE-1Vfbh3KQFTJVD4qnByg2HAYApVyQ4m39U)
> 
> ![image](https://private-user-images.githubusercontent.com/88936459/394998568-3940d2b0-8da6-46f9-8d9d-c96e0b8da615.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODA0NzgsIm5iZiI6MTczMzk4MDE3OCwicGF0aCI6Ii84ODkzNjQ1OS8zOTQ5OTg1NjgtMzk0MGQyYjAtOGRhNi00NmY5LThkOWQtYzk2ZTBiOGRhNjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA1MDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMzYzMDAwZmNiY2E2OTFkNTc2ZDJjZDkwMzQyMjk2MWJmZjZlYWU1MDM4OTg3YThjZWMyZjFjYWVmNDljZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8n_v7Sk9d_UxcfNyjkPWatk1nvPPVlwvyK33uUxtVAM)
> 
> 但是当我想用我的 Windows 笔记本电脑登录时，它没有问题
> 
> 有人可以帮我吗？我会给你一杯来自马来西亚的美味 TEH TARIK

Guess the link you clicked is incomplete

**Comment by bryanoltman** [comment]
I think @kuangruan is correct—the full link should be much longer. Your terminal might be concatenating (instead of wrapping) long lines?

**Comment by mahirandigital** [comment]
Already solved, i run the command in the vsCode terminal and the it give me the full link
