### ISSUE TITLE
fix: `shorebird patch` failed on iOS

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2680]
From Discord:
https://discord.com/channels/1030243211995791380/1317137871122993263/1317137871122993263

When I try to generate a patch for iOS it gives the following error:

stderr: Unhandled exception:
PathNotFoundException: Cannot copy file to '/var/folders/5f/6wny_wld3t72rwkxysxbq3900000gn/T/zLYIkw/App.class_table.json', path = '/var/folders/5f/6wny_wld3t72rwkxysxbq3900000gn/T/2B8Qo3/Products/Applications/Runner.app/Frameworks/App.framework/App.class_table.json' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.copySync (dart:io/file_impl.dart:366:5)
#2      LinkCommand._generateOptimizedPatchSnapshot (package:aot_tools/src/commands/link_command.dart:307:39)
#3      LinkCommand.run (package:aot_tools/src/commands/link_command.dart:140:40)
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#6      new Future.sync (dart:async/future.dart:313:27)
#7      CommandRunner.run (package:args/command_runner.dart:122:14)
#8      main.<anonymous closure> (file:///home/gha/.engine_checkout/engine/src/flutter/third_party/dart/pkg/aot_tools/bin/aot_tools.dart:9:57)
#9      _rootRun (dart:async/zone.dart:1399:13)
#10     _CustomZone.run (dart:async/zone.dart:1301:19)
#11     _runZoned (dart:async/zone.dart:1826:10)
#12     runZoned (dart:async/zone.dart:1763:10)
#13     LoggerOverrides.runZoned (package:aot_tools/src/logger.dart:28:18)
#14     runWithLogger (package:aot_tools/src/logger.dart:18:26)
#15     main (file:///home/gha/.engine_checkout/engine/src/flutter/third_party/dart/pkg/aot_tools/bin/aot_tools.dart:9:26)
#16     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

I'm using Flutter version 3.24.5 
app_id:  be4c7814-d407-480d-90c9-6979f7d4545a 
release: 3.4.7

**Comment by eseidel** [comment]
Release was created with    "shorebird_version": "1.4.13".

Patch claims to have been created with the same version.

https://admin.shorebird.dev/apps/be4c7814-d407-480d-90c9-6979f7d4545a/releases/140363

**Comment by felangel** [comment]
I believe this is fixed in the latest Shorebird CLI version (1.4.16).

**Comment by felangel** [comment]
Closing for now but feel free to reopen if it's still an issue in the latest Shorebird CLI
