### ISSUE TITLE
fix: Shorebird Flutter Version not upgraded to latest

### ISSUE THREAD

**Issue by aswanthdsrapha** [shorebirdtech/shorebird#2684]
App ID: (insert your app ID here)

**Description**

The Latest Flutter version is 3.27.0. But thee latest shorebird (1.4.16) uses flutter 3.24.5. 

**Steps To Reproduce**

1. Go to terminal
2. Run `shorebird doctor`
3. See warning

> The version of Flutter that Shorebird includes and the Flutter on your path are different.
>         Shorebird Flutter: 3.24.5
>         System Flutter:    3.27.0
>       This can cause unexpected behavior if you are switching between the tools and the version gap is wide. If you have any trouble, please let us know on Shorebird discord.

**Additional Context**

Please update to incorporate latest flutter version.

**Comment by bryanoltman** [comment]
Just released support for Flutter 3.27.0 with Shorebird 1.5.0

**Comment by eseidel** [comment]
Thanks for the report.  We typically try to release within a couple hours of Flutter, but we hit a hiccup with this release and it took us an extra day.  We finished Friday afternoon, but decided to hold the release until monday morning.
