### ISSUE TITLE
Erro on run or upgrade no cache directory found

### ISSUE THREAD

**Issue by JgomesAT** [shorebirdtech/shorebird#2686]
.shorebird/bin/cache/flutter/5a6dc546e8ecd01fe3b9527f082ff2d6864374f9/bin/cache/dart-sdk/bin/dart: No such file or directory

I think i lost this directory, how can I proceded

**Comment by bryanoltman** [comment]
You can probably fix this by running `shorebird cache clear` or by reinstalling shorebird
