### ISSUE TITLE
fix: I am unable to build the release for iOS

### ISSUE THREAD

**Issue by Premtejareddy11** [shorebirdtech/shorebird#2692]
App ID: (com.stanch.hrm.payroll)

**Description**

**Steps To [Reproduce**]([1734423211843_shorebird.log](https://github.com/user-attachments/files/18162958/1734423211843_shorebird.log))
running this command 
**shorebird release ios** 
will reproduce the same error

**Expected Behavior**

should have build the IPA file for the distribution but getting build failed error
but if i run through the **flutter build ipa** will generate the file or by using the xcode runner file i am able to build the IPA file

**Comment by Premtejareddy11** [comment]
[1734423211843_shorebird.log](https://github.com/user-attachments/files/18163011/1734423211843_shorebird.log)

**Comment by omar-hanafy** [comment]
Ensure your **local Flutter SDK** version matches your **Shorebird Flutter SDK**, then run:  
```bash
flutter build ipa
```  
If errors occur, it's likely not a Shorebird issue.

**Comment by Premtejareddy11** [comment]
flutter build ipa if i do this i am able to generate the IPA file

But I am unable to do that with shorebird release ios cmd

**Comment by bryanoltman** [comment]
It's not clear from the logs what the issue is, but it looks like you're using an old version of Xcode (Xcode 15.4). Could you try upgrading to 16.2 and running the command again?

**Comment by eseidel** [comment]
Apologies, we accidentally broke iOS as part of adding macOS in 1.5.1.  1.5.2 contains the fix.  Thank you for the report!
https://github.com/shorebirdtech/shorebird/releases/tag/v1.5.2
