### ISSUE TITLE
fix: Shorebird still providing patch update using version 3.24.5

### ISSUE THREAD

**Issue by aswanthdsrapha** [shorebirdtech/shorebird#2703]
App ID: (insert your app ID here)

**Description**

**Steps To Reproduce**

1. Go to flutter project via terminal
2. Run shorebird patch android
3. Got an Output

>  shorebird patch android
> ✓ Downloading patch... (0.6s)
> ✓ Extracting patch... (1.1s)
> ✓ Downloading bundletool.jar... (1.9s)
> ✓ Extracting bundletool.jar... (1.7s)
> ✓ Downloading aot-tools.dill... (0.4s)
> ✓ Extracting aot-tools.dill... (3.8s)
> ✓ Fetching apps (0.5s)
> ✓ Fetching releases (0.4s)
> Which release would you like to patch? 3.7.15+152
> ✓ Installing Flutter 3.24.5 (3faf56aafa) (16.3s)

**Expected Behavior**

The Flutter version is 3.27.1 so the patch should be done using version 3.27.5

**Screenshots**
![Screenshot 2024-12-18 at 10 58 32 AM](https://github.com/user-attachments/assets/0356d0ec-def3-4f38-8e8b-2dbf750b9a41)
![Screenshot 2024-12-18 at 10 58 39 AM](https://github.com/user-attachments/assets/fdf9d809-5e10-4a88-8ab0-4b17f2a4c007)

**Additional Context**

provided the screenshots of patcha nd shorebird doctor.

**Comment by bryanoltman** [comment]
The patch will always be made using the same Flutter version as the release. Without knowing your app id, I can't tell which that is, but I am willing to bet you made your release with Flutter 3.24.5. Closing as WAI
