### ISSUE TITLE
cannot be updated

### ISSUE THREAD

**Issue by sssolinjie** [shorebirdtech/shorebird#2731]
Previously, it could be updated, but after Shorebird was upgraded to version 1.5.4, it could no longer be updated. When checking the log, it can detect a new version, but fails to download it. Is it possible that the server has been migrated? The error message is: "error::Patch check request failed due to network error. Please check your internet connection."

```
[shorebird] Sending patch check request: PatchCheckRequest { app_id: "de3c0af9-b1df-4a3c-9694-5400674772ce", channel: "stable", release_version: "14.0+2024122601", platform: "ios", arch: "aarch64" }
[shorebird] Patch check response: PatchCheckResponse { patch_available: true, patch: Some(Patch { number: 1, hash: "6ca6c966b29190fc93bfeba029929676f2bf6f358f4c7967642b67d8b2a10cc7", download_url: "https://cdn.shorebird.cloud/api/v1/patches/de3c0af9-b1df-4a3c-9694-5400674772ce/ios/aarch64/135401/dlc.vmcode", hash_signature: None }), rolled_back_patch_numbers: Some([]) }
flutter: Patch check request failed due to network error. Please check your internet connection.
```

**Comment by sssolinjie** [comment]
I'm in China.

**Comment by sssolinjie** [comment]
It seems to be an issue with the shorebird_code_push plugin. When I use version 2.0.2, I can't download patches. And when I use version 1.1.6, it always prompts that there is an update available.

**Comment by eseidel** [comment]
We've worked to improved reachability of Shorebird's servers within China, but there is still work to do.
https://shorebird.dev/blog/improved-patch-delivery/
https://github.com/shorebirdtech/shorebird/issues/2483

My guess is that this is best tracked as https://github.com/shorebirdtech/shorebird/issues/2483?  Let me know if I've misunderstood.

**Comment by MarkZhongsh** [comment]
Facing the same error with wifi. But worked with cellular data.
