### ISSUE TITLE
fix: run "shorebuild release android --artifact apk", but log told that running "flutter build appbundle"

### ISSUE THREAD

**Issue by MarkZhongsh** [shorebirdtech/shorebird#2732]
App ID: 42c91bdd-f4e7-40ac-b273-9c4bbdd63919

**Description**

Still created aab by setting --artifact apk

**Steps To Reproduce**

1. shorebuild release android --artifact apk

**Expected Behavior**

It should download apk from shorebird server and the shorebird console should show apk, not aab.

**Additional Context**
Log below:

> shorebird release android --artifact apk --flutter-version=3.22.3 --verbose
> No checksum provided for patch, skipping file corruption validation
> No checksum provided for aot-tools.dill, skipping file corruption validation
> [HTTP] GET https://api.shorebird.dev/api/v1/apps
> ✓ Fetching apps (0.4s)
> [Process.run] git rev-parse --verify refs/remotes/origin/flutter_release/3.22.3 (in /Users/mark/.shorebird/bin/cache/flutter/77b6dc95d4e1f2de2af3c9241b874f0ede96e1ed)
> Exited with code 0
> 
> stdout:
> 393a5fc1df19ba36def7919ff64a8960c68a31ca
> 
> No checksum provided for patch, skipping file corruption validation
> No checksum provided for aot-tools.dill, skipping file corruption validation
> [Process.run] git for-each-ref --contains 393a5fc1df19ba36def7919ff64a8960c68a31ca --format %(refname:short) refs/remotes/origin/flutter_release/* (in /Users/mark/.shorebird/bin/cache/flutter/393a5fc1df19ba36def7919ff64a8960c68a31ca)
> Exited with code 0
> 
> stdout:
> origin/flutter_release/3.22.3
> 
> [Process.start] /Users/mark/.shorebird/bin/cache/flutter/393a5fc1df19ba36def7919ff64a8960c68a31ca/bin/flutter build appbundle --release --target-platform=android-arm,android-arm64,android-x64 --verbose

**Comment by eseidel** [comment]
It is true, we still run `flutter build appbundle` even when requesting an apk output.

`--artifact apk` just *additionally* produces an apk, it still produces an aab under the covers as well.

You are also correct that we only store the .aab on our servers (not the .apk).

We don't currently provide an easy mechanism to produce an .apk after the fact, although it is possible manually with bundletool:
https://developer.android.com/tools/bundletool

`shorebird preview` uses bundletool under the covers to create an .apk from the .aab for installing.

My understanding is that Google has largely moved away from .apk as a *storage* format and instead only uses it for per-device installs.

**Comment by MarkZhongsh** [comment]
yes, i found it . Thanks, I will close it .
