### ISSUE TITLE
feat: `shorebird upgrade` should print the new version number.

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#288]
e.g. moving from 0.0.4 to 0.0.5 just printed:

```
eseidel@Erics-MacBook-Pro build_engine % shorebird upgrade
✓ Checked for updates (0.5s)
✓ Updated successfully. (19ms)
```

But it should also tell me that it moved to 0.0.5.

**Comment by mateusfccp** [comment]
Considering the discussion in #447, is this not planned anymore?

**Comment by eseidel** [comment]
We always auto-upgrade now, so I'm not sure we even need this anymore.
