### ISSUE TITLE
feat: support linking discord account to shorebird

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#308]
We will need this to eliminate the last of the manual work as part of onboarding a trusted tester.  Even if we end the trusted tester program before we solve this, I still suspect we'll want to be able to identify paying customers on discord (should they choose to identify) and reward them with a Discord Role and possibly special channel access.

**Comment by eseidel** [comment]
Looks like we just need the "identify" scope:
https://discord.com/developers/docs/topics/oauth2

**Comment by eseidel** [comment]
So presumably this includes:
1. Adding the ability for our backend to store some identifier for discord like we do for google on the user table?
2. Adding a `shorebird account link-discord` or similar and implementing the discord oauth2 flow.
3. Creating a discord app (and presumably running with cloud run) and adding such to our discord server.  The app can then implement the linked-roles api: https://discord.com/developers/docs/tutorials/configuring-app-metadata-for-linked-roles
4. Connecting said app to a new role (e.g. "customers") and then trying to link our own shorebird accounts?

**Comment by ahmedmohy90** [comment]
Using Visual studio code, I got an error when I'm trying to generate an apk with this command(shorebird release android --artifact apk) and this error is "✗ Failed to build: Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
400 Bad Request trying to find package shorebird init at https://pub.dev."
could someone help me how to fix it?

**Comment by eseidel** [comment]
Closing this for now.
