### ISSUE TITLE
Please add more information about code push functionality in to readme.md

### ISSUE THREAD

**Issue by dsrenesanse** [shorebirdtech/shorebird#320]
Can you please add some short article how code push works to understand it's limitations. Will it be something like RN approach, or it is some how will override part of binary, thx.

**Comment by eseidel** [comment]
We have a bunch of docs on https://docs.shorebird.dev now, but possibly not one which directly answers your question.

**Comment by eseidel** [comment]
https://docs.shorebird.dec/architecture has some information.  If you (or others) type in more questions, happy to answer them in the docs!

**Comment by Ethan1983** [comment]
Would appreciate some clarity on versioning for end users (https://docs.shorebird.dev/code_push/patch). Can they tell the exact version from Android app settings page? This is critical for providing support to end users.

<img src="https://github.com/shorebirdtech/shorebird/assets/1020585/8fd712c2-ed0f-4007-9eda-c85727fe061c" width=250/>

**Comment by eseidel** [comment]
> Would appreciate some clarity on versioning for end users (https://docs.shorebird.dev/code_push/patch). Can they tell the exact version from Android app settings page? This is critical for providing support to end users.

Great idea.  Filed https://github.com/shorebirdtech/shorebird/issues/488
