### ISSUE TITLE
tt: expected `shorebird run -d` to work.

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#331]
There are several other common flutter pieces (like possibly `shorebird devices`?) that we should proxy through to flutter for you.  

Honestly we could probably make `shorebird` smart enough to check if Flutter commands support the underlying options and pass them through if they do, or offer to?

**Comment by eseidel** [comment]
Our output (really Flutter's output) even tells the user to use `-d`:

```
eseidel@erics-mbp test_app % ../_shorebird/shorebird/bin/shorebird --local-engine-src-path=/Users/eseidel/Documents/GitHub/engine/src --local-engine=android_release_arm64 run   
[!] The version of Flutter that Shorebird includes and the Flutter on your path are different.
        Shorebird Flutter: 3.7.10
        System Flutter:    3.7.12
This can cause unexpected behavior if you are switching between the tools and the version gap is wide. If you have any trouble, please let us know on Shorebird discord.
Running app...
More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.


macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137
```

**Comment by kaparray** [comment]
Hi guys, I am trying insert shorebird into demo project and I can't run `shorebird run`  on my machine with multiple active emulators.

<img width="996" alt="Screen Shot 2023-04-27 at 11 28 54 AM" src="https://user-images.githubusercontent.com/31259204/234807019-9b2c0642-528b-48cf-8b92-bface76efe9a.png">

**Comment by eseidel** [comment]
As a workaround, this should work until we fix this (soon):

```
shorebird run -- -d emulator-5554
```

Note the extra `--` before the `-d`, everything after `--` is passed straight to the underlying `flutter` commands (on `shorebird build`, `shorebird release`, `shorebird patch` and `shorebird run`).
