### ISSUE TITLE
feat: Support non-Google auth types

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#335]
Please comment to let us know what types of auth you need.

**Comment by jasonlau233** [comment]
wechat

**Comment by simc** [comment]
GitHub please. Can't use my company Google Workspace account because it won't let me share data with 3rd parties `Error 400: admin_policy_enforced`

**Comment by eseidel** [comment]
> GitHub please. Can't use my company Google Workspace account because it won't let me share data with 3rd parties `Error 400: admin_policy_enforced`

Makes sense.  Thanks!

**Comment by huzhiqin** [comment]
Github please. I'm waiting for your update~☺

**Comment by AmirrezaChegini** [comment]
(An unknown error occurred.) i have this error when login or create account

**Comment by eseidel** [comment]
Just got a request from a customer for Azure.

**Comment by eseidel** [comment]
We now support Azure/Microsoft login and have the infrastructure that we could (pretty easily) add more.

**Comment by eseidel** [comment]
These are now easy for us to add.  I think we can close this and handle specific requests when they come up.
