### ISSUE TITLE
fix: Shorebird flutter validation should not fail if a user does not have Flutter installed on their device

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#337]
**Description**

As a user, I should be able to use Shorebird without having Dart/Flutter installed on my machine. Currently, shorebird validators check if the shorebird flutter is the same as the system flutter but if there is no system flutter the validation check should pass instead of throwing.

**Steps To Reproduce**

1. Remove `flutter` from system path
2. Run `shorebird build appbundle`
3. See error

**Expected Behavior**

No validation error should occur

**Comment by eseidel** [comment]
I think we fixed this?
