### ISSUE TITLE
fix: `shorebird release` should derive `version` and `build_number` from appbundle

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#338]
**Description**

Currently `shorebird release` derives the version and build number from the `pubspec.yaml` which is not technically correct since the build_number and version can vary if they are passed via `commandline args or if changes are made to `build.gradle`.

**Comment by eseidel** [comment]
I looked at this briefly.  The CachedArtifact class will need a little refactoring to support artifacts like bundletool which aren't zips and don't get extracted.

**Comment by eseidel** [comment]
We will also need some logic to find java on the user's system (with which to run bundletool.jar), here is Flutter's:
https://github.com/flutter/flutter/blob/18e36dcb5de9f8ed65ce3e95278214b845671500/packages/flutter_tools/lib/src/android/android_studio.dart#L489

**Comment by eseidel** [comment]
https://stackoverflow.com/questions/60155905/how-do-i-get-the-versioncode-and-versionname-badging-of-an-android-aab-file

**Comment by eseidel** [comment]
https://github.com/google/bundletool/releases

**Comment by eseidel** [comment]
I think this was fixed in 0.2.0?

**Comment by felangel** [comment]
Yup this is fixed as part of 0.2.0
