### ISSUE TITLE
create and publish a shorebird app for e2e testing

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#34]
One suggestion was to have a clock which updates every ~hour to a new clock:
https://docs.flutter.dev/clock

**Comment by eseidel** [comment]
Store listing needs:
App Name: Time Shift
Short Description: A clock which changes over time.
Full Description: Demo app for shorebird.dev showing designs updated over time.
App icon (512x512)
Feature Graphic (1024x500)
2-8 phone screenshots (320px-3840px on side at 16:9 ratio)

**Comment by eseidel** [comment]
OK, I believe the store listing stuff is unblocked now.

**Comment by eseidel** [comment]
Over to @felangel to push a new version.

**Comment by felangel** [comment]
Uploaded and waiting for review now 🎉 🤞
