### ISSUE TITLE
feat: shorebird should detect/warn about non-dart app changes

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#385]
TTs have run into this.  Both by changing flutter_assets as well as changing java/kotlin code.

We should detect that there have been changes to the app that we do not support patching and warn users.

**Comment by bartekpacia** [comment]
Hi! :)

I think you should also warn about plugin updates. I think that there's no way to know if a new version of some Flutter plugin made changes to the native code (that can't be updated by Shortbird). Unless you do some clever diffing.
