### ISSUE TITLE
fix: Support for multiple Flavors

### ISSUE THREAD

**Issue by MaximilianFlechtner** [shorebirdtech/shorebird#389]
**Description**

I’m using [Very Good CLI](https://cli.vgv.dev/), which has the ability to add multiple flavors to the app, something that is not currently supported by Shoebird.

**Steps To Reproduce**

1. Create a new app with Very Good CLI 
2. shorebird release -- --flavor production --target lib/main_production.dart

**Expected Behavior**

Should build the app with the right flavor

**Screenshots**

<img width="2274" alt="Screenshot 2023-04-27 at 08 40 20" src="https://user-images.githubusercontent.com/66118057/234780270-f70741b9-56c4-4c6e-a428-297af56a8d50.png">

**Comment by eseidel** [comment]
Ah, this should be relatively straightforward to fix.  We just need to teach `shorebird release` where the resulting artifacts get built.  Thanks for the report!

**Comment by felangel** [comment]
Proposal:

1. Adjust the `app_id` in `shorebird.yaml` to be either a `String` or a `Map<String, String>`

```yaml
# No Flavors (default)
app_id: 6ff122d8-6d01-461b-a2bd-20dd774a5143
```

```yaml
# With Flavors
app_id:
  development: 6ff122d8-6d01-461b-a2bd-20dd774a5143
  production: 8d3155a8-a048-4820-acca-824d26c29b71
```

2. `shorebird init` to detect flavors are present and generate an app per flavor with the corresponding `shorebird.yaml` and include the flavor as part of the app's `display_name`
3. `shorebird release --flavor <FLAVOR>` to build artifacts for the specified flavor and ensure the bundled `shorebird.yaml` always has the correct `app_id` for the corresponding flavor

```
shorebird release --flavor development
```

resulting `flutter_assets/shorebird.yaml`

```
app_id: 6ff122d8-6d01-461b-a2bd-20dd774a5143
```

This way there are no changes to the backend or engine required.
