### ISSUE TITLE
fix: shorebird install fails on ubuntu on Ubuntu 22.04.1-Ubuntu (5.19.0-41-generic)

### ISSUE THREAD

**Issue by monstrum** [shorebirdtech/shorebird#395]
**Description**

Run install command on ubuntu 22.04
`curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | sh`
Failed with error
`/bin/sh: 13: Syntax error: "(" unexpected (expecting "}")`

This might be not an bug, rather than default selected shell on ubuntu. Happened on Ubuntu 22.04.

**Steps To Reproduce**

1. Execute `curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | sh`
Failed with error
2. Error: `/bin/sh: 13: Syntax error: "(" unexpected (expecting "}")`

**Expected Behavior**

If that failed, alternative install command might be useful. Using command below works for me.
`curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash`

**Screenshots**

![grafik](https://user-images.githubusercontent.com/6648831/234969137-46fb43c1-8773-4a27-a349-debaf481a864.png)

**Comment by eu-erwin** [comment]
I would love to contribute on this project, I create a PR with additional command for Ubuntu user, in case the installation is failed on them. If it is not necessary, then feel free to reject the PR.
https://github.com/shorebirdtech/docs/pull/21

**Comment by eseidel** [comment]
Apologies for the trouble.  Happy to help get this fixed this week.

**Comment by bryanoltman** [comment]
I believe this is fixed with https://github.com/shorebirdtech/docs/commit/7e81cdd4f74879d59f1006afea3eaf8628848dfd. Reopen and let us know if not!
