### ISSUE TITLE
feat: free tier

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#396]
We plan to re-work our pricing structure after we exit beta (likely to charge per-app + usage, rather than per-user)  Part of that will be adding a free tier.

One possible inspiration would be Expo's free tier: 
<img width="343" alt="image" src="https://user-images.githubusercontent.com/478541/234971309-52120ed9-6a4e-41b5-b3fd-0e05c503daa8.png">

The technical limitations for that are adding support for limiting number of updates allowed.

**Comment by SpajicM** [comment]
I think the Expo example is needlessly complicated.

> The technical limitations for that are adding support for limiting number of updates allowed.

Most people probably want a solution like this to ensure all users get the update, not just a part of them.
A simpler idea might be number of allowed patches monthly + number of users (from play store).

I'd like to use Shorebird, and support this great project. Just to toss in my usecase - my apps are much smaller (<10,000) and would need a patch or two a year, when business requirements change, so a monthly subscription isn't ideal for me.

**Comment by eseidel** [comment]
Thanks for the feedback.  I've written down some notes on other code push solution pricing in https://github.com/shorebirdtech/shorebird/issues/458.

We're in no rush to change our pricing model (currently $20 per user per month during beta), but more clarity on how we expect our pricing to evolve has come up in conversations with larger apps in the last week.

We've not added a free tier yet for simplicity, but plan to in the coming months, will update this bug when we get closer to that.  Thanks!

**Comment by itsahmed-dev** [comment]
Add a free-tier option plz.

**Comment by GeylanKalafMohe** [comment]
We need to have a free tier to try if it really fits our needs.

This should be essential as businesses will not adapt to a monthly tear if they didn't test it before with a free tier.

**Comment by eseidel** [comment]
This has launched: https://shorebird.dev/
