### ISSUE TITLE
Make it possible to access updater from Dart

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#40]
There is a bunch of work which is needed for the Rust side of the updater.

One is to make it possible to access from within a Flutter app (currently it's only called from the Flutter engine, but not then usable from Dart (what this bug is really about).

Another thing is that we need to send a bunch more information through the Rust side to the updater server.  So fixed that too, which encouraged me to refactor the Rust to take a config once at start/init time (rather than passing to each function call).

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/shorebird/tree/rust_struct is the wip branch.  (still need to recompile the engine and test it from within Dart).

**Comment by eseidel** [comment]
Only took me ~3 days 🤣 , but it appears to work with the latest "codepush" branch on flutter/engine combined with the latest from shorbird main branch!

**Comment by felangel** [comment]
> Only took me ~3 days 🤣 , but it appears to work with the latest "codepush" branch on flutter/engine combined with the latest from shorbird main branch!

🚀
