### ISSUE TITLE
Add ability to list and delete releases

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#407]
This may become less of a problem after https://github.com/shorebirdtech/shorebird/issues/368 is fixed, but right now you can get stuck if you ever put in a letter in a release name.

A TT just now had 3 releases for their app

1.0.0+1
1.0.0+2
Y

Y of course sorts later than 1, so was always the "latest" 🤦 

TT had no way to list or delete releases themselves w/o deleting the app.

**Comment by bryanoltman** [comment]
Reopening until docs are added
