### ISSUE TITLE
Would like a way to "re-init" for a known app_id

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#408]
We had a TT lose their shorebird.yaml and want to recreate it w/o also re-releasing the app.

Maybe the simpler thing is to just tell them to delete the app and re-init?  Or to edit manually?

**Comment by felangel** [comment]
I just added `shorebird init --force` which would re-init for you.

**Comment by eseidel** [comment]
I believe the use case the TT had in mind was one of "I lost my shorebird.yaml" (because I didn't commit the changes).

**Comment by eseidel** [comment]
So possibly more of a `shorebird init --id sdlkfjsdlkfjsdklfj" sort of thing. 🤷

**Comment by eseidel** [comment]
I think we can also just close this and wait for it to happen again.  @bryanoltman is in the middle of updating our docs to include things like committing the `shorebird init` changes, which will probably make this scenario uncommon.

**Comment by eseidel** [comment]
We're going to end up solving this via docs I think.
