### ISSUE TITLE
Support --verbose (-v) logging in `shorebird`

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#410]

**Comment by kishansr1** [comment]
@bryanoltman should we start using logger.detail ?

**Comment by rkishan516** [comment]
@bryanoltman should we start using logger.detail ?

**Comment by felangel** [comment]
> @bryanoltman should we start using logger.detail ?

Yes we would use logger.detail for verbose logging however I think it’d be nice to propose what additional logging to add so we can align before making any changes.

**Comment by rkishan516** [comment]
Hey @felangel ,
Currently I found only these improvement. Please let me know if these make sense ?

### Init

Found user user@gmail.com

Found flutter project with name : flutter_project_name

Deleting old shorebird yaml (Optional)

Getting flavours for app

Found flavours

1. Integration

2. Production

Registering app_name

Registered app_name successfully

Added shorebirdYaml file to project

Added shorebirdYaml fire in pubspec asset

### Doctor

Shorebird (v0.1.0 on macOS 13.3.1 22E772610a darwin-arm64)

-  Shorebird version 0.1.0 on channel stable at /Users/user/.shorebird/shorebird

- Upstream repository [https://github.com/shorebird/shorebird.git](https://github.com/shorebird/shorebird.git)

- Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400

- Engine revision c415419390

Shorebird is up-to-date

Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E772610a darwin-arm64, locale en-IN)

- Flutter version 3.7.12 on channel stable at /Users/kishan/development/flutter

- Upstream repository [https://github.com/flutter/flutter.git](https://github.com/flutter/flutter.git)

**Comment by eseidel** [comment]
We already have -v, we just need to add more logger.detail statements in places where they might be useful.  Closing.
