### ISSUE TITLE
fix: `shorebird doctor` takes over 13s to verify flutter install?

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#412]
Even on repeated runs.  I'll have to look what it's doing.

```
PS C:\Users\micro\demo\hello_shorebird> shorebird doctor

Shorebird v0.0.10
Shorebird Engine • revision c415419390e4751ddfa3110e0808e7abb3d45a18
✓ AndroidManifest.xml files contain INTERNET permission (97ms)
✓ Shorebird is up-to-date (0.7s)
✓ Flutter install is correct (13.5s)

No issues detected!
PS C:\Users\micro\demo\hello_shorebird> shorebird doctor

Shorebird v0.0.10
Shorebird Engine • revision c415419390e4751ddfa3110e0808e7abb3d45a18
✓ AndroidManifest.xml files contain INTERNET permission (0.1s)
✓ Shorebird is up-to-date (0.7s)
✓ Flutter install is correct (13.4s)

No issues detected!
```

**Comment by kishansr1** [comment]
@eseidel  It's happening because of shorebird flutter binary. If you use that binary and try checking version on that in terminal that takes approx 5-6 seconds.

**Comment by rkishan516** [comment]
@eseidel It's happening because of shorebird flutter binary. If you use that binary and try checking version on that in terminal that takes approx 5-6 seconds.

**Comment by eseidel** [comment]
We looked briefly and think this is just `flutter --version` taking a long time to run sometime (particularly after an upgrade).  We could fix this some by making `shorebird upgrade` do more https://github.com/shorebirdtech/shorebird/issues/289
