### ISSUE TITLE
`shorebird build appbundle` takes 3x as long as `flutter build appbundle --release`

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#417]
Are we running the command 3x?

From a TT:
```
I did this experiment:
shorebird patch
....
✓ Building patch (260.9s)
....

flutter build appbundle --release
...
Resolving dependencies... (23.9s)
Running Gradle task 'bundleRelease'...  84.8s
✓ Built build/app/outputs/bundle/release/app-release.aab (93.3MB).
This is on M1 Pro
```

**Comment by eseidel** [comment]
I think we decided this wasn't actually that we were doing too much work, just that we're not logging enough (when we run validation or download artifacts).

**Comment by eseidel** [comment]
I'm not sure we need to do much for this specific issue.  The overall issue is our logging is a little too sparse when things are slow (like builds or network).

**Comment by felangel** [comment]
Closing this for now since there doesn't appear to be any actionable items for this specific issue.
