### ISSUE TITLE
Add support for using local engine builds to `shorebird` tool

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#42]
This is the current bash script Felix uses to work around this:

```sh
#! /bin/sh -x

LOCAL_ENGINE_SRC_PATH=/path/to/local/flutter/engine
LOCAL_ENGINE=android_release_arm64
flutter build apk --release --no-tree-shake-icons --local-engine-src-path $LOCAL_ENGINE_SRC_PATH --local-engine=$LOCAL_ENGINE
 ```

**Comment by felangel** [comment]
@eseidel just to clarify, is the following what you had in mind?

```bash
shorebird run --local-engine-src-path=$LOCAL_ENGINE_SRC_PATH --local-engine=$LOCAL_ENGINE
shorebird build --local-engine-src-path=$LOCAL_ENGINE_SRC_PATH --local-engine=$LOCAL_ENGINE
```

**Comment by eseidel** [comment]
I don't have any specific set of commands in mind (although matching Flutter could make sense).  Mostly just trying to fulfill the user journey of "I just built my own shorebird engine, now how do I run it"?

**Comment by eseidel** [comment]
This ends up tied up in https://github.com/shorebirdtech/shorebird/issues/119.

**Comment by eseidel** [comment]
We fixed this.  --local-engine-src-path and --local-engine work with the `shorebird` tool now.
