### ISSUE TITLE
fix: can create multiple apps with the same name

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#420]
**Description**

Semi-related to https://github.com/shorebirdtech/shorebird/issues/408, it's possible to create several apps with the same name. While there's nothing technically wrong with this, I think the following is a bit confusing and probably not what anyone wants:

```
$ shorebird apps list
📱 Apps
┌────────────┬──────────────────────────────────────┬─────────┬───────┐
│ Name       │ ID                                   │ Release │ Patch │
├────────────┼──────────────────────────────────────┼─────────┼───────┤
│ time_shift │ e4caec3b-fd74-4921-8889-219a172e78d6 │ --      │ --    │
├────────────┼──────────────────────────────────────┼─────────┼───────┤
│ time_shift │ c3ece44f-dffb-4828-9dfa-06835bf9609d │ --      │ --    │
├────────────┼──────────────────────────────────────┼─────────┼───────┤
│ time_shift │ bbe03bf5-7abd-4c66-93db-b2b51ae8cfc3 │ --      │ --    │
├────────────┼──────────────────────────────────────┼─────────┼───────┤
│ time_shift │ 65486d8e-e04d-4fd9-b42b-aeefaeaa4eaf │ --      │ --    │
├────────────┼──────────────────────────────────────┼─────────┼───────┤
│ asdfasdf   │ 31faf9a6-2ff2-41cd-87cc-f12eba0e9ed8 │ --      │ --    │
├────────────┼──────────────────────────────────────┼─────────┼───────┤
│ time_shift │ 1225057b-2bc8-4df1-964e-84492fcb2d56 │ --      │ --    │
└────────────┴──────────────────────────────────────┴─────────┴───────┘
```

**Steps To Reproduce**

This can be reproduced simply by running `shorebird apps create` several times.

**Expected Behavior**

When the user tries to create an app with the same name as an existing app, some or all of the following should happen:
- A warning is shown informing the user that they already have an app with name
- We offer to [re-init](https://github.com/shorebirdtech/shorebird/issues/408) this project.

**Comment by felangel** [comment]
We talked about it on Discord but throwing my comments here for traceability:
I personally feel we shouldn't make assumptions about how users name their apps since app names don't have to be unique in the app store/play store but I do think we should surface more metadata about each app like when it was created and last modified in addition to allowing users to edit their app names.

**Comment by M97Chahboun** [comment]
@felangel
Why not based on name in pubspec file ?

**Comment by bryanoltman** [comment]
> @felangel Why not based on name in pubspec file ?

The `shorebird apps create` command reads from `pubspec.yaml` file and suggests the app name there as a default. The issue is that a user can create several apps with that name.

**Comment by eseidel** [comment]
My understanding from the above is we decided this was working as intended? (but yes, we can add more context in apps list).  Closing.  Feel free to open if I've misunderstood/misremembered.

**Comment by bryanoltman** [comment]
Yep, that's correct – this is a problem for people who are developing Shorebird, not for Shorebird users.
