### ISSUE TITLE
tt: customers expect some sort of validation message on payment (maybe an email?)

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#423]
I don't think stripe sends any emails by default.  They will send an invoice for you if you tell them to.  We could probably at least turn that on?

**Comment by maherjaafar** [comment]
@eseidel Stripe sends a receipt and an invoice automatically.

**Comment by eseidel** [comment]
Ah yes!  I think when I filed this I hadn't checked the checkbox in stripe to send invoices, but I think it does now.  Thanks!
