### ISSUE TITLE
feat: Shorebird should offer installers for Flutter

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#436]
Flutter has considered doing so before:
https://docs.google.com/document/d/1VooN2bddQ52Z2B4qYi1Lp20PGhyYDr1AKaXwo9e7PCw/edit#heading=h.pub7jnop54q0

But right now the setup process for Flutter is quite long and involved:
https://docs.flutter.dev/get-started/install

We could simply such with a per-platform installer.

**Comment by TimWhiting** [comment]
Do you mean something like this?

https://github.com/fluttertools/sidekick

I've used this for managing fvm flutter instances in the past and it works great.
