### ISSUE TITLE
`shorebird release` should check if app has network permissions (and probably other things?)

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#438]
I very strongly doubt that anyone using Flutter won't have added the internet permission to their AndroidManifest.xml file, but based on my experience writing https://github.com/shorebirdtech/docs/pull/28, this is a stumbling block that we could very easily remove.

**Comment by bryanoltman** [comment]
And possibly run `shorebird doctor --fix` for them to completely remove the potential of the user not having the internet permssion.

**Comment by eseidel** [comment]
We discussed and the plan is to hang the network check off of `shorebird release` instead.

**Comment by bryanoltman** [comment]
This has been fixed. `shorebird release` bails if no internet permission is found in the main AndroidManifest.xml file.
