### ISSUE TITLE
feat(shorebird_cli): add support for using other shorebird hosts

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#44]
**Description**

As a user, I want to be able to update the shorebird hosted url so that the shorebird cli can use other hosts (including localhost).

To specify the location of a particular shorebird server, use the `SHOREBIRD_HOSTED_URL` environment variable.

For example:

```
SHOREBIRD_HOSTED_URL = http://localhost:8080
```

**Comment by eseidel** [comment]
I suspect this should be from a config file (e.g. shorebird.yaml) in the project, rather than an environment variable.  That way it can also get built into the .apk and used on the device.

Thanks for filing this so we can have these discussions!

**Comment by felangel** [comment]
> I suspect this should be from a config file (e.g. shorebird.yaml) in the project, rather than an environment variable. That way it can also get built into the .apk and used on the device.
> 
> Thanks for filing this so we can have these discussions!

yeah good call, makes sense to introduce a shorebird.yaml

**Comment by eseidel** [comment]
This works today.  base_url? in shorebird.yaml

**Comment by eseidel** [comment]
@felangel clarifies that the publish side still does not support the base_url.

**Comment by bartcone-fulfilld** [comment]
@felangel @eseidel Being able to host a shorebird instance in a customers cloud provider (or in an on prem. containerized environment) would be very nice for large enterprise customers who want/require "all data" in house. This issue may have that in mind, but wanted to throw it out there anyway.

**Comment by eseidel** [comment]
Agree!  Will definitely be possible as part of enterprise plans.  We're focused on making the very basic Shorebird-hosted solution work first.

**Comment by eseidel** [comment]
This hasn't seemed to have been a problem in the last month.  We will definitely add an on-prem type option later, but that can be from a later bug.
