### ISSUE TITLE
Write up a pricing model

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#458]
This has come up as a request in several calls last week.

Here are some comparison points from other companies offering "code push" for react native or cordova:

Appcenter.ms
* https://learn.microsoft.com/en-us/appcenter/general/pricing (doesn't actually show dollar amounts)
* AFAICT, codepush is an included service (not billed for directly)
* They charge for concurrent builds (40$/mo per) and concurrent tests (99$/mo per)
* https://appcenter.ms/#pricing (not visible once you have an account)

Expo
* https://expo.dev/pricing
* Updates
  * First 1,000 monthly updated users included
  * Then, $5 per 1,000 monthly updated users
  * Contact us for custom pricing past 200,000 monthly updated users
  * 40 MiB of bandwidth per user included.
* Global edge bandwidth
  * First 100 GiB/mo included
  * Then, $10 per 100 GiB/mo
* Storage
  * First 20 GiB included
  * Then, $5 per 100 GiB

Ionic
* https://ionic.io/appflow/pricing
* Community - $49/mo
  * 1k updates per month
  * 1 seat
* Basic - $499/mo
  * 25k updates per month
  * 5 seats
* Scale - $999/mo
  * 25k updates per month
  * 5 seats

**Comment by eseidel** [comment]
Sentry is another interesting example: https://sentry.io/pricing/

They have org-based pricing, where orgs opt into a certain feature set/pricing tier and then charge usage based pricing for certain features beyond that.  It makes it feel straightforward to adopt at a specific tier level, but then lets those using the service pay as they go.  It's sorta a combination of Expo and Ionic models at some level.

**Comment by bryanoltman** [comment]
Research doc: https://docs.google.com/document/d/1LdL1NFK16gG_pNyQA0PWOFe4NEAOOg-CWxqdFNyj3VU/edit (non-public)

**Comment by eseidel** [comment]
This has launched: https://shorebird.dev/
