### ISSUE TITLE
Make it possible to publish `shorebird` changes to specific devs but not all (e.g. channels)

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#461]
I suspect the "easy" solution here is to just match what Flutter does and use git branches as "channels".  This would mean adding a `shorebird channel` command like `flutter channel` and making that call `git checkout $branch` as well as teaching the `shorebird --version` command to print the current "channel".

flutter_tools has a bunch of code for this I suspect we could take inspiration from.

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/shorebird/issues/181 is also related.

**Comment by eseidel** [comment]
Dupe of https://github.com/shorebirdtech/shorebird/issues/110.

**Comment by eseidel** [comment]
Actually this isn't a dupe of #110.  #110 is about staged rollouts of changes to your flutter app.  This is about staged rollout of  `shorebird` itself.

**Comment by tewarig** [comment]
hey , i think i can work on this.. can i pick this issue ?

**Comment by eseidel** [comment]
"What command do I run at the command line to know that I'm on "shorebird main", and if so how do I switch back to stable?"

```
git -C $HOME/.shorebird branch
git -C $HOME/.shorebird checkout stable
```
Is the current method. :)

**Comment by eseidel** [comment]
This hasn't turned out to be needed.
