### ISSUE TITLE
fix: shorebird works from .aab but not .apk?

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#467]
This has been reported by two customers.

"shorebird build+patch doesnt work. I send the apk via email for testing sent to my teammates"

"if i use shorebird release + patch ..its working fine.
but if i use shorebird build + patch it doest work.
the .apk file I transfer it via wire to my physical device"

**Comment by bryanoltman** [comment]
@felangel and I tried to reproduce this on an emulator but were unsuccessful. I'll give it another try when I have a physical device handy.

**Comment by felangel** [comment]
I looked into the logs from one customer and verified that it is due to #402 so closing this since we have a separate issue to track the underlying fix.
