### ISSUE TITLE
feat: Add-To-App support

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#480]
**Description**

Shorebird should support Add-To-App scenarios

**Comment by eseidel** [comment]
There are probably different levels of complexity here.
1. Just take a basic kotlin app, and add Flutter and see if Shorebird still works.
2. Take a more advanced add2app example (maybe flutter has one?) of running multiple engines for different screens.  Do we need to add tooling to support multiple engine updates from one "release", etc.

**Comment by eseidel** [comment]
We believe we have a working example, we would love to work with teams that have different add to app setups.  Please reach out!

https://docs.shorebird.dev/guides/code_push_add_to_app
