### ISSUE TITLE
feat: GitHub Action Support for Shorebird

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#484]
Shorebird should have a GitHub Action, or at least instructions on how to set up Shorebird to use from a GitHub action.

I believe @bryanoltman is looking at this for our own Time Shift app.

**Comment by daviresio** [comment]
it will be great to have shorebird integrated into the CI

**Comment by daohoangson** [comment]
> **eseidel** added this to **fluttercon** last week

Awesome!

**Comment by felangel** [comment]
Done 🎉 

Action: https://github.com/marketplace/actions/setup-shorebird
Docs: https://docs.shorebird.dev/ci/github

**Comment by mtwichel** [comment]
@felangel You'll want to take this out of the "What doesn't work" section haha https://docs.shorebird.dev/status
