### ISSUE TITLE
feat: on-prem, cloud-prem or self-hosting

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#485]
We should publish instructions on how to use Shorebird from on-prem, cloud-prem or self-hosting.

Sentry is an interesting example as they offer both self-hosting for free:
https://github.com/getsentry/self-hosted/blob/master/LICENSE

As well as on-prem:
https://sentry.io/pricing/

Expo appears to have historically offered self-hosting, but no longer does?
https://docs.expo.dev/archive/classic-updates/hosting-your-app/

See also https://github.com/shorebirdtech/shorebird/issues/458 where we're tracking towards having clearer guidance on our intended pricing post 1.0.

Update:

I've learned a bit more about this recently and there appear to be two main options:
1. "on-prem" bundle up and hand customers a VM image for them to install/manage themselves on whatever hardware/setup needed.
2. "cloud-prem" customers provide an IAM role specific to shorebird which it then uses to stand up and maintain a cluster within their cloud provider.

**Comment by kenzouno1** [comment]
waiting this feature

**Comment by liu731** [comment]
expect！

**Comment by sagar-tide** [comment]
This is really important for a fintech company. Since our security might not allow us to host binary on a third party cloud.

**Comment by emiliev** [comment]
I'm really looking forward for this to be released!

**Comment by shivamkj** [comment]
Eagerly waiting for self-hosting Shorebird Flutter code push.

**Comment by Medformatik** [comment]
The possibility to host shorebird ourselves is very important for us. Of course, Shorebird does not process any highly sensitive personal data (GDPR), but the data transfer to the USA is still problematic, which is why we are currently removing all US services from our app. Nevertheless, we would very much like to use Shorebird.

**Comment by hey-nicolasklein** [comment]
Looking out for this feature 👀

**Comment by eseidel** [comment]
https://commonpaper.com/standards/cloud-service-agreement/ was mentioned by another founder as being useful.  Also with the suggestion of hosting the "data plane" on-prem (where any customer data, binaries, etc. live), while keeping the "control plane" (UI, etc) centrally hosted for simplicity. 🤷

**Comment by eseidel** [comment]
https://www.replicated.com/ was also mentioned as a product which potentially can help with such. 🤷

**Comment by highread** [comment]
I've been really waiting for this feature, it's absolutely necessary for commercial purposes.

**Comment by mohamad72** [comment]
Waitiiiiiing so much

**Comment by MJHelloWorld** [comment]
May I ask when self-hosting will be supported?

**Comment by eseidel** [comment]
We don't have any specific date yet.  Right now we're focused on bringing iOS to feature parity with Android and supporting the large apps adopting Shorebird.  I expect this is still a couple months away.

**Comment by canewsin** [comment]
@eseidel are all the components of shorebird open sourced ?

**Comment by eseidel** [comment]
> @eseidel are all the components of shorebird open sourced ?

Most are open.  But currently our custom Dart interpreter and server source code are not.

**Comment by davidbt1** [comment]
There are no words to describe how important this feature is.

**Comment by newcolor1234** [comment]
This is very important, the sooner the better

**Comment by mohamad72** [comment]
Ok in the new version ios isuues fixed.
Now it's time to add this feature
Please 🥺🙏

**Comment by hairy-tortoise** [comment]
Any update on this?

**Comment by eseidel** [comment]
> Any update on this?

No update.  We're still entirely focused on shipping iOS.  https://github.com/shorebirdtech/shorebird/issues/674

**Comment by thanhdatvo** [comment]
Hi @eseidel 
Thank you for creating such an useful tool for developers and small companies.
I have a question: will users be charged when using self-hosting shorebird, like license fee or something?

Thank you,

**Comment by eseidel** [comment]
> Hi @eseidel Thank you for creating such an useful tool for developers and small companies. I have a question: will users be charged when using self-hosting shorebird, like license fee or something?

We don't yet have a plan for how self-hosting will work or what costs will be involved.  We've not looked at it in detail yet.

**Comment by light-speak** [comment]
Is there any new progress on this issue now, because App users cannot connect to Google Cloud normally?

**Comment by dinhtran16** [comment]
hope to see this feature soon

**Comment by theniceboy** [comment]
With the 1.0 release, will hope to see this planned

**Comment by abbos2101** [comment]
I've been really waiting for this feature, it's absolutely necessary for commercial purposes.

**Comment by Heloore** [comment]
We're also waiting for this feature! Looking forward to see it in future releases

**Comment by eseidel** [comment]
I recently wrote up a design doc about how we could implement a simple "cloud prem".  The proposal there would be that we support providing ones own S3 bucket (via any provider which supports the S3 protocol).  Shorebird would still host the UI (console.shorebird.dev) and service the patch-check requests (api.shorebird.dev) but all of the storage for your account would be controlled under your own S3 bucket which you would provide a Shorebird service account access to.

I would be interested to hear from others if such a solution would or would not solve the desire for "on prem" for their businesses.  I'd be happy to discuss in more detail if there is serious interest.

**Comment by celvinren** [comment]
> I recently wrote up a design doc about how we could implement a simple "cloud prem". The proposal there would be that we support providing ones own S3 bucket (via any provider which supports the S3 protocol). Shorebird would still host the UI (console.shorebird.dev) and service the patch-check requests (api.shorebird.dev) but all of the storage for your account would be controlled under your own S3 bucket which you would provide a Shorebird service account access to.
> 
> I would be interested to hear from others if such a solution would or would not solve the desire for "on prem" for their businesses. I'd be happy to discuss in more detail if there is serious interest.

Good to hear this, but some of the industries, like my company, we only allow to use Azure and Amazon cloud for security and privacy issue. If we want to use other services, we need to get approval and very hard. We cannot use firebase because google cloud is not allowed in our company. I think same as some industries like bank or fintech companies. 

This is the reason why we need self host. If go through console.shorebird.dev, it might be still a blocker. If we could run on docker or amazon cloud app something like that, that would be good.

**Comment by eseidel** [comment]
@celvinren If we were to offer a centrally-hosted (not-self-hosted), on Azure/Amazon instead of Google Cloud would that be sufficient? Or self-hosting everything the only allowed option in your case?

We've had lots of people ask for "self hosting" but it's not yet at all clear what a "sufficient" solution would look like in order for us to evaluate costs of implementing/maintaining such would be.

**Comment by onlyamessenger** [comment]
@eseidel What about a centrally hosted docker image that enterprise users can run on their own metal? Or would that give up too much "secret sauce"?

**Comment by Medformatik** [comment]
Not only for Enterprise customers. Regarding the GDPR, it is simply best to be able to self-host everything yourself. This may not be in line with the current trend, but I would still be very happy about this option. Also when it comes to data sovereignty and control.

**Comment by eseidel** [comment]
Oh, we don't have any secret sauce in our infra 🤣  It's mostly a cost-to-implement/maintenance concern of having to worry about *both* centrally hosted infra, as well as supporting customers running (possibly older) copies.

**Comment by lwj1994** [comment]
> I recently wrote up a design doc about how we could implement a simple "cloud prem".  The proposal there would be that we support providing ones own S3 bucket (via any provider which supports the S3 protocol).  Shorebird would still host the UI (console.shorebird.dev) and service the patch-check requests (api.shorebird.dev) but all of the storage for your account would be controlled under your own S3 bucket which you would provide a Shorebird service account access to.
> 
> I would be interested to hear from others if such a solution would or would not solve the desire for "on prem" for their businesses.  I'd be happy to discuss in more detail if there is serious interest.

Good idea，i need it

**Comment by eseidel** [comment]
I've had extensive discussions with the team, and while we recognize a desire for some form of self-hosting, we do not have any plans to add such in the near future.

Two main concerns:
1. Affording the complexity. Supporting additional configurations (potentially lagging ones) for copies of our infrastructure is more than we're able to afford at this time.
2. We're focused on wide adoption.  Right now I've asked the team to focus on issues which apply to thousands of customers over ones which apply to only a few.  So far self-hosting requests have been (and I expect to continue to be) a minority of our customer requests.

When I've asked around to other founders about when they implemented self-hosting, most have not or some who have, have regretted the choice (the contracts are nice money, but the complexity is high).  The consensus of my (limited) survey was it was best to stick with a centrally hosted solution for a long time (certainly when as small as we are).  I don't know if that's good advice, but it was the advice I was able to find.

I recognize that my response here is unlikely to be what folks were hoping to hear.  I expect we will re-visit self-hosting in the future, but that future is likely at least many months from now.  As such, I plan to update our documentation (including this bug) to make clear that we have no plans to support self hosting at this time.

Thank you all for your understanding and continued support and patience while we build out Shorebird.
