### ISSUE TITLE
feat: Dart bindings for the shorebird updater library

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#487]
We have some, but I suspect they need a little updating:
https://github.com/shorebirdtech/updater/tree/main/dart_bindings

The thing which is holding this back is that I don't know how to distribute the updater dart bindings with the shorebird sdk. Ideally they should be version locked (like package:flutter or package:flutter_test are).

We could hack the flutter sdk to teach it about package:updater, but if we did that then users builds would break when they build w/o shorebird's flutter.

We could publish to pub, but then users would have to very carefully make sure to track the dependency version of the shorebird updater package in lockstep with their shorebird version (or the shorebird tool would have to).

**Comment by eseidel** [comment]
This blocks several issues.

One hack we could consider is that we use pub to distribute in the short term and teach the `shorebird` tool to ensure that you're depending on exactly the right version of this `shorebird_updater` package from pub.  It would be hacky, but could get us past this blocker.

We would also then need to write the package in such a way that it did nothing when it detected you weren't running in shorebird and just logged and all the methods just returned immediately?

**Comment by bryanoltman** [comment]
I think this is what you're saying with "We could publish to pub, but then users would have to very carefully make sure to track the dependency version of the shorebird updater package in lockstep with their shorebird version (or the shorebird tool would have to)", but this seems like a thing we could enforce via the CLI, similar to what we do with the android INTERNET permission.

**Comment by eseidel** [comment]
Yup, I think we just enforce this in the CLI as the simple thing for now.  This is probably about a day of work to set up, the C/Rust side should be "done" already.

**Comment by MazEbeid** [comment]
This would be pretty handy to have and i think it woul also eliminate some of the dev confusion around when to expect the updates to take affect as I think now they only take place after a couple of relaunches or I am bot sure when 😁
