### ISSUE TITLE
feat: Some way to do progressive (percentage based?) rollouts

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#497]
In addition to channels (releasing to specific groups of users), https://github.com/shorebirdtech/shorebird/issues/110 some devs may also want to be able to release incrementally over time to large groups of users, e.g. percentage based rollouts.

https://github.com/shorebirdtech/shorebird/issues/181 is also related.

**Comment by FirdousNath** [comment]
This is must have feature for us and I believe everyone will need it at some point of time. Also we want control the rollout to x% users based on some criteria (locality, gender etc)

**Comment by eseidel** [comment]
> This is must have feature for us and I believe everyone will need it at some point of time. Also we want control the rollout to x% users based on some criteria (locality, gender etc)

@FirdousNath do you have any preferences for how this is implemented?  Do you have a specific rollout strategy you'd like to implement or rollout tools you'd like Shorebird to work well with?

**Comment by FirdousNath** [comment]
As of now we use google play rollout manager to manage the release. We do it manually whenever we need to increase the rollout. On iOS we use phased rollout.

**Comment by eseidel** [comment]
We got a request this morning to do geographic-based rollouts, which I suspect may be possible with a similar mechanism.  We've considered creating a "group id" that could be set from package:shorebird_code_push and could thus be used to opt a certain subset of users into a specific patch.

**Comment by eseidel** [comment]
We've gotten several requests for this in the last few weeks.  We're finally done with the bulk of our iOS work (which has consumed the entire team for most of the last year) and are starting to have bandwidth to take on wider polish issues like this one.  We have a few others (like https://github.com/shorebirdtech/shorebird/issues/112) queued up before this one, but I expect we'll get to this soon.  Thank you again for your patience.

**Comment by eseidel** [comment]
We're in the progress of planning implementation for this.  If you're interested in using this, we'd love to chat with you.  https://discord.gg/shorebird reaches us directly. Feedback is also welcome on this bug.  We're also happy to jump on a call with you.

**Comment by eseidel** [comment]
We're beginning this work now.

**Comment by eseidel** [comment]
This exists in package:shorebird_code_push 2.x
https://shorebird.dev/blog/tracks-percentage-rollouts-a-b-testing/
