### ISSUE TITLE
fix: builds with multi dimension flavors are failing

### ISSUE THREAD

**Issue by nilsreichardt** [shorebirdtech/shorebird#515]
**Description**

I'm unable to build a Shorebird release with multiple dimensions flavor:

```
Nils-MBP-13-M1-4:shorebird_flavor nils$ shorebird release --flavor prodAlpha
✗ Failed to build: Gradle build failed to produce an .aab file. It's likely that this file was generated under /Users/nils/Projects/shorebird_flavor/build, but the tool couldn't find it.
 (31.0s)
```

**Steps To Reproduce**

1. Create a new Flutter project
2. Add the `android.permission.INTERNET` to `AndroidManifest.xml`
3. Add two-dimensional flavors:
   ```
   productFlavors {
        dev {
            dimension "env"
            resValue "string", "app_name", "dev Shorbird Flavor"
            applicationIdSuffix ".dev"
            versionNameSuffix "-dev"
        }
        prod {
            dimension "env"
            resValue "string", "app_name", "Shorbird Flavor"
        }
        alpha {
            dimension "track"
        }
        stable {
            dimension "track"
        }
    }
   ```
4. Run `shorebird init`
5. Run `shorebird release --flavor prodAlpha`
6. See error

Here is the demo repository: https://github.com/nilsreichardt/shorebird_flavor

**Expected Behavior**

A build without issues.

**Screenshots**

No screenshots.

**Additional Context**

The issue is because when using multi dimensions flavors the `.aab` is stored at:
```
build/app/outputs/bundle/prodAlphaRelease/app-prod-alpha-release.aab
```

But Shorebird searches at:
```
build/app/outputs/bundle/prodAlphaRelease/app-prodAlpha-release.aab
```

Same applies for `.apk` files.

`shorebird doctor`:
```
Shorebird v0.2.1
Shorebird Engine • revision b7ddfb07396cd786a85709cdfdacfd737559bdb2
✓ AndroidManifest.xml files contain INTERNET permission (31ms)
✓ Shorebird is up-to-date (0.4s)
✓ Flutter install is correct (5.0s)

No issues detected!
```

**Comment by felangel** [comment]
Interestingly enough this seems to also be a bug with the flutter_tool:

```
flutter build appbundle --flavor prodAlpha
```

Results in:

```
Running Gradle task 'bundleProdAlphaRelease'...         4.4s
Gradle build failed to produce an .aab file. It's likely that this file was generated under /Users/felix/Desktop/my_app/build, but the tool couldn't find
it.
```
Relevant Issues:
- https://github.com/flutter/flutter/issues/92316
- https://github.com/flutter/flutter/issues/65264

Opened https://github.com/flutter/flutter/pull/127133 with a proposed fix

**Comment by eseidel** [comment]
We believe we fixed this and are just waiting on Flutter to ship?

**Comment by AbhijithKonnayil** [comment]
is this issue fixed ? @eseidel 
tried with flavor `prodGlobal`
appbundle shorebird looking for : app-prodGlobal-release.aab
appbundle created : app-prod-global-release.aab
<img width="1204" alt="Screenshot 2024-03-27 at 5 02 03 PM" src="https://github.com/shorebirdtech/shorebird/assets/25204682/1b9b33ef-13b9-40e6-a977-02a7315b9008">
