### ISSUE TITLE
fix: releases whose artifacts fail to upload are not deleted or marked as bad/incomplete

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#560]
**Description**

When running `shorebird release`, artifact creation/upload can fail for several different reasons (connectivity issues, etc.). Because of the order in which release operations occur, an artifact upload error will result in a release that is listed by `shorebird releases list` with no indication that it has an incomplete set of artifacts.

**Expected Behavior**

Releases whose artifacts failed to upload are deleted or somehow placed in an incomplete state (the former is probably more straightforward to implement).

**Comment by sladyn98** [comment]
```dart
} catch (error) {
    // Attempt to delete the artifact file before failing.
    try {
      if (await artifact.exists()) {
        await artifact.delete();
      }
    } catch (deleteError) {
      logger.error('Error deleting ${artifact.path}: $deleteError');
    }
    createArtifactProgress.fail('Error uploading ${artifact.path}: $error');
    return ExitCode.software.code;
  }
  ```
  
  Would we want to do this for all of the releases like release_android, release_arr

**Comment by eseidel** [comment]
This should be done.
