### ISSUE TITLE
feat: basic `shorebird release ios` and `shorebird patch ios`

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#580]
In order to have a working ios demo, I need the server/cli parts of `shorebird` to know what iOS is.

You can see my hacks at this:
https://github.com/shorebirdtech/shorebird/tree/ios_hacks

Specifically i would like to be able to run a `shorebird release ios` and have it create the necessary server entries.  It could upload the ipa parts, but that's not required.

I need `shorebird patch ios` to be able to create an artifact on the server that is *not* a patch (e.g. skip the patch creation logic on the client, the server can think it's a patch, that's fine, I can teach the rust to ignore that for iOS for now).

To create the file for the artifact we will use:
`/Users/eseidel/Documents/GitHub/ios_engine/src/out/ios_release_unopt_arm64/clang_x64/gen_snapshot_arm64 --deterministic --snapshot-kind=app-aot-elf --elf=out.aot .dart_tool/flutter_build/4d4af174f68149fadd13bb2aa91c5a1c/app.dill`
(which I can just hard code into my local `shorebird` for the demo).

The app.dill path is the most recently modified app.dill in the `.dart_tool` directory (I'm sure there is a better way to find it, but that will work for now).  The `gen_snapshot` path would get resolved from the --local-engine path, but again, it's not worth wiring up for real, just getting something basic checked in and then I can hack it locally to work for my demo.

Other issues I hit when trying this locally, were that the code doesn't really know that iOS exists and has global assumptions like "architectures" assuming android, and validators assuming android.  Some of that could certainly get cleaned up by someone hacking on that part. see https://github.com/shorebirdtech/shorebird/tree/ios_hacks for where I hacked things.

Another piece is probably reading out the version information from the Info.plist, which should be straighforward with the `defaults` command line tool build into mac which I believe is a generic plist reader/editor despite the name.

Once these basic commands are in place, I can finish the rust side of the work which should mean we have a working demo!

**Comment by eseidel** [comment]
The reason why we're calling gen_snapshot ourselves is to produce the elf binary which we're using as a bundle format for the compiled dart code.  On iOS gen_snapshot is called with --snapshot-kind=aot-assembly to create an assembly file instead to hand off to the xcode build system for creation of an App.framework.  We don't need to create a framework (or even involve XCode) to compile the patch from dart code.  We might do that later (diff between App.frameworks), but since Dart already has a parser for ELF, we're just using that as a bundling format for this demo.

**Comment by eseidel** [comment]
The reason why things need to be bundled is just that gen_snapshot actually makes 4 separate things.  For various reasons, these are distributed via an elf binary on Android and compiled into a mach-o binary (as part of a framework) on iOS.  But they also work as 4 separate files just fine.  But if I made them 4 separate files, I would then need to zip them (which I could do), but this seemed simple and convenient and so was how I build my demo.  Another way for me to build a (possibly next) demo would be to write a simple mach-o parser, and then just ship the newly compiled App.framework as the patch (similar to what we do on Android with libapp.so as our bundle format), that just seemed like more work and more confusion (because again, we're not actually producing "code" which needs to be signed, etc. we're just using these framework and libapp.so files as convenient ways of bundling architecture-specific resources).

**Comment by bryanoltman** [comment]
Closed with 4acf18667e3a51202cbfad060aba8d869d166bd6
