### ISSUE TITLE
Write up initial survey and trusted tester email

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#59]
Here's a draft email and survey:

Announcing: Shorebird Trusted Tester Program

Hi all.

We’re nearly ready to begin offering API keys to "trusted testers" interested in working closely with us to bring Shorebird code push to production. While we are ready for a few testers, the product is still very early and code push is not ready for production usage or wide app distribution yet.

If you're interested in participating, read on.  Otherwise, expect our next status update and video early next week!

What you get
We’ll provide you access to Shorebird code push (an API key/login), trusted tester support (private discord, email) and of course fix bugs as you hit them.  We're there to help you ship!  We’ll also share our roadmap and incorporate your feedback as to what we should build in what order.  We’ll be releasing updates regularly (hours, days) as we improve the product.

What we’re asking
We’re looking for testers who have serious interest, but are willing to try on small projects to start.  Our #1 design goal up until now is “first, do no harm”, so we don’t expect code push to break your app, but we just don’t have enough experience in the wild to feel certain about that yet.  We will also expect testers to engage with us regularly via Discord or Github with feedback and suggestions.  We are charging $20 per month for participation in this program.

Technical Requirements
At this time, the tester program requires a Mac host and only supports Android Arm64 devices.  We expect to quickly add other platforms and hosts, but on day 1 we will require our first set of testers to have access to both Mac and Android Arm64.  It also works in an Arm64 emulator, but we're most interested in testers will to ship to a small number (fewer than 1000) of devices.

Even if you’re unable to join us now, this is far from the last chance to try Shorebird or work with our team!  We’ll send more invites soon after we’ve gotten more of the core product built.  We hope by the end of this program to graduate code push to generally available production.

If you’re interested, please fill out the survey, and we’ll start reaching out to participants in the next few days, thanks!
https://forms.gle/xyNMHqHnDYF4HBPPA

Eric

Survey

Thank you for taking our survey.  Filling out the survey does *not* guarantee access to the trusted tester program.  Upon completion, we will reach out to some of you with a stripe payment link from “Code Town, Inc.”  Upon completion of payment, we will issue an API key and add you to our trusted tester room on Discord.

Responses will be recorded in Google sheets.  The sheet results will be deleted within 90 days (we have no interest in retaining your data), as we bring accounts online, data entered there will be retained as part of your usage of the services, per our privacy policy: shorebird.dev/privacy.html

What email address should we contact you with?

What Discord ID should we add to our trusted-tester room?

What platforms do you have regular access to?
(Note: Access to Mac and Android are required for the first round of trusted testers.)
Mac
Android
Windows
Linux
iOS
Other

Via which of these methods are you able to regularly (weekly) engage with us?
Discord
GitHub
Email
Other

Where is the app you intend to test with published?
Private distribution
Play Store
Amazon Store
Other

How many active users does your intended test app(s) have?
(Note: the first round of trusted testers should only publish to < 1000 users.)
< 100
100 - 1k
1k - 10k
10k - 100k
100k +

If provided an API key today, about when would you be able to try it?
Hours, Days, Weeks

Option: I would have loved to do this, but I don't have X?

**Comment by eseidel** [comment]
See also #61

**Comment by santoshgistto** [comment]
@eseidel  i am interested to be part of testing process. 
Let me to know how do i need to send the email after completion of survey ?

Thank you .

**Comment by eseidel** [comment]
Yup.  I will be sending out the survey to the mailing list likely this Friday (2 days from now).  Mailing list signup is posted on shorebird.dev  Thanks!

**Comment by santoshgistto** [comment]
Thank you

**Comment by eseidel** [comment]
Discord announcement and Email sent!
