### ISSUE TITLE
feat: support ios without a local engine

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#639]
Things I believe are remaining:

- upload.sh needs to bundle up and send both gen_snapshot and Flutter.xcframework.  These should be in /out/release from the build.sh script having run Flutter's create_unified_framework.py script.
- upload.sh will need to generate an updated proxy config
- artifact proxy may need to be modifed to serve the right artifacts?
- We will need to modify the proxy config and upload.sh to upload gen_snapshot for Android as well.
- We will need to build gen_snapshot from linux, windows, mac for both iOS and Android.  Since we're changing the dart version we will need to change the per-device/host pair gen_snapshot.  These are generated in the *device* build directories on a per-host basis.

It's possible the android gen_snapshot isn't needed because we modified our dart to disable snapshot version validation?
https://github.com/shorebirdtech/_shorebird/issues/1731

That should be it?  Once that's done `shorebird` should work without --local-engine.

**Comment by eseidel** [comment]
How flutter does the bundle and upload: https://github.com/flutter/engine/blob/main/ci/builders/mac_ios_engine.json#L73 https://github.com/flutter/engine/commit/1d7f0c66c316a37105601b13136f890f6595aebc

**Comment by eseidel** [comment]
https://gist.github.com/felangel/8e1ff2728211c87d92127cb73233a23e

**Comment by eseidel** [comment]
out/release/artifacts.zip goes to /.../ios-release/artifacts.zip in the artifact proxy

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/shorebird/blob/main/packages/artifact_proxy/tool/generate_manifest.sh

**Comment by felangel** [comment]
> https://github.com/shorebirdtech/shorebird/blob/main/packages/artifact_proxy/tool/generate_manifest.sh

PR: https://github.com/shorebirdtech/shorebird/pull/644

**Comment by bryanoltman** [comment]
This works as of https://github.com/shorebirdtech/shorebird/pull/649 now that we've got the artifacts sorted out. Closing.
