### ISSUE TITLE
feat: want to be able to see how many patches have been delivered this billing cycle

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#645]
This will let us consider usage based billing.

**Comment by bryanoltman** [comment]
Starting by finding a way to analyze our cloud storage logs

**Comment by bryanoltman** [comment]
![Screenshot 2023-06-14 at 10 47 42 AM](https://github.com/shorebirdtech/shorebird/assets/581764/3175fcc9-dc87-4fbc-9273-fa66858596bf)

(from https://cloud.google.com/storage/docs/access-logs)

😅

**Comment by eseidel** [comment]
In order to unlock usage based billing, we need:
- Be able to see the number of patches sent to your users on your behalf by shorebird in the last billing cycle.
- Need to be able to query this number from the command line (and see how many more until you hit your limit).
