### ISSUE TITLE
feat: upload release artifacts for iOS

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#677]
**Description**

We don't currently upload the release .ipa when running `shorebird release ios`. This is fine, because we don't currently do any diffing for iOS patches. However, to determine whether `shorebird release` has been run for a given platform + version, we check for release artifacts. This means `shorebird release ios` will always succeed no matter how many times it is run, and whether or not there are already patches available for a given release.

We could check for patch artifacts, but for consistency with other platforms, it would probably make more sense to upload the ipa built by `shorebird release ios`

**Comment by eseidel** [comment]
It will also let us warn when customers make non-dart changes, like we do on Android.
