### ISSUE TITLE
feat: warn for non-dart changes on iOS

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#679]
`shorebird patch android` will warn if it detects changes to the binary that we can't patch (e.g. changed Kotlin or Java code).

This bug tracks adding the same feature on iOS.

This will require https://github.com/shorebirdtech/shorebird/issues/677

**Comment by omar6533** [comment]
IOS patch will give warn if native changes are in patch you can remove this issue from the documentation page

**Comment by eseidel** [comment]
I believe @bryanoltman did fix this, yes thanks.
