### ISSUE TITLE
feat: expose --dart-define directly

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#684]
**Description**

Expose the dart define option in Shorebird CLI directly since it’s commonly used.

**Comment by ahmdaeyz** [comment]
Hello @felangel, 

Do you happen to have an ETA for this? We have configs in the app depending on env variables passed with --dart-define. We obv. can use defaults but we wanted to know when will this be available. 

Thanks!

**Comment by felangel** [comment]
> Hello @felangel,
> 
> Do you happen to have an ETA for this? We have configs in the app depending on env variables passed with --dart-define. We obv. can use defaults but we wanted to know when will this be available.
> 
> Thanks!

Hey 👋 

You can use dart-defines as is but you’ll need to pass them along after `--` like:

`shorebird run -- --dart-define…`

We can probably include 1st party support as part of this week’s release 👍
