### ISSUE TITLE
fix: Missing x-version header

### ISSUE THREAD

**Issue by esarbanis** [shorebirdtech/shorebird#685]
**Description**

I run `shorebird account create` and got:
```
The current version is not supported. Please upgrade to the latest version and try again.
Missing x-version header.
```

Did a `shorebird upgrade` and got:
```
✓ Checked for updates (1.7s)
Shorebird is already at the latest version.
```

**Steps To Reproduce**

1. run `shorebird account create`
2. Authenticate with your Google account through the provided link
3. See the following error:
```
The current version is not supported. Please upgrade to the latest version and try again.
Missing x-version header.
```

**Expected Behavior**
The account should have been created

**Additional Context**
`shorebird doctor`
```
Shorebird v0.1.0
Shorebird Engine • revision c415419390e4751ddfa3110e0808e7abb3d45a18
✓ AndroidManifest.xml files contain INTERNET permission (39ms)
✓ Shorebird is up-to-date (1.7s)
✓ Flutter install is correct (5.6s)
```

`flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on Ubuntu 23.04 6.2.0-20-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

`uname -a`
```
Linux efthymis-desktop 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by esarbanis** [comment]
IDK if I need to close this, apparently the problem was not `shorebird account create` but `shorebird upgrade`. The former had the right error, but the later didn't actually update the cli, so I was still running v0.1.0

**Comment by eseidel** [comment]
Oops.  We rolled out the X-Version header this week and clearly didn't test all the flows.  Thank you for the report.  I expect we'll have it fixed on Monday.

**Comment by felangel** [comment]
> IDK if I need to close this, apparently the problem was not `shorebird account create` but `shorebird upgrade`. The former had the right error, but the later didn't actually update the cli, so I was still running v0.1.0

Yeah I suspect there was a bug with Shorebird upgrade in v0.1.0. You should be able to either manually sync with the latest stable branch or reinstall the cli to resolve the issue.

**Comment by esarbanis** [comment]
@felangel I did manually upgrade and the error went away, feel free to close this if you feel there is nothing you can do about it
