### ISSUE TITLE
feat: Organization access

### ISSUE THREAD

**Issue by ahmdaeyz** [shorebirdtech/shorebird#687]
**Description**

Currently, the only way to use the CLI is to authenticate with a single Google account and use it everytime you log on a new machine. This makes it hard for teams with several members. So having organization access would be a nice feature.

**Comment by felangel** [comment]
Hi @ahmdaeyz 👋
Thanks for opening an issue!

Have you tried managing collaborators via `shorebird collaborators add`? You can add collaborators via email to one or more apps. Let us know if that helps 👍
