### ISSUE TITLE
fix: Could not create `ReleaseArtifact`

### ISSUE THREAD

**Issue by johnnypramadya** [shorebirdtech/shorebird#688]
johnnypramadya@192 codepush % shorebird releases list
🚀 Releases (b3bb6ecf-6aad-4897-beb2-4616cc03dcd7)
┌─────────┬──────┐
│ Version │ Name │
├─────────┼──────┤
│ 1.0.0+1 │ --   │
├─────────┼──────┤
│ 1.0.1+2 │ --   │
└─────────┴──────┘
johnnypramadya@192 codepush % shorebird patch android
✓ Building patch (2.7s)
✓ Fetching apps (0.6s)
✓ Detected release version 1.0.1+2 (0.2s)
✓ Fetching release (0.4s)
✓ Fetching Flutter revision (20ms)
✗ CheckedFromJsonException
Could not create `ReleaseArtifact`.
There is a problem with "id".
type 'Null' is not a subtype of type 'int' in type cast (0.5s)

**Comment by felangel** [comment]
Hi @johnnypramadya 👋
Can you provide the version of shorebird that you used? (`shorebird --version`)

If you’re on an older version you will need to upgrade via `shorebird upgrade` to resolve the issue. Sorry for any inconvenience!

**Comment by johnnypramadya** [comment]
Shorebird 0.4.5
Shorebird Engine • revision 016c3010948dcfe5b57838741374bc1c54fecf89

**Comment by felangel** [comment]
> Shorebird 0.4.5
> Shorebird Engine • revision 016c3010948dcfe5b57838741374bc1c54fecf89

You’ll need to upgrade to 0.5.0 (`shorebird upgrade`). Apologies for the inconvenience and let me know if that helps 👍

**Comment by johnnypramadya** [comment]
shorebird patch android successfully after I do shorebird upgrade
Thanks! @felangel
