### ISSUE TITLE
fix(shorebird_cli): `patch` commands report missing assets due to tree-shaking

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#691]
**Description**

Changes in icon font usage can result in different font files being included in the app bundle. These can trigger the asset change warning when running the patch command.

**Steps To Reproduce**

1. Create the default counter app
2. Make a release
3. Delete the floating action button
4. Attempt to patch
5. Notice the warning caused by the file diff in `base/assets/flutter_assets/fonts/MaterialIcons-Regular.otf`
 
**Expected Behavior**

Patch succeeds.

**Comment by eseidel** [comment]
This is correct behavior, no?  If the assets differ we need to include the asset or the app will break in production?

In this case, the app + patch will end up not using the correct font for the added text.

I think the correct solution here is https://github.com/shorebirdtech/shorebird/issues/318?

**Comment by bryanoltman** [comment]
> This is correct behavior, no? If the assets differ we need to include the asset or the app will break in production?

If an asset was _added_, yes. In the steps I took, an asset was removed, and there would be no problem patching.

**Comment by bryanoltman** [comment]
But I do think you're correct that #318 is the correct solution

**Comment by eseidel** [comment]
OK.  We may actually have specific trouble with removals, btw and may need to notice removals and cause special behavior, or somehow disambiguate them on the client side from omission-from-asset-diff-due-to-equality.

**Comment by eseidel** [comment]
We're just going to do https://github.com/shorebirdtech/shorebird/issues/318.
