### ISSUE TITLE
fix: unable to patch using ubuntu-latest GitHub Runner

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#698]
**Description**

As a developer, I would expect to be able to run `shorebird release android` on my local machine:

```
Description:    Ubuntu 22.04.2 LTS
Release:    22.04
```

And be able to use shorebird in my GitHub actions workflow with `runs-on: ubuntu-latest` to create patches.

Actual:

See error that says the Android App Bundle appears to contain Kotlin or Java changes which cannot be applied via a patch.

**Comment by 0x4ym4n** [comment]
@felangel 
I tried:
    runs-on: ubuntu-22.04
and the issue remains the same.

`Current runner version: '2.305.0' Operating System Ubuntu 22.04.2 LTS Runner Image Image: ubuntu-22.04 Version: 20230611.1`

**Comment by eseidel** [comment]
We believe we've fixed this.
