### ISSUE TITLE
fix: & was unexpected at this time.

### ISSUE THREAD

**Issue by 0x456d7265** [shorebirdtech/shorebird#732]
**Description**

I installed Shorebird on windows using this command:

> powershell -exec bypass -c "(New-Object Net.WebClient).Proxy.Credentials=[Net.CredentialCache]::DefaultNetworkCredentials;iwr -UseBasicParsing 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex"

And installed this version of Shorebird without showing any error
**Shorebird 0.7.0
Shorebird Engine • revision 6c1f35b941ba46596b88674cbb7c59ac3eff1119**

**shorebird doctor** gave me this error:
![image](https://github.com/shorebirdtech/shorebird/assets/81581135/e59204ef-3dde-487b-b26f-adac4b226f89)

I deleted **shorebird.ps1** from the bin folder to fix this.

Now it says this when I run **shorebird doctor** or any other shorebird command
![image](https://github.com/shorebirdtech/shorebird/assets/81581135/ea80998a-e9ff-4398-aaeb-95473b2cfa17)

I've tried to run where.exe to see if the path is correct and everything seems fine:
![image](https://github.com/shorebirdtech/shorebird/assets/81581135/501ec0ed-875c-4cec-9708-ef228cdd9fdd)

**Comment by SpajicM** [comment]
It says running scripts disabled on this system.
Might be an issue on your end.
Try this: https://tecadmin.net/powershell-running-scripts-is-disabled-system/

**Comment by 0x456d7265** [comment]
> It says running scripts disabled on this system. Might be an issue on your end. Try this: https://tecadmin.net/powershell-running-scripts-is-disabled-system/

You're right. The problem was with my machine. Running `Set-ExecutionPolicy RemoteSigned` on PowerShell fixed this. Thank you

**Comment by eseidel** [comment]
I hit this as well  just now.  https://github.com/shorebirdtech/shorebird/issues/736  We should definitely do more to help the user here.
