### ISSUE TITLE
fix: `shorebird` fails on brand new windows machine

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#736]
After getting past https://github.com/shorebirdtech/shorebird/issues/734 by installing git, I now face another issue installing shorebird on this new machine:

```
PS C:\Users\eric_> shorebird
shorebird : File C:\Users\eric_\.shorebird\bin\shorebird.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see 
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ shorebird
+ ~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

Presumably we could/should detect that and explain to users?  Or do  we need to use a .bat file?

**Comment by eseidel** [comment]
I think  `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned` is the answer?  If so, we should help the user with that.

**Comment by eseidel** [comment]
That's from https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3

**Comment by eseidel** [comment]
Or maybe we need to sign our powershell script?

**Comment by bryanoltman** [comment]
> Or maybe we need to sign our powershell script?

I think this is probably the answer. Do we have an existing certificate that we could use for this?

**Comment by eseidel** [comment]
I'm not aware of one, no.  Happy to figure out how to apply for one or you're welcome to.  I suspect I may need to as it likely involves signing things.

**Comment by eseidel** [comment]
We looked into signing a little.  We also looked at how other tools do this.  Most seem to use msi's or exes to install.  e.g.
Git for windows, GitHub, Loom, all used (signed) exes.  Rust uses rustup-init.exe which is not signed.
