### ISSUE TITLE
fix: `shorebird account create` is telling me to upgrade even though I'm  already subscribed?

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#738]
It might be related to "birder" accounts being special?

```
Waiting for your authorization...
You already have an account, Eric Seidel!
To upgrade, run shorebird account upgrade.
```

**Comment by felangel** [comment]
I think that’s just generic copy we show to everyone. We should probably either remove it or make the message dynamic based on your current plan.
