### ISSUE TITLE
feat: share GROUPS of apps with a group of people (organizations / teams)

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#739]
Right now collaborators are per-app.  I expect some customers are going to want to add collaborators on a per-account, or per-team basis.  When we get such a request, this is a bug to track such.

**Comment by eseidel** [comment]
Will open when we get such requests.

**Comment by RajeshPandey057** [comment]
How Can I add other devs to my account ? I am already on a paid plan

**Comment by felangel** [comment]
> How Can I add other devs to my account ? I am already on a paid plan

You can use `shorebird collaborators add` to invite collaborators to your apps.

**Comment by mhmalz** [comment]
The use of shorebird itself is straight forward. But the handling of collaborators is really painful. Why can't they add flavors (resulting if an additional app) to a team account? Please add groups to the user/app management which also should allow delegation of more rights to other persons.

**Comment by bryanoltman** [comment]
This hasn't been completed (we only support per-app collaborators), reopening until we add something like organizations support.

**Comment by eseidel** [comment]
Dupe with https://github.com/shorebirdtech/shorebird/issues/739?

**Comment by eseidel** [comment]
This should probably be one of our 1.1 "tent-pole" features?

**Comment by eseidel** [comment]
We're about ready to start into a new feature, this is one of the ones we're considering.

**Comment by eseidel** [comment]
Update: this is mostly implemented.  The backend has been transitioned and Felix and Bryan are just working on finishing the front end work.  We expect to launch "organizations" support next week.

**Comment by eseidel** [comment]
We're fixing the last issues in staging now.  This will be launching this week: https://x.com/shorebirddev/status/1843331456661364760

**Comment by eseidel** [comment]
Done! https://shorebird.dev/blog/organizations/
