### ISSUE TITLE
fix: Shorebird should only charge for successful patch installs.

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#740]
We can't quite do this yet because the updater client does not yet report patch success back to our servers.

We'll want to add that for analytics anyway, and once we do so, we can also fix our billing to only bill for successful patch installs rather than patch downloads.

**Comment by hello-coder-xu** [comment]
Hope to provide it as soon as possible

**Comment by eseidel** [comment]
We actually implemented this and just forgot to close it. :)

**Comment by eseidel** [comment]
Updated FAQ in https://github.com/shorebirdtech/docs/commit/a2357be567db66358374659944bf5a2c9687dba7
