### ISSUE TITLE
feat: install patches without having to restart the app

### ISSUE THREAD

**Issue by GeylanKalafMohe** [shorebirdtech/shorebird#741]
**Description**

It would be much better if we can manually trigger to download patch releases via a Shorebird flutter library so we can update our flutter code with the latest changes without the app actually having to be restarted.

If that's not possible:
It would be good if we can have like a loading spinner when for the first time the patch is being downloaded in the background instead of the need that the app has to be restarted again for the second time to see the changes.

**Comment by SpajicM** [comment]
Take a look at: https://pub.dev/packages/shorebird_code_push

**Comment by bryanoltman** [comment]
As @SpajicM mentioned, https://pub.dev/packages/shorebird_code_push will allow you to check whether a new patch is available and manually trigger a download if so. 

I've updated the issue title to better reflect the work we need to do to mark this issue as complete.

**Comment by eseidel** [comment]
This would be great to add, but we're quite a ways away from supporting this.  Closing for now.
