### ISSUE TITLE
fix:  "shorebird patch android" does not update changes in app that is downloaded from PlayStore

### ISSUE THREAD

**Issue by CodingWithTashi** [shorebirdtech/shorebird#744]
**Description**

I have push a patch by commenting out some of the code in IDE. But changes are not reflecting in application that is downloaded from Google Play store.
Note: Release build and patch release was successful

**Steps To Reproduce**

1. Create new release with shorebird and deploy to Play Store
2. Download the application
3. Go back to IDE, Comment out a widget code
4. Push the change using `shorebird patch android`

```
PS D:\Development\flutter\tibetan_language_learning_app> shorebird patch android
✓ Building patch (90.9s)
📦 Release Version: 2.0.2+15
📺 Channel: stable
🕹️  Platform:  android [arm64 (683.17 KB), arm32 (781.01 KB), x86_64 (826.89 KB)]

Would you like to continue? (y/N) Yes
✓ Creating patch (0.4s)
✓ Uploading artifacts (6.4s)
✓ Fetching channels (0.3s)
✓ Promoting patch to stable (0.3s)

✅ Published Patch!


```

**Expected Behavior**

Comment out widget should be removed

**Comment by CodingWithTashi** [comment]
Funny it did worked, but it took hours to reflect the changes for first time. After that it takes around 10 minutes to see changes.

**Comment by felangel** [comment]
The updates should be installed immediately on a subsequent launch of the app and a second launch of the app should boot from the new patch. It shouldn’t take hours and usually should take just a couple of seconds (depending on the patch size and network speed).
