### ISSUE TITLE
feat: consider removing `shorebird run`

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#747]
Maybe replace it with `shorebird install` and/or `shorebird logs`?

The purpose of `shorebird install` is to know where the built product is and install it for you.

The purpose of `shorebird logs` would be to know how to get logs off the device (which is only possible on Android, or for iOS when a debugger is connected).

It's possible run should just be replaced by https://github.com/shorebirdtech/shorebird/issues/290?  e.g when it "runs" it runs from a released version rather than the one in your build dir?

**Comment by bryanoltman** [comment]
This is done
