### ISSUE TITLE
macos  command not found: shorebird

### ISSUE THREAD

**Issue by heshesh2010** [shorebirdtech/shorebird#750]
i installed shorebird on terminal successfully and when i type : shorebird i got this error 

<img width="1232" alt="Screenshot 2023-07-01 at 4 03 32 PM" src="https://github.com/shorebirdtech/shorebird/assets/16393042/f8f2158e-6d72-43e7-9adc-d157b0c742a2">

**Comment by felangel** [comment]
Hi @heshesh2010 
I’m guessing you need to exit the terminal and relaunch it for the path changes to take effect. Can you confirm whether that resolves the issue? Thanks!

**Comment by heshesh2010** [comment]
Hi , yes i followed the docs and relunch it again , but still got same
error

**Comment by felangel** [comment]
> Hi , yes i followed the docs and relunch it again , but still got same error
> […](#)

Can you confirm that you’ve added shorebird to your PATH?

**Comment by eseidel** [comment]
You can see your path with:
`echo $PATH`
PATH is a set of paths separated by `:`, you would expect that to include `$HOME/.shorebird/bin` or `~/.shorebird/bin`.

Note to self, we should add this to our troubleshooting page.

**Comment by heshesh2010** [comment]
> You can see your path with: `echo $PATH` PATH is a set of paths separated by `:`, you would expect that to include `$HOME/.shorebird/bin` or `~/.shorebird/bin`.
> 
> Note to self, we should add this to our troubleshooting page.

here is 



hesham@HeshamElnemrs-MacBook-Pro ~ %  echo $PATH
/Users/hesham/.shorebird/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/hesham/flutter/bin:/Users/hesham/.rvm/bin

**Comment by heshesh2010** [comment]
fixed when restart mac
