### ISSUE TITLE
feat: Would like a way to delete a release for a specific platform

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#751]
This is only really matters for my demo at the moment, since I have the release already built for iOS and am building for Android and it tells me I need to bump the version number for Android (but I would like to keep the same version number).

So I presume the easiest way would be to delete the Android release since the code I "released" iOS is different (or maybe we need some other way to handle version skew between platforms)?

**Comment by felangel** [comment]
This is supported via the console
