### ISSUE TITLE
feat: It's not possible to create a patch for two platforms at the same time

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#752]
The Api we have in the CLI takes the "platform" separate from the "patchArtifactBundles":

```dart
    await codePushClientWrapper.publishPatch(
      appId: appId,
      releaseId: release.id,
      platform: platformName,
      channelName: channelName,
      patchArtifactBundles: patchArtifactBundles,
    );
```

So you can't publish to both iOS and Android at the same time with that API, as you can't just add the iOS patchArtifactBundle into the array (as it would then assume it's an android bundle) and you can't just call "publishPatch" a second time, as that would then make a second patch.id.

So if you have both iOS and Android using the same release (which they will do by default?) then if you ever release on iOS, you will then have all your android clients fail to update (since there is no Android artifact for the latest release) and vice versa.

**Comment by felangel** [comment]
This is possible if you use the `createPatch`, `createPatchArtifacts`, and `promotePatch` APIs:

```dart
// Create one patch.
final patch = await codePushClientWrapper.createPatch(releaseId: releaseId);

// Upload all artifacts
await Future.wait([
    codePushClientWrapper.createPatchArtifacts(
      patch: patch,
      platform: 'ios',
      patchArtifactBundles: iosArtifacts,
    ),
    codePushClientWrapper.createPatchArtifacts(
      patch: patch,
      platform: 'android',
      patchArtifactBundles: androidArtifacts,
    ),
]);

// Promote the patch.
final channel = await codePushClientWrapper.maybeGetChannel(
          appId: appId,
          name: channelName,
        ) ??
        await codePushClientWrapper.createChannel(
          appId: appId,
          name: channelName,
        );

await codePushClientWrapper.promotePatch(patchId: patch.id, channel: channel);
```

**Comment by felangel** [comment]
Closing for now until we get more feedback from customers.
