### ISSUE TITLE
fix: get stuck on Building release

### ISSUE THREAD

**Issue by mraslamiii** [shorebirdtech/shorebird#754]
Hello
Thank you for publishing this great tool
I have a problem
I installed shorebird correctly and ran the init and even run release commands with ease
But when I run the shorebird release android command, it gets stuck on building mode, even after waiting for 30 minutes, it doesn't show any error or any other error.
**Screenshots**
![image](https://github.com/shorebirdtech/shorebird/assets/49343061/cad0bec6-6de9-41dc-b8c7-25e472f4333c)

**Comment by felangel** [comment]
Hi @mraslamiii 
Creating a shorebird release builds a release build of your app for android which can take a while depending on the app and computer you’re using.

**Comment by felangel** [comment]
Hi @mraslamiii 
Can you confirm that creating a flutter build works `flutter build appbundle --release`?

**Comment by mraslamiii** [comment]
yes i can run this command 
but problem with shorebird release android

**Comment by eseidel** [comment]
Another image from discord:
![image](https://github.com/shorebirdtech/shorebird/assets/478541/a92e58eb-13f4-44ff-a297-f5258e32671a)

**Comment by eseidel** [comment]
I would try `shorebird release android -v -- -v` as @bryanoltman suggested.

**Comment by mraslamiii** [comment]
I also tested this command
The result did not matter
I really don't know what to do
![Screenshot (87)](https://github.com/shorebirdtech/shorebird/assets/49343061/a6db93a7-a1ca-4941-8ad1-320495a8a6ed)

**Comment by eseidel** [comment]
Does the timer stop updating?  (does it get stuck at 109.6s?).  Have you left it running longer than 2 minutes?

My understanding is that the first time we build with flutter it has to actually set up flutter itself, which may get included in that `building release` time (we probably should make that more clear in the UI).

It looks like `-- -v` doesn't do what we expected it to.  I suspect we will need to investigate a bit more on our end and get back to you.

**Comment by mraslamiii** [comment]
No, it is not stuck at a specific time. I even waited for nearly 20 minutes, but nothing happened

Anyway, thank you for your efforts and I look forward to hearing from you

**Comment by eseidel** [comment]
I'm not really sure how to help here.

Have you tried `flutter build appbundle --release`?  Does that hang as well?

We're also available on discord to help if needed: https://discord.gg/shorebird.

**Comment by eseidel** [comment]
We would love to help, but need more information.  Closing for now.
