### ISSUE TITLE
fix: `shorebird patch` reports unexpected dex changes

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#755]
From Discord:
![image](https://github.com/shorebirdtech/shorebird/assets/478541/b4535cf5-7b06-4f80-b033-80769341b519)

**Comment by abhilash-scapia** [comment]
1. shorebird release - no problem
[no changes in codebase]
2. shorebird patch - no problem
[make some X changes in dart file]
3. shorebird patch - problem seen
[undo the changes X]
4. shorebird patch - problem seen

So, step 2 and 4 are running essentially on same code base with no differences and having a different outcome.

**Comment by eseidel** [comment]
I've seen reports on the internet of tools like "dexguard" changing the contents of classes.dex every build, e.g. https://stackoverflow.com/questions/31424581/checksum-value-of-classes-dex-keep-changing-with-dexguard-for-every-build
Are you using any tools like that that might be trying to modify your dex files for you?

**Comment by SPiercer** [comment]
same issue here not using dexguard

**Comment by abhilash-scapia** [comment]
it was newrelic gradle plugin that is changing dex on every rebuild. Commented newrelic gradle plugin to fix it.
Nothing related to shorebird. We can close the issue @eseidel

**Comment by SPiercer** [comment]
@abhilash-scapia can you show me where u found this plugin ?

**Comment by abhilash-scapia** [comment]
If you use newrelic, It will be in your app > src> build.gradle 
newrelic is a comprehensive analytics tool that we use. https://newrelic.com/

![Screenshot 2023-07-04 at 6 00 07 PM](https://github.com/shorebirdtech/shorebird/assets/99723485/d952d478-e79a-46b7-a058-7de16f85f4db)

**Comment by SPiercer** [comment]
@abhilash-scapia but for my case i don't have such plugins
```Groovy
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
```

**Comment by abhilash-scapia** [comment]
Is it possible for you to send the complete build.gradle file or if the
project is available in github I can take a closer look

**Comment by SPiercer** [comment]
```Groovy
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
// START: FlutterFire Configuration
apply plugin: 'com.google.gms.google-services'
// END: FlutterFire Configuration
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 33
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        multiDexEnabled true
        minSdkVersion 21
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```
i removed the app id for privacy

**Comment by felangel** [comment]
I think this can be closed (https://github.com/shorebirdtech/shorebird/pull/843)

**Comment by eseidel** [comment]
Please let us know if 0.9.2 does not resolve your issues!

**Comment by alexmercerind** [comment]
We still get redundant native changes on Android. Not sure what to do.

**Comment by Nguyen-Ngoc-Phuoc** [comment]
Same, we change notthing from the code, and still get the error

**Comment by bryanoltman** [comment]
> We still get redundant native changes on Android. Not sure what to do.

If you create a release and immediately create a patch for that release without changing anything, do you see this warning? (same question for @Nguyen-Ngoc-Phuoc)

**Comment by SilentCatD** [comment]
Hello, I’m @Nguyen-Ngoc-Phuoc, same account as above. 

I have identified the problem in my case after throughout analyzing , it’s the newrelic plugin problem of generating new BUILD_ID in a java config file every build, not related to shorebird.

**Comment by eseidel** [comment]
Thanks.  Some plugins do not produce stable builds.  I wasn't aware of newrelic as being a culprit, but that makes sense.

Does newrelic provide a way to disable this behavior and produce stable builds?  (Otherwise it's not possible to produce the exact same APK across multiple machines or periods of time.)

**Comment by SilentCatD** [comment]
https://github.com/newrelic/newrelic-flutter-agent/issues/123#issuecomment-2442230586
 
 Thank you for following up with this issue. 

Afraid not, it would seem like a new feature request with them has to be filed

Before figured out it was newrelic, I used tools like [dex-diff](https://github.com/theapache64/dex-diff) and [diffuse](https://github.com/JakeWharton/diffuse), and apkanalyzer  to check the different between 2 apks, the only difference between them is this generated BUILD_ID string in generated config file.

Actions that cause rebuild, regenerate of this file is the trigger of natives changes (eg flutter clean)

This is not encountered on iOS though

**Comment by SilentCatD** [comment]
I created a PR https://github.com/newrelic/newrelic-android-agent/pull/304

This will allow us to custom set the BUILD_ID, ensure stable builds

**Comment by SilentCatD** [comment]
In the meantime, I think we could integrate these by building the android plugin ourselves.

- Clone the newrelic android main branch and revert to needed version
- Perform changes as the PR above
- `./gradlew clean assemble`
- Copy the build jars of: plugin module and instrument module
- Paste it inside Flutter project like this
<img width="298" alt="image" src="https://github.com/user-attachments/assets/7ae01a76-d64f-4274-99f0-57b3c0e7eaf7">


Inside `android/build.gradle` use these 2 jars, commented out the original plugin, and edit the repository


```

    repositories {
        // add this flatDir
        flatDir {
            dirs 'libs'
        }
        google()
        jcenter()
        ...

    }
    dependencies {
       ....

//        classpath "com.newrelic.agent.android:agent-gradle-plugin:7.2.0"
        classpath files('libs/instrumentation-7.2.0.jar')
        classpath files('libs/gradle-7.2.0.jar')
    }
``` 


Inside `app/build.gradle` add this, the previously `apply plugin: 'newrelic'` should still be there


```
newrelic {
    variantMapsEnabled = false
    buildId = "${flutterVersionName}.${flutterVersionCode}"
}
```


Then we won't have problem with patching and generating new BUILD_ID every patch builds

![Screenshot2024_10_30_111300](https://github.com/user-attachments/assets/75b3a63e-d626-4044-ac25-31e85a574c8b)

**Comment by alexmercerind** [comment]
> We still get redundant native changes on Android. Not sure what to do.

So, I also analysed my situation. Turns out few packages declare dependency like this:
- https://github.com/PostHog/posthog-flutter/blob/e1715271b1011d3daeea04ecf813bd1bbc47982f/android/build.gradle#L58
- https://github.com/razorpay/razorpay-flutter/blob/2daadbaa4d56c1ded1c79cc7e763efc929812252/android/build.gradle#L36

This makes the resulting .dex different (if any update is published by them, even if not to the Flutter package directly), causing the patch to fail.

**Comment by SilentCatD** [comment]
@eseidel I think we can close this, thank you for the support
