### ISSUE TITLE
fix: 'C:\Program' is not recognized as an internal or external command when shorebird install path contains space on Windows

### ISSUE THREAD

**Issue by syedmurtaza108** [shorebirdtech/shorebird#756]
**Description**

When I try to execute `shorebird release android` in my Windows 11, it throws
 ```
Exception: Failed to extract version name from app bundle: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by MozafarAlali93** [comment]
same problem

**Comment by eseidel** [comment]
This sounds like we're not quoting spaces, or possibly need to be enabling "useShell" for the command in question.

**Comment by eseidel** [comment]
I think this is probably in the JAVA_HOME handling?

https://github.com/shorebirdtech/shorebird/blob/47637044ab896e81e045704b5e79a4616ece910f/packages/shorebird_cli/lib/src/shorebird_release_version_mixin.dart#L38

Probably a very quick fix.  Thanks for the report!

**Comment by bryanoltman** [comment]
I think https://github.com/shorebirdtech/shorebird/issues/756#issuecomment-1618521746 is probably correct. However, I'm unable to reproduce this issue in either powershell or cmd.exe.

If someone experiencing this issue could run the command that triggers the issue with a `-v` flag and paste the output here, that would be very helpful!

e.g.,
```
shorebird release android -v
```

**Comment by syedmurtaza108** [comment]
@bryanoltman Here is output of `shorebird release android -v`
```
[Process.run] C:\Users\Murtaza Hussain\.shorebird\bin\cache\flutter\bin\flutter build appbundle --release
✓ Building release (67.7s)
⠦ Fetching apps... (1.3s)[HTTP] GET https://api.shorebird.dev/api/v1/apps
✓ Fetching apps (2.4s)
[Process.run] C:\Program Files\Java\jdk1.8.0_202\bin\java.exe -jar C:\Users\Murtaza Hussain\.shorebird\bin\cache\artifacts\bundletool\bundletool.jar dump manifest --bundle build\app\outputs\bundle\release\app-release.aab --xpath /manifest/@android:versionName
[Process.run] C:\Program Files\Java\jdk1.8.0_202\bin\java.exe -jar C:\Users\Murtaza Hussain\.shorebird\bin\cache\artifacts\bundletool\bundletool.jar dump manifest --bundle build\app\outputs\bundle\release\app-release.aab --xpath /manifest/@android:versionCode
✗ Exception: Failed to extract version name from app bundle: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
 (96ms)
```

**Comment by bryanoltman** [comment]
Thank you! I'm able to reproduce now. It seems like the issue is that we don't properly handle shorebird install paths that contain spaces. Will update this bug, and fix incoming.
