### ISSUE TITLE
fix: patch update is not working locally

### ISSUE THREAD

**Issue by dileep9490** [shorebirdtech/shorebird#757]
**Description**

I've built and installed the app to my phone through an `.apk` file and after doing a patch update succesfully my app didn't get the patch update

**Steps To Reproduce**

1. run the command `flutter create example`. a basic counter app will work
2. then `shorebird init`
3. `shorebird doctor --fix`
4. `shorebird release android`
5. after the release is successful share the `.apk` file to android 
6. install the app and test it 
7. Now in the example code change `_counter++` to `_counter--`
8. then run `shorebird patch android`
9. after the update check the app

**Expected Behavior**

when we click on the plus icon it should decrement the counter value i.e, 0 => -1 but it's not working as expected and does 0 => 1

**Additional Context**

I've shared the app through whatsapp since gmail doesn't allow sharing it and the second way to share the app is through a usb cable 

**Flutter Logs**
<img width="1710" alt="Screenshot 2023-07-03 at 10 50 15 PM" src="https://github.com/shorebirdtech/shorebird/assets/63330310/42a6fb93-3a62-4b01-9f57-e4dff2e137aa">

**Comment by eseidel** [comment]
The "hash mismatch" error happens most often when there is a difference between what compiled Dart code Shorebird expects for a release, vs what is contained in the binary claiming to be said release.

This most often happens when making a release (say 1.0.0+1) and then changing the binary and running it.  Shorebird will prepare a binary diff against the dart code from 1.0.0+1, but then try to apply it to whatever Dart code is in the running binary claiming to be 1.0.0+1, and find the patch doesn't apply cleanly (hence the hash mismatch).

We need to improve our logs here, you're far from the only person to have this issue.

The fix is to just make sure that you're running the exact binary for 1.0.0+1 that you told Shorebird about.  If you're running a modified copy it won't know how to patch said modified copy.

**Comment by dileep9490** [comment]
it's working as expected. 
first we need to do a release and then run the app locally. 
@eseidel changing the Documentation order might help as more people will follow the docs order.
the current documentation order is **run** and then **release**. we can change the order to **release** and **run**

**Comment by felangel** [comment]
> it's working as expected.
> first we need to do a release and then run the app locally.
> @eseidel changing the Documentation order might help as more people will follow the docs order.
> the current documentation order is **run** and then **release**. we can change the order to **release** and **run**

The order shouldn’t matter so long as you haven’t changed anything between creating a release and running the app.

**Comment by dileep9490** [comment]
I did a `shorebird run` then `shorebird release` after that i did a small change and did `shorebird patch android` i didn't get the patch update
I didn't change the code between **run** and **release**
### Logs
<img width="1240" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/63330310/a0540f91-6dbb-4cd0-a098-10a7f75f430d">

**Comment by eseidel** [comment]
The app id in that later screenshot is different from the earlier one.  I recommend checking `shorebird apps list` and make sure you've published a patch to the app you intend to.

**Comment by dileep9490** [comment]
I know they are different apps. after @felangel  said the order doesn't matter as long as we didn't change anything between `shorebird run` and `shorebird release android` i tried this order and that's the log i'm getting for the new app when i do a patch update this is the issue. But when i did `shorebird release android` and `shorebird run` then `shorebird patch android` worked without any error

Do i need to install the app again after running `shorebird release android`?

**Comment by minhtritc97** [comment]
same issue, it's not working on .apk file

**Comment by dileep9490** [comment]
@minhtritc97 try this way 
1. run `shorebird release android`
2. run `shorebird run` to get the .apk file
3. Install the .apk in you mobile
4. make some changes 
5. run `shorebird patch android`

**Comment by minhtritc97** [comment]
@dileep9490 

yes i did, but I run shorebird build apk  in step 2  and app doesn't change any thing

**Comment by dileep9490** [comment]
> > 
> 
> yes i did, but I run shorebird build apk in step 2 and app doesn't change any thing

i doesn't change anything because `shorebird build` won't create .apk file it'll create app bundle which will help you when you are uploading the app to playstore. To get the .apk file you need to do `shorebird run`

**Comment by minhtritc97** [comment]
@dileep9490 it worked, thank you so much

**Comment by bryanoltman** [comment]
Going to close this as we seem to have resolved the issue and other open issues (https://github.com/shorebirdtech/shorebird/issues/802 for example) address this.
