### ISSUE TITLE
fix: installer fails if git is too old.

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#758]
From a customer:

What's error ```error: unknown option `filter=tree:0'``` when installing ```curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash```?

we could just remove the filter-tree option if git is too old. Or just remove it always. It’s only an optimization.  We could also just error out if git is too old.  I guess I’d probably just error out.

**Comment by bryanoltman** [comment]
This manifests on Windows as well with https://gist.github.com/mir-smarts1/4d36d97972f0369fbb3b976f945865e3. We need to figure out what the oldest acceptable git is.

**Comment by eseidel** [comment]
> This manifests on Windows as well with https://gist.github.com/mir-smarts1/4d36d97972f0369fbb3b976f945865e3. We need to figure out what the oldest acceptable git is.

I'm not sure how that's a git failure?  It looks like it's failing to find dart.exe?

**Comment by bryanoltman** [comment]
The first error:

```
& : The term 'C:\Users\DELL\.shorebird\bin\cache\flutter\bin\flutter.bat' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
```

Stems (I think) from the flutter repo not being checked out. I'm on my phone atm but can find the command that I believe to have been failing when I'm at my laptop.

**Comment by bryanoltman** [comment]
The current oldest version on our team is 2.37.1, so that will be the oldest version we support
