### ISSUE TITLE
feat: better logs in case of no internet connection

### ISSUE THREAD

**Issue by abhilash-scapia** [shorebirdtech/shorebird#759]
**Requirements**

- [ ] Put descriptive logs in case of update error 

**Additional Context**

I recently got an error during patch update. 
It looked like updater::updater: Update thread finished with status: Update had error

The real reason was device wasn't connected to the internet

If error is described better, it will be easier to zero down on root cause and understand it.

**Comment by eseidel** [comment]
We've seen others hit this as well.  Definitely worth fixing, thanks.

**Comment by eseidel** [comment]
Sorry to be slow, yes this would be easy to fix.  Next time I'm in the rust code I will add something here.
