### ISSUE TITLE
feat: support adding a flavor after init

### ISSUE THREAD

**Issue by abhilash-scapia** [shorebirdtech/shorebird#761]
If, for example, a flavor is added after `shorebird init`, the shorebird.yaml file does not have it.

This results in an error like
 **Cannot get property 'flavor-name' on null object**
 
 If the error is more descriptive, this will help developer understand faster that the `shorebird init --force` should be run.

**Comment by eseidel** [comment]
In general we don't currently support updating Shorebird's knowledge of "what flavors this app has" other than at init time.  This is a totally valid request.

**Comment by felangel** [comment]
This is supported. If you re-run `shorebird init` after adding new flavors it'll detect the new flavors and update your `shorebird.yaml`.
