### ISSUE TITLE
feat: On Premise support

### ISSUE THREAD

**Issue by CodingAleCR** [shorebirdtech/shorebird#762]
**Description**

It'd be cool to have some sort of on premise support for Flutter Apps. That would enable a sort of custom app distribution.

My use case is the following:

I have a client with a custom built app that is distributed manually and does not go through the App Store/Play Store flow. This is because it's an in-house app that's only supposed to run on certain devices and for certain users. This said, we've got a custom server that handles the app's latest version and the app itself has code to check for the latest version. If the app is not updated, then it proceeds to download an APK from a storage server and prompts to the user the usual update/install process.

This works, and is already built, but I think it would be even better to have it so you don't have the user manually download the APK and instead the features are pushed through the app, this is where Shorebird comes in (I think!).

I know that Shorebird already has T&C to avoid this for App Store and Play Store but I think they could be adjusted so that you could allow scenarios like this.

I have a couple other clients that are looking for the same process so I believe that there is a market that could be explored from the business sense.

Of course this is an oversimplification of the whole idea but I believe the different hurdles could improve the service provided by Shorebird.

**Additional Context**

Anyways, I'm just a small developer from Costa Rica, but I believe this scenario might be broader and more common than this. Feel free to correct me if I'm wrong though. Cheers and keep up the good work!

**Comment by bryanoltman** [comment]
The scenario you describe is already supported, I think. Shorebird does not require the app to be downloaded from the Play Store. The user will need to download the app the first time (and for any subsequent non-Dart changes), but you should be able to push patches to an app distributed in this manner. Just be sure to use the `release` command to generate the binary.

**Comment by bryanoltman** [comment]
Going to close as "fixed", but please reopen if I'm missing something!

**Comment by CodingAleCR** [comment]
Oh, that's great. Although "on premise" I think should support more than patch releases, is that possible with the current feature-set of shorebird?
