### ISSUE TITLE
fix: Can't use `--dart-define-from-file`

### ISSUE THREAD

**Issue by definev** [shorebirdtech/shorebird#765]
**Description**

Using `shorebird build apk --dart-define-from-file=.env/.prod.json` not work.

<img width="823" alt="Screenshot 2023-07-04 at 14 18 17" src="https://github.com/shorebirdtech/shorebird/assets/62325868/3d3c6814-668d-41bf-8d9d-9b152c61a5b1">

**Comment by eseidel** [comment]
Add an extra — and it should:
‘shorebird build apk — —dart-define…’

Let us know if that doesn’t.

**Comment by definev** [comment]
Wow, you reply so fast :D It works!!! Yay!
