### ISSUE TITLE
error: unsupported android plugin version

### ISSUE THREAD

**Issue by duynv289** [shorebirdtech/shorebird#766]
**Description**

've installed app in my android device.
And  when I patch new release with error

**Steps To Reproduce**

1. `shorebird build apk `
2. Install app
3. Modify code 
4. `shorebird patch android`

**Screenshots**

![Screenshot_2023-07-04_at_3 18 48_PM](https://github.com/shorebirdtech/shorebird/assets/30969032/8b4bc348-7dff-4a5b-b062-ad4d3bae9afd)

**Additional Context**

Flutter version: 3.10.5
Shorebird version match flutter version

**Comment by bryanoltman** [comment]
I wouldn't expect the build to succeed but the patch to fail. Can you elaborate on what code changes you made and provide more detail about your project? Do you see these warnings when building? What do you see if you run `shorebird patch android -v`?

**Comment by eseidel** [comment]
I recommend trying again.  We've changed a ton in the last month.

https://docs.shorebird.dev/ shows the recommended flow.
```
shorebird release android
shorebird preview
```
is what we recommend over `shorebird build` and `shorebird run` these days.
