### ISSUE TITLE
New developers often get to a HashMismatched error

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#780]
I'm not entirely sure what we should do here.  Whether just make the rust logging much more clear what's going on?  Somehow fix the system in some other way (like `shorebird run` failing when it sees you running version X and having a libapp.so hash which doesn't match?  May also need to write docs which the Rust code points to?  Regardless, it's a too-common failure mode for new users.

**Comment by SpajicM** [comment]
I'm wondering how, or why users end up in this situation.

**Comment by eseidel** [comment]
I believe the most common cause is:
```
shorebird release
// make edits
shorebird patch
// don't revert edits
shorebird run // since edits were not reverted this isn't the same libapp.so the patch expects as base.
```

**Comment by felangel** [comment]
I propose we introduce a new command `shorebird patch preview --release <RELEASE_VERSION> --patch <PATCH_NUMBER>` which fetches the artifacts for the specified release/patch and runs them on the connected device. We might want to consider removing `shorebird run` entirely if we have something like the proposed `preview` command.

**Comment by eseidel** [comment]
Related also to #779
