### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by theappideasankit** [shorebirdtech/shorebird#782]
shorebird run wraps flutter run and can take any argument flutter run can. To pass arguments to the underlying flutter run, use a -- separator. For example, shorebird run -- -d my_device will run on a specific device.

any command available hot restart or update code when i'm using this command (shorebird run -- -d my_device)

**Comment by eseidel** [comment]
The above is correct.  Are you asking for us to update the website or docs to point that out better?  Not sure what action you'd like taken for this issue.  Thanks!
