### ISSUE TITLE
feat: support of partial rollouts of patches

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#783]
This is related to https://github.com/shorebirdtech/shorebird/issues/110, but #110 was closed after the infrastructure was landed, but before we actually released a fully working feature.

What blocked our release of a fully working feature, was that we realized we had no way to know which devices were/weren't in a specific test group from Google/Apple.

However upon further discussion with customers, simply disabling automatic update behavior e.g. https://github.com/shorebirdtech/shorebird/issues/716 may be sufficient for them to implement this themselves, but making their own call to their servers and then choosing based on the user/device whether to install a patch via package:shorebird_code_push apis.

This bug covers completing the work to make partial rollouts of packages work (via whatever mechanism).

Some customers may also wish to use this for A/B testing (which may imply additional analytics work).

**Comment by bryanoltman** [comment]
Implementing this would allow for customers to test/verify patches before releasing them to their full user base.

**Comment by eseidel** [comment]
I think what the customer is asking for is just a way to test a patch locally on their device, before going live.

So something as simple as:
```
shorebird patch android --staging
```
Which then says at the end:
```
This patch is not yet live.  Preview it with:
shorebird preview --app_id=abcd --release_version=1.0+1 --staging

You can make it live at the release page with "make live":
https://console.shorebird.dev/app_id/abcd/releases/1234
```

**Comment by eseidel** [comment]
Another way might be:

```
shorebird patch android --stage-to=test
```

```
This patch is staged to `test`.  Preview it with:
shorebird preview --app_id=abcd --release_version=1.0+1 --channel=test

You can make it live at the release page with "make live":
https://console.shorebird.dev/app_id/abcd/releases/1234
```

**Comment by eseidel** [comment]
Another proposal from Felix is to just make `shorebird patch` default to non-live (which I think we want eventually anyway).

So the flow would be:
```
% shorebird patch android
This patch is staged.  Preview it with:
shorebird preview --app-id=abcd --release-version=1.0.0+1 --include-staged

You can make it live from the console:
https://console.shorebird.dev/app_id/abcd/releases/1234
```

You could imagine having a flag:
`shorebird patch android --make-live` which did the old behavior.

**Comment by felangel** [comment]
This should be done now 🎉
