### ISSUE TITLE
Couldn't initialize shorebird_cli in the root of the flutter project

### ISSUE THREAD

**Issue by Vaibhav77e** [shorebirdtech/shorebird#789]
Can someone help me to fix this error. I have installed shorebird_cli but i can't initialize it root of flutter projects. I'm getting this error.
shorebird init
shorebird : The term 'shorebird' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

**Comment by eseidel** [comment]
Sounds like `shorebird` is not in your path.  Did the installer complete successfully?  You may need to restart your powershell or terminal after the install for the path environment update to take effect?

**Comment by Vaibhav77e** [comment]
Nah I checked with shorebird doctor it worked fine. But I couldn't initialize it in root of the flutter project.
Thank you for responding.

**Comment by felangel** [comment]
> Nah I checked with shorebird doctor it worked fine. But I couldn't initialize it in root of the flutter project. Thank you for responding.

Can you please share logs when you try to run `shorebird doctor` in the root of the Flutter project? Thanks!

**Comment by Vaibhav77e** [comment]
No it's fixed thank you I just it next day it;s just working fine.
