### ISSUE TITLE
"The Semaphore timeout period has expired"

### ISSUE THREAD

**Issue by Shams-Mahmoud** [shorebirdtech/shorebird#790]
this error happend when build new patch

shorebird patch android

✓ Building patch (3.1s)
✗ ClientException with SocketException: The semaphore timeout period has expired.
 (OS Error: The semaphore timeout period has expired.
, errno = 121), address = api.shorebird.dev, port = 51329, uri=https://api.shorebird.dev/api/v1/apps (21.2s)

**Comment by eseidel** [comment]
"The semaphore timeout period has expired." is a windows-specific networking error.  I've seen it in other contexts, but it's always been temporary.  Does it go away if you try again?

I believe another individual reported seeing this last week as well and I wonder if it could be some quirk in the Dart networking stack on Windows.

I don't have an answer for you, but I'd love to help get to the bottom of the issue.

**Comment by eseidel** [comment]
I expect this error was temporary and this has been resolved?

Let us know if that's not the case, we're happy to help!  https://discord.gg/shorebird also reaches us.

**Comment by bryanoltman** [comment]
Reopening as this was just reported again in Discord (https://discord.com/channels/1030243211995791380/1134459483767185419/1134474860429590628)

**Comment by ScottS2017** [comment]
I don't think this is specific to Shorebird. I'm running into it with the langchain dart package right now while trying to connect to Ollama, and I found this issue through a Google search.

**Comment by eseidel** [comment]
> I don't think this is specific to Shorebird. I'm running into it with the langchain dart package right now while trying to connect to Ollama, and I found this issue through a Google search.

See https://github.com/dart-lang/sdk/issues/52919

**Comment by ScottS2017** [comment]
I got around my issue by changing the port in my code to localhost instead of 10.0.2.2, so all I can think of is a bad base uri.
