### ISSUE TITLE
fix: shorebird init fails to detect product flavors

### ISSUE THREAD

**Issue by Augustinekan** [shorebirdtech/shorebird#794]
**Description**
I installed the shorebird cli and tried runing shorebird init for an existing project, every time it throws the exception "Unable to detect product flavors"

**Steps To Reproduce**

Run the followng commands on powershell
`Set-ExecutionPolicy RemoteSigned -scope CurrentUser 
iwr -UseBasicParsing 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex`

 Run `shorebird login` in command prompt

Change directory to an existing flutter project location then run `shorebird init`

**Expected Behavior**

The command should initialize shorebird in my flutter project

**Screenshots**

![image](https://github.com/shorebirdtech/shorebird/assets/41288069/a4bdbb55-9ce4-42fc-9e6e-231d6a7cee02)

**Additional Context**

Flutter Doctor
![image](https://github.com/shorebirdtech/shorebird/assets/41288069/721afe08-bdb7-4ece-be96-cb418520f125)

**Comment by felangel** [comment]
Hi @Augustinekan 👋 
Thanks for opening an issue!

I believe this is related to the Flutter doctor warning regarding Android Studio and not being able to detect the bundled Java version. Can you please ensure you have Android Studio/Java correctly installed/configured and retry?

**Comment by Augustinekan** [comment]
@felangel  Thank you, this turned out to be the issue. I had just updated to to the latest version of Android Studio Flamingo and there was apparently a new Android Studio folder marked AndroidStudio1 besides the existing Android Studio folder in Program Files/Android/.   I just deleted the old Android Studio and renamed the new one (Android Studio1) to Android Studio then, inside the newly renamed Android Studio Folder, copied the contents of the jbr folder into the jre folder.

Flutter doctor ran with no Errors
![image](https://github.com/shorebirdtech/shorebird/assets/41288069/dee6a60f-af49-4dcc-8e90-f4b53adefd1e)
 
Shorebird initializes successfully
![image](https://github.com/shorebirdtech/shorebird/assets/41288069/8dcb84b8-d0c0-45ed-a5cd-ccc7a9039a99)

**Comment by felangel** [comment]
Glad to hear you sorted it out. Going to close this for now 👍
