### ISSUE TITLE
Couldn't patch new changes

### ISSUE THREAD

**Issue by Vaibhav77e** [shorebirdtech/shorebird#810]
```
✓ Building patch (105.3s)
✓ Fetching apps (1.5s)
✓ Detected release version 1.0.0+1 (1.2s)
✓ Fetching release (0.4s)
✓ Fetching Flutter revision (0.3s)
✓ Fetching release artifacts (1.0s)
✓ Fetching aab artifact (0.3s)
✓ Downloading release artifacts (24.0s)
✗ Exception: Failed to create diff:  (0.9s)
```

I was testing app but the app isn't live on plastore could this is issue for the above Exception

**Comment by eseidel** [comment]
I might recommend trying with `shorebird patch android -v` to see the extra logging?  Thanks.

**Comment by eseidel** [comment]
Please let us know if we can help.  We're also reachable on discord: https://discord.gg/shorebird.

Without more information assuming this is resolved for now.
