### ISSUE TITLE
fix:  shorebird init -> Build failed with an exception.

### ISSUE THREAD

**Issue by ShankarKakumani** [shorebirdtech/shorebird#819]
**Description**

I just installed shorebird and tried to run 'shorebird init' in the terminal. then I was faced with this error.

**Steps To Reproduce**

1. installed shorebird 
2. then did shorebird login
3. shorebird init

**Error details**

$ shorebird init

✗ Detecting product flavors (1.1s)
Unable to extract product flavors.
Exception: 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':device_info_plus'.
> Could not open cp_proj generic class cache for build file '/Users/shankarkakumani/.pub-cache/hosted/pub.dev/device_info_plus-9.0.2/android/build.gradle' (/Users/shankarkakumani/.gradle/caches/7.5/scripts/aygwfejo1ju7y5buabxwm2num).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':device_info_plus' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':device_info_plus' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 947ms

**flutter doctor**
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**shorebird doctor -v**
$ shorebird doctor -v

Shorebird v0.9.1
Shorebird Engine • revision 6c1f35b941ba46596b88674cbb7c59ac3eff1119
[Process.run] git rev-parse --verify HEAD (in /Users/shankarkakumani/.shorebird/bin/cache)
[Process.run] git fetch --tags (in /Users/shankarkakumani/.shorebird/bin/cache)
⠇ Shorebird is up-to-date... (2.2s)[Process.run] git rev-parse --verify @{upstream} (in /Users/shankarkakumani/.shorebird/bin/cache)
✓ Shorebird is up-to-date (2.3s)
[Process.run] git status (in /Users/shankarkakumani/.shorebird/bin/cache/flutter)
⠹ Flutter install is correct... (0.2s)[Process.run] /Users/shankarkakumani/.shorebird/bin/cache/flutter/bin/flutter --version
⠼ Flutter install is correct... (27.5s)[Process.run] flutter --version
✓ Flutter install is correct (28.1s)

No issues detected!

**Screenshots**
<img width="1001" alt="Screenshot 2023-07-11 at 8 39 10 PM" src="https://github.com/shorebirdtech/shorebird/assets/35686278/7fffcd4a-664d-4b37-909b-b136d94c4089">
<img width="776" alt="Screenshot 2023-07-11 at 8 40 56 PM" src="https://github.com/shorebirdtech/shorebird/assets/35686278/01713f3a-ba1f-4831-97de-2b23794861cf">
<img width="990" alt="Screenshot 2023-07-11 at 8 41 05 PM" src="https://github.com/shorebirdtech/shorebird/assets/35686278/3c4d34c3-2b6d-432e-98d0-4e554f266f0d">

**Comment by eseidel** [comment]
When you `flutter build android` it works fine though, correct?

**Comment by eseidel** [comment]
@bryanoltman suggested https://github.com/fluttercommunity/plus_plugins/issues/1480 on Discord

**Comment by ShankarKakumani** [comment]
> 

yes, I can build the APK with flutter build apk.
I am also able to install this in the emulator and physical android device as well.


will try the solution @bryanoltman  suggested.

**Comment by ShankarKakumani** [comment]
Fixed after upgrading gradle
