### ISSUE TITLE
fix: validate that `patch aar` build-number matches the release build number

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#828]
AARs do not have a release version – the release version is derived from the app that includes them. They are identified by build number (specified by the `build-number` option, which defaults to `1.0`) – release version is only used by shorebird to associated an initial build of an AAR with patches. 

 It is currently possible to to do the following:

```
# release version 1.0.0
shorebird release aar --build-number=1.0

# still release version 1.0.0
shorebird patch aar --build-number=2.0
```

**Comment by eseidel** [comment]
This is still an issue, but no longer as common since we've fixed our docs.

**Comment by pro100svitlo** [comment]
do you have plans to add support of `--build-number=123 --build-name=2.0.2` to `shorebird release` command in the visible future?

**Comment by eseidel** [comment]
My understanding is that our current thinking is we should implement https://github.com/shorebirdtech/samples/issues/11 instead?  Please re-open if I've misunderstood @bryanoltman

**Comment by bryanoltman** [comment]
Correct
