### ISSUE TITLE
fix: cannot create patch after deleting release

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#838]
**Description**

Attempting to patch an older version (1.0.0+1) after releasing and deleting a newer version (1.0.0+2) fails.

**Steps To Reproduce**

1. Release version 1.0.0+1
2. Release version 1.0.0+2
3. Delete release 1.0.0+2
4. Attempt to patch 1.0.0+1

**Expected Behavior**

A patch is created

** Actual Behavior **

Fetching aab artifact fails with `✗ Exception: Failed to download release artifact: 404 Not Found (87ms)`

**Screenshots**

<img width="2040" alt="Screenshot 2023-07-12 at 2 01 20 PM" src="https://github.com/shorebirdtech/shorebird/assets/581764/00c43da6-0367-4cc5-8d46-86eaaa570207">

**Comment by bryanoltman** [comment]
The CLI is correctly identifying the current release and is successfully requesting release artifacts from our server for every artifact except the `aab`. Current theory is that our server is incorrectly deleting aab release artifacts when deleting a release.

**Comment by bryanoltman** [comment]
The aab artifact does not seem to be getting deleted from our DB, so it seems to just be a lookup failure

**Comment by eseidel** [comment]
Felix fixed a similar lookup failure for patches:
https://github.com/shorebirdtech/_shorebird/commit/b3560f29c19d9ea2cc021c3d1b3f6f2ea4d9fba1

**Comment by bryanoltman** [comment]
Deleting a release is currently deleting the entire storage bucket for the release https://github.com/shorebirdtech/_shorebird/blob/main/packages/code_push_server/routes/api/v1/releases/%5Bid%5D/index.dart#L52-L58. Fixing now.
