### ISSUE TITLE
Notify users when they have hit or are close to hitting overage

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#858]
"You have exceeded the limit, your app will continue to function but users will no longer receive patches. To upgrade, click here."

**Comment by eseidel** [comment]
Yeah.  GitHub does a nice job with this.  GCP's is less nice, but still functional.

**Comment by bryanoltman** [comment]
I think this was resolved a while ago with https://github.com/shorebirdtech/_shorebird/pull/439
