### ISSUE TITLE
feat: Make it possible to recover a lost shorebird.yaml

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#869]
A customer reached out tonight having lost their `shorebird.yaml` and wanting to be able to patch their app.

I gave them manual instructions, but this should just be a command option to `shorebird init` or similar, especially for covering things like the flavors case which are more complicated to restore.

**Comment by felangel** [comment]
Thoughts on having functionality in the console that allows users to view/copy the shorebird.yaml?

**Comment by eseidel** [comment]
Any of these sound fine to me. See the question in #support from last night.

**Comment by eseidel** [comment]
For us to support this well with Flavors we may need to teach "flavor" apps that they are related in some way.
