### ISSUE TITLE
fix:  Flutter run doesn't work after installing shorebird

### ISSUE THREAD

**Issue by itssidhere** [shorebirdtech/shorebird#870]
**Description**

After installing shorebird, I cannot run my app in debug mode using flutter run

 What went wrong:
Execution failed for task ':android_id:generateDebugRFile'.
> Could not resolve all files for configuration ':android_id:debugCompileClasspath'.
   > Could not find io.flutter:flutter_embedding_debug:1.0.0-3531f1ab7af264b4972c41ab5fdab72601c20444.
     Required by:
         project :android_id

**Steps To Reproduce**

Run the app using Flutter run

**Expected Behavior**

The app should run as expected before installing shorebird

**Comment by eseidel** [comment]
Sorry to hear that!  Shorebird definitely should not affect your installed Flutter.  This may be a vsc bug we're aware of https://github.com/Dart-Code/Dart-Code/issues/4607.

Can you print your path to `flutter`?  e.g. `which flutter`?

**Comment by itssidhere** [comment]
@eseidel The path of my `flutter ` is `C:\flutter`

**Comment by harmeetsingh-work** [comment]
Hi @eseidel ,
Facing similar issue with Android Studio.
```
shorebird release android -v

[Process.run] /Users/xmachina/.shorebird/bin/cache/flutter/bin/flutter build appbundle --release
✗ Failed to build: 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-3531f1ab7af264b4972c41ab5fdab72601c20444.
     Required by:
         project :app > project :firebase_core
         project :app > project :firebase_app_check
         project :app > project :firebase_crashlytics
         project :app > project :flutter_plugin_android_lifecycle
         project :app > project :firebase_database
         project :app > project :path_provider_android
         project :app > project :cloud_firestore
         project :app > project :firebase_analytics
         project :app > project :firebase_auth
         project :app > project :package_info_plus
         project :app > project :firebase_remote_config
         project :app > project :image_picker_android
         project :app > project :firebase_messaging
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-3531f1ab7af264b4972c41ab5fdab72601c20444.
         > inconsistent module metadata found. Descriptor: io.flutter:flutter_embedding_debug:1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d Errors: bad version: expected='1.0.0-3531f1ab7af264b4972c41ab5fdab72601c20444' found='1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Gradle task bundleRelease failed with exit code 1
```

Which flutter:
```
/Users/xmachina/flutter/bin/flutter
``` 

Flutter version:
```
flutter --version 
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (11 days ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1
```

Shorebird version:
```
shorebird --version
Shorebird 0.10.0
Shorebird Engine • revision 3531f1ab7af264b4972c41ab5fdab72601c20444
```

**Also dont know why, my Android Studio project local.properties contains**
```
flutter.sdk=/Users/xmachina/.shorebird/bin/cache/flutter
```
Even tried changing above path, but when I run `shorebird release android`, it gets changed back to above.

Please help, and thank you for this great tool.

**Comment by bryanoltman** [comment]
> flutter.sdk=/Users/xmachina/.shorebird/bin/cache/flutter

I would remove this. It may not be the cause of this particular problem, but it might be, and it's definitely not something you want.

**Comment by eseidel** [comment]
> > flutter.sdk=/Users/xmachina/.shorebird/bin/cache/flutter
> 
> I would remove this. It may not be the cause of this particular problem, but it might be, and it's definitely not something you want.

Could `flutter build aar` be causing that (via `shorebird build aar`)?

**Comment by eseidel** [comment]
@harmeetsingh-work I see you calling `[Process.run] /Users/xmachina/.shorebird/bin/cache/flutter/bin/flutter build appbundle --release` and then it saying:
`      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-3531f1ab7af264b4972c41ab5fdab72601c20444.`

That seems surprising.

Is there something set up in your gradle file to make your release builds depend on debug artifacts?

We may need to split this into two bugs, since I think you two may be having separate issues.  Regardless, I'd like to help you both get these resolved!  Reaching out to us on Discord: https://discord.gg/shorebird may allow us to help quicker.

**Comment by bryanoltman** [comment]
> Could flutter build aar be causing that (via shorebird build aar)?

I doubt it, but it's not impossible

**Comment by harmeetsingh-work** [comment]
@eseidel Correct

That was so noobish of me.

For debugging purpose, I did add `debuggable true` flag to gradle release buildType instead of creating separate buildType.

Removing `debuggable` flag, release building is now success with shorebird command.

Thank you very much. 😃

**Comment by eseidel** [comment]
I'm going to close this for now, but @itssidhere, please don't hesitate to re-open if you're still having the issue!

`flutter` should be used from your flutter install, which for you sounds like C:\flutter\bin\flutter

Visual Studio Code seems to sometimes get confused and use the `flutter` inside Shorebird (`$HOME/.shorebird/bin/cache/flutter/bin/flutter`) which won't work.
