### ISSUE TITLE
fix: "shorebird preview" Error: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME or PATH environment variable.

### ISSUE THREAD

**Issue by choepro577** [shorebirdtech/shorebird#877]
I am having the following problem, hope someone can help me !!!!!!!!

hieudz@x3109lp2 testshorebird % shorebird preview  
✓ Fetching apps (0.4s)
Which app would you like to preview?
❯ ◉  shorebird
Which app would you like to preview?
  ◯  shorebird
Which app would you like to preview?
❯ ◉  shorebird
Which app would you like to preview?
  ◯  shorebird
Which app would you like to preview? test
✓ Fetching releases (0.3s)
Which release would you like to preview?
Which release would you like to preview? 1.0.0+1
✓ Extracting metadata (0.2s)
✗ Exception: Failed to install apks: [BT:1.14.1] Error: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME or PATH environment variable.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME or PATH environment variable.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.commands.CommandUtils.lambda$getAdbPath$0(CommandUtils.java:48)
        at java.base/java.util.Optional.orElseThrow(Unknown Source)
        at com.android.tools.build.bundletool.commands.CommandUtils.lambda$getAdbPath$1(CommandUtils.java:41)
        at java.base/java.util.Optional.orElseGet(Unknown Source)
        at com.android.tools.build.bundletool.commands.CommandUtils.getAdbPath(CommandUtils.java:37)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.fromFlags(InstallApksCommand.java:153)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.fromFlags(InstallApksCommand.java:147)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:117)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)

=============================

hieudz@x3109lp2 testshorebird % shorebird doctor                              

Shorebird v0.9.2
Shorebird Engine • revision 3531f1ab7af264b4972c41ab5fdab72601c20444
✓ AndroidManifest.xml files contain INTERNET permission (30ms)
✓ Shorebird is up-to-date (1.8s)
✓ Flutter install is correct (22.7s)

No issues detected!
hieudz@x3109lp2 testshorebird %

**Comment by choepro577** [comment]
i have run shorebird docter and no problem. Below is the description

hieudz@x3109lp2 testshorebird % shorebird doctor                              

Shorebird v0.9.2
Shorebird Engine • revision 3531f1ab7af264b4972c41ab5fdab72601c20444
✓ AndroidManifest.xml files contain INTERNET permission (30ms)
✓ Shorebird is up-to-date (1.8s)
✓ Flutter install is correct (22.7s)

No issues detected!
hieudz@x3109lp2 testshorebird %

**Comment by eseidel** [comment]
Can you try running `flutter doctor` as well?  If `flutter doctor` can find ANDROID_HOME or `adb` we should be able to too.

`echo $ANDROID_HOME` may also give you more information.

Thank you!

**Comment by choepro577** [comment]
here is my flutter doctor -v running code
```
hieudz@MacBook-Pro-cua-Nguyen testshorebird % flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.1 22C65 darwin-arm64, locale en-VN)
    • Flutter version 3.10.6 on channel stable at /Users/hieudz/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/hieudz/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by eseidel** [comment]
Thank you.  I guess we just need to update our adb finding logic:
https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/android_sdk.dart#L19
To be closer to Flutter's:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_sdk.dart#L73

**Comment by felangel** [comment]
@choepro577 can you share the contents of `/Users/hieudz/Library/Android/sdk`?

**Comment by eseidel** [comment]
I think the question here is why do we require `adb` and the Flutter tool doesn't?

**Comment by felangel** [comment]
We use adb so that we can preview the apk/aab on either an emulator or a physical device. After looking a bit more closely at the flutter tool, they only use adb when running on a physical device -- on emulators they use avd hence the difference in behavior. I also double checked, and in cases where shorebird cannot find adb (it's not part of the PATH), the flutter tool similarly cannot detect adb.

**Comment by eseidel** [comment]
Our understanding is that Flutter use `avd` when running in an emulator, and `adb` when running on a device.  We use `adb` for both.  We've updated `shorebird doctor` to better notice when `adb` is missing.  We believe the bug here was just the setup in question was missing `adb` (thus running on devices wouldn't have worked in Flutter either).

We could change shorebird to use `avd` for emulators, but for now we don't plan to.

Let us know if this doesn't help!

**Comment by neetable-chollarasan** [comment]
Getting same issue while running shorebird preview. What I have to do to fix it?
