### ISSUE TITLE
fix:  Split per abi option not found

### ISSUE THREAD

**Issue by warrenlayson** [shorebirdtech/shorebird#878]
**Description**
I already tried to look for similar issues but I found none. I tried build an apk with split-per-abi option. As per my understanding that shorebird cli wraps the flutter cli. I'm not sure if this is intended but let me know.

**Steps To Reproduce**

1. run shorebird release android --artifact apk -- --split-per-abi

**Expected Behavior**

It should produce multiple apk file per abi like what flutter build apk --split-per-abi does. Which will produce a smaller apk size that a fat one.

**Screenshots**

![image](https://github.com/shorebirdtech/shorebird/assets/81952460/ac1dc36e-9e97-46df-b38e-988cd163095e)

**Additional Context**

N/A

edit: reupload image

**Comment by eseidel** [comment]
In general what you're saying is true that shorebird passes all options after `--` down to the Flutter commands.  I suspect --split-per-api may be special since it affects the produced APKs and we may need to test and get back to you.

Thank you for the issue!

**Comment by warrenlayson** [comment]
> In general what you're saying is true that shorebird passes all options after `--` down to the Flutter commands.  I suspect --split-per-api may be special since it affects the produced APKs and we may need to test and get back to you.
> 
> Thank you for the issue!

Thanks for the reply, highly appreciated!

**Comment by eseidel** [comment]
Looks like we're calling `flutter build appbundle` under the covers and this option is only available on `flutter build apk`.

**Comment by warrenlayson** [comment]
Ah! then you're getting the apk from the appbundle. I was under the impression that you're calling `flutter build apk` if we supplied `--artifact apk`. Thanks for the clarification, haven't gone through the source code to check.

**Comment by bryanoltman** [comment]
Fixed by https://github.com/shorebirdtech/shorebird/pull/1010

**Comment by FirdousNath** [comment]
Facing  it on `0.14.6 `

<img width="1090" alt="Screenshot 2023-09-05 at 8 07 26 PM" src="https://github.com/shorebirdtech/shorebird/assets/19954996/226215a1-3118-4902-8f08-9b4e770bc48a">

**Comment by felangel** [comment]
> Facing it on `0.14.6 `
> 
> <img alt="Screenshot 2023-09-05 at 8 07 26 PM" width="1090" src="https://user-images.githubusercontent.com/19954996/265734246-226215a1-3118-4902-8f08-9b4e770bc48a.png">

Looks like only `shorebird release android` supports this atm.

**Comment by eseidel** [comment]
> Facing it on `0.14.6 `
> 
> <img alt="Screenshot 2023-09-05 at 8 07 26 PM" width="1090" src="https://user-images.githubusercontent.com/19954996/265734246-226215a1-3118-4902-8f08-9b4e770bc48a.png">

Filed. https://github.com/shorebirdtech/shorebird/issues/1220
