### ISSUE TITLE
my app doesn't update after I use command for android shorebird patch android

### ISSUE THREAD

**Issue by BuiXuanQuan** [shorebirdtech/shorebird#879]
I follow the example and change some color 
https://docs.shorebird.dev/guides/code_push_quickstart
![Screen Shot 2023-07-20 at 17 14 52](https://github.com/shorebirdtech/shorebird/assets/65236097/b9e91e42-7415-4124-ab51-d2e120332b04)

**Comment by eseidel** [comment]
Are you able to share the android logs from running your app?  e.g.
`adb logcat | grep flutter`?

**Comment by tronghuy5555** [comment]
I have the same issue  when init ShorebirdCodePush `[ShorebirdCodePush]: Error initializing updater: Invalid argument(s): Failed to lookup symbol 'shorebird_current_boot_patch_number': undefined symbol: shorebird_current_boot_patch_number`, `shorebird patch android` work well, but no any updates when restart the app

**Comment by eseidel** [comment]
Hmm, that's definitely our bug.  I recall us having that problem, but I thought we recently fixed it.  I wonder if this was fixed in 0.10.0 (which we just released today) but was broken in 0.9.2 (last week's release).

**Comment by eseidel** [comment]
I think @felangel fixed this?

**Comment by felangel** [comment]
> I think @felangel fixed this?

Yeah this is should be resolved. @tronghuy5555 can you confirm you’re using the latest stable version of shorebird (v0.10.0) via `shorebird --version`?

**Comment by BuiXuanQuan** [comment]
Did you deploy the new version to fix my issue?

**Comment by felangel** [comment]
> Did you deploy the new version to fix my issue?

I’m not sure what your issue is? Can you please share some logs (`adb logcat | grep flutter`)? I’m not aware of any such issues on the latest stable version (0.10.0) so if you haven’t already, I highly recommend upgrading and trying again.

**Comment by BuiXuanQuan** [comment]
![Screen Shot 2023-07-21 at 08 26 11](https://github.com/shorebirdtech/shorebird/assets/65236097/1cc14fcf-d7a3-4632-9db4-a8b99172e269)
 I upgraded new Shorebird version and then run the command  again, it seems like shorebird engine have some problems

**Comment by BuiXuanQuan** [comment]
![Screen Shot 2023-07-21 at 08 34 00](https://github.com/shorebirdtech/shorebird/assets/65236097/5fd3c58a-0c42-4c95-96d8-bdbdb964e4e1)
adb logcat | grep flutter

**Comment by BuiXuanQuan** [comment]
> > Did you deploy the new version to fix my issue?
> 
> I’m not sure what your issue is? Can you please share some logs (`adb logcat | grep flutter`)? I’m not aware of any such issues on the latest stable version (0.10.0) so if you haven’t already, I highly recommend upgrading and trying again.

Please check man

**Comment by felangel** [comment]
> > > Did you deploy the new version to fix my issue?
> > 
> > 
> > I’m not sure what your issue is? Can you please share some logs (`adb logcat | grep flutter`)? I’m not aware of any such issues on the latest stable version (0.10.0) so if you haven’t already, I highly recommend upgrading and trying again.
> 
> Please check man

Those logs look like you’re running the app in debug mode. Are you sure you’re running the release build generated by `shorebird release android`? The easiest way to run the release build locally is to use the `shorebird preview` command after you’ve run `shorebird release android`.

**Comment by BuiXuanQuan** [comment]
I was trying to use release mode, and shorebird preview, my app bar still does not change color

**Comment by BuiXuanQuan** [comment]
![Screen Shot 2023-07-21 at 09 12 23](https://github.com/shorebirdtech/shorebird/assets/65236097/e4e4ad89-ba6a-476a-941e-792f16fd3246)

**Comment by BuiXuanQuan** [comment]
I think it worked, but I don't know why I need to run Shorebird patch android --force 2 times, and then I can see an update (I saved the file I changed in release mode) why it took two times to see the change?

**Comment by BuiXuanQuan** [comment]
2 patches to see the updation in Flutter app

**Comment by felangel** [comment]
> 2 patches to see the updation in Flutter app

That should not be necessary. I’m guessing the first time you tried, you were not using shorebird preview and we’re running a different build instead of the one generated by `shorebird release android`. Are you sure you followed the steps outlined in the docs? https://docs.shorebird.dev/guides/code_push_quickstart

You can also see a video of those steps executed on the [shorebird website](https://shorebird.dev)

**Comment by BuiXuanQuan** [comment]
First step: I used the Shorebird preview
Second step: I make a small change
Third steps: I usedShorebirdd patch android (It doesn't work)
Four steps: I used Shorebird patch android again (now It  worked)
I already followed the docs man

**Comment by felangel** [comment]
> First step: I used the Shorebird preview
> Second step: I make a small change
> �Third steps: I usedShorebirdd patch android (It doesn't work)
> �Four steps: I used Shorebird patch android again (now It worked)
> I already followed the docs man

After you use shorebird patch, you need to relaunch the app once to install the patch, and a second time to boot from the patch. Can you confirm you relaunched the app twice after patching?

**Comment by BuiXuanQuan** [comment]
yes I did it 
use shorebird patch for the first time and then relaunch the app it doesn't work
Second time I used shorebird patch and then relaunch the app it worked

**Comment by BuiXuanQuan** [comment]
I figure out I used await _shorebirdCodePush.downloadUpdateIfAvailable() (Using the button check for an update like example); and then restart the app
It worked well the first time
It only happend when I try to use  shorebird patch and then relaunch the app

**Comment by felangel** [comment]
> yes I did it
> use shorebird patch for the first time and then relaunch the app it doesn't work
> Second time I used shorebird patch and then relaunch the app it worked

Just to clarify you need to relaunch the app 2 times for the patch to take effect by default.

**Comment by BuiXuanQuan** [comment]
![Screen Shot 2023-07-21 at 11 57 20](https://github.com/shorebirdtech/shorebird/assets/65236097/52dfa896-d4d3-4cc0-8807-397753670b38)
I thought it need only one time for relaunch (kill and open)
why do I need to relaunch 2 times to see the update?

**Comment by tronghuy5555** [comment]
> > I think @felangel fixed this?
> 
> Yeah this is should be resolved. @tronghuy5555 can you confirm you’re using the latest stable version of shorebird (v0.10.0) via `shorebird --version`?

I just upgraded latest version `Shorebird 0.10.0 Shorebird Engine • revision 3531f1ab7af264b4972c41ab5fdab72601c20444` but the issue still existed, already uninstall and install again 
<img width="349" alt="ScreenShot 2023-07-21 at 12 15 27@2x" src="https://github.com/shorebirdtech/shorebird/assets/13816239/23db6c0a-4f5c-4378-8934-43ab7abf9bd7">
<img width="594" alt="ScreenShot 2023-07-21 at 12 16 20@2x" src="https://github.com/shorebirdtech/shorebird/assets/13816239/27920853-00a7-4107-aaad-bbb15692a413">

**Comment by BuiXuanQuan** [comment]
me too man, sometimes it's not stable we need to wait to make sure it will be stable in the upcoming time, and then we can apply it to the project 

> > > I think @felangel fixed this?
> > 
> > 
> > Yeah this is should be resolved. @tronghuy5555 can you confirm you’re using the latest stable version of shorebird (v0.10.0) via `shorebird --version`?
> 
> I just upgraded latest version `Shorebird 0.10.0 Shorebird Engine • revision 3531f1ab7af264b4972c41ab5fdab72601c20444` but the issue still existed, already uninstall and install again <img alt="ScreenShot 2023-07-21 at 12 15 27@2x" width="349" src="https://user-images.githubusercontent.com/13816239/255078939-23db6c0a-4f5c-4378-8934-43ab7abf9bd7.png"> <img alt="ScreenShot 2023-07-21 at 12 16 20@2x" width="594" src="https://user-images.githubusercontent.com/13816239/255079036-27920853-00a7-4107-aaad-bbb15692a413.png">

**Comment by felangel** [comment]
> > > I think @felangel fixed this?
> > 
> > 
> > Yeah this is should be resolved. @tronghuy5555 can you confirm you’re using the latest stable version of shorebird (v0.10.0) via `shorebird --version`?
> 
> I just upgraded latest version `Shorebird 0.10.0 Shorebird Engine • revision 3531f1ab7af264b4972c41ab5fdab72601c20444` but the issue still existed, already uninstall and install again <img alt="ScreenShot 2023-07-21 at 12 15 27@2x" width="349" src="https://user-images.githubusercontent.com/13816239/255078939-23db6c0a-4f5c-4378-8934-43ab7abf9bd7.png"> <img alt="ScreenShot 2023-07-21 at 12 16 20@2x" width="594" src="https://user-images.githubusercontent.com/13816239/255079036-27920853-00a7-4107-aaad-bbb15692a413.png">

Shorebird engine not available most likely means the app you’re running was not built with shorebird release.

**Comment by felangel** [comment]
> ![Screen Shot 2023-07-21 at 11 57 20](https://user-images.githubusercontent.com/65236097/255076699-52dfa896-d4d3-4cc0-8807-397753670b38.png)
> I thought it need only one time for relaunch (kill and open)
> why do I need to relaunch 2 times to see the update?

You need one launch to trigger the patch check & download and a second launch to boot from the patch.

**Comment by felangel** [comment]
Closing for now as there is no actionable item here. Feel free to comment with additional questions/thoughts if you have any and we're happy to continue the convo 👍

**Comment by eseidel** [comment]
We're also available on Discord every day: https://discord.gg/shorebird
