### ISSUE TITLE
feat: Support flavors on iOS

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#910]
To match parity with Android.

**Comment by M97Chahboun** [comment]
Hi guys, I want contribute by implement this issue but the flavor already passed and used on [buildIpa method](https://github.com/shorebirdtech/shorebird/blob/4ac96fd5147daeda983bd815a2281e7f572f060a/packages/shorebird_cli/lib/src/commands/release/release_ios_command.dart#L98)...

**Comment by felangel** [comment]
> Hi guys, I want contribute by implement this issue but the flavor already passed and used on [buildIpa method](https://github.com/shorebirdtech/shorebird/blob/4ac96fd5147daeda983bd815a2281e7f572f060a/packages/shorebird_cli/lib/src/commands/release/release_ios_command.dart#L98)...

I’m working on this and should have it ready sometime in the next few days 🙂

**Comment by M97Chahboun** [comment]
@felangel OK, Good luck 👍🏼
