### ISSUE TITLE
Deprecate `shorebird releases delete`

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#924]
Once this is exposed via console.shorebird.dev

**Comment by LinXunFeng** [comment]
Hello, is it possible to restore the deletion function? We want to use the engine modified by shorebird to automatically compile and build the App through jenkins during the testing phase. Now we need to delete it through console.shorebird.dev every time we build.

**Comment by eseidel** [comment]
Thanks for the suggestion, I've opened an issue.
