### ISSUE TITLE
Error on patch, after use shorebird release android --artifact=apk

### ISSUE THREAD

**Issue by JgomesAT** [shorebirdtech/shorebird#926]
THis error has been closed but in the last version 0.11 we have the same error after do:
shorebird release android --artifact=apk
✓ Building release (49.3s)
✓ Fetching apps (0.3s)
✓ Detecting release version (0.4s)
✓ Fetching releases (0.2s)

🚀 Ready to create a new release!

📱 App: my_andorra_telecom (b6a80ead-ae84-4729-87d3-b3d30300b869)
📦 Release Version: 3.0.0+2
🕹️  Platform: android (arm64, arm32, x86_64)

Would you like to continue? (y/N) Yes
✓ Fetching Flutter revision (16ms)
✓ Creating release (0.4s)
✓ Creating artifacts (10.2s)
✓ Updating release status (0.2s)

✅ Published Release!

with and OK

and after do:

shorebird patch android -v IA have the same error:

[Process.run] /Users/jorgegomes/.shorebird/bin/cache/flutter/bin/flutter build appbundle --release
✓ Building patch (22.9s)
[HTTP] GET https://api.shorebird.dev/api/v1/apps
✓ Fetching apps (0.3s)
[Process.run] java -jar /Users/jorgegomes/.shorebird/bin/cache/artifacts/bundletool/bundletool.jar dump manifest --bundle=./build/app/outputs/bundle/release/app-release.aab --xpath /manifest/@android:versionName
[Process.run] java -jar /Users/jorgegomes/.shorebird/bin/cache/artifacts/bundletool/bundletool.jar dump manifest --bundle=./build/app/outputs/bundle/release/app-release.aab --xpath /manifest/@android:versionCode
✓ Detected release version 3.0.0+2 (0.4s)
[HTTP] GET https://api.shorebird.dev/api/v1/apps/b6a80ead-ae84-4729-87d3-b3d30300b869/releases
✓ Fetching releases (0.2s)
[Process.run] git rev-parse HEAD (in /Users/jorgegomes/.shorebird/bin/cache/flutter)
✓ Fetching Flutter revision (15ms)
[HTTP] GET https://api.shorebird.dev/api/v1/apps/b6a80ead-ae84-4729-87d3-b3d30300b869/releases/2802/artifacts?arch=aarch64&platform=android
⠙ Fetching release artifacts... (80ms)[HTTP] GET https://api.shorebird.dev/api/v1/apps/b6a80ead-ae84-4729-87d3-b3d30300b869/releases/2802/artifacts?arch=arm&platform=android
⠼ Fetching release artifacts... (0.3s)[HTTP] GET https://api.shorebird.dev/api/v1/apps/b6a80ead-ae84-4729-87d3-b3d30300b869/releases/2802/artifacts?arch=x86_64&platform=android
✓ Fetching release artifacts (0.5s)
[HTTP] GET https://api.shorebird.dev/api/v1/apps/b6a80ead-ae84-4729-87d3-b3d30300b869/releases/2802/artifacts?arch=aab&platform=android
✓ Fetching aab artifact (0.2s)
✓ Downloading release artifacts (5.5s)
Unhandled exception:
Bad state: No element
#0      ListBase.firstWhere (dart:collection/list.dart:132:5)
#1      AabDiffer._metaInfMfContent (package:shorebird_cli/src/archive_analysis/aab_differ.dart:50:12)
#2      AabDiffer.changedFiles (package:shorebird_cli/src/archive_analysis/aab_differ.dart:34:27)
#3      PatchAndroidCommand.run (package:shorebird_cli/src/commands/patch/patch_android_command.dart:245:37)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:151:18)
<asynchronous suspension>
#6      ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:93:14)
<asynchronous suspension>
#7      main (file:///Users/jorgegomes/.shorebird/packages/shorebird_cli/bin/shorebird.dart:22:5)
<asynchronous suspension>

I think that the problem is that internally this command launch the .shorebird/bin/cache/flutter/bin/flutter build appbundle --release aapbundle release, but in my case I create previously and APK and not a APPBUNDlE

**Comment by felangel** [comment]
This has been fixed on main by https://github.com/shorebirdtech/shorebird/pull/922 and will be available in the next stable release.

**Comment by JgomesAT** [comment]
Now it is working,
