### ISSUE TITLE
shorebird release ios-alpha option to change the name of plist

### ISSUE THREAD

**Issue by JgomesAT** [shorebirdtech/shorebird#927]
I have this error when shorebird release ios-alpha
ios/Runner/Info.plist' (OS Error: No such file or directory, errno = 2)

Because the name of my list is Info-Release.plist, can I customize the command to specify this name of plist??

**Comment by felangel** [comment]
Hi @JgomesAT 👋
Is that because you have flavors setup? Shorebird iOS currently doesn’t support flavors. What flutter command do you run to release normally?

**Comment by JgomesAT** [comment]
IN the step of my Ci/CD flutter build ios --no-codesign --build-name=20230719.6 --obfuscate --split-debug-info=./ofuscate/debug

after that a second step: xcodebuild -sdk iphoneos16.2 -configuration Release -workspace /Users/runner/work/1/s/app_andorratelecom/ios/Runner.xcworkspace -scheme Runner build CODE_SIGN_STYLE=Manual

but in develope tools like VS code I only throw flutter build ios  
Building ad.andorratelecom.ios.andorratelecom for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: CF9CTW5HWV
Running Xcode build...           

and work fine                                      ⣾

**Comment by JgomesAT** [comment]
with the vesrion 0.12.2 works fine
