### ISSUE TITLE
Not able to generate release for iOS.

### ISSUE THREAD

**Issue by fitterfly-parth** [shorebirdtech/shorebird#928]
I run the below command to generate an iOS release for stage flavor but not working

shorebird release ios --flavor stage

Getting this error while generating a release for iOS.

<img width="1361" alt="Screenshot 2023-07-27 at 2 47 37 PM" src="https://github.com/shorebirdtech/shorebird/assets/104829044/34257803-a635-45b9-ab4b-ec0123e5a4ea">

Is there I missed anything here?

**Comment by eseidel** [comment]
Thanks for filing!  Unfortunately we haven't yet added Flavor support for iOS. See https://github.com/shorebirdtech/shorebird/issues/910 and https://github.com/shorebirdtech/shorebird/issues/929.

**Comment by eseidel** [comment]
We have added Flavor support for iOS now.  However this sounds very similar to https://github.com/shorebirdtech/shorebird/issues/936, I wonder if something else is wrong.

Are you still able to reproduce?

**Comment by bryanoltman** [comment]
Closing to due inactivity. Please reopen this issue if you're still having trouble
