### ISSUE TITLE
fix: `Missing extension byte` error when backspacing wrong char

### ISSUE THREAD

**Issue by SPiercer** [shorebirdtech/shorebird#935]
**Description**

I'm facing the below issue whenever i use the CLI by any form when there's a prompt and i type a wrong char then backspace into `y` 

**Steps To Reproduce**

1. [shorebird release android]
2. type wrong char (i guess in non unicode char) like [غ] which is the same place as y in english layout
3. backspace the [غ] then type [y]
4. [enter]

**Expected Behavior**

the cli detects correct char

using ZSH cli

**Screenshots**

```bash
Missing extension byte
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      SystemEncoding.decode (dart:io/string_transformer.dart:27:47)
#3      Stdin.readLineSync (dart:io/stdio.dart:110:21)
#4      Logger.confirm (package:mason_logger/src/mason_logger.dart:255:26)
#5      ReleaseAndroidCommand.run (package:shorebird_cli/src/commands/release/release_android_command.dart:149:30)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:151:18)
<asynchronous suspension>
#8      ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:93:14)
<asynchronous suspension>
#9      main (file:///Users/nour/.shorebird/packages/shorebird_cli/bin/shorebird.dart:22:5)
<asynchronous suspension>
```

**Comment by eseidel** [comment]
Yeah, this is probably a mason_logger issue.  Obviously we're responsible in the end, but I suspect the fix will go there:
https://github.com/felangel/mason/blob/master/packages/mason_logger/lib/src/mason_logger.dart#L251

**Comment by felangel** [comment]
I’ll have a look 👀
