### ISSUE TITLE
fix: IOS build for release with error: "Runner.app" requires a provisioning profile with the Associated Domains feature.

### ISSUE THREAD

**Issue by zhushenwudi** [shorebirdtech/shorebird#936]
**Description**

run "shorebird release ios-alpha", It will toast an error
"Runner.app" requires a provisioning profile with the Associated Domains feature.

**Steps To Reproduce**

1. shorebird release ios-alpha
2. watch board

**Expected Behavior**

build successfully

**Screenshots**

<img width="843" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/30340027/a95f1183-e845-4efc-8d53-896f18d610d1">

**Additional Context**

in xcode, it will build successfully
<img width="525" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/30340027/1d949469-a991-4cc4-bfbb-61d631658c08">

**Comment by eseidel** [comment]
Sorry for the delay.  Does `flutter build ipa` work?

**Comment by jonasbark** [comment]
`shorebird build ipa` works for me because it has codesigning disabled by default.

Yet `shorebird release ios-alpha` does not and fails with the error above.
`flutter build ios` also fails with the same error because codesigning is enabled.

I assume that it should be reproducible by enabling any kind of "Capability" in Xcode:
![image](https://github.com/shorebirdtech/shorebird/assets/1151304/768173b6-a686-4d1e-a647-10b11b98ce73)

**Comment by zhushenwudi** [comment]
<img width="1005" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/30340027/cd9cb3be-5fa9-44c7-b5c5-129f73223e47">
<img width="739" alt="image" src="https://github.com/shorebirdtech/shorebird/assets/30340027/b6036681-143b-489f-9b28-c3573c1365c8">

So the current problem is that the packaging failed due to the signature of the release. How can we solve it?

**Comment by eseidel** [comment]
We'd love to learn more from you about how you normally build with Flutter?  Sounds like the way we're calling `flutter build` from within Shorebird must be missing something about your normal provisioning setup?  Do you typically build from XCode?  Do you ever build with `flutter build ios --release`?  If so, what's the command you use?  Thanks!

You can also reach us on discord: https://discord.gg/shorebird.

**Comment by jonasbark** [comment]
@eseidel as already mentioned in https://github.com/shorebirdtech/shorebird/issues/936#issuecomment-1692892451 it is easy to reproduce:

1. create new flutter project
2. use a working team + bundle ID in Xcode
4. `shorebird release ios-alpha` work
5. disable automatic signing
6. add a capability in Xcode, such as "Access wifi information"
7. `shorebird release ios-alpha` fails:
> "Runner.app" requires a provisioning profile with the Access Wi-Fi Information feature.

I noticed `flutter build ios --release` also fails.

Related flutter issue: https://github.com/flutter/flutter/issues/106612#issuecomment-1536580775
Related shorebird issue: https://github.com/shorebirdtech/shorebird/issues/938

**Comment by jonasbark** [comment]
FWIW here's my current workaround (using fastlane):

```ruby
        sh("cd ../.. && shorebird build ipa")
        build_app(
            scheme: "Runner",
            export_method: "app-store",
            export_team_id: "***",
        )
        sh("mkdir -p ../../build/ios/ipa")
        sh("mv ../../ios/Runner.ipa ../../build/ios/ipa/fieldbots_app_flutter.ipa")
        sh("cd ../.. && shorebird release ios-alpha -- --no-codesign")
        upload_to_testflight(
            skip_waiting_for_build_processing: true,
            api_key: api_key,
            app_identifier: "io.fieldbots.app.test",
            ipa: "../build/ios/ipa/fieldbots_app_flutter.ipa",
        )
```

**Comment by zhushenwudi** [comment]
@eseidel  Yes, as described as the brothers above, Shorebird is available for projects without complex configuration

The problem may be as saying in https://github.com/flutter/flutter/issues/106612, when there is certain configurations in Xcode, the Flutter Build IPA command is not easy to use.So Shorebird cannot run successfully
