### ISSUE TITLE
feat: Support --no-codesign argument when building for iOS

### ISSUE THREAD

**Issue by jonasbark** [shorebirdtech/shorebird#938]
**Description**

Due to the still horribly complicated provisioning for iOS apps we are building our flutter apps without code signing, then rebuilding them using fastlanes build_app and the correct team IDs:

```ruby

        sh("cd ../.. && flutter build ipa --release --no-codesign")
        build_app(
            scheme: "Runner",
            export_method: "app-store",
            export_team_id: "...",
        )
```
The --no-codesign command is not available in shorebird at this point.

**Requirements**

- [ ] add support for --no-codesign argument when building with `shorebird release ios-alpha`

**Additional Context**

We also tried to use the standard shorebird release command, but we also fail at issue #936

**Comment by eseidel** [comment]
We generally pass all commands after `--` through to the underlying Flutter, so in this case:
```
shorebird release ios-alpha -- --no-codesign
```
(Note the extra `--` to delineate when `shorebird` arguments stop and and `flutter` arguments start.)
might work.

**Comment by jonasbark** [comment]
Thanks - that does work indeed. However, the no-codesign argument does not create an IPA, thus the script fails at the next step. It creates a "Runner.xcarchive" file instead.

```
❯ shorebird release ios-alpha -- --no-codesign
[WARN] iOS support is alpha. See https://docs.shorebird.dev/status#ios-alpha for more information.
✓ Fetching apps (0.3s)
✓ Building release (53.5s)
✗ Failed to determine release version: PathNotFoundException: Cannot open file, path = '/Users/.../build/ios/ipa/....ipa' (OS Error: No such file or directory, errno = 2) (21ms)
```

**Comment by eseidel** [comment]
Reminds me of https://github.com/shorebirdtech/shorebird/issues/878 in that it's an option `flutter` supports which changes the artifact output.

I'd love to help, but i'm not entirely sure what you're trying to achieve or how we can best help here. It sounds like you need the --no-codesign option to fit into your build process?   We don't actually care about the IPA itself, we could use a different artifact for our processes, but that would be quite a bit of change on our end, so we're unlikely to make that super soon.

Feel free to ping us on discord, happy to discuss there too.

**Comment by jonasbark** [comment]
The reason I needed to use the --no-codesign option was different issues in regards to provisioning profiles/certificates. Once I will get past issue #936 I will do a few experiments and will provide the proper context to this issue.

**Comment by eseidel** [comment]
So a fix we could make would be to not depend on an IPA being generated.  Are you still attempting to use Shorebird?  We're happy to work with you here, but we've not heard of anyone else with a config like this. :) https://discord.gg/shorebird.

**Comment by jonasbark** [comment]
I will investigate further, but I am still blocked by #936

**Comment by bryanoltman** [comment]
This is fixed by https://github.com/shorebirdtech/shorebird/pull/1267
