### ISSUE TITLE
fix: Shorebird Not working properly

### ISSUE THREAD

**Issue by sudo-which-qp** [shorebirdtech/shorebird#939]
I have been having this error for close to 1 week now from shorebird, after installing shorebird and adding the path, I am running on a MacBook Pro, I get this error each time.

HEAD is now at 914d5b5f Roll engine for iOS alpha
Shorebird Engine • revision 7736cb3c15dd9dac608948e6c416b8bf419b987b
'sysctl -n hw.optional.arm64' returned unexpected output: ''

**Comment by eseidel** [comment]
That appears to come from Flutter:
https://github.com/search?q=repo%3Aflutter%2Fflutter%20hw.optional&type=code
https://github.com/flutter/flutter/blob/7d89617a92b7c008dbee6914cf04f67f36912b40/bin/internal/update_dart_sdk.sh#L79

Can you share the output of `sysctl -n hw.optional.arm64`?

**Comment by eseidel** [comment]
Mine says:
```
sysctl -n hw.optional.arm64
1
```

**Comment by sudo-which-qp** [comment]
> Mine says:
> 
> ```
> sysctl -n hw.optional.arm64
> 1
> ```

mine is returning an empty string

**Comment by eseidel** [comment]
If you type:
```
sysctl -n hw.optional.arm64
echo $0
```
What does it return?  Mine is:
```
sysctl -n hw.optional.arm64
echo $?
1
0
```

**Comment by sudo-which-qp** [comment]
> 

You mean in my terminal?

**Comment by eseidel** [comment]
Correct, in your terminal (Visual Studio Code, or Terminal.app).

**Comment by sudo-which-qp** [comment]
> Correct, in your terminal (Visual Studio Code, or Terminal.app).

Oh.... I am getting

zsh: command not found: sysctl

**Comment by eseidel** [comment]
Odd.  Mine is at:
```
which sysctl
/usr/sbin/sysctl
```

**Comment by eseidel** [comment]
So maybe try:
```
/usr/sbin/sysctl -n hw.optional.arm64
echo $?
```

**Comment by sudo-which-qp** [comment]
> So maybe try:
> 
> ```
> /usr/sbin/sysctl -n hw.optional.arm64
> echo $?
> ```

okay I got a response now

sysctl: unknown oid 'hw.optional.arm64'
1

**Comment by eseidel** [comment]
https://stackoverflow.com/questions/72708385/what-may-cause-error-sysctl-n-hw-optional-arm64-returned-unexpected-output is related. That "unknown oid" is strange though.

**Comment by eseidel** [comment]
I suspect what's happened is somehow `/usr/sbin` was removed from your path.  You can check your path with:
`echo $PATH`.

Flutter could be more resilient against this by using `arch` instead of `sysctl`.

I'd try to run `flutter doctor` and get that clean.  Once `flutter doctor` works, Shorebird should work.

**Comment by sudo-which-qp** [comment]
> I suspect what's happened is somehow `/usr/sbin` was removed from your path. You can check your path with: `echo $PATH`.
> 
> Flutter could be more resilient against this by using `arch` instead of `sysctl`.
> 
> I'd try to run `flutter doctor` and get that clean. Once `flutter doctor` works, Shorebird should work.

Thank You... you were very helpful to be very honest, everything is working fine now

It's downloading now
