### ISSUE TITLE
Shorebird login : An unknown error occurred.

### ISSUE THREAD

**Issue by nimahedayati** [shorebirdtech/shorebird#946]
**Console**
The Shorebird CLI needs your authorization to manage apps, releases, and patches on your behalf.
In a browser, visit this URL to log in:
https://accounts.google.com/o/oauth2/v2/auth?client_id=.....
Waiting for your authorization...
An unknown error occurred.

**Redirected Google Authorization**
Application has successfully obtained access credentials
This window can be closed now.

**Comment by mohamad72** [comment]
I have this error too
