### ISSUE TITLE
Dart_eval technology

### ISSUE THREAD

**Issue by macwilko** [shorebirdtech/shorebird#948]
Dear Shorebird Tech,

I curious, have you developed a similar library to [dart_eval](https://pub.dev/packages/dart_eval) for Shorebird?

I'de like to run untrusted Dart code within my App, and I'm exploring what the best solutions are available.

Thanks

Matt

**Comment by eseidel** [comment]
https://docs.shorebird.dev has more information.  We work very differently from dart_eval, but you could use Shorebird for similar use cases.
