### ISSUE TITLE
fix: I get this error.

### ISSUE THREAD

**Issue by thurain11** [shorebirdtech/shorebird#949]
[WARN] iOS support is alpha. See https://docs.shorebird.dev/status#ios-alpha for more information.
✓ Fetching apps (0.5s)
✗ Failed to build IPA (287.2s)
    "Runner.app" requires a provisioning profile with the App Groups, Associated Domains, and Push Notifications features.
    "OneSignalNotificationServiceExtension.appex" requires a provisioning profile with the App Groups feature.

**Comment by eseidel** [comment]
That looks like a provisioning error.  Are you able to build within XCode (`open ios/Runner.xcworkspace`) or from Flutter directly e.g. `flutter build ios --release`?

See also https://docs.shorebird.dev/guides/code_push_release_app_store

**Comment by eseidel** [comment]
Let us know if we can help!  https://discord.gg/shorebird.

**Comment by kukufree** [comment]
"shorebird release ios" is ok. but "shorebird patch ios" failed:
======================================
shorebird patch ios        
[WARN] iOS support is beta. Some apps may run slower after patching.
See https://docs.shorebird.dev/status for more information.
✓ Fetching apps (0.5s)
✗ Failed to build IPA (255.4s)
    "SNLiveActivityWidgetExtension.appex" requires a provisioning profile with the App Groups feature.
    "Runner.app" requires a provisioning profile with the App Groups and Push Notifications features.

**Comment by kukufree** [comment]
fvm flutter build ios --release is successed

**Comment by kukufree** [comment]
shorebird flutter versions use 3.13.2
