### ISSUE TITLE
fix: Crashed: io.flutter.1.ui EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by NamBuiDanh2001** [shorebirdtech/shorebird#958]
**Description**
Log in Firebase crashlytic
```
Crashed: io.flutter.1.ui
0  Flutter                        0xafd978 dart::Simulator::InstructionDecode(dart::Instr*) + 116
1  Flutter                        0xb03cb4 dart::Simulator::Execute() + 128
2  Flutter                        0xa5abd0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) + 980
3  Flutter                        0xb719cc Dart_InvokeClosure + 1068
4  Flutter                        0x8411b4 tonic::DartMicrotaskQueue::RunMicrotasks() + 220
5  Flutter                        0x7215b4 fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 1244
6  Flutter                        0x72463c fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
7  CoreFoundation                 0xa5fdc __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
8  CoreFoundation                 0x30348 __CFRunLoopDoTimer + 1016
9  CoreFoundation                 0x2afdc __CFRunLoopDoTimers + 324
10 CoreFoundation                 0xaeb4 __CFRunLoopRun + 1948
11 CoreFoundation                 0x1dd8c CFRunLoopRunSpecific + 572
12 Flutter                        0x724728 fml::MessageLoopDarwin::Run() + 88
13 Flutter                        0x724218 void* std::_LIBCPP_ABI_NAMESPACE::__thread_proxy[abi:v15000]<std::_LIBCPP_ABI_NAMESPACE::tuple<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<std::_LIBCPP_ABI_NAMESPACE::__thread_struct, std::_LIBCPP_ABI_NAMESPACE::default_delete<std::_LIBCPP_ABI_NAMESPACE::__thread_struct> >, fml::Thread::Thread(std::_LIBCPP_ABI_NAMESPACE::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0> >(void*) + 208
14 libsystem_pthread.dylib        0x2458 _pthread_start + 116
15 libsystem_pthread.dylib        0xab0 thread_start + 8
```
**Steps To Reproduce**

1. Run ```shorebird patch ios-alpha```
2. Launch app ios 
3. when open features had updated in patch error crash occur

**Expected Behavior**

**Screenshots**

**Additional Context**
iOS version 15 .

**Comment by eseidel** [comment]
Thank you for the report!  I'd love to learn more so I can reproduce.  Are you willing to share more about what packages your app uses (e.g. pubspec.yaml dependencies)?

**Comment by buidanhnam** [comment]
> Thank you for the report! I'd love to learn more so I can reproduce. Are you willing to share more about what packages your app uses (e.g. pubspec.yaml dependencies)?

@eseidel thank you for your support. 
Packages in project
```
  flutter_facebook_auth: 3.5.7 # do not update
  dio: ^4.0.6 # do not update
  intl: ^0.17.0 # do not update
  collection: ^1.17.0 # do not update
  cupertino_icons: 1.0.5
  shared_preferences: ^2.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  pull_to_refresh: ^2.0.0
  page_transition: ^2.0.9
  share: ^2.0.4
  google_sign_in: ^6.1.0
  youtube_player_flutter: ^8.1.2
  flutter_widget_from_html: ^0.10.0
  webview_flutter: ^4.0.7
  carousel_slider: ^4.2.1
  path_provider: ^2.0.14
  image_cropper: ^3.0.2
  image_picker: ^0.8.7+3
  file_picker: ^5.2.10
  flutter_native_image: ^0.0.6+1
  flutter_pdfview: ^1.3.0
  flutter_cached_pdfview: ^0.4.1
  tree_view: ^0.0.6
  flutter_typeahead: ^4.0.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  url_launcher: ^6.1.10
  external_path: ^1.0.3
  permission_handler: ^10.2.0
  flutter_share: ^2.0.0
  firebase_dynamic_links: ^5.3.0
  package_info: ^2.0.2
  launch_review: ^3.0.1
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  #  firebase_analytics: "^7.0.1"
  flutter_local_notifications: ^13.0.0
  photo_view: ^0.14.0
  flutter_slidable: ^3.0.0
  device_info: ^2.0.3
  states_rebuilder: ^6.2.0
  fluttertoast: ^8.2.1
  open_filex: ^4.3.2
  dotted_border: ^2.0.0+3
  scrollable_positioned_list: ^0.3.5
  sign_in_with_apple: ^4.3.0
  firebase_crashlytics: ^3.3.0
  percent_indicator: ^4.2.3
  cloud_firestore: ^4.7.0
  provider: ^6.0.5
  firebase_storage: ^11.2.0
  lottie: ^2.3.2
  firebase_auth: ^4.6.0
  connectivity_plus: ^3.0.4
  flutter_staggered_grid_view: ^0.6.2
  linkfy_text: ^1.1.5
  video_player: ^2.6.1
  video_thumbnail: ^0.5.3
  chewie: ^1.4.0
  flutter_linkify: ^5.0.2
  wechat_assets_picker: ^8.4.2
  fwfh_text_style: ^2.22.8+1
  screenshot: ^1.3.0
  wechat_camera_picker: ^3.7.0
  in_app_purchase: ^3.1.5
  flutter_spinkit: ^5.1.0
  app_settings: ^4.2.0
  in_app_update: ^4.0.1
  qr_flutter: ^4.0.0
  image: ^4.0.15
  qr_code_scanner: ^1.0.1
  uni_links: ^0.5.1
  flutter_native_splash: ^2.2.19
  flutter_expandable_fab: ^1.7.1
  animated_text_kit: ^4.2.2
  dart_openai: ^1.8.0
  markdown_widget: ^2.0.0+1
  flutter_keyboard_visibility: 5.3.0
  timer_count_down: ^2.2.2
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.2
  speech_to_text: ^6.1.1
```
I don't know whether this issue was caused after the patch update.  So I have updated the new version with 'shorebird release' to Store. I will be tracking more.

**Comment by eseidel** [comment]
Shorebird should *never* crash.  I would recommend not using Shorebird for your app until we fix this, since it appears you've found a crash in our custom Dart interpreter.  @kmillikin and I will see if we can reproduce, thanks.

**Comment by eseidel** [comment]
I'd be curious if you're willing to share the full crash report?  You're also welcome to email it to us if you'd rather it not be public.  contact@shorebird.dev reaches me.  Thanks!

**Comment by eseidel** [comment]
Kevin and I were looking at this just now and we think this is likely due to a bug in our FFI call logic.  We're not entirely sure yet.

You mention this occurred during the use of Firebase login?

**Comment by NamBuiDanh2001** [comment]
> I'd be curious if you're willing to share the full crash report? You're also welcome to email it to us if you'd rather it not be public. [contact@shorebird.dev](mailto:contact@shorebird.dev) reaches me. Thanks!

@eseidel this is report from Firebase 
[issue_stacktrace.txt](https://github.com/shorebirdtech/shorebird/files/12246628/issue_3d74baf474c455e1cb18b18e0e9ec472_crash_session_4941a5124ce143be89f24a5ee9134aae_DNE_0_v2_stacktrace.txt)

**Comment by NamBuiDanh2001** [comment]
> You mention this occurred during the use of Firebase login

not quite like that, maybe I'm too hastily when think that errors have occurred when login with Firebase, I have carefully checked and realized the error occurred with most features have been updated by Shorebird.

**Comment by eseidel** [comment]
Kevin is currently working on a related issue which we think may fix this problem. We hope to have a fix in a week or two.  Thank you for your help reporting!

**Comment by eseidel** [comment]
We believe we've fixed this on main, we should be releasing in the next day or so and you'll be able to test.  Thanks for your patience.

**Comment by kmillikin** [comment]
The fix for this (or a similar issue) should be in v0.13.0.  @NamBuiDanh2001, I'd be interested in knowing if you can still reproduce this issue.

**Comment by eseidel** [comment]
We weren't able to reproduce it locally, so we don't know for sure that we've fixed it, but we fixed another crasher with the same stack trace so we hope we got this one. 🤞

**Comment by eseidel** [comment]
We believe this is resolved.  Please let us know if you see any issues with iOS!
