### ISSUE TITLE
feat: How to build both `apk` and `aab` artifacts for release with single command?

### ISSUE THREAD

**Issue by niteshsh4rma** [shorebirdtech/shorebird#959]
**Description**

How to build both `apk` and `aab` artifacts for release with single command?

**Requirements**

- [x] Checklist of requirements to be fulfilled

**Additional Context**

- I am trying to build both apk and aab for my app, but as far as docs is followed, only one type of artifact is generated with one command. How can I generate both artifacts with single command?

**Comment by felangel** [comment]
Hi @niteshsh4rma 

You can use `shorebird release android --artifact apk` to generate both aab and apk.

**Comment by niteshsh4rma** [comment]
Thanks, got it
