### ISSUE TITLE
fix: FAQ (What can't we use Shorebird code push for? | Does Shorebird comply with Play Store guidelines?)

### ISSUE THREAD

**Issue by danielGz** [shorebirdtech/shorebird#965]
**Description**

Documentation is not clear enough on the limits for the app stores compliance.

**Expected Behavior**

A list of dos and don'ts or examples.

**Additional Context**

I think this is one of the main concerns for enterprise teams and why they scrutinize the adoption of the tool.
How much should you push, how big of a change is it allowed and what not to do.

https://docs.shorebird.dev/faq#what-cant-we-use-shorebird-code-push-for
https://docs.shorebird.dev/faq#does-shorebird-comply-with-play-store-guidelines

**Comment by eseidel** [comment]
Agreed we could do more here.

**Comment by eseidel** [comment]
We've updated these several times since.  Let us know if you still have concerns, we would *love* to help!
