### ISSUE TITLE
Smoke Tests

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#968]
- [x] iOS release
    - [x] Windows Machine
    - [x] MacOS Machine
- [x] iOS patch
    - [x] Windows Machine
    - [x] MacOS Machine
- [x] iOS preview
    - [x] Windows Machine: https://github.com/shorebirdtech/shorebird/issues/970
    - [x] MacOS Machine

- [x] Android release
    - [x] Windows Machine
    - [x] MacOS Machine
- [x] Android patch
    - [x] Windows Machine
    - [x] MacOS Machine
- [x] Android preview
    - [x] Windows Machine
    - [x] MacOS Machine

- [x] iOS Add to App release
    - [x] Windows Machine
    - [x] MacOS Machine
- [x] iOS Add to App patch
    - [x] Windows Machine
    - [x] MacOS Machine
- [x] iOS Add to App preview
    - [x] Windows Machine: https://github.com/shorebirdtech/shorebird/issues/970
    - [x] MacOS Machine

- [x] Android Add to App release
    - [x] Windows Machine: https://github.com/shorebirdtech/shorebird/issues/980 https://github.com/shorebirdtech/shorebird/issues/982 https://github.com/shorebirdtech/shorebird/issues/985
    - [x] MacOS Machine
- [ ] Android Add to App patch
    - [x] Windows Machine
    - [x] MacOS Machine

- [x] iOS Flavors release
    - [x] Windows Machine
    - [x] MacOS Machine (@felangel)
- [x] iOS Flavors patch
    - [x] Windows Machine
    - [x] MacOS Machine (@felangel)
- [x] iOS Flavors preview
    - [x] Windows Machine
    - [x] MacOS Machine (@felangel)

- [x] Android Flavors release
    - [x] Windows Machine
    - [x] MacOS Machine (@felangel)
- [x] Android Flavors patch
    - [x] Windows Machine
    - [x] MacOS Machine (@felangel)
- [x] Android Flavors preview
    - [x] Windows Machine
    - [x] MacOS Machine (@felangel)

**Comment by eseidel** [comment]
Testing windows Android flavors:
```
PS C:\Users\micro\Documents\GitHub\samples\flavors> shorebird release android
✗ Failed to build: Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
Flutter assets will be downloaded from https://download.shorebird.dev. Make sure you trust this source!
Gradle build failed to produce an .aab file. It's likely that this file was generated under C:\Users\micro\Documents\GitHub\samples\flavors\build, but the tool couldn't find it.
 (110.3s)
PS C:\Users\micro\Documents\GitHub\samples\flavors> ls .\build\app\outputs\bundle\


    Directory: C:\Users\micro\Documents\GitHub\samples\flavors\build\app\outputs\bundle


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          8/1/2023   1:09 PM                internalRelease
d-----          8/1/2023   1:09 PM                stableRelease

PS C:\Users\micro\Documents\GitHub\samples\flavors> ls .\build\app\outputs\bundle\stableRelease\


    Directory: C:\Users\micro\Documents\GitHub\samples\flavors\build\app\outputs\bundle\stableRelease


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          8/1/2023   1:09 PM       24066606 app-stable-release.aab

PS C:\Users\micro\Documents\GitHub\samples\flavors> ls .\build\app\outputs\bundle\internalRelease\


    Directory: C:\Users\micro\Documents\GitHub\samples\flavors\build\app\outputs\bundle\internalRelease


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          8/1/2023   1:09 PM       24066616 app-internal-release.aab

```

Similar to https://github.com/shorebirdtech/shorebird/issues/515

**Comment by felangel** [comment]
Opened https://github.com/shorebirdtech/shorebird/issues/971
