### ISSUE TITLE
fix: `shorebird preview` lists aar and ios-framework releases

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#981]
**Description**

Releases created with `shorebird release aar` and `shorebird release ios-framework` appear in the `shorebird preview` as `android` and `ios` targets, respectively. This is wrong and confusing, as there isn't anything to meaningfully preview without an apk. 

Preview should either download the `.aar`/`.xcframework` and give the user instructions about how to include it in their app, or simply not list these as available platforms.

**Comment by eseidel** [comment]
Just got a report from someone who ran into this:

```flutter_module_test % shorebird preview
✓ Fetching apps (0.4s)
Which app would you like to preview?
Which app would you like to preview? flutter_module_test
✓ Fetching releases (0.3s)
Which release would you like to preview?
Which release would you like to preview? 8.18.1+249
Which platform would you like to preview?
Which platform would you like to preview? android
✗ No artifact found for architecture aab in release 6605 (0.3s)
this is case of addtoapp android```
