### ISSUE TITLE
feat: support changing Runner.xcproj name

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#991]
Turns out it's now possible with Flutter:
 https://github.com/flutter/flutter/pull/124533

When users do that however, Shorebird will break.

**Comment by bryanoltman** [comment]
It appears that, despite the contents of that PR, `flutter` breaks as well:

```
⑆ flutter build ipa --release

Expected ios/Runner.xcodeproj but this file is missing.
Application not configured for iOS
```

**Comment by bryanoltman** [comment]
There seem to be places in the Flutter codebase where "Runner" is still hard-coded (https://github.com/flutter/flutter/blob/f80ff55a7675e86147fefcd2ce54e176b584078b/packages/flutter_tools/lib/src/xcode_project.dart#L24). I filed https://github.com/flutter/flutter/issues/131779. Closing this issue until Flutter fully supports renaming `Runner.xcodeproj`.
